- pkg/cache/client/round_tripper.go
- pkg/cache/server/bootstrap/bootstrap.go
- pkg/cache/server/config.go
- pkg/cache/server/handler.go
provides an ordered list of HTTP round-trippers that add shard and cluster awareness to all clients that use the loopback config.
requires https://github.com/kcp-dev/kcp/pull/1926 and https://github.com/kcp-dev/kubernetes/pull/100
Fixes #
> 🌱 cache: makes all internal clients shard and cluster aware

- pkg/cache/server/config.go
- pkg/server/apiextensions.go
- pkg/server/apiextensions_test.go
- pkg/server/config.go
- pkg/server/filters/filters.go
- pkg/server/filters/filters_test.go
- pkg/server/handler.go
- pkg/server/handler_test.go
It moves common HTTP handlers to a separate package.
Those handlers are used by the kcp-server and the cache-server.
Since we are going to run the cache from the kcp.
Importing will cause a cycle. 
Thus common functionality is moved to a common package.
Fixes #
> :seedling: cache: moves common HTTP handlers to a shared pkg

- docs/cache-server.md
describes the cache-server, atm under `docs/cache-server.md`, could be moved to `kcp/pkg/cache/server` or `docs/compontents`.
Fixes https://github.com/kcp-dev/kcp/issues/1865
> 📝 documents the cache-server

- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
This PR will take into account if the deletionTimestamp of the resource is set in order to schedule new placements or not. 
This PR fixes a situation where the syncer and the resource controller will enter into a reconciliation storm, due to the resource controller re-adding the sync intention to a location once it has been removed by the syncer.
Related issue(s)
Fixes https://github.com/kcp-dev/kcp/issues/1891
> 🐛 Don't calculate new placements for resources that are being deleted

- pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
- pkg/reconciler/apis/identitycache/api_export_identity_controller.go
- pkg/reconciler/kubequota/kubequota_controller.go
- pkg/reconciler/scheduling/location/location_controller.go
- pkg/reconciler/scheduling/placement/placement_controller.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/placement/placement_controller.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
If we encode a key with MetaNamespaceKeyFunc, we must decode it with SplitMetaNamespaceKey, instead of assuming no namespace was encoded.
/assign @sttts @ncdc
> :bug: *: split meta namespace keys correctly

- pkg/syncer/namespace/namespace_downstream_controller.go
- pkg/syncer/namespace/namespace_downstream_process.go
- pkg/syncer/namespace/namespace_downstream_process_test.go
- pkg/syncer/namespace/namespace_upstream_controller.go
- pkg/syncer/namespace/namespace_upstream_process.go
- pkg/syncer/namespace/namespace_upstream_process_test.go
- pkg/syncer/syncer.go
Today, one controller/workqueue is used to drive two separate reconciliation flows: reacting to events in the upstream and downstream informers. The presence of a cluster in the queue key is used to infer which informers the event came from.
This is hard to reason about, and the logic for the two cases is entirely separate, and, furthermore, when we're syncing to a kcp logical cluster, the "downstream" objects have a cluster set and the keys do not follow the expected format.
Instead of inferring things from stringified keys in one queue, we can just split the two controllers and explicitly use cluster-aware or cluster-unaware keyfunctions where necessary.
Needed for #1958 
/assign @jmprusi 
/cc @ncdc
> :bug: syncer: bifurcate the namespace controller

- pkg/server/filters/filters.go
- pkg/server/home_workspaces.go
- pkg/server/home_workspaces_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
clients should specify a cluster name before storing something in the db as that leads to more readable code.
the server should not assign a default cluster name.
at the moment requests without a cluster name are rejected by the storage layer.
Things to consider:
reject a request without a name in the filter
will this break some external clients?
Fixes #
> 🌱 WithClusterScope: should not assign a default cluster name

- pkg/server/options/options.go
The possible values include the defaults, and we're missing the new option recently added via #1962
Covers option discussed in #1959
> :seedling:  Update batteries-included option usage

- pkg/admission/webhook/generic_webhook.go
Only if a bound API export is set but no bound API export workspace we want to log. This fixes it.
Related with #2028
Follow-up for #2029
> :bug: pkg/admission/webhook: differentiate states

- cmd/cache-server/main.go
- pkg/cache/server/config.go
- pkg/cache/server/server.go
- pkg/server/cache.go
- pkg/server/options/cache.go
- pkg/server/options/options.go
- pkg/server/server.go
This PR allows for running the cache-server in-process with the kcp server. 
The new server is exposed under `/services/cache/...` path. 
By default, the cache server won't run with the kcp server.
In order to turn it, pass `--run-cache-server=true` flag.
Fixes #
> 🌱 Wire the cache server into the kcp server

- config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
- config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-maximal-permission-policy.yaml
- test/e2e/reconciler/locationworkspace/rootcompute_test.go
the root:compute kubernetes APIExport should add maximal permission policy RBAC.
Fixes https://github.com/kcp-dev/kcp/issues/1959
> 🐛 bug fix Add maximal permission policy for compute APIExport

- .github/ISSUE_TEMPLATE/community_meeting.yaml
- Switch default text from markdown (not submitted) to textarea
- Update YouTube URL to community meetings playlist
See https://github.com/ncdc/kind-action-test/issues/new/choose for how this looks post-merge
> 🌱 Update community meeting template

- cmd/kcp-front-proxy/filters/filters.go
- cmd/kcp-front-proxy/main.go
Minor refactoring, so that we can run a customized front-proxy without needing to copy the `filters.go`
Related to discussions with @sttts where it was mentioned that we may want the ability to run a customized front-proxy for experimental reasons (specifically to test out rate-limiting at the proxy level)
> :seedling: cmd/kcp-front-proxy move filters into module

- test/e2e/framework/audit-policy.yaml
- test/e2e/framework/kcp.go
- test/e2e/framework/util.go
This adds audit logs for e2e tests.
None
> :seedling: test/e2e: enable audit logs

- cmd/virtual-workspaces/command/cmd.go
- cmd/virtual-workspaces/options/options.go
- pkg/server/server.go
- pkg/server/virtual.go
This enables audit logging in the virtual workspace apiserver (`/services/.*` handler).
None
> :seedling: pkg/server: enable audit logging in virtual workspace apiserver

- pkg/authorization/local_authorizer.go
- pkg/authorization/system_crd_authorizer.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
The `ValidClustrFrom` method doesn't allow for a cluster name to be empty.
Since the authorizers handle cases in which a cluster name wasn't provided using the `ClusterFrom` method leads to a more readable code.
The `ValidClusterFrom` returns an error when the name is empty which leads to slightly less readable code.
This is a follow-up from https://github.com/kcp-dev/kcp/pull/1871
Fixes #
> 🌱 authorisation: stop using the ValidClusterFrom method

- docs/authorization.md
- pkg/authorization/anonymizer.go
- pkg/authorization/apibinding_authorizer.go
- pkg/authorization/audit_logger.go
- pkg/authorization/bootstrap_policy_authorizer.go
- pkg/authorization/decision.go
- pkg/authorization/local_authorizer.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/server/apiextensions.go
- pkg/server/config.go
- pkg/server/handler.go
- pkg/virtual/apiexport/authorizer/content.go
- pkg/virtual/apiexport/authorizer/content_test.go
- pkg/virtual/apiexport/authorizer/maximal_permission_policy.go
- pkg/virtual/apiexport/authorizer/maximal_permission_policy_test.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/framework/forwardingregistry/store.go
- test/e2e/fixtures/apifixtures/apibinding.go
- test/e2e/framework/auth-tokens.csv
- test/e2e/virtual/apiexport/authorizer_test.go
- test/e2e/virtual/apiexport/crd_cowboys.yaml
- test/e2e/virtual/apiexport/virtualworkspace_test.go
This adds maximal permission policy authorization to the virtual apiexport apiserver. Currently, this is not enforced at all.
Part of #1219
Fixes #1337
/cc @sttts
> ✨ pkg/virtual/apiexport: add maximal permission policy authorization

- config/crds/apis.kcp.dev_apibindings.yaml
- config/crds/workload.kcp.dev_synctargets.yaml
- config/root-phase0/apiexport-workload.kcp.dev.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/apibinding_admission_test.go
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/openapi/zz_generated.openapi.go
- pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
This removes ancestor checks for API bindings.
Follow-up for #1739
Fixes #2059
> :seedling: apibinding, types: remove ancestor check

- cmd/kcp-front-proxy/main.go
- hack/logcheck.out
- pkg/proxy/index/index_controller.go
- pkg/proxy/mapping.go
Follow-up to #2042 - to convert these we have to pass the context in from main
Part of #1694
> 🌱  proxy: pass context for contextual logging

- go.mod
- go.sum
- pkg/apis/go.mod
- pkg/apis/go.sum
- pkg/apis/tenancy/v1alpha1/helper/helper.go
- pkg/apis/tenancy/v1alpha1/helper/helper_test.go
Fixes #2018
Update to kcp-dev/logicalcluster#23 to pull in a fix to allow single-character names.
> :seedling: tenancy: allow single-character logical cluster names

- pkg/syncer/shared/finalizer.go
- pkg/syncer/status/status_process_test.go
When a resource is deleted downstream, the finalizer doesn't acknowledge it. This PR changes the behavior of the syncer, to delete a finalizer if the downstream resource was deleted, to better reflect the situation.
This also fixes some common issues with resources that don't have a status field getting deleted and not getting recreated (due to a missing status update upstream).
Related to: [#1787](https://github.com/kcp-dev/kcp/issues/1787)
> 🐛 syncer: remove finalizer if downstream resource has been deleted

- .github/workflows/goreleaser.yml
Signed-off-by: Mohamed Chiheb <mohamed@giantswarm.io>
Make goreleaser runs only on tags
Fixes #2037
> :seedling: turn off goreleaser from PRs and pushes to main

- go.mod
- go.sum
Upgrade to logicalcluster v2.0.0-alpha.3, which removed the v1 package.
https://github.com/kcp-dev/logicalcluster/pull/24
> 🌱 Upgrade to logicalcluster v2.0.0-alpha.3

- pkg/cache/server/bootstrap/bootstrap.go
this will allows us to update both the spec and status of an object atomically.
normally, when the status subresource is enabled,
callers have to use the /status endpoint for updating the status field.
updates to a regular endpoint simply ignore the status field.
will be used by https://github.com/kcp-dev/kcp/pull/2024
required to complete https://github.com/kcp-dev/kcp/issues/342
> 🌱 cache server: stop serving subresources for built-in resources

- Dockerfile
Combining the chmod with the download avoids creating another layer, which saves about 45MB currently
> :seedling: Combine Dockerfile kubectl layers to save space

- .github/workflows/kcp-image.yaml
This task triggers a deploy to an internal Red Hat environment, but now this is done with a separate component.  We do not want a direct connection to the internal environment like this.
> :seedling: Remove deploy task from github actions

- pkg/server/controllers.go
When the vw server is colocated in kcp, the apibinder controller was trying to connect to the external address for
/services/initializingworkspaces. This works when there is no front proxy, but if there is one, we get x509 verification errors, because the client making the request is the local loopback client, and there is no way for that to work against the front proxy.
Fixes #2094
> 🐛 apibinder: don't use external address for now

- Makefile
- go.mod
- Add `make modules` to run `go mod tidy` on the repo root and pkg/apis
- Add `make verify-modules` to ensure the everything is up to date
Fixes #
> 🌱 Add make targets to update and verify go.mod

- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go
Only delete cluster scoped resource in workspace deletion, the ns scoped resource will be deleted by ns deletion.
Fixes #
> 🐛 Avoid redundant delete in workspace deletion

- Makefile
Allow go to determine ARCH and OS during build
Fixes #2088
> :bug: Allow go to determine ARCH and OS during build

- pkg/authorization/apibinding_authorizer.go
- pkg/authorization/local_authorizer.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
- pkg/virtual/framework/wrappers/rbac/merging.go
No code ever relied on the merged informer doing anything other than merging the listers. Refactor to reflect this reality in the type.
/assign @ncdc @sttts
/cc @s-urbaniak
> :seedling: authz: remove the concept of a merged informer

- cmd/kcp-front-proxy/main.go
- cmd/kcp-front-proxy/options/options.go
- cmd/virtual-workspaces/command/cmd.go
- cmd/virtual-workspaces/options/options.go
- hack/logcheck.out
- pkg/virtual/options/options.go
Adds profiler address as command line argument
Fixes https://github.com/kcp-dev/kcp/issues/1836
Screenshot:
> :sparkles: Add profiler support to front proxy and virtual workspaces

- pkg/syncer/shared/helpers.go
- pkg/syncer/shared/helpers_test.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/status/status_process.go
- test/e2e/syncer/syncer_test.go
Specific resources (kcp-root-ca.crt configmap and kcp-* secrets) weren't recreated if deleted downstream due to a missing name transformation. This PR fixes that.
> 🐛 syncer: apply name transformations to spec controller downstream informer

- pkg/apis/go.mod
- pkg/apis/go.sum
Update go.mod in pkg/apis to bump logicalcluster to v2.0.0-alpha.3 to match the main go.mod file.
I missed this when doing #2070
Fixes #
> 🌱 pkg/apis: update logicalcluster to v2.0.0-alpha.3

- docs/quickstart-tenancy-and-apis.md
Similar in approach to the quickstart in the README but focusing on workspaces, apiexports, and apibindings rather than workload APIs.
> :book:Add a quickstart doc for tenancy and APIs

- pkg/cliplugins/workspace/cmd/cmd.go
Wrong command context was passed in `ws use` subcommand because of which there was a null pointer error when using it.
Issue:
Workspace use command run from building kubectl-kcp binary gives null pointer error. The passed command context was from parent (workspace command) was getting closed, causing seg fault. 
```
➜  kcp git:(debug/ws-use) ✗ ./bin/kubectl-kcp ws use webapp-back
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4d6b83d]
goroutine 1 [running]:
golang.org/x/time/rate.(*Limiter).WaitN(0xc000181c20, {0x0, 0x0}, 0x1)
/Users/vnarsing/go/pkg/mod/golang.org/x/time@v0.0.0-20220210224613-90d013bbcef8/rate/rate.go:234 +0x1bd
```
Fixes #
> :bug: fix- nil context in workspace-use plugin

- pkg/cache/server/config.go
disabling SSA stops the cache server from modifying "managedFields" field.
https://github.com/kcp-dev/kcp/issues/342
> 🌱  cache-server: disable ServerSideApply feature

- pkg/reconciler/cache/replication/indexers.go
- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/cache/replication/replication_reconcile_apiexports_test.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured_test.go
The new controller copies objects of defined resources that have the `internal.sharding.kcp.dev/replicate` annotation to the cache server.
The replicated object will be placed under the same cluster as the original object.
In addition to that, all replicated objects will be placed under the shard taken from the shardName argument.
For example: shards/{shardName}/clusters/{clusterName}/apis/apis.kcp.dev/v1alpha1/apiexports
As of today the controller replicates the ApiExport resources.
The reconcileAPIExports function handles the following cases:
1. creation of the object in the cache server
happens when the cached object is not found in c.cacheApiExportsIndexer
2. deletion of the object from the cache server
happens when either of the following is true:
- the original/local object was …
> 🌱 cache: introduce the replication controller

- cmd/kcp-front-proxy/main.go
This avoids the explicit handling of log Init/Flush, since the Run function [already does this](https://github.com/kubernetes/component-base/blob/release-1.24/cli/run.go#L90..L143), and it's more consistent with most other cmds
> :seedling: cmd/kcp-front-proxy: use component-base/cli Run

- cmd/kubectl-kcp/main.go
- cmd/kubectl-workspace/main.go
- go.mod
- go.sum
- pkg/cliplugins/workspace/cmd/cmd.go
The current approach uses the binary name, which won't work in the case where code gets run via [hack/generate/cli-doc/gen-cli-doc.go](https://github.com/kcp-dev/kcp/blob/main/hack/generate/cli-doc/gen-cli-doc.go)
Fixes #2119
> :bug: Detect kubectl plugin via FlagSet Name

- pkg/admission/plugins.go
- pkg/admission/reservednames/OWNERS
- pkg/admission/reservednames/admission.go
- pkg/admission/reservednames/admission_test.go
- pkg/apis/tenancy/v1alpha1/types.go
Adds a mutating admission plugin for ClusterWorkspaces and
ClusterWorkspaceTypes to ensure that a more helfpul error message is
returned if a user attempts to create with a reserved name. A mutating
webhook is used due to the fact that we want to catch this prior to
OpenAPI schema validation.
Before
```
🤖 (kcp) k kcp ws create root
error: ClusterWorkspace.tenancy.kcp.dev "root" is invalid: <nil>: Invalid value: "": "metadata.name" must not validate the schema (not)
exit status 1
```
After
```
🤖 (kcp) k kcp ws create root
error: clusterworkspaces.tenancy.kcp.dev "root" is forbidden: cannot use reserved name "root" as "metadata.name"
exit status 1
```
Fixes https://github.com/kcp-dev/kcp/issues/1214
> ✨ Add reservednames admission plugin to surface clearer error messages

- cmd/kubectl-kcp/cmd/kubectlKcp.go
In #2121 I added this to the main.go (which is consistent with most other usage) but missed it was already done here, so cleaning up the duplication
Related to fix for #2119
> 🐛 kubectl-kcp: remove duplicated NewFlagSet

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/apibinding_admission_test.go
- test/e2e/apibinding/apibinding_authorizer_test.go
Improves the error message on non existent API export references.
Fixes #1786
> ✨ pkg/admission/apibinding: more informative authorization failure message

- pkg/reconciler/workload/resource/resource_controller.go
- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
Signed-off-by: David Festal <dfestal@redhat.com>
This PR fixes several bugs in the resource controller:
- We should not add the `RequestState` label to [Sync](url) for a `SyncTarget` when the namespace already has the deletion annotation for this `SyncTarget`. It doesn't make sense to start syncing a resource to a SyncTarget while the intent already expressed on the namespace is to delete all resources from this `SyncTarget`
- Additional small fixes in the resource `computePlacement` function.
See the individual commits for more information
Bugs spotted while debugging the Syncer Virtual Transformations e2e test
> :bug:  Fix bugs in the resource controller

- pkg/syncer/spec/spec_process.go
When the Syncer is running in AdvancedScheduling mode, the experimental status annotation is synced to the downstream resource, this PR removes that annotation when syncing the resource downstream.
> 🐛 Syncer AdvancedScheduling fixes: Avoid syncing down the experimental status annotation.

- cmd/apigen/main.go
When the output dir specified through flag is not present, the apigen command fails with an error. This PR fixes the same by creating a new output directory.
Previously when the output directory is not present:
```
$ apigen --input-dir=config/crd --output-dir=kcp/
INFO[0000] Loading CustomResourceDefinitions from config/crd  logger=apigen
INFO[0000] Loaded CustomResourceDefinition for catalogentries.catalog.kcp.dev from config/crd/catalog.kcp.dev_catalogentries.yaml  logger=apigen
INFO[0000] Loaded 1 CustomResourceDefinitions            logger=apigen
INFO[0000] Loading APIResourceSchemas from kcp/          logger=apigen
ERRO[0000] Could not load previous APIResourceSchemas.   error="lstat kcp/: no such file or directory" logger=apigen
```
Now, when output dir is not present, the command …
> :bug: fix: apigen to write files when previous versions are not present

- Makefile
- config/crds/apiresource.kcp.dev_apiresourceimports.yaml
- config/crds/apiresource.kcp.dev_negotiatedapiresources.yaml
- config/crds/apis.kcp.dev_apibindings.yaml
- config/crds/apis.kcp.dev_apiexports.yaml
- config/crds/apis.kcp.dev_apiresourceschemas.yaml
- config/crds/scheduling.kcp.dev_locations.yaml
- config/crds/scheduling.kcp.dev_placements.yaml
- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
- config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
- config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
- config/crds/tenancy.kcp.dev_workspaces.yaml
- config/crds/workload.kcp.dev_synctargets.yaml
- config/root-phase0/apiexport-scheduling.kcp.dev.yaml
- config/root-phase0/apiexport-tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml
- config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
This bump controller-gen to pull in XValidation/CEL capabilities.
I am not sure what additional text to add here. We want CEL validation in CRDs, hence I am bumping controller-gen here, this is to make the verifier bots happy.
Relates to #2051
> 🌱 bump controller gen

- hack/logcheck.out
- pkg/logging/constants.go
- pkg/logging/tmc.go
- pkg/syncer/apiimporter.go
- pkg/syncer/namespace/namespace_downstream_controller.go
- pkg/syncer/namespace/namespace_downstream_process.go
- pkg/syncer/namespace/namespace_upstream_controller.go
- pkg/syncer/namespace/namespace_upstream_process.go
- pkg/syncer/resourcesync/controller.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
- pkg/syncer/tunneler.go
Complete the move to structural logging in the Syncer.
This has been started in a previous PR, but many places were not finished.
> :seedling: Syncer: Complete the move to structural logging

- Makefile
When `make install` is run on Mac it gives the error:
```
ln -sfr /Users/vnarsing/go/bin/kubectl-workspace /Users/vnarsing/go/bin/kubectl-ws
ln: illegal option -- r
usage: ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file [target_file]
ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file ... target_dir
link source_file target_file
make: *** [install] Error 1
```
Since `-r` is not supported in Mac.
> :bug: fix 'make install' on mac

- pkg/cliplugins/workload/plugin/sync.go
Serviceaccounts are currently synced by default, but this shouldn't be the case as it will cause issue overriding downstream SAs.
> :bug: cmd/Sync: remove serviceaccounts from default resource list

- cmd/kcp-front-proxy/main.go
- cmd/kcp/kcp.go
- cmd/syncer/main.go
- go.mod
- go.sum
- pkg/server/options/flags.go
Registers the JSON logging format in the commands:
* kcp
* kcp-front-proxy
* syncer
#1694
> :sparkles: Allow use of JSON logging format

- pkg/server/bootstrap/identity.go
Signed-off-by: David Festal <dfestal@redhat.com>
:bug: Wrong annotation in logging call
no issue created
Fixes #
> 🐛 Fix wrong annotation in logging call

- docs/locations-and-scheduling.md
- docs/storage.md
- pkg/apis/workload/v1alpha1/types.go
Signed-off-by: Guy Margalit <guymguym@gmail.com>
This is the first story of the storage epic - #1615
> :sparkles: :book: tmc: storage docs and apis

- pkg/indexers/apibinding.go
- pkg/indexers/apiexport.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/apis/apiexport/apiexport_controller_test.go
- pkg/reconciler/apis/apiexport/apiexport_reconcile.go
- pkg/server/controllers.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Defer creating an APIExport's first virtualWorkspaceURL until the first APIBinding is created.
Fixes #1183
> 🐛 Create VirtualWorkSpaceURL on first APIBinding

- pkg/proxy/authentication/groups.go
AFAICS it's unused and duplicates code in [options/authentication.go](https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/options/authentication.go)
This was introduced in #1305
> :seedling: proxy: remove unused/duplicated Authentication code

- pkg/admission/namespacelifecycle/admission.go
- pkg/admission/namespacelifecycle/admission_test.go
- Remove fake client usage from namespacelifecycle unit test
- Remove other unnecessary setup from the test (it wasn't being used/invoked)
- Update the admission struct to use a function pointer for getClusterWorkspace
Fixes #
> 🌱 Remove fake client from namespacelifecycle test

- pkg/reconciler/apis/identitycache/api_export_identity_controller.go
- pkg/reconciler/apis/identitycache/api_export_identity_reconcile.go
- pkg/reconciler/apis/identitycache/api_export_identity_reconcile_test.go
Fake clients were not proving us with much benefit here, and we weren't even creating informers from the clients in testing, so we can make a more robust test suite by using the member function approach.
/cc @p0lyn0mial 
/assign @ncdc 
part of #2167
> :seedling: identitycache: refactor to not use fake clients in testing

- config/crds/apis.kcp.dev_apibindings.yaml
- config/crds/workload.kcp.dev_synctargets.yaml
- config/root-phase0/apiexport-workload.kcp.dev.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/apis/apis/v1alpha1/types_apiexport.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
- Add map keys to APIBinding.Status.AppliedPermissionClaims and .ExportPermissionClaims
- Switched to using a sorted list when calculating applied permission claims so it doesn't keep generating new patches because of different ordering in the list.
Fixes #
> 🐛 Fix permissionclaim patch thrashing

- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/cache/replication/replication_reconcile_test.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
makes the replication controller a bit more generic so that adding new resources is easier.
it also extends the controller to reconcile `ApiResourceSchema` resources.
requires https://github.com/kcp-dev/kcp/pull/2024
> 🌱 cache: extend the replication controller to reconcile apiresourceschema

- hack/logcheck.out
- pkg/indexers/indexers.go
- pkg/reconciler/workload/placement/placement_controller.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
- pkg/server/controllers.go
- pkg/server/server.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/shared/helpers.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/status/status_process.go
- test/e2e/fixtures/kube/core.k8s.io_persistentvolumes.yaml
- test/e2e/syncer/persistentvolume.yaml
- test/e2e/syncer/syncer_test.go
This PR enables the Resource reconciler to label cluster-wide resources with the available synctargets for a workspace with the desired state of "pending". 
Currently, the list of allowed cluster-wide resources is hardcoded to "persistentvolumes" in preparation for upcoming storage work.
Fixes https://github.com/kcp-dev/kcp/issues/1890
> :sparkles: Add cluster-wide resources support to the resource reconciler

- config/crds/apis.kcp.dev_apibindings.yaml
- config/crds/workload.kcp.dev_synctargets.yaml
- config/root-phase0/apiexport-workload.kcp.dev.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/apis/apis/v1alpha1/types_apiexport.go
- pkg/openapi/zz_generated.openapi.go
This partially reverts commit f0bb055536a435aa13381e7ee1c878df4b5e522c.
Setting the list-type to map won't work semantically as we plan to add additional fields into permission claims which would need to be part of the key.
The types need to stay atomic.
Partially reverts #2174
> 🐛 types_apibinding,types_apiexport: revert applied/export permission claims

- pkg/server/options/cache.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
points to a kubeconfig file for the cache server.
the config will be used by a kcp instance to establish a secure connection with the cache server. when a kubeconfig wasn't specify and the "run-cache-server" was provided the kcp will use the loop back client. assuming the cache server runs in the same process as the kcp server.
will be used in https://github.com/kcp-dev/kcp/pull/2132
> 🌱 cache: indroduce cache-server-kubeconfig-file flag

- pkg/server/options/options.go
when the cache server is run within kcp we need a copy of etcd options that have been completed with optional EmbeddedEtcd options.
Otherwise, the cache server is unable to connect to the etcd cluster.
> 🐛 cache: take into account EmbeddedEtcd options

- .github/workflows/ci.yaml
- config/rootcompute/bootstrap.go
- pkg/cliplugins/workload/plugin/sync.go
- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/reconciler/workload/apiexport/workload_apiexport_controller.go
- pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
- pkg/reconciler/workload/apiexport/workload_apiexport_reconcile_test.go
- pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
- pkg/reconciler/workload/defaultplacement/defaultplacement_indexes.go
- pkg/server/controllers.go
- pkg/syncer/resourcesync/controller.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
- test/e2e/reconciler/locationworkspace/synctarget_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- do not add apiresourceschmea in synctarget's local APIExport
- add exports flag in sync command
- setup syncer's rbac on physical cluster based on synctarget status.
This is to introduce the export flag in sync command. After this fix, the fix includes
- do not add apiresourceschmea in synctarget's local APIExport
- add exports flag in sync command
- setup syncer's rbac on physical cluster based on synctarget status.
After this change, the sync command will be changed:
1. run `kubectl kcp sync` without resource flag will sync resources in kubernetes APIExport in root:compute workspace
2. run `kubectl kcp sync --resources xxx` will sync both resources specified in the flag and kubernetes APIExport in root:compute workspace
3. run `kubectl kcp …
> ✨ Update kcp sync command to support global kubernetes APIExport

- pkg/admission/apiexport/OWNERS
- pkg/admission/apiexport/admission.go
- pkg/admission/apiexport/admission_test.go
- pkg/admission/plugins.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- pkg/virtual/apiexport/schemas/builtin/builtin.go
- pkg/virtual/apiexport/schemas/builtin/builtin_test.go
- pkg/virtual/framework/internalapis/import.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
- pkg/virtual/syncer/schemas/builtin/builtin.go
- pkg/virtual/syncer/schemas/builtin/builtin_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
This patch set includes two primary changes:
Update the APIResourceSchema generation to consider multiple versions of
an API and append the schemas to one ARS rather than generating a
separate ARS for each.
Adds an APIExport admission plugin that, for the time-being, only
validates that any permissionClaims for types that are not built-in
include an identityHash.
The first can be observed when creating an `APIExport` with `permissionClaims` on `FlowSchemas` or `PriorityLevelConfigurations`.
Before:
```
🤖 (kxp) k -s https://192.168.1.189:6443/services/apiexport/root/kxp.crossplane.io/clusters/* api-versions
apiextensions.crossplane.io/v1
apiextensions.crossplane.io/v1alpha1 …
```
> ✨ Check for identityHash in APIExport admission and support multiple versions for APIs in permission claims

- hack/logcheck.out
- pkg/syncer/namespace/namespace_downstream_process.go
- pkg/syncer/namespace/namespace_upstream_process.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/status/status_process.go
- pkg/syncer/syncer.go
- tmc/pkg/logging/constants.go
This PR fixes a small structured logging bug in the Syncer that was overriding the SyncTargetName structured logging value.
But most importantly, it isolates the tmc-related logging constants in a dedicated tmc-specific package, and . imports them so that code is more readable (see the discussion [here](https://kubernetes.slack.com/archives/C021U8WSAFK/p1666022954832189))
> 🐛 Isolate tmc-related logging constants in a dedicated package

- docs/syncer.md
Update the doc on sync command:
- document the change on default command
- document the change on --resources flag
- document the new --apiexports flag
Fixes #
> 📖  Update syncer doc on apiexports flag

- test/e2e/audit/audit_log_test.go
- test/e2e/framework/kcp.go
- test/e2e/homeworkspaces/home_workspaces_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Allows for providing a custom configuration when creating a `PrivateKcpServer`. Could be extended in the future to `SharedKcpServer`
It will be used in https://github.com/kcp-dev/kcp/pull/2132. The `PrivateKcpServer` will be created with `WithScratchDirectories`. The scratch directories will be shared with an instance of `the cache server`
> 🌱 e2e framework:  introduce KcpConfigOption function

- .github/workflows/docs-gen-and-push.yaml
- Makefile
- hack/generate/cli-doc/gen-cli-doc.go
- hack/generate/crd-ref/config.yaml
- hack/generate/crd-ref/crd.template.md
- hack/generate/crd-ref/run-crd-ref-gen.sh
- hack/verify-go-versions.sh
This GitHub Actions does the following:
- generates CLI docs
- generates CRD refs
- saves new tags as archive in gh-pages branch for doc versioning
- builds and deploys hugo docs to github pages
- depends on PR #2120
- depends on PR #2219
> :book: add github actions to push docs 

- pkg/reconciler/cache/replication/replication_controller.go
Since we don't anticipate a huge number of `APIExports` and `APIResourceSchemas` we have decided to replicate all instances of those resources by default.
Previously only objects with `internal.sharding.kcp.dev/replicate: "true"` were replicated.
Closes #https://github.com/kcp-dev/kcp/pull/2087
Closes #https://github.com/kcp-dev/kcp/pull/2116
> 🌱 cache: replicate all APIExports and APIResourceSchemas

- cmd/syncer/cmd/syncer.go
- hack/logcheck.out
cmd/syncer: switch to contextual logging
Part of #1694
> 🌱 cmd/syncer: switch to contextual logging

- .github/workflows/docs-gen-and-push.yaml
- docs/content/en/main/cli/_index.md
- Fix docs deploy github actions
- please create an orphan and empty `gh-pages` branch before merging this pr
```
git switch --orphan gh-pages
git commit --allow-empty -m "create empty gh-pages branch"
git push origin gh-pages
```
- ensure that GitHub Actions is set as source in GitHub Pages
https://avinal.space/kcp/main
> :book: Fix docs deploy github action

- pkg/server/server.go
> 🐛 kcp: run the embeeded cache server only when a kubeconfig was provided

- config/crds/apis.kcp.dev_apiexports.yaml
- docs/content/en/main/concepts/authorization.md
- pkg/apis/apis/v1alpha1/types_apiexport.go
- pkg/authorization/maximal_permission_policy_authorizer.go
- pkg/openapi/zz_generated.openapi.go
- pkg/server/options/authorization.go
- test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
In the advent of reverse permission claims the "API binding authorizer" name is too coarse grained. We're introducing a "reverse permission claim authorizer" which will also handle API bindings but we don't want to conflate the implementations of both.
Relates to #2089
> :seedling: pkg/authorization: rename apibinding_authorizer to maximal_permission_policy_authorizer

- pkg/cache/server/server.go
the logger object needs to be created when a webhook is created otherwise it can be accessed from multiple goroutines.
```
==================
WARNING: DATA RACE
Read at 0x00c000b59a28 by goroutine 212:
runtime.racereadrange()
<autogenerated>:1 +0x1b
k8s.io/apiserver/pkg/server.runPostStartHook.func1()
/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/server/hooks.go:198 +0xa1
k8s.io/apiserver/pkg/server.runPostStartHook()
/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cbf/pkg/server/hooks.go:199 +0xda
k8s.io/apiserver/pkg/server.(*GenericAPIServer).RunPostStartHooks.func2()
/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20221005071841-6cfb7d485cb …
```
> 🐛 cache: fix a datarace

- Dockerfile
Since #2202, container image builds were broken (https://github.com/kcp-dev/kcp/actions/workflows/kcp-image.yaml) because it moved tmc-related logging constants into a directory that was previously not copied as part of the `Dockerfile` COPY directives:
```
pkg/syncer/namespace/namespace_downstream_process.go:33:2: no required module provides package github.com/kcp-dev/kcp/tmc/pkg/logging; to add it:
go get github.com/kcp-dev/kcp/tmc/pkg/logging
```
This PR should fix that, re-enabling image builds (locally and via GitHub actions).
> :bug: Fix Dockerfile by copying tmc directory into build directory

- cmd/kubectl-kcp/cmd/kubectlKcp.go
- contrib/demos-unmaintained/demo/prototype3-script/apibinding/cert-manager-apibinding.yaml
- pkg/cliplugins/bind/cmd/cmd.go
- pkg/cliplugins/bind/plugin/bind.go
This PR adds a cli command for users to be able to bind to an APIExport.
```
kubectl kcp bind apiexport <ws_ref:export_obj> —-name <name of APIBinding> 
Required arguments 
- path of the APIExport to bind to. Needs to be the absolute reference to workspace.
Optional flag
Name - name of the apibinding which is created. It defaults to name of apiexport”
```
Example:
```
➜  kcp git:(cmd/kcp-bind) ✗ ./bin/kubectl-kcp bind apiexport root:webapp:cert-manager-stable
apibinding cert-manager-stable created. Waiting to successfully bind ...
cert-manager-stable created and bound.
```
Design doc: https://docs.google.com/document/d/1J31wXY1-2aCyyGFjUlusKoHDzV-zktAmRdIMjMf4OR0/edit 
Add command to help users bind to an APIExport.
> :sparkles: Add command to create APIBindings

- pkg/cliplugins/workspace/plugin/kubeconfig.go
Tree skips bottom if List returns notFound. Separate bug raised why it returns NotFound with custom Workspace type.
I understand this is not the fix, but more of patch. Root cause if 404 itself.
````
[mjudeikis@unknown kcp]$ go run ./cmd/kubectl-workspace/ tree
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(*errors.StatusError)(0xc0008ca780)(the server could not find the requested resource (get clusterworkspaces.tenancy.kcp.dev))
(*errors.StatusError)(0xc0008cac80)(the server could not find the requested resource (get clusterworkspaces.tenancy.kcp.dev))
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
.
└── root
├── compute
├── faros
│   └── default
├── faros-system
│   ├── controllers
│   └── tenants
└── users
```` …
> :bug: fix CLI tree not showing bottom leafs

- pkg/virtual/workspaces/builder/build.go
We added some metrics in #2246 but forgot to register them.
With this PR, we now see:
```
$ k --user shard-admin get --raw /metrics|grep workspace_authorizer
workspace_authorizer_caches{type="org"} 1
workspace_authorizer_caches{type="root"} 1
workspace_authorizer_invalidations{type="org"} 3
workspace_authorizer_invalidations{type="root"} 3
workspace_authorizer_sync_duration_seconds_bucket{result="skip",type="org",le="0.0001"} 55
.....
```
Fixes #
> 🌱 Register workspace authz metrics

- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/apis/apibinding/conflict_checker.go
- pkg/reconciler/apis/apibinding/conflict_checker_test.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- test/e2e/virtual/apiexport/apibindings_access_binding1.yaml
- test/e2e/virtual/apiexport/apibindings_access_binding2.yaml
- test/e2e/virtual/apiexport/apibindings_access_binding3.yaml
- test/e2e/virtual/apiexport/apibindings_access_export1.yaml
- test/e2e/virtual/apiexport/apibindings_access_export2.yaml
- test/e2e/virtual/apiexport/apibindings_access_export3.yaml
- test/e2e/virtual/apiexport/apibindings_access_schema1.yaml
- test/e2e/virtual/apiexport/apibindings_access_schema2.yaml
- test/e2e/virtual/apiexport/apibindings_access_schema3.yaml
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Fix bug in the APIExport virtual workspace that prevented it from including APIBindings for the APIExport when there wasn't a permission claim for APIBindings.
Switch from checking APIBinding phase for determining what actions to perform to instead always trying to resolve desired state.
Add e2e test for APIBindings with/without permission claims in the APIExport virtual workspace.
Fixes #1421
Fixes: #2181
> 🐛 Correctly serve APIBindings in the APIExport virtual workspace

- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
The upstreamInformers was part of NewStatusSyncer() signature but never used in the code. The signature is already long so we might as well remove what's not used.
Signed-off-by: Sébastien Han <seb@redhat.com>
Just code hygiene, not bound to an issue.
> 🌱 remove unused informer

- pkg/permissionclaim/permissionclaim_labeler.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
permissionclaim_labeler: use accepted claims in spec to drive labels
---
reconciler/permissionclaim: bump log level higher
---
/assign @ncdc
> :bug: permissionclaim_labeler: use accepted claims in spec to drive labels

- cmd/kubectl-kcp/cmd/kubectlKcp.go
- pkg/cliplugins/claims/cmd/cmd.go
- pkg/cliplugins/claims/plugin/claims.go
This PR adds command to get permission claims related to an APIBinding.
Example:
```
➜  kcp git:(cmd/permission-claim-get) ✗ kubectl-kcp claims get apibinding cert-manager
NAME                       BINDING            STATUS
group1-resource1    cert-manager   Rejected
group2-resource2   cert-manager   Rejected
```
```
➜  kcp git:(cmd/permission-claim-get) ✗ kubectl-kcp claims get apibinding
NAME                       BINDING            STATUS
group1-resource1    cert-manager   Rejected
group2-resource2   cert-manager   Rejected
group3-resource3   solo                   Accepted
```
Related design doc: https://docs.google.com/document/d/1J31wXY1-2aCyyGFjUlusKoHDzV-zktAmRdIMjMf4OR0/edit
> :sparkles: Add command for fetching permission claims

- cmd/test-server/kcp/shard.go
- hack/logcheck.out
cmd/test-server/kcp/shard.go: use contextual logging
Part of #1694
> 🌱 cmd/test-server/kcp/shard.go: use contextual logging

- README.md
The links to `additional documentation` (Concepts, Workspaces, etc) are broken, this PR fixes the links path
> 📖 Updated README.md links

- .github/workflows/ci.yaml
- Makefile
- test/e2e/audit/audit_log_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/authorizer/serviceaccounts_test.go
- test/e2e/framework/accessory.go
- test/e2e/framework/expect.go
- test/e2e/framework/kcp.go
- test/e2e/framework/syncer.go
- test/e2e/homeworkspaces/home_workspaces_test.go
- test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/syncer/tunnels_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
- test/e2e/workspacetype/controller_test.go
test/e2e: make sure tests actually run in parallel
---
test/e2e: be consistent about timeouts and poll intervals
---
test/e2e/workspacetype: poll, don't blindly wait for 5s
---
test/e2e/syncer: send one request, not many
You can't prove a negative, and eventually consistent systems don't like
to conform to your idea of "long enough" before synchronizing. We can't
assume that "nothing will happen" within 5s here. If we wanted to make
sure that the controller had seen & acknowledged the object, we should
have it post some observed generation.
Since these polls were not effective at best, and flaky at worst, we can
save 10s by just …
> :seedling: make: add non-kind shared and sharded e2e

- cmd/kcp/kcp.go
Before this PR, the help message contains the sentence
```
Advanced use cases including <list of advanced use cases>.
```
, which is incomplete. This PR fixes that.
> 📖 Fix grammar of kcp command help message

- pkg/syncer/namespace/namespace_downstream_process.go
- pkg/syncer/namespace/namespace_downstream_process_test.go
This PR adds an additional check (synctarget UID) when deleting downstream namespaces to avoid a reconciliation loop between different syncers from different kcp instances. (or for example, an old syncer from a previous KCP deployment)
related to: https://github.com/kcp-dev/kcp/issues/2041 (doesn't fix it as there are multiple root causes for that issue)
> :bug: Avoid syncers deleting namespace from other synctargets. 

- pkg/reconciler/kubequota/kubequota_controller.go
When there's a lot of churn in the types contained in `kcp`, the type-aware shared informer factory will be sending out a lot of notifications in a short window of time. The previous implementation used a single goroutine to consume the notifications, therefore restricting the allowed production throughput to the consumption throughput, leading to notifications being lost.
In order to be more resilient to this type of situation, we need to decouple consumption from production, and while we're doing that we do not want to hold on to a large number of pending notifications, nor do we want to duplicate work when many notifications are received during the handling of the first.
As the monitor update is idempotent, but not reentrant, we can utilize a workqueue with one worker to ensure that …
> :bug: quota: use a workqueue to manage updating monitors

- .github/workflows/ci.yaml
> :bug: .github: cache Go build output

- .github/workflows/ci.yaml
- Makefile
Depends on https://github.com/openshift/release/pull/33497
> :seedling: .github: restrict kind tests to those that require it

- test/e2e/framework/syncer.go
Fixes some flaky tests due to the syncer-dns pod not being in "running" state (synctarget heartbeat is sent by the syncer pod, and doesn't take into account the syncer-dns POD state.)
This is causing some e2e-shared tests to fail, due to the collecting of logs failing as the syncer-dns pod is not ready.
related to: https://github.com/kcp-dev/kcp/issues/2284
> :bug: test/e2e/framework: Don't try to pull logs from a non-ready POD

- pkg/cliplugins/workload/plugin/sync.go
- pkg/syncer/apiimporter.go
- pkg/syncer/resourcesync/controller.go
- pkg/syncer/syncer.go
syncer should only watch a certain synctarget, but not all synctarget in the workspace.
Fixes #
> 🐛 Fix: watch a certain synctarget only

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/shard.go
- cmd/sharded-test-server/virtual.go
This allows the -work-dir-path option to accept a path other than $PWD
Co-authored-by @ncdc - this is derived from his [shard-standalone-vw branch](https://github.com/hardys/kcp/commit/bf7cbeec5276aec5b4e84e9d54631307cb6b0c7c) which I'm breaking into a series of smaller commits/PRs
The  [shard-standalone-vw branch](https://github.com/hardys/kcp/commit/bf7cbeec5276aec5b4e84e9d54631307cb6b0c7c) adopts a client-cert auth model which we can reuse to resolve #2274 by switching to client-cert for the informer auth (the client-cert changes will be proposed via a subsequent PR)
> :seedling: sharded-test-server: consistently use workDirPath

- test/e2e/reconciler/cache/replication_test.go
The new test checks if an APIResourceSchema is propagated to the cache server.
The test exercises a creation, modification and removal of the APIExport object.
> 🌱 cache: add replicateAPIResourceSchema test scenario 

- test/e2e/reconciler/cache/helpers.go
- test/e2e/reconciler/cache/replication_test.go
This PR exports `StartStandaloneCache` and `CacheClientRoundTrippersFor` to start a standalone server and add the required `RT` for HTTP clients. I'll use in https://github.com/kcp-dev/kcp/pull/2256
> 🌱 cache:replication:e2e: export functions for working with the cache server

- pkg/cache/server/handler.go
It looks like that not all requests require a valid shard name. In order to make checking the health status of the cache server, this PR changes the `WithShardScope` to not require a shard name for `/livez, /readyz, /healthz` paths.
> 🌱 cache: WithShardScope doesn't require a shard name for well-know paths

- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
This PR fixes an incorrect cleaning of SyncTarget-related deletion annotations.
Fixes #2287
> 🐛 Fix incorrect cleaning of deletion annotations

- cmd/cache-server/main.go
- pkg/cache/server/options/options.go
- pkg/server/options/cache.go
adds a new flag (`root-directory`) to the cache server binary. The flag will be used by the `sharded-test-server` to the controller where the assets for the cache server are created.
In addition to that, it also exposes `o.EmbeddedEtcd.AddFlags(fs)` and `o.SecureServing.AddFlags(fs)` for the cache server binary. Those flags will be consumed by the `sharded-test-server` binary.
Lastly, it slightly changes the way options are used when the cache server runs in-process with kcp. That is, in that case the cache servers options are simply omitted because they overlap with the ones defined by kcp. This causes some undefined behavior. The issue will be eventually addressed by https://github.com/kcp-dev/kcp/issues/2021
> 🌱 add new flag (root-directory) for the cache server binary

- test/e2e/cache/cache_server_test.go
- test/e2e/reconciler/cache/helpers.go
- test/e2e/reconciler/cache/replication_test.go
adds the following e2e scenarios for testing behaviour of the cache server:
1. `TestSchemaIsNotEnforced` - for making sure an obj with any schema can be created
2. `TestShardClusterNamesAssigned` - for making sure that a shard name and a cluster name are passed in the annotations
3. `TestUIDGenerationCreationTimeOverwrite` - for making sure that `UID, Genaration, CreationTime` can be overwritten 
4. `TestUIDGenerationCreationTimeOverwriteNegative`  - for making sure that `UID, Genaration, CreationTime` are assigned by the server if the shard annotation is not provided
5. `TestGenerationOnSpecChanges` - for making sure that the Generation is not increased after updating the spec
6. `TestDeletionWithFinalizers` - for making sure that an object with some `Finalizers` can be deleted …
> 🌱 cache: add e2e scenarios for testing behaviour of the cache server

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/shard.go
- cmd/test-server/kcp/shard.go
- cmd/test-server/main.go
Decouple the steps to start the test server so we can define a new test-server, start it then call WaitForReady to ensure shard readiness
This is another change decoupled from the [shard-standalone-vw branch](https://github.com/hardys/kcp/commit/bf7cbeec5276aec5b4e84e9d54631307cb6b0c7c) from @ncdc
Follow-up to #2297 and another incremental step towards integrating the the [shard-standalone-vw branch](https://github.com/hardys/kcp/commit/bf7cbeec5276aec5b4e84e9d54631307cb6b0c7c) from @ncdc 
Fixes #
> :seedling: test-server: split New/Start/Ready phases

- config/helpers/bootstrap.go
- hack/logcheck.out
Make sure that when binding root APIs, we keep retrying updates until they succeed.
Fixes #2148
> 🐛 Fix root phase 0 bootstrapping sometimes failing

- config/crds/apis.kcp.dev_apibindings.yaml
- config/crds/apis.kcp.dev_apiexports.yaml
- go.mod
- go.sum
- pkg/apis/apis/v1alpha1/types_apiexport.go
- pkg/apis/apis/v1alpha1/types_apiexport_test.go
- pkg/openapi/zz_generated.openapi.go
This sets the fields `all` and `resourceSelector/namespace` optional.
Fixes https://github.com/kcp-dev/kcp/pull/2222#discussion_r1008530913
Fixes https://github.com/kcp-dev/kcp/pull/2222#discussion_r1008532082
> 🌱 types_apiexport: make all and resourceSelector/namespace optional

- hack/logcheck.out
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/builder/forwarding.go
- pkg/virtual/syncer/builder/template.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
- pkg/virtual/syncer/options/options.go
- pkg/virtual/syncer/upsyncer/storage_wrapper.go
- pkg/virtual/syncer/upsyncer/transformer.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Implementation of a VirtualWorkspace for the Upsync of resources (Downstream to Upstream). 
* Refactor the syncer virtual workspace to return multiple workpsaces
* New Upsync VW
* Transformations for the Upsync VW.
Fixes https://github.com/kcp-dev/kcp/issues/2141
> :sparkles: Implements Upsyncer Virtual Workspace

- pkg/proxy/options/authentication.go
This adds OIDC to the enabled optional auth methods
Follow-up to #2178
> :seedling: proxy: optionally enable OIDC auth

- README.md
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
The link to the developers doc is currently broken
Fixes #
> :book: Correcting the link to the developers doc

- Makefile
Go 1.19 will update files on a clean checkout if `make imports` is run;
require the user to acknowledge this with the IGNORE_GO_VERSION var.
/cc @csams
Fixes #
> 🌱 Protect imports target with Go version check

- pkg/indexers/apibinding.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller_test.go
- pkg/server/apiextensions.go
- pkg/server/controllers.go
- pkg/server/server.go
- test/e2e/apibinding/apibinding_deletion_test.go
When all API bindings that use a particular APIResourceSchema are deleted, the CRDs that back those bindings need to be deleted.
Fixes #2300
> :bug: Clean up shadow CRDs after API bindings are deleted

- cmd/sharded-test-server/shard.go
- cmd/sharded-test-server/shard_test.go
previously the ports were overlapping with a previous instance
needed by https://github.com/kcp-dev/kcp/issues/342
> 🐛 sharded-test-server: fix the way we calculate the embedded etcd client ports

- config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
- config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
- config/root/bootstrap.go
- config/root/clusterworkspaceshard.yaml
- config/root/secret-shard.yaml
- pkg/admission/clusterworkspaceshard/admission.go
- pkg/admission/clusterworkspaceshard/admission_test.go
- pkg/admission/clusterworkspacetypeexists/admission_test.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/openapi/zz_generated.openapi.go
- pkg/server/config.go
- pkg/server/server.go
Admission is not the right place to default the shard.status URLs values as it is run on the server side and the server side is always the root shard. This PR moves it into the server initialization "client-side".
> :bug: clusterworkspaceshard: fix admission and shard creation for multi-shard setups

- pkg/cliplugins/workload/plugin/sync.go
This PR fixes a typo and a discrepancy in the workspace reference format of the `kcp workload sync --apiexports` option usage.
> :bug: CLI: Fix sync command apiexports option usage

- go.mod
- pkg/proxy/mapping.go
- pkg/proxy/metrics/metrics.go
- pkg/proxy/proxy.go
- pkg/proxy/server.go
Add front proxy specific metrics to enable accurate SLO tracking across shards even in the case of a shard being down.
Fixes #2301
> :bug: Add request, latency, and workqueue metrics to front proxy

- pkg/syncer/namespace/namespace_downstream_controller.go
- pkg/syncer/namespace/namespace_upstream_controller.go
- pkg/syncer/resourcesync/controller.go
- pkg/syncer/spec/dns/dns_process.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process_test.go
We should:
- trigger the creation of the CoreDNS deployment (if not already created) by the Syncer on any resource syncing, at the condition that deployments are part of the synced GVRs for this synced target.
- wait for the CoreDNS deployment to be reachable through a service before syncing a resource, but only when syncing a deployment. In this case, the deployment resource should be requeued after a small delay.
Fixes flaky e2e tests
> 🐛 syncer: Fix wrong logic in dns-related process

- pkg/syncer/spec/mutators/deployment.go
- pkg/syncer/spec/mutators/deployment_test.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process_test.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/locationworkspace/rootcompute_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- Get the DNS IP address from the Service object.
- Rename BoundWorkspace to WorkspaceBound
Fixes #2365
> 🐛 Lookup DNS IP in Service

- config/root/clusterrole-scheduling-maximal-permission-policy.yaml
This PR fixes wrong `apiGroups` for sub-resources in the `scheduling.kcp.dev` group maximum permission policy cluster role.
> :bug: Fix group in scheduling.kcp.dev maximum permission policy cluster role

- pkg/cache/server/config.go
Since the `c.ApiExtensionsClusterClient` used by the apiextention server is wrapped into `rt` we cannot use protobuf. We maintain a custom `RoundTripper` that assumes json. This also means protobuf was never used before and it is safe to remove.
Fixes #
> 🐛 cache: do not use protobufs for self-communication

- pkg/cliplugins/workload/plugin/sync.go
- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/spec/spec_process.go
- test/e2e/framework/kcp.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
- test/e2e/reconciler/locationworkspace/rootcompute_test.go
- test/e2e/reconciler/locationworkspace/synctarget_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Signed-off-by: David Festal <dfestal@redhat.com>
Further cleanup to tmc-related e2e tests:
- we should always add the CRDs for deployments, services, endpoints in the fake pclusters, since they are now all required by the Syncer to correctly work.
- In a Syncer Virtual Workspace test, we should have been waiting for the Syncer finalizer bing set before trying to patch the resource.
- Rewite of the Syncer virtual workspace tests to avoid starting 2 syncers when it's not necessary.
- Cleanup the way Syncer are started to sync user workspaces, and remove the need of the `BoundWorkload` method.
Additional fixes on code bugs found at this occasion:
- Skip the `kcp-system` in namespace and resource scheduling (was obviously bringing much load for nothing)
- Small fix in the `workload sync` …
> 🐛 Further cleanup to tmc-related e2e tests

- pkg/syncer/apiimporter.go
🐛 Syncer: fix APIImporter broken after one recent rebase
Issue met while doing manual tests for PR https://github.com/kcp-dev/kcp/pull/2336
> 🐛 Syncer: fix APIImporter broken after one recent rebase

- pkg/cliplugins/bind/plugin/bind_compute.go
Provide more detailed error messages when the `bind compute` CLI command fails with a timeout error.
No related issue. Encountered this need when working on PR https://github.com/kcp-dev/kcp/pull/2336
> :bug: CLI: Better error messages to `bind compute`

- pkg/cliplugins/workspace/plugin/kubeconfig.go
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
When changing to a workspace where the user could not `GET` APIBindings, the 403 error would be bubbled up to the command's output.
This change ignores the error, since it's not actionable and is expected.
Fixes: #2390
> :bug: Ignore APIBinding 403 errors when changing WS

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- pkg/proxy/config.go
- pkg/proxy/options/options.go
- pkg/proxy/server.go
The front proxy needs a direct and privileged way of authNZ with any shard. At the same time it needs to be able to validate an incoming certificate from a shard.
This PR allows the above by introducing a kubeconfig that holds a client certificate and a CA certificate for validating incoming certs.
The new kubeconfig can be passed via `shards-kubeconfig` flag.
Previously an incorrect configuration was used for communication with shards. As a result the proxy didn't work in a multi shard environment.
required by https://github.com/kcp-dev/kcp/issues/342
fixes https://github.com/kcp-dev/kcp/issues/2274
> 🐛 give the front proxy a distinct config for direct(internal) shard communication.

- pkg/server/bootstrap/identity.go
- pkg/server/server.go
- pkg/virtual/apiexport/builder/forwarding.go
- pkg/virtual/framework/forwardingregistry/rest.go
- pkg/virtual/framework/forwardingregistry/rest_test.go
- pkg/virtual/framework/forwardingregistry/wrappers.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- pkg/virtual/syncer/upsyncer/storage_wrapper.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Fix a bug where wildcard requests coming from the APIExport virtual workspace for "built-in" kcp types (e.g. ClusterWorkspaceTypes) had the identity set by the virtual workspace, then set a second time by `decorateWildcardPathsWithResourceIdentities`.
Fixes #2184
Fixes #2308
Incorporates & supersedes #2245
> 🐛 Fix double identities for wildcard requests from APIExport virtual workspace

- pkg/cliplugins/bind/plugin/bind_compute.go
When binding a workspace to compute, if some of the apibindings is not ready, the `bind` cli will output an error like:
```
error: bind compute is not ready placement-23sk5wr9: not bound to apiexport 'root:compute:root:compute': Unable to bind APIs: naming conflict with a bound API kubernetes, spec.names.plural=pods is...
```
This error is confusing, as the workspace is duplicated, and doesn't specify the export name: 'root:compute:root:compute'
This PR changes it to include the name of the export, as in: 'root:compute:kubernetes'
> 🐛 cliplugins/bind: fix incorrect error message

- hack/logcheck.out
- pkg/server/controllers.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Move the following to contextual logging
- virtual apireconciler
- pkg/serve
Also disables the newly-introduced key name check for the time being.
Fixes #
> 🌱  Contextual logging fixes

- pkg/cliplugins/bind/plugin/bind_compute.go
- test/e2e/reconciler/namespace/controller_test.go
do not list synctarget during bind compute cmd, as it will bring authz issue.
Fixes https://github.com/kcp-dev/kcp/issues/2349
> 🐛 Remove list SyncTarget in bind compute cmd

- pkg/reconciler/committer/committer.go
Fix a bug introduced in #2458 that caused no-op patches to actually issue a `""` patch.
Fixes #2466
> 🐛 Fix no-op patches in committer

- pkg/syncer/namespace/namespace_downstream_controller.go
- pkg/syncer/spec/spec_controller.go
This Remaining fixes on downstream namespace cleaning in the Syncer
No dedicated issue.
This fixes issues found in the code when working on issue https://github.com/kcp-dev/kcp/issues/2358
> 🐛Syncer: Remaining fixes on downstream namespace cleaning

- .ci-operator.yaml
- .github/workflows/ci.yaml
- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/e2e-ci-ppc64le.yml
- .github/workflows/goreleaser.yml
- .github/workflows/kcp-image.yaml
- .github/workflows/kcp-test-image.yaml
- .github/workflows/syncer-image.yaml
- CONTRIBUTING.md
- Dockerfile
- cmd/sharded-test-server/doc.go
- docs/content/en/main/concepts/syncer.md
- docs/go.mod
- go.mod
- manifest/kcp.yaml
- pkg/apis/go.mod
- pkg/apis/third_party/conditions/util/conditions/merge.go
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
- pkg/virtual/framework/dynamic/apiserver/handler.go
- pkg/virtual/framework/dynamic/doc.go
- pkg/virtual/syncer/doc.go
- pkg/virtual/syncer/transformations/types.go
- test/e2e/fixtures/wildwest/client/clientset/versioned/fake/register.go
- test/e2e/fixtures/wildwest/client/clientset/versioned/scheme/register.go
This PR changes how we build KCP and provides an example on how to set the GOMEMLIMIT environment variable based on requests
Fixes #
> 🌱 Use Go 1.19, set GOMEMLIMIT in kcp manifest

- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
In some cases, especially when some concurrency occurs while creating the downstream namespace, the [syncer might need to `get` a just-created namespace](https://github.com/kcp-dev/kcp/blob/2d0e18c790b0d882ebb817c713c6301350f60bfa/pkg/syncer/spec/spec_process.go#L277).
But currently the `syncer` service account isn't granted the `get` permission on downstream namespaces, though it is granted both `list` and `watch`. This PR adds the `get` verb to the syncer cluster role.
No related issue. Bug identified during the tests of another PR.
> 🐛 Syncer: add 'get' permission on downstream namespaces

- pkg/authorization/bootstrap_policy_authorizer.go
- pkg/authorization/decorator.go
- pkg/authorization/decorator_test.go
- pkg/authorization/local_authorizer.go
- pkg/authorization/maximal_permission_policy_authorizer.go
- pkg/authorization/system_crd_authorizer.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
- pkg/authorization/workspace_content_authorizer_test.go
- pkg/server/options/authorization.go
- pkg/virtual/apiexport/builder/build.go
This is scavenging `DelegateAuthorization` from https://github.com/kcp-dev/kcp/pull/2089 to have delegation resons included in the kcp audit log.
Example for delegated authorization:
```
"authorization.k8s.io/decision": "allow",
"authorization.k8s.io/reason": "access granted",
"bootstrap.authorization.kcp.dev/decision": "Allowed",
"bootstrap.authorization.kcp.dev/reason": "bootstrap policy: RBAC: allowed by ClusterRoleBinding \"system:kcp:clusterworkspace:admin\" of ClusterRole \"cluster-admin\" to Group \"system:kcp:clusterworkspace:admin\"",
"content.authorization.kcp.dev/decision": "Allowed",
"content.authorization.kcp.dev/reason": "delegating due to \"root:e2e-org-b7zvn\" content policy: : systemcrd.authorization.kcp.dev: access granted", …
```
> 🌱 pkg/authorization: add delegation reason in audit

- config/rootcompute/kube-1.24/apiexport-kubernetes.k8s.io.yaml
- config/rootcompute/kube-1.24/clusterrole-kubernetes-maximal-permission-policy.yaml
- config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-maximal-permission-policy.yaml
the annotation should be added to all resources in root:compute workspace
Fixes https://github.com/kcp-dev/kcp/issues/2406
> 🐛 Add missing battery annotation for root-compute-workspace

- .github/workflows/goreleaser.yml
#2492 added testing goreleaser in CI, but the upcoming goreleaser action v4 for some reason no longer detects non-tagged commits and automatically enables snapshot mode. This is an attempt to do that. Please let me know if there is a cleaner way to do this in GH actions
Fixes #
> 🌱 goreleaser: distinguish tags and PRs

- pkg/server/filters/filters.go
kcp is rejecting (valid) calls to the root path of a cluster. With a default setup, the following error is returned:
```
$ kubectl get --raw='/'
[{
"metadata": {},
"status": "Failure",
"message": "unable to parse cluster: no `/` found in path root",
"reason": "BadRequest",
"code": 400
}]
```
This PR resolves this issue by fixing the parsing and removing the error. With this fix:
```
$ kubectl get --raw='/'
{
"paths": [
"/api",
"/api/v1",
"/apis",
"/apis/",
"/apis/admissionregistration.k8s.io",
"/apis/admissionregistration.k8s.io/v1",
"/apis/apiextensions.k8s.io",
...
]
}
```
> 🐛 Fix parsing of requests to root path of a workload cluster

- .github/workflows/docs-gen-and-push.yaml
The docs workflow was failing on tags because it was trying to move content to a directory that did not yet exist.
Fixes #2502
> 🐛 docs: mkdir before moving

- pkg/server/options/authentication.go
The quote used to highlight `admin.kubeconfig` in the error message [1] was closed using a backtick leading to a quote mismatch. So, just changed the quotes over there.  (just a simple change)
> :seedling: Correct the typo in an error message

- pkg/server/apiextensions.go
- pkg/server/apiextensions_test.go
- test/e2e/conformance/crd_partial_metadata_test.go
Fix should go in kcp/kubernetes (maybe?), this test captures the sequence of events leading up to the issue
Related to #2278 
/cc @ncdc @stevekuznetsov @sttts
> 🐛 Fix and add test to capture a race w/ partial metadata in cache

- pkg/softimpersonation/softimpersonation.go
`.Wrap` mutates the `WrapTransport` field of the given rest config. This should be covered as part of the shallow copy, however this is a dangerous coupling. This changes to `rest.CopyConfig` in order to have a guaranteed deep copy of the given rest config.
Fixes #2136
> 🐛 pkg/softimpersonation: deep copy rest config

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
Make the front proxy in sharded-test-server honor `--quiet`
Fixes #
> 🌱 sharded-test-server: add quiet support to front-proxy

- pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
- pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
Switch places that potentially might get a cache.DeletedFinalStateUnknown to use the deletion handling key function variant.
Fixes #
> 🌱 Use deletion handling keyfunc where needed

- test/e2e/framework/syncer.go
No clients set the context anymore, so this round-tripper does nothing.
> :seedling: test/e2e: remove MultiClusterRoundTripper

- .dockerignore
- Dockerfile
- Makefile
- hack/boilerplate/boilerplate.Dockerfile.txt
This PR also adds support for better caching when building layers
Fixes #798
> ✨ Use distroless/static:debug as base image

- .github/workflows/kcp-image.yaml
- Dockerfile
This changeset includes a few changes to optimize our github action builds to run under 10 minutes. In more details it:
- Switches from buildah to buildx, buildah has a really old version that doesn't support caching in Github actions (ubuntu repositories).
- Introduces a build matrix, which lets different platforms to run in parallel
- Introduces caching for docker build layers
- Switches from output variables (deprecated) to environment vars
Kind of related to #902
> 🌱 Use buildx to build KCP images

- pkg/authorization/decorator.go
- pkg/authorization/decorator_test.go
- pkg/server/config.go
Currently, double audit log entries are generated because the authorization chain is used multiple times. Examples:
1. Subject access reviews: kubernetes/pkg/registry/authorization/subjectaccessreview/rest.go
2. Escalation authorization: kubernetes/pkg/registry/rbac/escalation_check.go
3. bind authorization: kubernetes/pkg/registry/rbac/escalation_check.go
This prevents it by setting a context in the main handler authorization chain only.
Fixes #2500
> :bug: pkg/authorization: prevent double audit logs

- pkg/server/controllers.go
before this method was waiting for `syncedCh` which is handled by `waitForSync` method.
`syncedOptionalCh` is fulfilled by `kcp-start-optional-informers`hook.
Fixes #
> 🐛 kcp: fix waitForOptionalSync method to wait for a proper signal

- config/root-phase0/bootstrap.go
- pkg/admission/logicalcluster/admission.go
- pkg/admission/logicalcluster/admission_test.go
- pkg/admission/namespacelifecycle/admission.go
- pkg/admission/pathannotation/pathannotation_admission.go
- pkg/admission/workspace/admission.go
- pkg/admission/workspace/admission_test.go
- pkg/admission/workspacetypeexists/admission.go
- pkg/admission/workspacetypeexists/admission_test.go
- pkg/authorization/requiredgroups_authorizer.go
- pkg/index/index.go
- pkg/proxy/index/index_controller.go
- pkg/reconciler/core/logicalcluster/logicalcluster_reconcile.go
- pkg/reconciler/core/logicalcluster/logicalcluster_reconcile_url.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/server/home_workspaces.go
- pkg/server/localproxy.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
<details>
<summary>Script used to generate this</summary>
```
commit 226d0d24566680c029c1ccb558021e815d7d0071
Author: Steve Kuznetsov <skuznets@redhat.com>
Date:   Wed Dec 21 07:22:28 2022 -0700
automated refactor
diff --git a/go.mod b/go.mod
index dcad2074..98cf850f 100644
--- a/go.mod
+++ b/go.mod
@@ -9,6 +9,7 @@ require (
github.com/bombsimon/logrusr/v3 v3.0.0
github.com/coredns/caddy v1.1.1
github.com/coredns/coredns v1.9.3
+	github.com/dave/dst v0.27.2
github.com/egymgmbh/go-prefix-writer v0.0.0-20180609083313-7326ea162eca
github.com/emicklei/go-restful v2.9.5+incompatible
github.com/evanphx/json-patch v5.6.0+incompatible
@@ -34,6 +35,7 @@ require (
go.etcd.io/etcd/server/v3 v3.5.0
go.uber.org/multierr v1.7.0
golang.org/x/net …
```
> :seedling: :*: use 'logicalCluster' instead of 'this'

- .goreleaser.yaml
Add `CGO_ENABLED=to` to `.goreleaser.yaml`.
I downloaded kcp 0.10.0 from [the release page](https://github.com/kcp-dev/kcp/releases/tag/v0.10.0)  and executed it on `Ubuntu 18.04.06 LTS`, but got the following error.
```
ubuntu@ip-XXX-XXX-XXX-XXX:~$ ./bin/kcp 
./bin/kcp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./bin/kcp)
./bin/kcp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bin/kcp)
ubuntu@ip-XXX-XXX-XXX-XXX:~$ ls -la  /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 May  3  2022 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so
```
It seems that kcp doesn't need CGO and [Dockerfile](https://github.com/kcp-dev/kcp/blob/2b5c1f10d964b2ddb682564a5bfc37c3e958243c/Dockerfile#L27) is already built with …
> :seedling: Update .goreleaser.yaml to build binaries with CGO_ENABLED=0

- Makefile
> :bug: Add missing CGO_ENABLED flag in the install makefile target

- .github/workflows/kcp-image.yaml
By using a matrix github actions spins up different VMs to build these images, upon pushing tags and the manifest, the different VMs have no information about the other builds, so each build context will build and push a manifest only for its own image.
Fixes #
> 🐛 Docker build/push should not use a matrix

- go.mod
- go.sum
cel-go: update to pull in data race fix
Fixes #2548
> 🐛 cel-go: update to pull in data race fix

- pkg/reconciler/workload/resource/resource_reconcile.go
Resources upsynced from a downstream cluster, and thus having the `Upsync` label should not be taken in account by resource scheduling.
No issue dedicated. Spotted while testing PR https://github.com/kcp-dev/kcp/pull/2338
> 🌱 Skip upsynced resources in resource scheduling

- test/e2e/authorizer/authorizer_test.go
/healthz /livez /readyz and /version
Fixes #
> 🌱  Add authorizer test for static endpoints

- pkg/authorization/workspace_content_authorizer_test.go
- pkg/cliplugins/bind/plugin/bind.go
- pkg/cliplugins/workload/plugin/sync.go
Follow-ups of https://github.com/kcp-dev/kcp/pull/2510.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
It probably isn't descriptive enough.
> :seedling: follow-ups of workspace refactor

- .github/workflows/kcp-image.yaml
- Dockerfile
- hack/verify-go-versions.sh
The compilation of the binaries in the builder stage of the container image is very slow when QEMU is used: 
```
#44 [linux/amd64 builder 11/11] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     make
#44 881.5 ln -sf kubectl-workspace bin/kubectl-workspaces
#44 881.5 ln -sf kubectl-workspace bin/kubectl-ws
#44 DONE 882.2s
#49 [linux/arm64 builder 11/11] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     make
#49 5526.2 ln -sf kubectl-workspace bin/kubectl-workspaces
#49 5526.3 ln -sf kubectl-workspace bin/kubectl-ws
#49 DONE 5527.0s
#50 [linux/ppc64le builder 11/11] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=cache,target=/go/pkg/mod     make
#50 5266.1 ln -sf …
```
> :seedling: Cross-compile container image binaries from host platform

- test/e2e/reconciler/deployment/deployment_coordinator_test.go
Add a check in the Deployment Coordinator e2e test, that will try to list deployment, to validate they are correctly exposed by the root compute APIExport URL, before starting the deployment coordinator.
This should help debugging the flake recorded in issue #2501
> 🌱 Debug deployment coordinator e2e

- pkg/reconciler/tenancy/workspace/workspace_controller.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile.go
- pkg/server/controllers.go
This means we can bootstrap without relying on the shard BaseURL, which may not be available during bootstrapping e.g if the endpoint is behind a k8s service controlled by a readiness probe
> :bug: workspace controller: use loopback client for local shard

- go.mod
- go.sum
> :seedling: Switch cel-go to upstream v0.12.6

- pkg/admission/kubequota/kubequota_admission.go
- pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go
- pkg/proxy/index/index_controller.go
- pkg/reconciler/garbagecollector/garbagecollector_controller.go
- pkg/reconciler/kubequota/kubequota_controller.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
This renames a couple of occurences of clusterworkspace to logicalcluster.
some more text.
some more text.
some more text.
some more text.
some more text.
some more text.
some more text.
some more text.
https://github.com/kcp-dev/kcp/pull/2510
> 🌱 cluster workspace rename

- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller_test.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Fix bug in the APIExport virtual workspace where the APIDefinitionSet was sometimes calculated incorrectly. When an APIResourceSchema informer event came in, we were supposed to enqueue all APIExports in the same logical cluster, but instead it was accidentally trying to enqueue the APIResourceSchema itself.
Fixes #2501
> 🐛 Fix APIExport virtual workspace API bug

- config/crds/tenancy.kcp.io_workspaces.yaml
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
- pkg/admission/workspace/admission.go
- pkg/admission/workspace/admission_test.go
- pkg/apis/tenancy/projection/workspaces.go
- pkg/apis/tenancy/v1beta1/types.go
- pkg/apis/tenancy/v1beta1/types_workspace_test.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/cliplugins/workspace/plugin/kubeconfig_test.go
- pkg/index/index.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
- pkg/server/home_workspaces.go
- test/e2e/reconciler/clusterworkspace/controller_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
- test/e2e/workspacetype/controller_test.go
In order to preserve the URL field, given that Status may be wiped under a number of conditions and most times URL cannot be easily or at all reconstructured, this changeset moves the field under Spec.
In addition, now the admission code also checks that any modification to the URL is performed by a system user.
Fixes #
> ⚠️ Move Workspace.Status.{Cluster, URL} to Spec

- cmd/sharded-test-server/cache.go
- pkg/cache/server/bootstrap/bootstrap.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/identitycache/api_export_identity_controller.go
- pkg/reconciler/apis/identitycache/api_export_identity_reconcile.go
- pkg/reconciler/apis/identitycache/api_export_identity_reconcile_test.go
- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/server/bootstrap/identity.go
- pkg/server/config.go
- pkg/server/controllers.go
- pkg/server/server.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- wire the cache informers into the relevant controllers that are needed to create and initialize a workspace.
- add workspace types to replication to the cache server
- fix workspace initialization VW on a non-root shard
- add `--location-selector` flag to `kubectl ws create` plugin
> :sparkles: server: wire cache informers instead of root informers

- pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
Strongly type the params used in our enqueue functions to avoid accidentally enqueueing the wrong kind of object.
Fixes #
> 🌱 crdcleanup: strongly type enqueue params

- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Strongly type the params used in our enqueue functions to avoid accidentally enqueueing the wrong kind of object.
Fixes #
> 🌱 vw/apiexport: strongly type enqueue params

- config/crds/workload.kcp.io_synctargets.yaml
- config/root-phase0/apiexport-workload.kcp.io.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
- pkg/apis/workload/v1alpha1/synctarget_types.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/workload/synctarget/synctarget_reconcile.go
- pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
- pkg/syncer/syncer.go
- pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
- test/e2e/framework/syncer.go
To prepare for the Upsyncing support, on the Synctarget we should have distinct URLs for the both syncer and upsyncer
virtual workspaces.
Pre-requisite to PR https://github.com/kcp-dev/kcp/pull/2452
> ✨ Synctarget: Have URLs for both syncer and upsyncer

- hack/verify-contextual-logging.sh
> 🌱 verify-contextual-logging should diff from old to new

- hack/logcheck.out
- pkg/informer/informer.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/syncer/controllermanager/controllermanager.go
- pkg/syncer/endpoints/endpoint_downstream_controller.go
- pkg/syncer/indexers/indexes.go
- pkg/syncer/namespace/namespace_downstream_controller.go
- pkg/syncer/resourcesync/controller.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/shared/helpers.go
- pkg/syncer/shared/namespace.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
PROOF PR of a refactoring of the Syncer to use common ddsif informer factories for all the Syncer + other controllers.
It also includes a controller manager, which allows starting / stopping GVR-specific controllers when new GVRs are supported in the list of Synced resources.
It is based on the work done on the ddsif in PR https://github.com/kcp-dev/kcp/pull/2440
No related issue. But it is a pre-requisite to the merge of PRs like https://github.com/kcp-dev/kcp/pull/2338
> ✨ Refactor Syncer based on the enhanced ddsif, with controller manager and endpoints controller

- Makefile
- hack/verify-contextual-logging.sh
This patch also disables the check for logger keys against upstream naming conventions
Fixes #2538
>  🌱 Update logcheck to 0.4.0

- pkg/reconciler/committer/committer.go
Extract common code from scoped and non-scoped committer functions.
> :sparkles: DRY committer factory functions

- .golangci.yaml
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/cache/replication/replication_reconcile_test.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
Maybe fixing the npe flake.
Maybe fixing the npe flake.
Maybe fixing the npe flake.
Maybe fixing the npe flake.
Maybe fixing the npe flake.
> :bug: reconciler/cache: remove reflection and fix replicate+NotFound logic

- pkg/reconciler/committer/statusless_committer.go
The old bytes comparison was always false.
> :bug: committer: fix equality check in statusless committer

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/apibinding_admission_test.go
- pkg/admission/workspacetypeexists/admission.go
- pkg/admission/workspacetypeexists/admission_test.go
- pkg/authorization/delegated/authorizer.go
- pkg/authorization/delegated/caching_authorizer.go
- pkg/virtual/apiexport/authorizer/content.go
- pkg/virtual/apiexport/authorizer/maximal_permission_policy.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/syncer/builder/template.go
This changeset is scoped to the virtual/initializingworkspace package.
Fixes #
> 🌱 Use caching authorizers per-workspace in initializingworkspaces/builder

- test/e2e/framework/kcp.go
Otherwise we end up with zero-length audit logs in CI...
For example see [this](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/kcp-dev_kcp/2594/pull-ci-kcp-dev-kcp-main-e2e/1613198333013135360/artifacts/e2e/e2e/artifacts/TestUserHomeWorkspaces/Create_a_workspace_in_the_non-existing_home_and_have_it_created_automatically_through_~/3662491291/artifacts/kcp/main/) - AFAICS all tests using PrivateKcpServer have this problem because we only set the audit-policy flag in the [SharedKcpServer fixture](https://github.com/kcp-dev/kcp/blob/main/test/e2e/framework/kcp.go#L151)
> :bug: e2e: PrivateKcpServer enable audit-policy

- pkg/indexers/indexers.go
I think IndexByLogicalClusterPathAndName should return clusterPath+Name by default?
Fixes #
> 🐛 IndexByLogicalClusterPathAndName should return clusterpath and name

- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/cache/replication/replication_reconcile_test.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured_test.go
- pkg/server/controllers.go
Generalized to host more resources more easily and simplified whole flow.
Generalized to host more resources more easily and simplified whole flow.
Generalized to host more resources more easily and simplified whole flow.
Generalized to host more resources more easily and simplified whole flow.
Generalized to host more resources more easily and simplified whole flow.
> :seedling: reconciler/cache/reconciler: simplify and generalize

- test/e2e/audit/audit_log_test.go
This decouples scratch directory creation from the `PrivateKcpServer` fixture, so that we can log to the regular artifactDir location (which means the log data will show up in saved CI job artifacts), and avoid the duplicate flag and associated test cleanup.
Follows on from #2591 to ensure audit log output shows up in the saved CI artifacts for all tests.
> :seedling: e2e: TestAuditLogs remove duplicate audit-log-path

- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
- pkg/virtual/framework/wrappers/rbac/merging.go
- pkg/virtual/framework/wrappers/rbac/merging_test.go
This PR also reverts 0831b69e29298cb6d6561d9cfa0a200882155ef7
Fixes #
> :bug: Role and ClusterRole merger should not modify cache objects

- .github/workflows/ci.yaml
- Makefile
> 🌱 Enable KUBE_CACHE_MUTATION_DETECTOR in e2e tests

- .github/workflows/ci.yaml
- test/e2e/kind/config-calico.yaml
Default kind configuration does not support network policies. This PR modifies the kind configuration disabling kindnet and install Calico.
/cc @davidfestal
> :sparkles:  Install Calico in kind for CI testing

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/binding_permissions.go
- pkg/admission/apiexportendpointslice/apiexportendpointslice_admission.go
- pkg/admission/apiexportendpointslice/apiexportendpointslice_admission_test.go
- pkg/admission/apiexportendpointslice/validation.go
- pkg/admission/plugins.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
check for binding authorization against the referenced APIExport.
Contributes to #2332
> :sparkles: Admission for APIExportEndpointSlice

- config/rootcompute/kube-1.24/clusterrole-kubernetes-apiexport-bind.yaml
- config/rootcompute/kube-1.24/clusterrolebinding-kubernetes-apiexport-bind.yaml
Fixes https://github.com/kcp-dev/kcp/issues/2597
> 🐛 Add bind permission for kubernetes apiexport

- test/e2e/virtual/apiexport/authorizer_test.go
This makes the e2e test for virtual apiexport authorizer self-contained. The `apply` method will be used to add new e2e tests asserting existing issues.
> 🌱 test/e2e/virtual/apiexport: make authorizer test self-contained

- cmd/sharded-test-server/main.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/cache/replication_test.go
previously all scenarios were run in a private environment. After the change only the scenarios that are disruptive run in a sandbox, the rest is run on a shared kcp instance (either on a single or multi-shard env)
This change allows us to run non-disruptive scenarios on a multi-shard cluster.
https://github.com/kcp-dev/kcp/pull/2596
https://github.com/kcp-dev/kcp/issues/2269
> 🌱 run replication tests on a shared kcp instance

- pkg/admission/apibinding/apibinding_admission.go
Cleaning up fields that seem to be unused in APIBinding admission.
> :seedling: Admission cleanup

- pkg/reconciler/scheduling/location/location_controller.go
Update the location controller to use the committer package.
#2635 
> :seedling: location_controller uses committer

- pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
Switch from storing listers/indexers as struct fields to using function pointers to implement listing/getting data from the informer caches.
> 🌱 extraannotationsync: use function pointers

- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
This fixes failed local sharded startup failures. The observed symptom was:
```
- apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
annotations:
kcp.io/cluster: system:shard
creationTimestamp: "2023-01-18T14:29:39Z"
finalizers:
- apis.kcp.io/apibinding-finalizer
generation: 1
labels:
internal.apis.kcp.io/export: bmCdly9xXiUpEHe3ypvDwvXMTfoVZUE92mqAQf
name: tenancy.kcp.io
resourceVersion: "195"
uid: 9cf38f12-663c-4673-84be-b5aae0cb4bdc
spec:
reference:
export:
name: tenancy.kcp.io
path: root
status:
conditions:
- lastTransitionTime: "2023-01-18T14:29:42Z"
message: 'Unable to bind APIs: error checking for naming conflicts for APIBinding
system:shard|tenancy.kcp.io: error getting CRDs: APIResourceSchema.apis.kcp.io
"v220628-546034da.negotiatedapiresources.apiresource.kcp.io" not …
```
> 🐛 pkg/reconciler/apis/apibinding: return error in case of conflicts

- test/e2e/watchcache/watchcache_enabled_test.go
previously the tests were trying to create content in a workspace by providing a full path which couldn't have been resolved by the local proxy.
xref: https://github.com/kcp-dev/kcp/pull/2596
> 🐛 e2e/watchcache: use cluster client for creating content in a workspace

- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/server/controllers.go
since `Shard` resources are only on the root shard the `apiexport` controller must use the global (cached) informer otherwise the list will always be empty on a non-root shard.
xref: https://github.com/kcp-dev/kcp/pull/2596
> 🐛 reconciler/apiexport: use the gloabl informer to get Shards

- test/e2e/conversion/conversion_test.go
> 🐛 e2e/conversion: wrap create in eventually

- Makefile
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/shard.go
- cmd/sharded-test-server/virtual.go
- cmd/virtual-workspaces/command/cmd.go
- pkg/server/config.go
- pkg/server/controllers.go
- pkg/server/handler.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
This is another change decoupled from the [shard-standalone-vw branch](https://github.com/hardys/kcp/commit/bf7cbeec5276aec5b4e84e9d54631307cb6b0c7c) from @ncdc
Follow up to ##2297 and #2303 which also merged changes from the WIP branch
Fixes #2254
Fixes #2056
> :bug: add support for standalone virtualworkspace server

- pkg/server/controllers.go
In #2407 we introduced this validation, but it doesn't handle the case where the VW server is not standalone, but you still want to specify `--shard-virtual-workspace-url`
This scenario is likely when deploying a sharded environment, since you'll want the VW traffic to go via the front-proxy regardless of whether the VW server is standalone or not.
Fixes an issue introduced via #2407
> :bug: server: relax ShardVirtualWorkspace flag validation

- test/e2e/framework/workspaces.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/deployment/deployment_coordinator_test.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
- test/e2e/reconciler/locationworkspace/rootcompute_test.go
- test/e2e/reconciler/locationworkspace/synctarget_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/api_compatibility_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/syncer/dns/dns_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/syncer/tunnels_test.go
the issue will be eventually addressed in kcp-dev#2649
https://github.com/kcp-dev/kcp/pull/2596
> 🐛 e2e: temporarily schedule all workspaces on the root shard for tmc-related tests

- pkg/server/controllers.go
since Shard resources are only on the root shard all controllers must use the global (cached) informer otherwise the list will always be empty on a non-root shard.
xref: https://github.com/kcp-dev/kcp/pull/2596
> 🐛 controller: use the global informer to get Shards

- config/crds/apis.kcp.io_apibindings.yaml
- pkg/admission/webhook/generic_webhook.go
- pkg/admission/webhook/generic_webhook_test.go
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Look up APIExports by name, not path, within the generic webhook.
Adds a new required field that the APIBinding reconciler sets: `APIBinding.Status.LogicalCluster`.
Fixes #2622
> 🐛 Use APIExport cluster names within webhooks

- docs/content/en/main/concepts/authorization.md
Drops a trailing parentheses in the link to the ASCII diagram for authorization.
n/a
> 🌱 Remove trailing parentheses in ASCII diagram link

- cmd/test-server/main.go
- test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/framework/kcp.go
- test/e2e/framework/util.go
- test/e2e/virtual/apiexport/authorizer_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
- test/e2e/workspacetype/controller_test.go
This adds support to generate users on the fly in e2e tests. Currently, only users predefined in a token fixture file can be used. This allows for more descriptive user names and also allows adding groups dynamically.
N/A
> 🌱 test/e2e: add support for dynamic users using client certs

- pkg/server/controllers.go
Partially reverts logic introduced in #2407 so we don't unconditionally use the external URL - when non-standalone VW mode is used we still need the old behavior, or the loopback client can't access the non-standalone VW server.
This breaks shard bootstrapping (evidently not in our e2e scenarios, but in a real deployment where probes mean the proxy isn't ready until the shard bootstrap is complete)
I suspect further work will be required to make standalone VW mode work when deployed on a real cluster, since the ExternalAddress will go via the proxy, which depends on proxy bootstrapping (when the shard is deployed via a Service)
> :bug: server: revert non-standalone VW URL

- pkg/server/config.go
- pkg/server/requestinfo/kcp_request_info_resolver.go
Add a kcp-specific RequestInfoResolver that can populate a RequestInfo from a /services/... URL. This is needed so the code that proxies a virtual workspace request knows if it's a watch request or not. If so, it avoids adding a 1-minute deadline to the request.
Fixes at least one cause of #2479
> 🐛 Add a kcp RequestInfoResolver

- pkg/authorization/decorator.go
- pkg/authorization/decorator_test.go
- pkg/authorization/requiredgroups_authorizer_test.go
- pkg/authorization/workspace_content_authorizer_test.go
- pkg/server/config.go
- pkg/server/options/authorization.go
- test/e2e/audit/audit_log_test.go
This PR:
- adds domain annotation for audit logging: this allows separating regular workspace requests (`request.auth.kcp.io` domain) vs. SAR requests (`sar.auth.kcp.io`)
- in case of SAR request: audit are created for the actual SAR authorization review and not for the create authorization request. This allows debugging why a SAR denies.
- adds numbering of authorizers in audit logs so the ordering is clear
- removes audit logging of delegation reasons for more concise audit log entries. Reasons of delegated authorizers can be inspected in the corresponding audit annotation of the delegated authorizer.
Audit example for a SAR request:
```
"annotations": {
"apiserver.latency.k8s.io/response-write": "3µs",
"apiserver.latency.k8s.io/serialize-response-object": "155.625µs", …
```
> 🌱 pkg/authorization: enable audit logging for SAR requests

- pkg/apis/core/v1alpha1/logicalcluster_types.go
- pkg/apis/tenancy/v1alpha1/types_workspace.go
The phase is now represented in the status rather than in labels.
n/a
> 🐛 Use status.phase as printer column on workspaces and logical clusters

- pkg/syncer/spec/spec_process_test.go
Make sure the informer factories have synced the specific GVRs we care about in the test before clearing test client actions. This way, we know we won't get watch actions from the informers after we've cleared the actions, which is what was causing the flakiness.
🤞 that this fixes the issue.
Fixes #2589
> 🐛 Deflake TestSpecSyncerProcess

- test/e2e/framework/workspaces.go
The value of `ws` previously would have been mutated by the `Eventually()` call after this cleanup, leading to a race when cleanup occurred during workspace initialization. We don't expect the name of the workspace to ever change, so it's appropriate to capture the name before registering eleanup and simply assuming the name is static.
Fixes #2693
> :bug: test/e2e: remove a data race

- pkg/admission/webhook/generic_webhook.go
- pkg/admission/webhook/generic_webhook_test.go
- pkg/reconciler/workload/resource/resource_controller.go
The generic webhook was still using an APIExport lookup to determine cluster name, when all it needed to do was return a value off the APIBinding.
Also cleaned up some NotFound noise from the resource controller.
Fixes #2622
> 🐛 Do not look up APIExports in the generic webhook

- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
This  PR introduces end-to-end tests covering APIExportEndpointSlice reconcilation.
Contributes to #2332
> :seedling: End-to-end tests for APIExportEndpointSlice

- README.md
Signed-off-by: Paolo Dettori <dettori@us.ibm.com>
Update the Quickstart guide to add the `kcp bind compute` command so that first time users can successfully sync a deployment to a sync cluster. Also, update example command for syncer to use the latest release (v0.10.0)
#2697 
#2655
> :book: document kcp bind commmand to allow to sync deployment in quickstart

- .github/workflows/docs-gen-and-push.yaml
- docs/config.toml
- fixes the issue where a wrong folder name causes the command to
exit, the expected action is renaming the folder rather than
moving, fixes #2502
- fixes directory names for older versions. the github.ref is
a variable with "refs/tags/$REF" structure, for releases $REF
is of "vMAJOR.MINOR.PATCH" format, the archived docs directory
must be named as version tag
- fixes push permissions for pushing to gh-pages brnach. the
github action by default cannot push to branches, fixes #2655
- changes some links to relative links. this will help test the
docs locally s well as a separate deployments
No longer needed: #2656
See the deployment here: https://github.avinal.space/kcp/main/
- Utilize the homepage of the docs to show all the versions available, currently it shows nothing: …
> :book: fix docs versioning and permissions for gh-pages

- pkg/indexers/apiexport.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- test/e2e/virtual/apiexport/authorizer_test.go
Fix a gap in the APIExport virtual workspace queueing where it was possible to incorrectly return a "not found" error when trying to list a claimed resource. The gap was that we weren't queueing the dependent APIExports; i.e., if APIExport A gets updated, and APIExport B has a permission claim on A's identity, we need to make sure to queue B in this situation.
Fixes #2713
> 🐛 Fix gap in APIExport virtual workspace queues

- config/crds/core.kcp.io_logicalclusters.yaml
- config/root-phase0/apiresourceschema-logicalclusters.core.kcp.io.yaml
- hack/update-codegen-crds.sh
This fixes a typo in codegen, which induces the saving of newly generated crds not in the expected directory.
> :bug: Fix typo breaking codegen: crds not stored at the right location

- test/e2e/quota/quota_test.go
Properly check for forbidden errors within Eventually blocks
Fixes #2685
> 🐛 Deflake quota e2e

- Makefile
The `clean` target was added in https://github.com/kcp-dev/kcp/pull/2562 but doesn't currently work due to the wildcard in the `GOBIN_DIR` test.
Also following some discussion on slack about cleanup for the `.kcp*` directories I added cleanup so we can more easily switch between e.g shared/sharded e2e tests locally e.g `make clean test-e2e-sharded-minimal`
> :bug: Fix Makefile clean target and add .kcp cleanup

- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/builder/forwarding.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/framework/forwardingregistry/rest.go
- pkg/virtual/framework/forwardingregistry/rest_test.go
- pkg/virtual/framework/forwardingregistry/store.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- pkg/virtual/syncer/builder/forwarding.go
- test/e2e/virtual/apiexport/authorizer_test.go
- test/e2e/virtual/apiexport/binding_test.go
Currently, privilege escalation can be provoked when creating APIBindings
for exported resources.
This fixes it by impersonating virtual API export requests with a
service account that is bound to the requested workspace.
Fixes https://github.com/kcp-dev/kcp/issues/2239
> 🐛 Fix API binding privilege escalation

- Makefile
- cmd/sharded-test-server/main.go
- cmd/test-server/main.go
- config/root/bootstrap.go
- go.mod
- pkg/server/config.go
- pkg/server/home_workspaces.go
- pkg/server/options/flags.go
- pkg/server/options/homeworkspaces.go
- pkg/server/server.go
- test/e2e/framework/accessory.go
- test/e2e/framework/kcp.go
- test/e2e/homeworkspaces/home_workspaces_test.go
- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
- test/e2e/virtual/apiexport/authorizer_test.go
- remove deprecated home workspaces fields
- add waiting for unmanaged servers in e2e
Can split into separate PRs if desired
> 🌱 remove deprecated home workspaces fields, add waiting for unmanaged servers in e2e

- test/e2e/apibinding/apibinding_deletion_test.go
- test/e2e/apibinding/apibinding_permissionclaims_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/conversion/conversion_test.go
- test/e2e/fixtures/apifixtures/apibinding.go
- test/e2e/framework/util.go
- test/e2e/garbagecollector/garbagecollector_test.go
- test/e2e/quota/quota_test.go
- test/e2e/reconciler/apiexport/apiexport_controller_test.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
- test/e2e/reconciler/locationworkspace/synctarget_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/api_compatibility_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspacedeletion/controller_test.go
- test/e2e/virtual/apiexport/authorizer_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
> :seedling:  test/e2e: DRY up waiting on conditions

- Dockerfile
Currently the image can't be built e.g with podman unless `--format=docker` is used, because SHELL isn't in the OCI spec - we can remove it and instead specify the shell directly in the RUN.
> :seedling: Dockerfile: remove SHELL for OCI compliance

- cmd/sharded-test-server/main.go
This PR changes `sharded-test-server` binary so that it reuses various cryptographic certificates (i.e CAs or ClientCerts) instead of always creating new ones.
This allows for preserving a previous environment created by the binary. (yes, you can run `sharded-test-server` multiple times!)
**Note**  it will work as long as the default IP address stays the same. We could change that as well but that would make the code a bit more complex. Given that most of us run `make clean-workdir` before anyway I think it is a good starting point.
Fixes #https://github.com/kcp-dev/kcp/issues/2726
> 🐛 cmd/sharded-test-server: Reuse Certificates instead of generating new ones

- docs/content/en/main/concepts/syncer.md
In one of the kcp bind compute --apiexports has been added as --apiexport and if user tries to copy paste the same into his command line it throws an error which reads "unknown flag --apiexport" so fixing the same in docs
Fixes #
> :book: Fix unknown flag --apiexport

- README.md
1. Show the output of `kubectl kcp bind`.
2. Be clear about when the kind cluster needs to be running.
3. Warn that the use of the root workspace to hold workload source is unusual.
4. s/and/or/ where needed.
5. Note one of the places (the one with a web UI) where CI puts built images.
Fixes #
> :book: Brush up TMC quickstart

- pkg/cliplugins/workspace/cmd/cmd.go
Drops the kubectl kcp workspace get example from help output as it is not a valid command.
n/a
> 🐛 Drop non-existent workspace get command from help output

- .gitignore
- Makefile
Proposing a small change to the Makefile so it is possible to do 
KIND_CLUSTER_NAME=foo build-kind-images 
Which is nice to have when testing scheduling on multiple clusters.
Also, proposing to have a tmp folder in .gitignore where each developer can store temporary files, and get rid of .DS_Store files on mac.
Fixes #
> 🌱 Small improvements to dev workflow

- pkg/syncer/syncer.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/deployment/deployment_coordinator_test.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/locationworkspace/multiple_apiexports_test.go
- test/e2e/reconciler/locationworkspace/rootcompute_test.go
- test/e2e/reconciler/locationworkspace/synctarget_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/api_compatibility_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/syncer/dns/dns_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/syncer/tunnels_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Split the `SyncerFixture` start method to provide a way to only maintain Synctarget heartbeat and import apis, without
effectively syncing upstream resources.
No related issue, but this is required in order to avoid conflicting with the e2e tests of the Upsyncer virtual workspace with the implementation of the Upsyncer controller (on the Syncer side) is merged.
This will also allow lighter e2e tests for all the tests that don't need effective syncing of resources to the downstream cluster.
> 🌱 tmc e2e : Split SyncerFixture

- pkg/reconciler/workload/resource/resource_controller.go
- pkg/reconciler/workload/resource/resource_reconcile.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
This PR fixes an issue with upsynced resources getting it's state changed into "Sync" when the initial synctarget is gone or unhealthy.
If the resource is upsynced, check if the synctarget still exists, if not, delete the resource, if the synctarget still exists, do nothing, exit early.
- https://github.com/kcp-dev/kcp/pull/2730
Fixes https://github.com/kcp-dev/kcp/issues/2530
> :bug: workload/resource: handle upsynced resources

- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
Fix a possible flake where the referenced APIExport may not be available on the cache server before the APIExportEndpointSlice is created.
Fixes #2740
> :bug: E2E failing on APIExportEndpointSlice creation (flake)

- test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
Upsynced test was created, requiring a real k8s cluster to run. This is not truly necessary so we can remove that requirement.
> :bug: test/e2e/scheduling: don't require kind for upsynced test

- Makefile
Fixed the actual bug, without requirement tools, the target `install` doesn't check requirements and target `build` doesn't exit compiling.
Fixes #2759
> 🐛 Fix make install doesn't exit without required tools

- pkg/proxy/mapping.go
- pkg/proxy/server.go
To simplify deployment we want the `/readyz` and `/livez` not be handled by the regular auth chain. This allows us to use simple httpGet kube probes.
Related helm chart update: https://github.com/kcp-dev/helm-charts/pull/24
> 🌱 /pkg/proxy/server: handle /readyz and /livez outside of the auth chain

- Makefile
Newer versions of git have a security measure in place to prevent git from parsing the .git/config file or running any hooks if the user running git is not the owner of the repository files. Prow runs as a random UID, which is not guaranteed to be the same as the UID that owns the cloned files, so this change disables the ownership check and considers all cloned repositories "safe" regardless of owner.
Fixes #
> 🌱 Fix git in Prow

- pkg/tunneler/podsubresourceproxy_handler.go
When the KCPSyncerTunnel feature is enabled, the podsubresourceproxy_handler outputs an error log line that's not an error and is too verbose:
```
E0208 19:18:24.074484 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:27.150451 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:28.073389 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:28.746808 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:30.579766 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:31.075186 1740192 podsubresourceproxy_handler.go:113] "no cluster found in the context"
E0208 19:18:32.343049 1740192 …
```
> 🐛 pkg/tunneler: remove non-error verbose log

- test/e2e/framework/kcp.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
TMC E2E: Attempt at fixing Syncer virtual workspace e2e test flakes.
Not sure it would fix them all, but at east it fixes a possible cause, and increases log details (through the use of `framework.Eventually` instead of `require.Eventually`
Fixes #
> 🐛 tmc e2e: fix Syncer virtual workspace e2e test flakes

- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
- pkg/syncer/shared/helpers.go
- pkg/syncer/shared/namespace.go
- pkg/syncer/spec/dns/dns_process.go
- pkg/syncer/spec/dns/dns_process_test.go
- pkg/syncer/spec/dns/networkpolicy_dns.yaml
- pkg/syncer/spec/dns/resources.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/syncer.go
- test/e2e/fixtures/kube/networking.k8s.io_networkpolicies.yaml
- test/e2e/framework/kcp.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/syncer/dns/dns_test.go
Restrict access to DNS pods to workspace associated to them. Also, make sure DNS pods have only access to CoreDNS pods.
This is enforced by create this networking policy, one per workspace:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: Name
namespace: Namespace
spec:
podSelector:
matchLabels:
app: Name
policyTypes:
- Ingress
- Egress
ingress:
- from:
- namespaceSelector:
matchLabels:
internal.workload.kcp.io/cluster: Cluster # workspace key
ports:
- protocol: TCP
port: 5353
- protocol: UDP
port: 5353
egress:
- to:
- namespaceSelector:
matchLabels:
kubernetes.io/metadata.name: kube-system
- podSelector:
matchLabels:
k8s-app: kube-dns
ports:
- protocol: TCP
port: 53
- protocol: UDP
port: 53
- to:
- ipBlock:
cidr: APIServerIP/32
ports:
- protocol: TCP
port: 6443 …
```
> :sparkles: Adding DNS network policies

- pkg/reconciler/workload/placement/placement_controller.go
We cannot directly read the logicalcluster path from synctarget to get the related placement, since the value of that path is not unique. Instead, we need to get the location of the related synctarget at first, which always has the path annotation.
Fixes  https://github.com/kcp-dev/kcp/issues/2579
> 🐛 Enqueue location upon synctarget update

- pkg/reconciler/garbagecollector/garbagecollector_controller.go
- pkg/reconciler/kubequota/kubequota_controller.go
Run the initial monitor syncing in a goroutine to avoid any stalling here to block a worker.
Maybe #1878 #2665
> 🐛 Prevent gc/quota workqueue backlogs

- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
> 🌱 syncer vw: add API definition logging

- docs/content/en/GOALS.md
The link for `investigations directory` in [docs website](https://docs.kcp.io/kcp/main/en/GOALS/#process) is pointing to a 404 page. It might be good to point to the investigations folder in GitHub instead of 404 page.
> 📖 Update link for investigations directory

- pkg/cliplugins/bind/plugin/bind.go
- pkg/cliplugins/bind/plugin/bind_test.go
> 🐛 Only validate the path component of a fully-qualified `APIExport` ref

- .github/workflows/ci.yaml
- .gitignore
- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- cmd/test-server/kcp/shard.go
- cmd/test-server/main.go
- go.mod
- hack/run-with-prometheus.sh
- test/e2e/framework/kcp.go
- test/e2e/framework/util.go
This adds support for scraping metrics via Prometheus for e2e tests and local shard testing. If the environment variable `PROMETHEUS_URL` is set, scraping targets are being configured automatically.
For e2e tests, `ARTIFACT_DIR` needs to be set additionally.
This is the first part of adding scraping support. The second part will add wiring in CI.
> 🌱 test/e2e,cmd/test: scrape metrics for test servers and e2e tests

- pkg/reconciler/scheduling/placement/placement_controller.go
- pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go
- test/e2e/reconciler/scheduling/controller_test.go
It happens when setting the alternative workspace name on placement, which needs to be considered during scheduling
Fixes https://github.com/kcp-dev/kcp/issues/2737https://github.com/kcp-dev/kcp/issues/2737
> 🐛 Fix location cannot be found by placement during scheduling

- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
introduces an annotation that can be used to indicate that a shard is unschedulable. The annotation is meant to be used by e2e tests that otherwise started a private instance of kcp server.
I decided to go with an annotation because it is easier to change/delete than an API field.
Fixes #
> 🌱 workspace_reconcile_scheduling: allow for skipping a shard with a special annotation during scheduling

- pkg/cliplugins/workspace/plugin/kubeconfig.go
Today, a user has to write `kubectl kcp ws '~'` to go home, as most shells will expand `~` to the home directory path before passing the argument to our CLI. This is awkward and we can do better.
We know that the literal content of the user's home directory cannot be a valid workspace name, since we don't allow path separators in workspace names. So, we can just handle the case where the argument we got *is* the home directory just like we handle it being `~`.
/assign @mjudeikis
> :bug: cli: honor expanded `~` in kcp ws

- Makefile
- cmd/sharded-test-server/cache.go
- cmd/sharded-test-server/main.go
- pkg/cache/server/config.go
- pkg/cache/server/handler.go
- pkg/cache/server/options/options.go
/cc @ncdc 
/assign @p0lyn0mial
> :sparkles: cache: add a synthetic delay to the cache server

- pkg/syncer/upsync/upsync_process_test.go
- pkg/syncer/upsync/upsync_reconcile.go
🐛 Fix nil pointer error in the Upsyncer reconcile
No issue related.
> 🐛 Fix nil pointer error in the Upsyncer reconcile

- test/e2e/framework/kcp.go
This PR makes DirectOrGoRunCommand func in the test framework aware of the deployment-coordinator being moved to tmc/cmd.
> 🌱 Make DirectOrGoRunCommand aware of the deployment-coordinator being moved to tmc/cmd

- pkg/cliplugins/workload/plugin/sync.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/deployment/deployment_coordinator_test.go
This PR adds a --labels flag to be used for setting labels in the SyncTarget created by `kcp workload sync`, thus allowing to easier to test scenarios like the east/west workload placement described in [this PR](https://github.com/kcp-dev/kcp/pull/2336) (it is not required anymore to patch SyncTarget after they are created).
The same capability is added to the `syncerFixture` in the test framework
> 🌱 Add --labels to kubectl kcp workload sync

- pkg/cliplugins/workload/plugin/sync.go
Add `access` verb to default syncer cluster role for `NonResourceURLs: /`
> :bug:  Add verb `access`to syncer

- pkg/syncer/spec/mutators/podspecable.go
- pkg/syncer/spec/mutators/podspecable_test.go
- pkg/syncer/spec/mutators/secrets.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/syncer.go
- Also mutate the `StatefulSet`s and the `ReplicaSet`s as it is done for the `Deployment`s
- Extract the mutators from the SpecSyncer (will make it easier to disable them in alternate syncers)
Fixes #2844
> ✨ Syncer: also mutate `StatefulSet`s and `ReplicaSet`s

- cmd/crd-puller/pull-crds.go
Provide an additional flag (--resources-to-sync) to specify which CRDs the user wants to pull.
Note: If the flag is not used or is empty, the default behavior(pull all CRDs on the cluster) is followed.
Typical usage is as shown below:
`go run cmd/crd-puller/pull-crds.go --kubeconfig /home/bnr/.kube/config --resources-to-sync "pods,services,deployments"`
https://github.com/kcp-dev/kcp/issues/839
Fixes #839
> ✨ Add a flag to crd-puller to specify only the required CRDs that needs to be synced

- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
- test/e2e/reconciler/workspace/controller_test.go
The spec.URL in workspace should use canonicalPath
The spec.URL of workspace should use canonicalPath instead of absolute path.
Fixes https://github.com/kcp-dev/kcp/issues/2737
> 🐛 Fix the spec.URL in workspace using canonicalPath

- config/crds/apis.kcp.io_apibindings.yaml
- config/crds/apis.kcp.io_apiexports.yaml
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/apis/apis/v1alpha1/types_apiexport.go
Adds column for readiness of apibinding and apiexport:
```
[mjudeikis@unknown2 kcp]$ k get apiexport 
NAME                 AGE   READY
apiresource.kcp.io   13d   True
scheduling.kcp.io    13d   True
shards.core.kcp.io   13d   True
tenancy.kcp.io       13d   True
topology.kcp.io      13d   True
workload.kcp.io      13d   True
[mjudeikis@unknown2 kcp]$ k get apibinding
NAME                 AGE   READY
apiresource.kcp.io   13d   True
scheduling.kcp.io    13d   True
shards.core.kcp.io   13d   True
tenancy.kcp.io       13d   True
topology.kcp.io      13d   True
workload.kcp.io      13d   True
```
Fixes #2182
> :sparkles: Add Ready column to `APIBinding` and `APIExport`

- pkg/syncer/syncer.go
- pkg/syncer/tunneler.go
- pkg/syncer/tunneler_test.go
- pkg/tunneler/podsubresourceproxy_handler.go
- test/e2e/framework/syncer.go
- test/e2e/syncer/tunnels_test.go
This PR adds an extra layer of security at the syncer side of the tunneler to ensure that the proxied requests are against a namespace owned by the syncer and a pod in upsync state. 
Fixes https://github.com/kcp-dev/kcp/issues/1975
> 🌱  Tunnel: Validate namespace/pod at the syncer side

- pkg/features/kcp_features.go
- test/e2e/syncer/tunnels_test.go
This PR enables the SyncerTunel feature-gate by default.
Fixes #
> ✨ Enable the SyncerTunnel featuregate by default

- docs/content/concepts/rest-access-patterns.md
- docs/content/developers/etcd-structure.md
> 📖 docs: add rest access patterns, etcd storage path

- config/crds/tenancy.kcp.io_workspacetypes.yaml
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
- pkg/apis/tenancy/v1alpha1/types_workspacetype.go
- pkg/openapi/zz_generated.openapi.go
https://github.com/kcp-dev/kcp/pull/2569 follow-up
> :seedling: rename ClusterWorkspace to Workspace

- pkg/tunneler/podsubresourceproxy_handler.go
This PR sends a Retry-after to the client when the tunneler handler can't find the reverse connection dialer, this will help in some cases and mitigate the "syncer tunnels: tunnel closed" issues. 
related to https://github.com/kcp-dev/kcp/issues/2886
> :bug: tunneler: return retry-after when dialer not ready

- pkg/server/config.go
This PR adds the tunnel subresource (used by the syncer reverse tunnel) to the `LongRunningFunc` filter function. That is done to avoid the default timeout of 60s when accessing the tunnel subresource; this will fix the current issue where the Syncer tunnel is disconnected every minute, improving the end-user experience when accessing pods logs/exec... 
Fixes https://github.com/kcp-dev/kcp/issues/2886
> :bug: Disable default apiserver timeout (60s) for Syncer tunnel connection

- pkg/authorization/maximal_permission_policy_authorizer.go
This adds a delegation reason for the maximal permission policy authorizer. Currently a not very meaningful message is added in the audit logs in case no relevant API bindings have been found:
```
$ cat audit.log | jq .
{
"kind": "Event",
...
"annotations": {
...
"request.auth.kcp.io/04-maxpermissionpolicy-decision": "Allowed",
"request.auth.kcp.io/04-maxpermissionpolicy-reason": "05-bootstrap: access granted",
...
}
}
```
This changes the above message to:
```
"request.auth.kcp.io/04-maxpermissionpolicy-reason": "delegating due to no relevant binding found",
```
N/A
/cc @hardys @sttts
> 🌱 pkg/authorization/maxpermpolicy: add delegation reason

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/shard.go
- pkg/admission/logicalcluster/admission.go
- pkg/admission/logicalcluster/admission_test.go
- pkg/authorization/bootstrap/policy.go
- pkg/authorization/requiredgroups_authorizer.go
- pkg/authorization/requiredgroups_authorizer_test.go
- pkg/proxy/options/authentication.go
- pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
- pkg/reconciler/tenancy/workspace/workspace_controller.go
- pkg/server/config.go
- pkg/server/controllers.go
- pkg/server/options/options.go
- pkg/server/server.go
Currently the logical cluster admin kubeconfig is used to access both the [external front-proxy endpoint](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_controller.go#L194..L195), and also the [shard directly via the baseURL](https://github.com/kcp-dev/kcp/blob/main/pkg/reconciler/tenancy/workspace/workspace_reconcile.go#L71..L72) - this won't work in the case where different CA certs are used for shard and front-proxy (such as in the [helm-charts](https://github.com/kcp-dev/helm-charts))
This only works in CI because we use the same serving-ca.crt for both shard and front-proxy, (in a future PR I will propose a change which better reflects the likely scenario in production deployments).
Fixes #2872
> :bug: Decouple internal and external logical-cluster-admin access

- docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
> 🌱 fix some typos in the syncer documentation

- pkg/reconciler/workload/synctarget/synctarget_reconcile.go
- pkg/reconciler/workload/synctarget/synctarget_reconcile_test.go
- test/e2e/framework/kcp.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/deployment/deployment_coordinator_test.go
- test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
- test/e2e/syncer/tunnels_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
First step towars sharding support for TMC e2e tests
This PR is a prefactored PR coming from PR https://github.com/kcp-dev/kcp/pull/2675
#2834
> 🌱 TMC E2E tests sharding support - step 1

- config/crds/workload.kcp.io_synctargets.yaml
- config/root-phase0/apiexport-workload.kcp.io.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.io.yaml
- docs/content/concepts/registering-kubernetes-clusters-using-syncer.md
- pkg/cliplugins/workload/plugin/sync.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/workload/apiexport/apiresourceschema.go
- pkg/reconciler/workload/apiexport/workload_apiexport_controller.go
- pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go
- pkg/reconciler/workload/apiexport/workload_apiexport_reconcile_test.go
- pkg/reconciler/workload/defaultlocation/defaultlocation_controller.go
- pkg/reconciler/workload/synctargetexports/synctarget_indexes.go
- pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
- sdk/apis/workload/v1alpha1/synctarget_types.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/locationworkspace/local_apiexport_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/reconciler/scheduling/upsynced_scheduling_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- tmc/pkg/server/controllers.go
- tmc/pkg/server/server.go
- tmc/pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_indexes.go
1. create imported-api APIExport during sync cmd if resources flag is set
2. controller updated imported-api APIExport with updated APIResourceSchema
Fixes https://github.com/kcp-dev/kcp/issues/2625
> 🐛 Remove root:compute deps in controller

- pkg/reconciler/workload/placement/placement_controller.go
- pkg/reconciler/workload/placement/placement_reconcile.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
- tmc/pkg/server/controllers.go
Signed-off-by: Nolan Brubaker <nolan@nbrubaker.com>
Add cache informer for locations in placement controller.
Part of #2900
> 🌱 Add cache informers for synctargets/locations in placement controller

- docs/content/CONTRIBUTING.md
While we have this code structure in some controllers, it's useful to document for contributors.
> :book: Document data types that are replicated

- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
- pkg/reconciler/workload/namespace/namespace_reconcile_placementbind.go
- pkg/reconciler/workload/namespace/namespace_reconcile_placementbind_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile_status.go
- pkg/reconciler/workload/namespace/namespace_reconcile_status_test.go
- sdk/apis/scheduling/v1alpha1/types_location.go
1. Switch committer to allow changes to both spec/meta and status in the same reconcile loop. If both were changed, only the spec/meta patch is sent. If nothing else changes, the presumption is the status patch will go through on the next reconcile iteration.
2. Switch workload/namespace controller to use committer. This involved removing the individual places where it was sending namespace patches directly and replacing them with calculating the desired state of the namespace in the reconcile logic. Then, after reconcile() is done, the committer will send a patch if needed.
Part of #2635
> 🌱 Switch workload/namespace controller to use committer

- pkg/reconciler/workload/replicateclusterrole/replicateclusterrole_controller.go
- pkg/reconciler/workload/replicateclusterrolebinding/replicateclusterrolebinding_controller.go
- pkg/reconciler/workload/replicatelogicalcluster/replicatelogicalcluster_controller.go
- test/e2e/reconciler/cache/replication_test.go
- tmc/pkg/server/controllers.go
- tmc/pkg/server/server.go
The SyncTarget-related cluster roles and cluster role bindings, as well as logical clusters, should be replicated in order to have the Syncer virtual workspace work correctly.
This is a split of PR https://github.com/kcp-dev/kcp/pull/2675
> 🌱 Replicating SyncTarget-related rbac and logicalclusters objects

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apiexportendpointslice/apiexportendpointslice_admission.go
- pkg/admission/workspacetypeexists/admission.go
- pkg/authorization/maximal_permission_policy_authorizer.go
- pkg/indexers/indexers.go
- pkg/permissionclaim/permissionclaim_labeler.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
- pkg/reconciler/workload/placement/placement_controller.go
Every single consumer of these functions operating over replicated data needs to use the same exact pattern to access their data. There's no need to make them all duplicate the logic.
/cc @nrb @sttts 
/assign @p0lyn0mial
> :sparkles: pkg/indexers: add helers for cache server fallback

- pkg/informer/fallback_lookup.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/reconciler/workload/synctarget/synctarget_controller.go
- pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go
- tmc/pkg/server/controllers.go
- Use SyncTargets cache in resource controller
- Add cache lookup to SyncTarget(Export) controllers
Fixes #2900
> :seedling: Add cache lookup to TMC controllers

- pkg/reconciler/scheduling/placement/placement_controller.go
- pkg/reconciler/scheduling/placement/placement_reconcile.go
- pkg/reconciler/workload/placement/placement_controller.go
- tmc/pkg/server/controllers.go
Use cached informers in scheduling controllers.
Fixes #2900
> 🌱 Use cached informers in scheduling controllers

- docs/content/CONTRIBUTING.md
fixes #2904 
Does not improve the verify-go-versions.sh script which uses a hardcoded high level go version "1".
Fixes #
> 📖 Update CONTRIBUTING.md re golang version

- GOVERNANCE.md
- OWNERS
- SECURITY.md
This PR adds a GOVERNANCE.md file inspired by CNCF's Project Governance template https://github.com/carolynvs/cncf-project-template/blob/79bce741b54f33f1e81a313b0b077e2dd79c0096/GOVERNANCE-maintainer.md.
The main changes are:
1. a manifesto of goals to be a good Kube citizen is added
2. a set of values to be an open and inclusive project are added
3. a bootstrap set of maintainers is defined which are going to be replaced by maintainers following "the rules".
This PR also removes former Red Hat maintainers from the OWNERs file, and replaces them with volunteers from the community of interested parties who want to see kcp to continue under its own governance.
This PR must be lgmt'ed and approved by Red Hat's former maintainers.
> :seedling: Bootstrap governance

- docs/content/developers/rebasing-kubernetes.md
Add documentation on the rebase process.
> 📖 Add rebase documentation

- GOVERNANCE.md
For more consistency: kcp is lower-case.
> :bug: GOVERNANCE.md: lower-case kcp outside of captions

- pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
Taken from @ncdc's rebase https://github.com/kcp-dev/kcp/pull/2945
> :bug: tenancy: only delete LogicalCluster if needed

- pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
- pkg/reconciler/core/replicateclusterrolebinding/replicateclusterrolebinding_controller.go
Taken from @ncdc's rebase PR https://github.com/kcp-dev/kcp/pull/2945.
> :bug: cache: only enqueue ClusterRoleBindings for the right logical cluster

- .ci-operator.yaml
- .prow.yaml
- hack/verify-go-versions.sh
This moves the Prowjobs that were previously part of the openshift/release repo into a simple in-repo configuration (i.e. a `.prow.yaml`).
I combined the various verify tasks into a single `pull-kcp-verify` job, but had to pull the codegen task out into its own Prow job, as running it as part of other tasks seems to make it get stuck and I have not further investigated why. `client-gen` seems to just sit forever (I checked the pod, CPU usage was basically idling).
part of kcp-dev/infra#43
```release-note
NONE
```
> :seedling: Add Prowjobs

- .github/workflows/kcp-image.yaml
- .prow.yaml
- Dockerfile
- hack/build-image.sh
- hack/verify-go-versions.sh
This PR is part 1 of 2 to convert the Github Workflow for building the kcp container image innto a regular Prowjob. Part 2 will happen in the infra repository, as the postsubmit will need elevated credentials and so has to be maintained there.
I've used buildah to build the image because that's what I'm used to and it seems to work just fine.
part of kcp-dev/infra#43
```release-note
NONE
```
> 🌱 Add images Prowjob

- docs/content/CONTRIBUTING.md
Fix typo in the link to the prow job in the documentation.
> :book: Fix typo in CONTRIBUTING.md

- Makefile
```
(⎈|kind-kind:N/A)➜  kcp git:(main) make help
Makefile                       Build the project
Makefile                       Show this help.
Makefile                       Install the project
Makefile                       Run go mod tidy to ensure modules are up to date
Makefile                       Vendor the dependencies
Makefile                       Verify go modules are up to date
```
with this change:
```console
(⎈|kind-kind:N/A)➜  kcp git:(makefile) make help
build                          Build the project
clean-workdir                  Clean workdir
clean                          Clean all
codegen                        Generate all
crds                           Generate crds
deploy-docs                    Deploy docs
download-e2e-logs              Download e2e logs from a …
```
> :bug:  make help

- docs/content/developers/publishing-a-new-kcp-release.md
I would like to cherry-pick #2988 for two reasons:
1. The release process for 0.20 as documented on the release branch is incorrect since 0.20 is the first release under community governance and using Prow for automation. Now we likely will never release a 0.20.1 and instead move to 0.21.0.
2. However, we also never published 0.20 documentation. The reason for that I believe is the GitHub Actions triggers not running when the `release-*` branch is first created. A push event to the branch would be necessary, which we could achieve with a simple cherry-pick PR like this one being merged.
Therefore I would like to merge at least one commit to `release-0.20`, so we get documentation deployed to docs.kcp.io. it might not be strictly necessary and the docs are probably outdated, but I think it …
> [release-0.20] 📖  update release process doc

- pkg/proxy/options/options.go
- pkg/proxy/server.go
The APIserver config already has a flag to configure allowed CORS origins, but the front-proxy does not use the APIServer options and so did not get this flag. This PR adds it to the proxy's options to make the flag available.
```release-note
Add `--cors-allowed-origins` flag to kcp-front-proxy
```
> :sparkles: Add --cors-allowed-origins flag to kcp-front-proxy

- README.md
The readme still references community meeting issues, but we have now moved to a Google doc. This updates it accordingly.
I also believe that the community calendar might be dead, there are no entries on it and we also don't mention it on kcp.io. So maybe it's time to remove that reference as well to avoid confusion. The agenda document has dates, and should therefore help figuring out when the next community meeting happens.
Fixes #
```release-note
NONE
```
> :book: Update README to include link to community meeting agenda doc

- OWNERS
Implementing https://groups.google.com/g/kcp-dev/c/mwUkINOiMjQ after @scheeles's +1 (and mine of course as I proposed them to get added).
```release-note
NONE
```
> :seedling: Add new maintainers

- test/e2e/framework/workspaces.go
Our e2e tests are very unstable and flake a lot. Since they seem to be stable when run locally, we suspect it's related to Prow jobs performing poorly.
This PR will not fix the issue completely, but hopefully improves the situation by waiting longer for workspaces to initialize. The current theory is that tests interfere too much with each other (e.g. by competing for shared resources like disks), and we will need to fix this on the infrastructure level. To be discussed.
xref #2995
```release-note
NONE
```
> :seedling: Increase workspace init timeout in e2e tests to 60 seconds

- README.md
- code-of-conduct.md
We are joining the CNCF as Sandbox project, and as such are subject to the CNCF CoC. I would suggest this PR as a way to adopting it and fulfil the onboarding requirement. 
Fixes #
```release-note
NONE
```
> 📖 Adopt CNCF Code of Conduct

- hack/verify-go-versions.sh
Prow go version is not checked in go version checking CI so it was missed in rebase ;/ 
Fixes #
```release-note
NONE
```
> :bug:  prow fix go version validate

- .prow.yaml
This PR increases the memory and cpu requests on Prow jobs for e2e tests to ensure that they get their own nodes with minimal interference. At the same time, it adds `run_if_changed` to ensure that we no longer run e2e tests on non-code changes.
In addition, I'm reducing the number of runs in `pull-kcp-test-e2e-multiple-runs` from 3 to 2. That should be "good enough" while reducing the runtime of the job by one third.
Fixes #
```release-note
NONE
```
> :seedling: Increase resource requests on Prow jobs but only run if code changed

- pkg/crdpuller/discovery.go
- pkg/informer/informer_test.go
- pkg/server/scheme/scheme.go
- pkg/virtual/apiexport/schemas/builtin/builtin.go
Attempt to add CRDs to built-in types so they could be claimed
Fixes #
```release-note
CRD resources are now part of Built-in types. 
```
> :sparkles:  Add CRDs to built-in types

- pkg/admission/mutatingwebhook/plugin.go
- pkg/admission/validatingwebhook/plugin.go
Each time `informer.Informer().AddEventHandler` is called go routine is spanned to monitor the event.
`configuration.NewMutatingWebhookConfigurationManagerForInformer` does just that so each time `plugin.Admit` is called we span a go routine. And so it infinity; 
Fixes https://github.com/kcp-dev/kcp/issues/3016
```release-note
NONE
```
> :bug: Memory leak fix in mutating & validating webhooks

- pkg/proxy/options/authentication.go
Fix frontproxy deployment 
Fixes #
```release-note
NONE
```
> :bug: Fix frontproxy

- config/root-phase0/metrics-cluster-role-binding.yaml
- config/root-phase0/metrics-cluster-role.yaml
- config/root-phase0/metrics-service-account-secret.yaml
- config/root-phase0/metrics-service-account.yaml
- pkg/server/options/batteries/batteries.go
While hunting down OOM/go-routine issue found that I needed to setup metrics scrapping. For this I needed service account to access them. Where it is easily done, I found this uslefull for few reasons;
1. I did it multiple times myself so it kinda got to the place - its need to be in the batteries
2. When using TILT, it does not have a clear phases approach. It usually - You deploy everything and wait. So I ended up maintaining a separate job just to deploy this into KCP with dependency created:
`KCP -> Job -> Prometheus`
Having this tilt case becomes - "While deploying Prometheus, read this secret and configure scraping and removing job out of the picture"
Fixes #
```release-note
NONE
```
> :seedling:  Add metrics-viewer 'battery'

- pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor.go
- pkg/reconciler/core/logicalclusterdeletion/deletion/logicalcluster_resource_deletor_test.go
- pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
- pkg/server/controllers.go
Skip deleting bound resources in the logicalcluster deletor as this can
race with the apibinding deletion controller. If the apibinding deletion
controller deletes an APIBinding and all its instances and then the
logicalcluster deletor tries to delete the collection of the same
resources (because it saw the resource in discovery), it will get a 404
and go into rate limited backoff, which we don't want.
Taken from @ncdc's rebase PR https://github.com/kcp-dev/kcp/pull/2945.
> :bug: logicalcluster-deletion: skip bound resources

- config/crds/apis.kcp.io_apibindings.yaml
- config/crds/apis.kcp.io_apiexports.yaml
- pkg/informer/informer.go
- pkg/informer/informer_test.go
- pkg/server/scheme/scheme.go
- pkg/virtual/apiexport/schemas/builtin/builtin.go
- sdk/apis/apis/v1alpha1/types_apiexport.go
- sdk/apis/apis/v1alpha1/types_apiexport_test.go
- sdk/apis/core/install/install.go
- test/e2e/apibinding/apibinding_logicalcluster_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Attempt to make LogicalCluster native resource so it can be used in claims. 
Fixes #
```release-note
Make LogicalCluster claimable resource for deeper level integration ontop of KCP
```
> :seedling:  Make LogicalCluster claimable

- cmd/sharded-test-server/cache.go
- test/e2e/apibinding/apibinding_logicalcluster_test.go
- test/e2e/framework/util.go
#3035 added some new tests for binding `LogicalClusters`. The test works fine when running "normal" e2e tests, but `test-e2e-sharded-minimal` fails more or less all the time. The reason is that the test was accessing the VirtualWorkspace URL at index 0, but sharded testing makes the situation more complex (with two VW servers). The APIExport and APIBinding workspaces were always added to `shard-1`, and then another virtual workspace is presenting the data we are looking for.
This adjusts the tests to consider multiple VWs and gather objects across VWs for the two new tests.
Fixes #
```release-note
NONE
```
> :bug: Be aware of sharding in APIBinding tests for LogicalCluster

- pkg/server/config.go
- pkg/server/options/batteries/batteries.go
- pkg/server/options/options.go
- pkg/server/server.go
This is a follow-up to #3033 and the discussion it created. This new approach adds a new battery called `admin` and enables it by default. Without this battery, `admin.kubeconfig` will not be generated and no admin token will be created to be injected into a new authenticator.
I've also added a check to make sure that the `user` battery is not enabled when `admin` is not.
Fixes #
```release-note
Add new `admin` battery which is enabled by default
```
> :sparkles: Add `admin` battery to kcp server and enable it by default

- pkg/index/index.go
- pkg/index/index_test.go
- pkg/proxy/index/index_controller.go
- pkg/server/localproxy.go
Simplify index package and wire in the ability to forward to different URLs. For now only in insecure mode in dev, as we need to wire in certificates deeper into stack. This is preparation for the experimental feature "workspace mounts"
Follow-up PR will follow: https://github.com/kcp-dev/kcp/pull/3057 
Fixes #
```release-note
Simplify index package for frontproxy
```
> :sparkles: Simplify index pkg

- config/root/metrics-3-cluster-role-binding.yaml
- pkg/server/options/options.go
I've been thinking about how to get metrics out of kcp for the Helm chart. The `metrics-viewer` battery is a great starting point, but requires you to extract the service account token out of kcp, which seems hard to do.
This PR adds another entity to the `ClusterRoleBinding` subjects: A `metrics-viewer` user. In the Helm chart, we can create a certificate for that user entity and then pass that certificate as credentials to e.g. a `ServiceMonitor` for [prometheus-operator](https://prometheus-operator.dev/). That seems to be the smoothest course of action to me.
Fixes #
```release-note
Add a `metrics-viewer` user subject to the ClusterRoleBinding created by the battery `metrics-viewer`, for which credentials can be generated outside of kcp
```
> :sparkles: Add 'metrics-viewer' user to ClusterRoleBinding in `metrics-viewer` battery

- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/virtual.go
- cmd/test-server/kcp/shard.go
- docs/content/concepts/workspaces.md
- pkg/server/config.go
- pkg/server/options/authentication.go
- test/e2e/framework/kcp.go
A long while ago, `/` redirected to the `system:admin` workspace. That is no longer the case, and as such the `admin.kubeconfig` generated by kcp should have a separate cluster/server from the `base` one, so that the `system:admin` context in it is functional.
I'm also adding a `shard-base` context because the combination of "base" server and "shard-admin" credentials are required in a lot of testing and sharding.
I also found this outdated information in the docs, so replaced it with some more up-to-date information.
Fixes #
```release-note
Fix `system:admin` context and add `system:base` in generated `admin.kubeconfig`
```
> 🐛 Generate `admin.kubeconfig` with correct cluster for `system:admin` context

- config/crds/bootstrap.go
- pkg/proxy/index/index_controller.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
- pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
- pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_reconcile.go
- pkg/reconciler/cache/labelclusterroles/labelclusterrole_reconcile.go
- pkg/reconciler/cache/labellogicalcluster/labellogicalcluster_reconcile.go
- pkg/reconciler/core/logicalcluster/logicalcluster_controller.go
- pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
- pkg/reconciler/core/shard/shard_controller.go
- pkg/reconciler/garbagecollector/garbagecollector_controller.go
- pkg/reconciler/kubequota/kubequota_controller.go
- pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_reconcile.go
- pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
- pkg/reconciler/tenancy/workspace/workspace_controller.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
- pkg/reconciler/tenancy/workspacetype/workspacetype_controller.go
- pkg/server/bootstrap/identity.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
This PR reduces the log verbosity of many logging statements in kcp. I tried to debug something recently and the sheer amount of "processing key" and "queueing thing" messages that flew by made it difficult.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md defines some guidance for log level usage and most importantly, queueing things should not be on level 1 (what i would consider the "panic" level). So I changed the levels to be
* Level 4 for every basic enqueue/process log lines. Just enqueueing something does not change cluster state and so should not printed every single time.
* Operations that actually change cluster state (creating/deleting/updating objects) have generally been moved to level 2.
My hope is that running kcp with …
> 🌱 reduce log verbosity for queueing operations

- .prow.yaml
What it says on the title. The build image got bumped in https://github.com/kcp-dev/infra/pull/64, this updates our prow jobs for this repository.
Fixes #
```release-note
NONE
```
> 🌱  Bump prow jobs to use `ghcr.io/kcp-dev/infra/build:1.20.13-1`

- .github/pull_request_template.md
- docs/content/developers/publishing-a-new-kcp-release.md
This PR is to propose a change in our release process, namely the release note generation. So far, we have relied on the GitHub auto-generated release notes, but we implemented all the tooling via Prow to use Kubernetes release note generation. I've tested this process in anticipation of the upcoming kcp 0.22.0 release and this seems to work fine, so I think we should change this to have a more meaningful changelog.
Fixes #
```release-note
NONE
```
> :book: Update release process with release note generation

- docs/content/developers/publishing-a-new-kcp-release.md
- docs/scripts/deploy-docs.sh
I was looking at how to get our documentation deployed without a commit pushed to `release-0.22`, and we can trigger the workflow for deploying docs manually. Unfortunately the deploy script doesn't react to manual workflow triggers. I think it should because I cannot think of a situation where you want to trigger a manual run but _not_ see the results deployed.
Also updating the release documentation to include the step.
Fixes #
```release-note
NONE
```
> 📖  Update deploy-docs.sh script to also deploy on manual runs

- config/root/metrics-1-cluster-role.yaml
Some things take you much longer to find than you'd be willing to admit - This is one of them. I was trying to get metrics from `/metrics` with the `metrics-viewer` user we added in #3064, and it just. wasn't. working. I banged my head against that wall for several days.
Until I read the [upstream documentation](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes) and realised the difference to our `ClusterRole`: The verb was all caps in ours. And - obviously, some might say - verbs in ClusterRoles are case-sensitive! So `GET` != `get`. This confusion is compounded by the fact that the HTTP verb, in fact, is `GET`. Kubernetes still seems to expect `get` here.
Binding to this `ClusterRole` gave me two different outcomes depending on which verb I …
> :bug: Use correct case on verb for metrics-viewer ClusterRole

- config/crds/apis.kcp.io_apiresourceschemas.yaml
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- sdk/apis/apis/v1alpha1/types_apiresourceschema.go
- sdk/client/applyconfiguration/apis/v1alpha1/apiresourceschemaspec.go
Add optional nameValidation field to ApiResourceSchemaSpec.
This field is propagated to the bound crd and the name validation strategy is decided based on the value.
Related [slack thread](https://kubernetes.slack.com/archives/C021U8WSAFK/p1700650436108499).
Fixes #
```release-note
Add optional nameValidation field to ApiResourceSchemaSpec. This field is used to add an internal annotation to the bound API and the name validation strategy is decided based on the value.
```
> ✨ Add optional nameValidation field to ApiResourceSchemaSpec

- docs/content/CONTRIBUTING.md
- docs/content/index.md
Our documentation still links to the GitHub meeting issue filter that we abandoned in favour of a Google Doc. This PR updates references to the filter to our Google Doc link and also removes the mention of the community calendar in favour of noting that joining kcp-dev will net you an invite to the community meeting.
Fixes #
```release-note
NONE
```
> :book: Update link for community meetings in documentation

- cli/pkg/workspace/plugin/kubeconfig.go
- config/crds/bootstrap.go
- pkg/index/index.go
- pkg/index/index_test.go
- pkg/proxy/mapping.go
- pkg/proxy/mapping_test.go
- pkg/reconciler/cache/replication/replication_reconcile.go
This PR does few things:
1. Fixes usage of HOME workspace where it does not honour host fixes: https://github.com/kcp-dev/kcp/issues/3011
2. A few debug logs for cache and CRD creation (way too many hours spend on those...)
3. Add weight into index routes:
```
// 1. We detect URL for the request and find the correct handler. URL can be
// shard based, virtual workspace or mount. First two are covered by r.URL,
// where mounts are covered by annotation on the workspace with the mount path.
// 2. If mountpoint is found, we rewrite the URL to resolve, else use one in
// request to match with mappings.
// 3. Iterate over mappings and find the one that matches the URL. If found,
// use the handler for that mapping, else use default handler - kcp.
// Mappings are done from most specific to …
```
> :sparkles: Index mounting ordering & few debug nits

- .github/workflows/goreleaser.yml
- .goreleaser.yaml
Fixes #
```release-note
Add krew-index build
```
> :sparkles: add krew index build

- pkg/server/options/flags.go
- pkg/server/options/options.go
This simply re-enables Kubernetes [Webhook Token Authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication) that was previously commented out.
I verified it worked in a local setup against a custom authenticator. See below:
```
$ \cat me.kubeconfig
apiVersion: v1
clusters:
- cluster:
insecure-skip-tls-verify: true
server: https://localhost:6443/clusters/root
name: workspace.kcp.io/current
- cluster:
insecure-skip-tls-verify: true
server: https://localhost:6443/clusters/root
name: workspace.kcp.io/previous
contexts:
- context:
cluster: workspace.kcp.io/current
user: test
name: workspace.kcp.io/current
- context:
cluster: workspace.kcp.io/previous
user: test
name: workspace.kcp.io/previous
current-context: workspace.kcp.io/current …
```
> ✨ Feature: Re-enable webhook token authentication

- README.md
- docs/content/index.md
We were notified on Slack that our docs still refer to the community calendar, which we no longer maintain. This replaces the reference with our CNCF community group instead. I've also made the docs index and repository readme consistent.
Fixes #
```release-note
NONE
```
> :book: Update documentation with CNCF community group

- .github/workflows/docs-gen-and-push.yaml
- docs/scripts/deploy-docs.sh
- docs/scripts/serve-docs.sh
I noticed that on https://docs.kcp.io, the "default" release (the release you get when going to https://docs.kcp.io/kcp/) points to 0.11. The reason for that is that the "default" release was set at _some_ point manually, but it was never automated.
This PR:
- tries to figure out if the pipeline is running for the latest released version series (e.g. v0.23 at the moment)
- if so, updates a version alias "latest" to the version while deploying
- ensures that the default version points to the "latest" alias
Fixes #
```release-note
NONE
```
> :book: Deploy most recent release documentation as 'latest' alias

- .gitignore
- Makefile
- contrib/tilt/Dockerfile.cache
- contrib/tilt/Dockerfile.kcp
- contrib/tilt/Dockerfile.proxy
- contrib/tilt/README.md
- contrib/tilt/Tiltfile
- contrib/tilt/coredns.yaml
- contrib/tilt/dex-values.yaml
- contrib/tilt/generate-admin-kubeconfig.sh
- contrib/tilt/grafana-values.yaml
- contrib/tilt/ingress-values.yaml
- contrib/tilt/kcp-values.yaml
- contrib/tilt/kernel-limits-job.yaml
- contrib/tilt/kind.sh
- contrib/tilt/loki-values.yaml
- contrib/tilt/prometheus-values.yaml
- contrib/tilt/promtail-values.yaml
- contrib/tilt/tempo-values.yaml
Adds test tilt setup to contrib
Missing parts:
Fixes #
```release-note
Add contrib folder to run Sharded dev env on Tilt with dex
```
> :sparkles:  Add Tilt setup to contrib 

- docs/content/concepts/braindump.md
This text was an attempt/experiment to teach GPT about KCP's concept and make it write a summarizing text about it. The success of this was limited, but the dictated text might be of use to understand KCP better.
```release-note
NONE
```
> :book: Add architecture brain-dump.

- pkg/server/config.go
Configure the controller rest config timeout to 30 seconds by default to avoid any client stuck at infinitely.
> :seedling: Set controller rest config timeout to 30secs

- pkg/server/config.go
- pkg/server/controllers.go
- pkg/server/openapiv3/controller.go
- pkg/server/openapiv3/servicecache.go
- pkg/server/server.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/openapi/openapi_test.go
The OpenAPI v3 stack was not yet cluster-aware. This PR adds
1. a controller generating and caching OpenAPI v3 specs for all CRDs, including bound CRD for APIBindings
2. a filter `WithOpenAPIv3` that merges these specs on-demand keeping a cache for different API configurations.
It makes heavy use of the lazy evaluation to avoid computation where possible.
Currently, (2) is implemented with a LRU cache of size 100 holding the (lazily) merged specs for API configurations. This means that with more than a 100 different configurations and constant OpenAPI v3 requests, this will not work well. Either we increase the number of different API configurations in the cache, or we use another kind of cache. But it's probably not common that there are so many different API configurations because some …
> :sparkles: Implement cluster-aware OpenAPI v3

- pkg/cache/client/round_tripper.go
- pkg/metadata/dynamic.go
- pkg/server/bootstrap/identity.go
After https://github.com/kcp-dev/kcp/pull/3112, plenty `Unable to cancel request for` errors appeared after bootstrapping. This PR fixes that by implementing the client-go `RoundTripperWrapper` interface on all of our wrappers.
Fixes #
```release-note
NONE
```
> :bug: Implement RoundTripperWrapper everywhere to allow cancellation

- .github/workflows/goreleaser.yml
In #3105, we added additional triggers to the `goreleaser` action, but it seems to me that had unintended consequences, namely #3121 -- now the action runs three times, and all three of them tried to upload binaries to the release:
- https://github.com/kcp-dev/kcp/actions/runs/8789380794
- https://github.com/kcp-dev/kcp/actions/runs/8789380790
- https://github.com/kcp-dev/kcp/actions/runs/8789380789
Looks like they raced to upload artefacts, and now the checksum file (which came from one of these jobs) doesn't match all uploaded artefacts (since they came from different jobs). I'm not sure if `prerelease: auto` should be removed, so I'm only reverting the triggers since they are the root cause for this behaviour. 
Fixes #
```release-note
NONE
```
> :bug: Partially revert 3105 to not run goreleaser multiple times

- docs/mkdocs.yml
One last minor follow up to documentation improvements. We now have https://docs.kcp.io/kcp/latest/ and it points to v0.24, but I think it would make more sense if it redirected to https://docs.kcp.io/kcp/v0.24/ over just showing the same content. That way it's clearer what version you are actually looking at and links are more permanent (a link to a page in `/latest/` might no longer work when we update the documentation).
Fixes #
```release-note
NONE
```
> :book: Redirect aliases instead of symlinking to their targets

- pkg/permissionclaim/permissionclaim_labeler.go
- pkg/virtual/apiexport/schemas/builtin/builtin.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
The list of native resources that are claimable is static and defined at https://github.com/kcp-dev/kcp/blob/main/pkg/virtual/apiexport/schemas/builtin/builtin.go#L88.
This PR adds `SubjectAccessReview` and `LocalSubjectAccessReview` to that list.
```release-note
Allow claiming `SubjectAccessReview` and `LocalSubjectAccessReview` in apiexports.
```
> :sparkles: apiexports: make SubjectAccessReview and LocalSubjectAccessReview claimable

- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
- test/e2e/apibinding/apibinding_permissionclaims_test.go
Since https://github.com/kcp-dev/kcp/pull/3129, both `SubjectAccessReview` and `LocalSubjectAccessReview` can be claimed. But as these are not persisted, there is no need for labelling of objects. It's not even possible to create such an informer. Hence, skip these resources.
```release-note
NONE
```
> :bug: apibindings/reconciler/labeller: fix informer error on non-persisted resources

- cli/pkg/OWNERS
- cli/pkg/workspace/plugin/use.go
- cli/pkg/workspace/plugin/use_test.go
While working on https://github.com/embik/kubectl-switch-ws I noticed that `kubectl-workspace use` will always print diagnostic information (deprecation notices and warnings about unfinished API bindings), even when using `--short` for inclusion in scripts / terminal prompts. There is no good way to avoid these warnings for scripts that only expect the workspace name returned as output.
I would like to propose that we start writing this supplementary information to stderr, which is specifically for diagnostic information and errors. This way, scripts can avoid the warnings by using something like `kubectl workspace use --short <workspace> 2>/dev/null` to make sure you only get back the workspace name (or an exit code that isn't zero, which signals that something bad happened).
There's …
> ✨ cli: write diagnostics in `kubectl-workspace` to stderr

- cli/pkg/workspace/cmd/cmd.go
`kubectl-kcp` already has a `--version` flag, but `kubectl-workspace` does not. This sets the version on the root cmd for `kubectl-workspace`, mirroring what we do in the other kubectl plugin already.
Fixes #
```release-note
Add `--version` flag to `kubectl-workspace`
```
> ✨ Add version to kubectl-workspace

- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/server/controllers.go
- pkg/server/server.go
At times we faced workspace controller creation stuck at scheduling phase and never recovers, we found that RCA of the issue is that , when the controllers are started using leaderElection, if the leader is lost once, the Queue processing is never restored ,because workqueue depth increases
* initialize informers before starting the controllers and informers ,and stop controllers when the pod is no longer a leader 
* reinitialize when the pod is elected as leader 
* move the openapi controller to a seperate post hook to avoid stopping when the pod is lost leader election. 
Fixes #
```release-note
Fix sequencing of controllers/informers start and leader election 
```
> ✨ Add installControllers and uninstallControllers for leaderElectionStopping

- pkg/server/server.go
I've observed log lines like the one below for quite a while:
```json
{"ts":1715849616335.2378,"caller":"replication/replication_reconcile.go:200","msg":"Updating object in global cache","component":"kcp","postStartHook":"kcp-start-informers","postStartHook":"kcp-start-controllers","reconciler":"kcp-replication-controller","key":"v1.clusterroles.rbac.authorization.k8s.io::root|system:kcp:universal-workspacetype-use","reconcilerKey":"root|system:kcp:universal-workspacetype-use","kind":"ClusterRole","namespace":"","name":"system:kcp:universal-workspacetype-use","v":2}
```
Note the double entry `"postStartHook":"kcp-start-informers","postStartHook":"kcp-start-controllers"`.
Turns out that in the `kcp-start-informers` post start hook the logger gets injected into `ctx`. That's however not the …
> :bug: Inject `kcp-start-informers` logger into correct hook context

- pkg/permissionclaim/permissionclaim_labeler.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
- pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go
- pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go
- pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
- pkg/reconciler/cache/replication/replication_controller.go
- pkg/reconciler/cache/replication/replication_reconcile.go
- pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go
- pkg/reconciler/tenancy/workspace/workspace_controller.go
- pkg/server/controllers.go
- pkg/server/server.go
When the controller startup sequence is fixed with https://github.com/kcp-dev/kcp/pull/3132 , there is a race condition introduced which would throw panic as the controller reintialization adds indexer to running informers
Fixes #
```release-note
Calls intialize indexer only once before the informer starts
```
> :bug:  Fix race issues in leader relection

- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/goreleaser.yml
- .prow.yaml
- Dockerfile
- docs/content/contributing/index.md
This bumps the build image (https://github.com/kcp-dev/infra/pull/72) and Go versions to the latest Go 1.22.5. It's also the first build image that has an arm64 variant, so with this we could execute prowjobs on ARM64 nodes in the future.
Fixes #
```release-note
kcp is built with Go 1.22.5 now
```
> :seedling: Bump to Go 1.22.5

- config/crds/admissionregistration.k8s.io_validatingadmissionpolicies.yaml
- config/crds/admissionregistration.k8s.io_validatingadmissionpolicybindings.yaml
#3140 removed `admissionregistrationv1alpha1.ValidatingAdmissionPolicies` and `admissionregistrationv1alpha1.ValidatingAdmissionPolicyBindings` from the CRDs used to bootstrap the cache server. This works fine on fresh kcp installations, but causes problems with kcp setups upgrading from v0.24.0. This brings back the `v1alpha1` versions to both CRDs as they exist in the `v0.24.0` git tag and adds them to the CRD. This allowed me to upgrade from an existing kcp setup initially set up with the last official release.
Fixes #
```release-note
NONE
```
> 🐛  Bring back `v1alpha1` versions of validating admission policy resources

- .gitignore
- cmd/sharded-test-server/cache.go
- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/virtual.go
- cmd/test-server/kcp/shard.go
- test/e2e/framework/kcp.go
When debugging e2e tests for shared and sharded setups, I struggled a bit with figuring out what was going on on the server side of the e2e tests. Tests I could launch via `dlv` to debug them, but for the KCP server/cache/front-proxy side I needed to attach to the running processes or similar.
I added a new environment variable `RUN_DELVE` to the test framework to launch the various processes not from binaries or from `go run`, but from `dlv debug` directly. The workflow is like this:
1. Launch `test-server` or `sharded-test-server`:
```sh
$ RUN_DELVE=1 ./bin/sharded-test-server 2>&1 | tee kcp.log
```
2. Wait for `dlv-cache.sock` to appear, connect to it via `dlv connect unix:dlv-cache.sock`, set your breakpoints for the cache server and then hit `c` to start the cache server.
3. Repeat …
> :seedling: Allow launching components from (sharded-)test-server with delve

- FAQ.md
- code-of-conduct.md
- contrib/demos-unmaintained/demo/prototype3-script/apibinding/cert-manager.yaml
- docs/content/concepts/authorization.md
- docs/content/concepts/components/sharding.md
- docs/content/concepts/workspaces.md
- hack/build-image.sh
- pkg/admission/logicalcluster/admission.go
- pkg/admission/logicalcluster/admission_test.go
- pkg/proxy/config.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller_test.go
- pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go
- pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller_test.go
- pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
- pkg/server/config.go
- pkg/server/server.go
- test/e2e/cache/cache_server_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Fixes typos across the repository. 
Fixes #
```release-note
NONE
```
> :seedling: Fixed typos across the repository

- pkg/openapi/zz_generated.openapi.go
- sdk/apis/apis/v1alpha1/types_apiexport.go
- sdk/client/applyconfiguration/apis/v1alpha1/acceptablepermissionclaim.go
- sdk/client/applyconfiguration/apis/v1alpha1/permissionclaim.go
The JSON tag for the permission claim `GroupResource` embedded struct was wrong. The apply configuration resulted in an object like the following:
```json
{
"apiVersion": "apis.kcp.io/v1alpha1",
"kind": "APIExport",
"metadata":
{
"name": "fabrics.upbound.io"
},
"spec":
{
"latestResourceSchemas":
[
"v240816-2328.projects.fabrics.upbound.io",
"v240816-2328.services.fabrics.upbound.io",
"v240816-2328.servicetiers.fabrics.upbound.io",
"v240816-2328.spaces.fabrics.upbound.io"
],
"permissionClaims":
[
{
"GroupResource":
{
"group": "tenancy.kcp.io",
"resource": "workspaces"
},
"all": true,
"identityHash": "1422105e93411affc2d91b197e07d9168c1e7ca3b01fc6955b393122be112491"
}
]
}
}
```
Fixes #
```release-note
Fix apply configuration client for APIExport.
```
> :bug: Fix APIExport SSA apply configuration client

- .github/workflows/goreleaser.yml
- .goreleaser.yaml
Release file copies, and not softlink'ed one. Go release does not know how to handle those
Fixes #
```release-note
NONE
```
> :sparkles:  split go releaser archives

- .goreleaser.yaml
- FAQ.md
- Makefile
- cli/cmd/kubectl-create-workspace/main.go
- cli/cmd/kubectl-ws/main.go
- cli/pkg/workspace/cmd/cmd.go
- contrib/kcp.code-workspace
- docs/content/setup/kubectl-plugin.md
With https://github.com/kubernetes/kubernetes/pull/124123, kubectl supports create plugins. This PR adds `create workspace`.
```release-note
Add `kubectl create workspace` plugin.
```
> :sparkles: add kubectl-create-workspace command supported with latest kubectl

- pkg/server/config.go
- pkg/server/filters/filters.go
In order to do maintenance on a workspace, without controllers reconciling the resources inside the window during the maintenance period, I need a mechanism by which to disable access to the workspace. This feature adds a new optional annotation to `LogicalCluster` which disables API access through to the resource while present:
```
internal.kcp.io/inactive: "true"
```
All requests to the logical cluster while the annotation is set are denied with a 400 error, except for requests to CRUD the logical cluster itself or the OpenAPI spec (so that you can reasonably disable the annotation).
None
```release-note
Add support for inactive annotation on logical clusters
```
> :sparkles: Add inactive annotation to logicalcluster

- cmd/kcp/options/generic.go
- pkg/server/options/controllers.go
`--root-directory` is an extremely handy flag when running `kcp start` locally, and the `.kcp` directory is filled with automatically generated certificates, kubeconfigs, etc.
When running kcp in Kubernetes (e.g. via the Helm chart), this is not needed because certificates are fed from the outside (generated by cert-manager) and kubeconfig generation is disabled. We set this in the Helm chart:
https://github.com/kcp-dev/helm-charts/blob/5e745b2cfbd7ad7cf926fd61b550d9c6c695265e/charts/kcp/templates/server-deployment.yaml#L135
This references an emptyDir volume we mount. The only reason we do that is because kcp fails to start if the root-directory doesn't exist and it cannot create it.
Thus, this PR eliminates the code path that was always trying to create the root directory. It should …
> ✨ Allow setting root directory to empty string to disable creation

- pkg/authorization/delegated/authorizer.go
- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
A typo led to a zero ttl for the deny cache of delegated authz.
Fixes #
```release-note
Fix performance problem in virtual workspace authorization.
```
> :bug: authorization/delegated: fix typo leading to zero deny cache ttl

- pkg/reconciler/apis/apibinding/apibinding_controller.go
The apibinding reconciler listed ALL bindings and then filtered by cluster. Obviously, this can be done through the informer indexer.
Fixes #
```release-note
NONE
```
> :bug: reconciler/apibinding: filter by cluster through index, not manually

- pkg/virtual/framework/wrappers/rbac/merging.go
No need to deep-copy for changing the name. This switches to shallow copies in virtual workspace authorization hot path.
Fixes #
```release-note
Optimize authorization in virtual workspaces.
```
> :bug: virtual/authorization: shallow copy of RBAC objects

- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
The fallback code to always serve APIBindings in the apiexport virtual workspace lacked logic to preserve the old storage. So on any other change or resync, the APIBinding storage was recretaed.
Fixes #
```release-note
NONE
```
> :bug: virtual/apiexport: don't keep recreating APIBindings storage

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/apis/apibinding/conflict_checker.go
- pkg/reconciler/apis/apibinding/conflict_checker_test.go
Share the conflict checker when checking all resources in a APIBinding. The checker showed up pprof because it does don't of informer lookups. With https://github.com/kcp-dev/kcp/pull/3169, this should be a lot better.
Fixes #
```release-note
NONE
```
> :bug: reconciler/apibinding: share conflict checker for all schemas in bindings

- sdk/apis/core/helper/replicate.go
- test/e2e/reconciler/cache/replication_test.go
The uncontroversal parts of https://github.com/kcp-dev/kcp/pull/3171
Fixes #
```release-note
NONE
```
> :seedling: cache-server: misc cleanups

- Makefile
Now that plugins have their own go module, the Makefile must change to that module's directory before running go commands on that module.  Currently, `make install` does not do this and therefore plugins don't get installed as expected.
This PR updates `make install` following the pattern of `make build` to fix this.
Before this PR, notice the last line `go: warning: "github.com/kcp-dev/kcp/cli/cmd/..." matched no packages`, and the plugins don't get installed in `$GOPATH/bin`:
```
$ make install
hack/verify-go-versions.sh
set -x; for W in ./cmd/... ./cli/cmd/...; do \
W=$(echo "${W}" | sed 's,^\./,github.com/kcp-dev/kcp/,') && \
GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go install -ldflags="-X k8s.io/client-go/pkg/version.gitCommit=c1ff50b3 -X k8s.io/client-go/pkg/version.gitTreeState=clean …
```
> 🐛 Fix 'make install' to respect plugin go module

- pkg/reconciler/tenancy/workspace/workspace_reconcile.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
The front-proxy might return errors when looking for the `LogicalCluster` on workspace deletion,
especially when the `LogicalCluster` is already gone, and it returns a 403. This PR adds another attempt through the workspace admin client.
Fixes #
```release-note
Make workspace deletion more reliable, trying harder to not leak `LogicalClusters`.
```
> :bug: tenancy/workspace-deletion: try harder with the admin client to delete the LogicalCluster

- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/goreleaser.yml
- .prow.yaml
- Dockerfile
Update to go 1.22.7. This is needed to get rid of vulnerability scan results for CVE-2024-34156.
Depends on kcp-dev/infra#73
```release-note
NONE
```
> 🌱 go 1.22.7

- pkg/metadata/dynamic.go
- pkg/proxy/config.go
- pkg/reconciler/tenancy/replicateclusterrolebinding/replicateclusterrolebinding_controller.go
- pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go
- pkg/virtual/apiexport/authorizer/maximal_permission_policy_test.go
- sdk/apis/core/install/install.go
Aliases equal to the names of the imported packages have no effect and the package name can be used directly
Fixes #
```release-note
NONE
```
> :seedling: Remove redundand imports

- pkg/virtual/apiexport/builder/build.go
We have some validations on our CRDs where we would like to act based on the user information, i.e., we want to allow a specific field to only be initialized by a controller but no one else. The current implementation of build virtual workspaces loses the original user info while doing impersonation. 
This PR adds original user and groups information to impersonating client as `extra`, so that our validator can extract the user/group information and make decisions accordingly. 
N/A
```release-note
Add original user/groups information as extra to the impersonating client used by virtual workspace.
```
> :sparkles: Add original user/group as extra to the impersonating client used by virtual workspace

- cmd/compat/main.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
Some variable names are same like reserved words. This should be avoided
Fixes #
```release-note
NONE
```
> :seedling: Rename variables

- cli/cmd/kubectl-kcp/main.go
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/third_party/library-go/crypto/crypto.go
- pkg/crdpuller/discovery.go
- pkg/index/index.go
- pkg/informer/informer.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/cache/replication/replication_reconcile_unstructured.go
- pkg/reconciler/topology/partitionset/partitionset_reconcile.go
- pkg/server/handler_test.go
- pkg/server/localproxy.go
- pkg/server/openapiv3/servicecache.go
- pkg/virtual/apiexport/schemas/builtin/builtin.go
- pkg/virtual/framework/dynamic/apiserver/handler_test.go
- pkg/virtual/framework/fixedgvs/register.go
- pkg/virtual/framework/internalapis/import_test.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- sdk/cmd/apigen/main.go
- test/e2e/cache/cache_server_test.go
- test/e2e/fixtures/apifixtures/sheriffs.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/cache/replication_test.go
Should be avoided because the package exported identifiers can't be used after the declaration. This may be also confusing for the reader.
Variable renaming is aligned to the official golang guidelines: 'Variable names in Go should be short rather than long. This is especially true for local variables with limited scope. Prefer c to lineCount. Prefer i to sliceIndex'.
Source: https://go.dev/wiki/CodeReviewComments#variable-names
Fixes #
```release-note
NONE
```
> :bug: Fix probable bug: imported package name as name identifier

- hack/update-codegen-clients.sh
At some point we lost this in the last releases. `kube_codegen.sh` does not work the same way as before. 
We will need to migrate the rest of the generators when we can. For now just patching the bleeding. 
Fixes #
```release-note
Fix regression in DeepCopy generator
```
> :bug: Fix regression when generating deep copy

- pkg/server/server.go
As per discussions on Slack (https://kubernetes.slack.com/archives/C021U8WSAFK/p1730131234224829), it makes sense to let the kcp process crash when it wins a leader election but then fails to install controllers. If this happens, it might hold onto the leader election lock but no controllers are actually running to reconcile objects. By making it crash, we make a new leader election possible.
The leader election package unfortunately doesn't have a "native" way to handle such failures.
Fixes #
```release-note
Purposefully crash if leader election was won but controllers failed to install, allowing another instance to take leadership
```
> :bug: Terminate kcp process if controller installation fails

- config/crds/core.kcp.io_logicalclusters.yaml
- config/crds/tenancy.kcp.io_workspaces.yaml
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-logicalclusters.core.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.io.yaml
- pkg/index/index.go
- pkg/proxy/handler.go
- pkg/proxy/index/index_controller.go
- pkg/proxy/mapping.go
- pkg/reconciler/tenancy/workspace/README.md
- pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_phase_test.go
- pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile_updater.go
- pkg/server/localproxy.go
- sdk/apis/core/v1alpha1/logicalcluster_types.go
- sdk/apis/tenancy/v1alpha1/types_mounts.go
- test/e2e/mounts/apiresourceschema_kubecluster.yaml
- test/e2e/mounts/kubecluster_mounts.yaml
- test/e2e/mounts/mounts_machinery_test.go
Add a reconciler to switch workspaces phase to "Unavailable" if any workspace conditions are not ready.
This way, if some of the auxiliary conditions are `Unavailable`, the phase will change.
Adds mounts controller to propagate status to the workspace when mount is not ready. This way we don't use the workspace at all if the mount is not responding. 
Adds code to index/proxy to not serve workspaces which are in `Unavailable` state, so we avoid using workspaces with errorous backends. 
partially based on https://github.com/kcp-dev/enhancements/pull/6 
Fixes #
```release-note
Add workspace phase reporter reconciler 
Add the Unavailable phase to the API
Implement exclusion of Unavailable workspaces from serving via proxy to avoid serving something which is not supposed to be served. 
```
> :sparkles:  Add workspace phase update logic

- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/goreleaser.yml
- .prow.yaml
- Dockerfile
The usual housekeeping, updating the Go version we use to build kcp (and run tests) to the latest 1.22.x version.
Fixes #
```release-note
kcp is built with Go 1.22.9
```
> :seedling: Use Go 1.22.9

- .gitignore
- contrib/kcp-dex/README.md
- contrib/kcp-dex/kcp-config.yaml
Quick readme on how to run kcp with local dex instance for closer to real-life development. 
Fixes #
```release-note
NONE
```
> :book:  add dex quickstart

- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/goreleaser.yml
- .prow.yaml
- Dockerfile
A manual backport of #3212. Since 0.27 is still out a bit, it would be nice to have some basic maintenance on the active release branch since we should get into the habit of patch releases.
Fixes #
```release-note
kcp is built with Go 1.22.10
```
> [release-0.26] :seedling: Update to Go 1.22.10

- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
it's a harmless bug, but may cause some bug in future.
the code check the `deleteError != nil` but return an other nil `err`
return a other nil `err` , but it was check the 
https://github.com/alingse/sundrylint/issues/4
I have an idea to detect the return nilness error bug, and check the top 1000 github go repos, and found this.
Fixes #
```release-note
NONE
```
> 🐛 fix check `deleteError != nil` but return an other nil value `err`

- Makefile
- cmd/kcp/kcp.go
- docs/content/concepts/authorization/authorizers.md
- docs/content/concepts/authorization/index.md
- docs/mkdocs.yml
- hack/bump-k8s.sh
- pkg/server/config.go
- pkg/server/options/authorization.go
- pkg/server/options/options.go
- test/e2e/authorizer/webhook.kubeconfig
- test/e2e/authorizer/webhook_test.go
- test/e2e/framework/kcp.go
This PR allows to configure an external webhook for authorization. Previously the relevant flags have been explicitly disabled in kcp, because kcp has its own authorizer. The webhook authorizer will sit next to the existing authorizers (allowPath, allowGroup) and so is an alternative to the built-in authorizers.
In the documentation, it looks like this:
I chose to let the webhook authorizer run in parallel to the existing RBAC chain so that admins have full freedom to tweak the authorization. This comes with the warning that if your webhook is configured to deny everything, it will block kcp's startup (thankfully, kcp recovers quickly when the webhook stops denying everything and starts to either have no opinion or allow things explicitly).
Since the webhook authorizer is part of a union …
> ✨ Enable webhook authorization options

- hack/build-image.sh
This prefixes non-branch or tag images with `dev-` so we can start publishing them (follow-up pr). and later purge them
Fixes #
```release-note
NONE
```
> :sparkles:  Add prefix to dev images for gc

- cmd/kcp/kcp.go
- cmd/kcp/options/generic.go
- pkg/proxy/handler.go
- pkg/proxy/index/index_controller.go
- pkg/proxy/mapping.go
- pkg/server/config.go
- pkg/server/localproxy.go
- pkg/server/options/options.go
- pkg/server/proxy/handler.go
- pkg/server/proxy/mapping_test.go
In this PR:
1. Move some of the proxy handler code from `pkg/proxy` into `pkg/server/proxy` so it could be reused in `miniproxy`. This is to avoid circular imports problem :/ didn't find better place for this.
2. Add flag `--mapping-file` for `kcp start` in dev mode, so once can start kcp locally and iterate on external virtual workspace binary code without having to deal with embedding code. It makes kcp core more standalone and forces people to think "core vs non-core" 
3. Refactors proxy index with error codes to be more consistent (a consequence of reusing same more in miniproxy and front-proxy)
All in all, this makes local development of anything outside kcp (like mounts proxy) exponentially easier. 
Fixes #
```release-note
Enhance local development experience for VirtualWorkspaces …
```
> ✨  Enhance local-dev for VirtualWorkspaces 

- pkg/admission/validatingwebhook/plugin.go
- pkg/admission/validatingwebhook/plugin_test.go
The undo function of the admission webhook wiped annotations if the cluster annotation was not present.
Fixes #3182 introduced in #3124 
```release-note
Fix external modifications to annotations being reverted by admission webhook
```
> :bug: Fix undo function of cluster annotation setter wiping annotations

- cmd/kcp/kcp.go
- pkg/server/localproxy.go
This got lost in rebase and cherry-pick :/ There is no impact on production as this codepath is hit only when `--miniproxy-mapping-file` is provided. 
Fixes #
```release-note
NONE
```
> :bug: Fix localproxy routing

- cli/cmd/kubectl-create-workspace/cmd/kubectlCreateWorkspace.go
- cli/cmd/kubectl-create-workspace/main.go
- cli/cmd/kubectl-ws/cmd/kubectlWs.go
- cli/cmd/kubectl-ws/main.go
- docs/generators/cli-doc/main.go
Creates CLI docs for currently missing commands
Note: see that the `create workspace` command is manually modified to reflect the invocation style over the needed cobra style for runtime
Fixes #3222
```release-note
Fix CLI docs generation
```
> :book: Create CLI docs for workspace and create workspace cli

- docs/main.py
- docs/overrides/partials/section-overview.html
- docs/requirements.txt
- docs/scripts/serve-docs.sh
Resolves #3218
The fix_url function that we are using doesn't work at a nested level. Given how we are using this partial, using a "current level" value (i.e. `./workspace-types`) vs a "go up levels" (i.e. `../concepts/workspace/workspace-types`) will be portable across any level of nesting.
```release-notes
NONE
```
> :book: Create section navigation that works across any level of nesting

- cmd/kcp/kcp.go
Send `kcp start options` to stdout instead of stderr
Fixes #3236 
```release-note
update kcp start options to print to stdout
```
> :bug: Send options to stdout instead of stderr

- .prow.yaml
We're using an outdated image of `buildah`, this bumps the version up to v1.38.0.
Fixes #
```release-note
NONE
```
> :seedling: Bump buildah image to v1.38.0

- Dockerfile
When running kcp in docker and want to add simple heathchecks, this gets tricky. See the issue below. Dont want to add curl as its way too big, but wget should do just fine to achieve:
```
HEALTHCHECK --interval=30s \
--timeout=5s \
CMD ["/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:6443/health"]
```
https://github.com/GoogleContainerTools/distroless/issues/183
Fixes #
```release-note
add wget to final image
```
> :sparkles: Add wget to final image

- docs/content/concepts/terminology.md
The purpose of this PR is to rework the Terminology document to be beginner-friendly. My idea is that if you're coming to the kcp project for the very first time, this should be the document that you get started with. It should give you insights into what's kcp about, how it works, and what to expect.
However, my experience was somewhat different -- I encountered a lot of terms and definitions that are not easy to grasp. Hence, I'm proposing this PR, to rework the Terminology document:
- to improve the readability
- to improve the formatting
- to match definitions across different documents
I'm working on some other documents as well, but I decided to start with this one. If this is something that you like, I'll bring PRs for other documents so we can discuss.
```release-note
NONE
``` …
> :book: docs: rework the Terminology document

- pkg/server/filters/impersonation.go
- pkg/server/filters/impersonation_test.go
We discovered that the `WithImpersonationScoping` filter had a flaw: It was checking the already impersonated user identity to determine whether adding a scope should be skipped for `system:masters` impersonators. But this check needs to run against the original user identity, not the impersonated identity (since that will never include `system:masters`).
This PR stores the user identity during `WithImpersonationGatekeeper` in the request context to fetch it at a later stage in `WithImpersonationScoping`.
As a bonus, I discovered that the check for extra impersonation headers is not correct: It was checking the HTTP header values, but it should be checking the name/key of the header. So the list of extra impersonations was always empty. The tests didn't check this.
Fixes #
```release-note …
```
> :bug: Correctly check original groups against `system:masters` in scope filter

- pkg/virtual/initializingworkspaces/builder/build.go
As part of #3235, we added scoping to the impersonation that happens in the `initializingworkspaces` virtual workspace when proxying through content access. This creates a fundamental problem: When creating `APIBindings` through it (a common activity done by kcp itself for the default API bindings in a `WorkspaceType`), the impersonated identity will always be  out-of-scope for the workspace that holds the target `APIExport` for a default binding.
This means default API bindings would always be bound as `system:anonymous` / `system:authenticated` (the identity of out-of-scope entities), which means you cannot properly provide permissions to the owner of a workspace (which is the identity impersonated by the virtual workspace).
So for now we think we should undo the scoping in the virtual …
> :bug: Remove scope from initializingworkspaces virtual workspace

- pkg/server/filters/impersonation.go
- pkg/server/filters/impersonation_test.go
There are some more priviliged groups that this PR is adding to the impersonation guard. Only `system:master` suffices to impersonate as any of them if the incoming user does not have that group already.
Fixes #
```release-note
NONE
```
> :bug: impersonation: add missing privileged groups

- test/e2e/authorizer/scopes_test.go
Adding an e2e test for SelfSubjectRulesReview for scoping.
Needs https://github.com/kcp-dev/kcp/pull/3269.
Fixes #
```release-note
NONE
```
> :seedling: e2e: add SelfSubjectRulesReview test

- pkg/index/index.go
- pkg/index/index_test.go
- test/e2e/authorizer/serviceaccounts_test.go
- test/e2e/mounts/mounts_machinery_test.go
The old code stored the error code under the logical cluster which was supposed to fail, not the workspace pointing to it. This kind of worked on one shard, but with multiple it failed when workspace and target cluster were not colocated.
Fixes #
```release-note
NONE
```
> :bug: index: fix how error codes are stored for unavailable workspaces

- .prow.yaml
- Makefile
- cmd/sharded-test-server/cache.go
- cmd/test-server/main.go
- test/e2e/framework/util.go
Prow collects artifacts from the directory in `$(ARTIFACTS)`. In kcp we use `ARTIFACT_DIR`. This PR sets it up correctly that `ARTIFACT_DIR` is set to `$(ARTIFACTS)`.
Fixes #
```release-note
NONE
```
> :seedling: Configure prow artifacts correctly

- cmd/cache-server/main.go
- cmd/kcp-front-proxy/main.go
- cmd/kcp/kcp.go
- cmd/sharded-test-server/main.go
- config/crds/bootstrap.go
- config/helpers/bootstrap.go
- pkg/crdpuller/discovery.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_reconcile.go
- pkg/reconciler/core/logicalcluster/logicalcluster_reconcile.go
- pkg/reconciler/tenancy/workspacemounts/workspacemounts_reconcile.go
- pkg/server/bootstrap/identity.go
- pkg/server/controllers.go
- pkg/virtual/framework/internalapis/import.go
- sdk/apis/apis/v1alpha1/crd_to_apiresourceschema.go
- test/e2e/framework/expect.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/cache/helpers.go
No actual change is happening here. Just cleaning. 
Fixes #
```release-note
NONE
```
> :seedling: Noop: Clean code and organize imports

- cmd/sharded-test-server/shard.go
The real fix might be https://github.com/kcp-dev/kcp/pull/3274. But to reduce flakes, we need this quick fix in e2e.
Fixes #
```release-note
NONE
```
> :seedling: stop the bleeding: e2e/sharded: temporarily disable service account lookup

- docs/content/concepts/authorization/authorizers.md
Let's change the order of authorizers shown on the authorizers page in the documentation.
AlwaysAllowGroups comes before the AlwaysAllowPaths: https://github.com/kcp-dev/kcp/blob/4c2d1061d8411e32adbe8184fdd694a5e830eaf9/pkg/server/options/authorization.go#L137-L150
Fixes #
```release-note
NONE
```
> 📖  change the order of authorizers in the docs

- contrib/kcp-dex/README.md
- contrib/kcp-dex/auth-config.yaml
- pkg/server/options/flags.go
Enables flag for structured authentication flag that was planned as a follow-up during 1.30 k8s [update](https://github.com/kcp-dev/kcp/pull/3140).
I have added also an example guide to our dex guide made by MJ to verify the functionality.
Fixes #3216 
```release-note
Enable structured authentication configuration from a file with —authentication-config flag.
```
> ✨ Enable structured authentication config flag

- pkg/admission/workspacetypeexists/admission.go
The function `allOfTheFormerExistInTheLater` is renamed to `anyOfTheFormerExistInTheLater` to better reflect its behavior. The function implements additive type extension where a type gains capabilities of types it extends.
The implementation was correct, but the name suggested an "all" check when it performs an "any" check. This aligns with documented behavior where a type can be used anywhere its extended type is allowed.
This is a naming-only change with no behavioral modifications.
Fixes `nil`
```release-note
NONE
```
> :bug: fix(admission): rename allOf to anyOf for type extension

- Makefile
- config/crds/apis.kcp.io_apiexportendpointslices.yaml
- pkg/authorization/bootstrap/policy.go
- pkg/indexers/apiexport.go
- pkg/indexers/apiexport_test.go
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller_test.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_indexes.go
- pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_reconcile.go
- pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_controller.go
- pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_controller_test.go
- pkg/reconciler/apis/apiexportendpointsliceurls/apiexportendpointsliceurls_reconcile.go
- pkg/reconciler/cache/replication/replication_controller.go
- pkg/server/controllers.go
- pkg/server/server.go
- sdk/apis/apis/v1alpha1/types_apiexportendpointslice.go
- sdk/client/applyconfiguration/apis/v1alpha1/apiexportendpointslicestatus.go
- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
- test/e2e/reconciler/apiexportendpointslice/apiresourceschema_cowboys.yaml
This part makes APIExportEndpointSlices consumers aware. Meaning it will add or remove URLs if consumers are present or goes away.
In this PR:
1. Current APIExportEndpointSlice reconcile is split into 2 - `status` and `url`
`status` - status controller checks if API export is valid, partitions are set right, and it can be queried. Most of these objects operate in a single-shard context, so this reconciliation works only in a single-shard context. CAVITE: Based on the partition setup - the shards involved will be different. Hence we store the final computed selector into status for the `URL` reconciler to pick up. 
`url` - URL reconcile operates cross-shards setup. It takes `APIExportEndpointSlice` from the cache and local shard and observes `APIBindings` and `APIExports` and, based on …
> :sparkles: make APIExportEndpointSlice consumer aware

- .prow.yaml
- hack/run-with-prow.sh
This implements another wrapper script, `run-with-prow.sh`, which uses `tar` to pre-compress all build artifacts to save on storage.
I chose to keep the difference between `ARTIFACT_DIR` and `ARTIFACTS`, but to properly inject it into the ProwJob,
* setting them via `env` is not possible because Prow adds `ARTIFACTS` _after_ the env vars declared in the ProwJob, so an `env{name: ARTIFACTS_DIR, value: '$(ARTIFACTS)'}` has no effect.
* setting it the old way did not actually work, evident by the fact that the Prometheus artifacts were also never uploaded to S3. Doing `./run-with-prometheus.sh make e2e FOO=BAR` works well for `make`, but is invisible to the surrounding script.
* I could have replaced the command in the ProwJob with a mini bash script, but that's ugly as well.
* So I chose to …
> 🌱 compress all build artifacts after e2e tests

- config/shard/logicalcluster.yaml
- pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission.go
- pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission_test.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/apis/apibinding/conflict_checker.go
- pkg/reconciler/apis/apibinding/conflict_checker_test.go
- pkg/reconciler/apis/apibinding/logical_cluster_lock.go
- pkg/reconciler/apis/apibinding/logical_cluster_lock_test.go
- pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go
- pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller.go
- pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller_test.go
- pkg/server/controllers.go
- pkg/server/server.go
- sdk/apis/apis/v1alpha1/types_apibinding.go
The conflict checker in the APIBinding reconciler computed a list of CRDs, both real and bound ones. It took the APIExport as reference instead of the bindings directly. This seems wrong. If a schema is removed from an export, or the whole export is deleted, the binding still exists, but it didn't contribute the conflict checker anymore.
This PR does the following:
1. make the conflict checker use the `APIBinding.status.boundResources` as reference.
2. store group resource bindings in an `apis.kcp.io/resource-bindings` annotation on the `LogicalCluster`. It records the APIBinding or whether it is a CRD. This annotation (a JSON map) is updated BEFORE (a) a CRD is created (admission) or (b) an APIBinding bind the group resource:
```yaml
internal.apis.kcp.io/resource-bindings: …
```
> :bug: reconciler/apibinding: make group resources of APIBindings + CRD race-free

- Dockerfile
`go list -m -json k8s.io/kubernetes | jq -r .Version` outputs a version string in format `v0.<Minor>.<Patch>`, but binaries at dl.k8s.io/release are versioned in line with real K8s versions. This commit replaces the "v0" part with "v1" so that the URL is correct.
```release-note
NONE
```
> :bug: Dockerfile: fix constructing URL for kubectl

- docs/content/setup/kubectl-plugin.md
The output from `make install` no longer matches the output in the docs. So we just remove that to prevent confusion as to what to execute.
Fixes #
```release-note
remove superflous output from make install command
```
> :book: remove superflous output from make install command

- hack/verify-go-modules.sh
This PR adds checks for go.mod dependencies, verifying the versions used in our modules are the same as the ones used declared by k8s.io/kubernetes module. When rebasing or otherwise bringing in dependency updates, they can break our code -- see https://github.com/kcp-dev/kcp/issues/3283#issuecomment-2676780112 for example. Just following the recommendations from this script, the issue I've just linked to was solved in a couple of minutes instead of regrettably spending a day or two debugging different things... :D
The checks only report warnings if our deps are more than a patch version apart with k8s.io/kubernetes, but never return non-zero exit code to not fail CI in cases when we want to use different versions deliberately.
Example output:
```
$ make verify-modules …
```
> :sparkles: hack/verify-go-modules.sh: compare dependency versions

- .prow.yaml
We are running several jobs on changes to `docs/` which are not necessary and just put load on the CI environment. Let's scope down Prow jobs a bit here.
Fixes #
```release-note
NONE
```
> :seedling: Limit several jobs to not run for doc changes

- hack/verify-go-modules.sh
Depending on which pager git is configured to use, it may clear terminal's screen, including the error message from verify-go-modules.sh. This then may be confusing for the user where is this `git diff` coming from.
```release-note
NONE
```
> :seedling:  hack/verify-go-modules.sh: don't run pager with git diff

- cli/pkg/bind/cmd/cmd.go
- cli/pkg/bind/plugin/bind.go
- cli/pkg/bind/plugin/bind_test.go
Fixes https://github.com/kcp-dev/kcp/issues/3189
```release-note
Add --accept-permission-claim & --reject-permission-claim flag to `kubectl kcp bind apiexport`
```
> :sparkles: Add --{accept/reject}-permission-claim flag to bind cli

- pkg/virtual/apiexport/authorizer/binding.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/options/options.go
- test/e2e/virtual/apiexport/authorizer_test.go
This adds an additional authorizer to the authorizer chain for the APIExport VW, incorporating the configuration on the APIBinding present in the target workspace.
Fixes #
```release-note
Add additional authorizer to APIExport Virtual Workspace that queries APIBinding for authorization decisions
```
> :bug: Add binding authorizer to APIExport virtual workspace

- .gitignore
- .goreleaser.yaml
This fixes the deprecation warnings output by goreleaser 2.8.x, namely:
* only  version: 2  configuration files are supported, yours is  version: 0 , please update your configuration
* DEPRECATED:  archives.builds  should not be used anymore, check https://goreleaser.com/deprecations#archivesbuilds for more info
Fixes #3341
```release-note
NONE
```
> 🌱 update goreleaser config to version 2

- docs/content/concepts/quickstart-tenancy-and-apis.md
Hi!
While going through the Tenancy and APIs section, I noticed that the kubectl ws create command is deprecated. I've updated it to kubectl create workspace and added a link to the latest release page.
Additionally, the documentation states that apigen needs to be built, but from what I observed, it is already available on the release page. I’ve adjusted this accordingly.
Hope this helps!
None
```release-note
NONE
```
> :book: Update docs

- Makefile
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
- hack/verify-apiresourceschemas.sh
This [Slack thread](https://kubernetes.slack.com/archives/C021U8WSAFK/p1742888913738159) mentions that we have a problem with the 0.26 to 0.27 upgrade with the WorkspaceType `APIResourceSchema`. The reason is that we changed the file in #3233 but it looks like changes in that PR were done manually with search and replace, which evaded detection by `apigen` and by any other validation logic we have.
This PR, intended to be backported to `release-0.27`, does two things: It manually resets the `APIResourceSchema` name in question so that upgrades can proceed.
It _also_ adds a small `hack/verify-apiresourceschemas.sh` script that compares the `APIResourceSchemas` against the pull request target branch and if there is a diff in the file, it errors if the object name is the same (a diff is …
> :bug: Bump WorkspaceType `APIResourceSchema` name

- docs/content/concepts/apis/exporting-apis.md
Adds an APIBinding example to fit with the example previously on the page and adds some more information on APIBindings/turns some of the bullets into full text.
The asciiflow link did not resolve for me and is also not rendered in the documentation at the moment, so I removed it.
Fixes #
```release-note
NONE
```
> 📖 Add APIBindings example

- .github/dependabot.yaml
- .github/workflows/add-to-project.yml
- .github/workflows/docs-gen-and-push.yaml
- .github/workflows/gh-image-purge.yaml
- .github/workflows/goreleaser.yml
- .github/workflows/pr-verifier.yaml
It's a [best practice](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) to pin workflows used in GitHub Actions to specific commits. We should do that.
In addition, I feel like our dependabot configuration doesn't work (is it maybe not enabled?), so I'm copying the one we are using in kubernetes-sigs/multicluster-runtime.
Fixes #
```release-note
NONE
```
> :seedling: Pin GitHub Actions workflows to commits

- pkg/server/localproxy.go
It looks like we missed a conditional in https://github.com/kcp-dev/kcp/commit/d8cbc0a122831367a63fb879f9fdf2d908bf9189 and now every kcp setup that starts sets up the mini-front-proxy handlers. Looking at the PR (#3199), I don't think that was the intention, and it also started exposing an unauthenticated `/metrics` endpoint on the kcp server binary.
My quick read of the code / logic is: Only register the extra handlers if we indeed want to start a mini-front-proxy by passing additional mappings, but I'm not sure if this is the way to go. @mjudeikis please advise if we should do it differently, but we need to make sure this development feature doesn't bleed into kcp-the-server.
Fixes #3360
```release-note
Stop exposing mini-front-proxy handlers (including `/metrics`) on kcp server unless …
```
> 🐛 Do not set up local mini-front-proxy without additional mappings file

- Makefile
Our make targets don't wait for `test-server` and `sharded-test-server` to properly exit, they just send the signal to shut down. I've seen this before on my local command line where logs where printed after `make test-e2e-sharded-minimal` ended, but it wasn't a huge problem.
However we are seeing this now being an issue on our OCI prow cluster where audit logs were still being written when prow is already trying to archive output files. Therefore, we should wait for `*-test-server` processes to shut down before continuing.
/kind cleanup
/kind flake
Fixes #
```release-note
NONE
```
> Wait for test-server processes to exit in make targets

- cli/OWNERS
In #3342, there was a request for better release notes for the kubectl plugins in specific, since they are being picked up by distribution package maintainers. While this PR doesn't give an easily accessible changelog for the kubectl plugins yet, it's a step towards being able to filter for those changes.
All PRs into `cli/` will be marked with the [area/cli](https://github.com/kcp-dev/kcp/pulls?q=is%3Aopen+is%3Apr+label%3Aarea%2Fcli) label.
Towards #3342
```release-note
NONE
```
> Ensure all PRs into `cli/` are marked with area/cli label

- cmd/kcp-front-proxy/main.go
- cmd/kcp-front-proxy/options/options.go
- pkg/proxy/options/options.go
/kind feature
Fixes #
```release-note
kube-front-proxy: print flags in sections.
```
> kube-front-proxy: add named flags

- Makefile
- cmd/test-server/kcp/shard.go
- cmd/test-server/main.go
- sdk/testing/config.go
- sdk/testing/kcp.go
- test/e2e/reconciler/cache/replication_test.go
I prefer having temporary files, artifacts and the like under e.g. `TMPDIR` and noticed that `WORK_DIR` isn't always honoured.
For the sharded and shared recipes setting `WORK_DIR` actually breaks the runs because the servers are setup with `WORK_DIR` but the clients aren't.
/kind bug
Fixes #
```release-note
NONE
```
> Honour `WORK_DIR`

- config/root-identities/bootstrap.go
- config/root-identities/namespace/bootstrap.go
- config/root-identities/namespace/namespace-kcp-system.yaml
- config/root-identities/secret-identity.yaml
- pkg/server/options/options.go
- pkg/server/server.go
This PR adds a way to inject identities from a file while performing phase0 bootstrapping, making it possible to override core identities with pre-defined ones.
The file is expected to by YAML-formatted, passed via `--root-identities-file` kcp command line flag; its structure is rather simple, see the linked issue for reference.
/kind feature
Fixes https://github.com/kcp-dev/kcp/issues/3320
```release-note
Adds a new --root-identities-file kcp cli flag used to bootstrap APIExport identities inside the root workspace
```
> Bootstrap with pre-defined identities

- .prow.yaml
- Makefile
- go.mod
- pkg/network/dialer.go
- pkg/server/config.go
- pkg/server/options/controllers.go
- sdk/testing/kcp.go
- sdk/testing/server/fixture.go
- test/e2e/framework/inprocess.go
- test/integration/framework/goleak.go
- test/integration/framework/goleak_test.go
- test/integration/framework/server.go
- test/integration/framework/server_test.go
Adding a framework for integration tests.
Startup takes a long time - I am contemplating adding support for a shared embedded etcd (or an external etcd like in kube) if that significantly improves startup.
/kind feature
-
```release-note
NONE
```
> Add `test/integration`

- cmd/sharded-test-server/cache.go
- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/virtual.go
- cmd/test-server/kcp/shard.go
- pkg/server/config.go
- pkg/server/options/options.go
- sdk/testing/config.go
- sdk/testing/kcp.go
- sdk/testing/server/config.go
- sdk/testing/server/fixture.go
- test/e2e/apibinding/apibinding_webhook_test.go
- test/e2e/conformance/webhook_test.go
- test/e2e/fixtures/webhook/webhook.go
- test/integration/framework/server.go
Fix `--bind-address`
The fix is really only this commit, that sets the ExternalAddress if BindAddress is set:  [`eff92dd` (#3418)](https://github.com/kcp-dev/kcp/pull/3418/commits/eff92ddf7200ea05a19416193fbcaced39038cbc)
The others are changing the tests to run on localhost, which I had wanted to implement previously but failed one one hand because the ExternalAddress was the default IP rather than the BindAddress and because the loopback addresses were missing the in the certificates.
/kind bug
Fixes #3404 
```release-note
Fix `--bind-address` not being honoured in some generated configuration files
```
> Fix `--bind-address`

- test/e2e/virtual/apiexport/binding_test.go
Point the `TestAPIBindingPermissionClaimsVerbs` to the consumer workspace (where the APIBinding is) instead to the provider workspace. This caused the sharded test to flake because it couldn't access the APIBinding to read verbs from.
/kind flake
xref #3255 
```release-note
NONE
```
> Point PermissionClaim verbs test to the correct workspace

- docs/content/concepts/apis/admission-webhooks.md
- test/e2e/apibinding/apibinding_webhook_test.go
- test/e2e/conformance/webhook_test.go
- test/e2e/fixtures/webhook/webhook.go
This PR adds more checks for apibinding webhook tests. Also adds docs to note down the behavior of kcp's webhook admission plugins.
Fixes https://github.com/kcp-dev/kcp/issues/3294
```release-note
NONE
```
> Improvements for webhooks docs and tests

- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- pkg/virtual/framework/dynamic/apiserver/openapi.go
- test/e2e/virtual/apiexport/apiresourceschema_cowboys_versions.yaml
- test/e2e/virtual/apiexport/binding_test.go
- test/e2e/virtual/apiexport/openapi_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
At the moment, `kubectl api-resources` in the APIExport Virtual Workspace shows that we serve APIBindings v1alpha2. However, getting an APIBinding (`kubectl get apibinding`) results into getting the v1alpha1 version of the object (it's impossible to get the `v1alpha2` version at all).
This PR addresses this by ensuring both v1alpha1 and v1alpha2 are available via the APIExport Virtual Workspace.
Additionally, fixing this bug undercovered an issue with the virtual workspace OpenAPI v3 endpoint/implementation. If there's a resource with two different versions, it'll cause a panic because we try to register the same GR (GroupResource) two times. This is fixed in this PR as well and it needs to be cherry-picked to `release-0.27`.
Tests are added to cover both of these bugs.
/kind bug
None …
> Serve both v1alpha1 and v1alpha2 APIBindings in APIExport VW, fix virtual workspace OpenAPI v3 panics

- Dockerfile
It looks like we never removed this directive from our Dockerfile, which resulted in unexpected behaviour when running this image on containerd vs CRI-O (containerd mounts a temporary volume into it, CRI-O does not and fails with a "read-only filesystem" error in the Helm chart).
Given that we removed the need for this directory in https://github.com/kcp-dev/kcp-operator/pull/22/commits/06541c98c97a51a91143a506a8d793b17298a6e5, I would vote for removing this volume as well as it shadowed a misconfiguration of the Helm chart that only happens on CRI-O based clusters.
/kind bug
/kind cleanup
Fixes #
```release-note
Remove `VOLUME` from Dockerfile so no `/data` volume is mounted anymore
```
> Remove VOLUME directive from Dockerfile

- pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
- pkg/reconciler/cache/cachedresources/cachedresources_reconcile_replication.go
The reconciler for CachedResources always assumes the label selector is present, which then leads to nil ptr deref panics.
/kind bug
```release-note
NONE
```
> CachedResources reconciler should check for missing label selector

- Makefile
- pkg/features/kcp_features.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/apis/apiexport/apiexport_controller_test.go
- pkg/reconciler/apis/apiexport/apiexport_reconcile.go
- pkg/server/controllers.go
- pkg/server/server.go
- sdk/apis/apis/v1alpha2/types_apiexport.go
- test/e2e/apibinding/apibinding_logicalcluster_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go
- test/e2e/virtual/apiexport/authorizer_test.go
- test/e2e/virtual/apiexport/binding_test.go
- test/e2e/virtual/apiexport/openapi_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Disable APIExport URL population. 
/kind feature
/kind deprecation
Fixes https://github.com/kcp-dev/kcp/issues/3366
```release-note
Deprecated APIExport VirtualWorksapce URL population
Add FeatureFlag to re-enable deprecated APIExport VirtualWorkspace URLs. 
```
> Disable APIExport VirtualWorkspace URL population

- pkg/virtual/framework/forwardingregistry/store.go
- test/e2e/virtual/apiexport/binding_test.go
At the moment, server-side apply requests in the virtual workspaces are authorized exclusively as `patch`. This doesn't match the upstream Kubernetes behavior where such requests are authorized as `create`. This is documented here: https://kubernetes.io/docs/reference/using-api/api-concepts/#patch-and-apply
The initial idea for mitigating this issue, for the APIExport Virtual Workspace, was to bundle `patch` and `create` verbs. In other words, if you request `patch`, you must request `create` as well. However, this doesn't solve the issue that exclusive `patch` can create new resources using SSA, it only "hides" the issue.
This PR takes another approach by running the admission chain if it is determined that the object needs to be created. The admission chain in this case includes the …
> Authorize server-side apply as create in `forwardingregistry`

- pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go
- pkg/reconciler/cache/cachedresources/replication/replication_reconcile.go
Resources from core API use empty group, but this breaks
label selectors that end up being empty, and fail validation.
This PR replaces empty group with 'core'.
/kind bug
```release-note
NONE
```
> Use 'core' group to replicate core API objects

- pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
It looks like all the way back in #2510, we added some logic to mirror the `experimental.tenancy.kcp.io/owner` annotation from `Workspace` objects to `LogicalClusters`. Unfortunately, this is how `pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go` ended up looking like:
https://github.com/kcp-dev/kcp/blob/68596e1e59e966cfc44b1c3c1e6287193f27ca38/pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go#L246-L270
There is a check if `ExperimentalWorkspaceOwnerAnnotationKey` is set on the workspace later on in the code, but the annotation is already set by this time (see the initial set of annotations). This produces an annotation with an empty value, which trips up the owner annotation parser.
Since there might be existing kcp installations out there with bad …
> Do not set the owner annotation on `LogicalClusters` to empty value

- config/crds/tenancy.kcp.io_workspacetypes.yaml
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml
- pkg/openapi/zz_generated.openapi.go
- pkg/reconciler/tenancy/defaultapibindinglifecycle/default_apibinding_lifecycle_controller.go
- pkg/reconciler/tenancy/defaultapibindinglifecycle/default_apibinding_lifecycle_reconcile.go
- pkg/server/controllers.go
- pkg/server/server.go
- sdk/apis/tenancy/v1alpha1/types_workspace.go
- sdk/apis/tenancy/v1alpha1/types_workspacetype.go
- sdk/apis/tenancy/v1alpha1/zz_generated.deepcopy.go
- sdk/client/applyconfiguration/tenancy/v1alpha1/workspacetypespec.go
- test/e2e/apibinding/default_apibinding_test.go
Add a controller to automatically keep defaultAPIBindings defined in a workspacetype up to date in all workspaces that derive from it.
on-behalf-of: @eon-se opensource@eon.com
/kind feature
/kind api-change
* Fixes https://github.com/kcp-dev/kcp/issues/3248
* Replaces: https://github.com/kcp-dev/kcp/pull/3279
```release-note
Add a controller to automatically keep defaultAPIBindings defined in a workspacetype up to date in all workspaces that derive from it.
```
> feat(workspacetype): Add defaultAPIBinding lifecylce

- docs/content/concepts/apis/admission-webhooks.md
- docs/content/concepts/apis/exporting-apis.md
Convert ASCII diagrams to Mermaid diagrams in API documentation to improve readability and maintainability. The changes affect two files:
- docs/content/concepts/apis/admission-webhooks.md
- docs/content/concepts/apis/exporting-apis.md
/kind cleanup
Fixes #3432 
```release-note
NONE
```
```
> docs: Convert ASCII diagrams to mermaid

- go.mod
- go.sum
This fixes CVE-2025-30204
/kind bug
```release-note
Update github.com/golang-jwt/jwt/v4 to 4.5.2 (CVE-2025-30204)
```
> Bump github.com/golang-jwt/jwt/v4 to 4.5.2

- Makefile
There haven't been any relevant changes in 0.9, only a new golangci-lint plugin wrapper. So this PR is just pure maintenance.
/kind cleanup
```release-note
NONE
```
> bump logcheck to 0.9

- pkg/virtual/framework/dynamic/apiserver/openapi.go
- test/e2e/virtual/apiexport/apiresourceschema_cowboys_versions.yaml
- test/e2e/virtual/apiexport/openapi_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Partial cherry-pick of #3430
Fixes an issue with the virtual workspace OpenAPI v3 endpoint/implementation. If there's a resource with two different versions, it'll cause a panic because we try to register the same GR (GroupResource) twice.
/kind bug
```release-note
Fix a panic in the OpenAPI v3 endpoint for Virtual Workspaces happening if there's a resource with two or more versions
```
/assign @xrstf @embik
> :bug: [release-0.27] Fix virutal workspace OpenAPI v3 endpoint panics

- pkg/server/options/flags.go
Under PoC conditions, I tested the usage of an encryption plugin.
It worked smoothly with the built-in and custom resources. I populated the root and another workspace.
/kind feature
```release-note
Enable CLI flag `--encryption-provider-config` in the KCP binary.
```
> Enable --encryption-provider-config flag

- README.md
- docs/content/index.md
- docs/mkdocs.yml
Small docs PR that enriches the docs.kcp.io/kcp landing page with badges and references to the other projects also hosted on docs.kcp.io.
I've looked for a better way to integrate those links but the only thing I found is links in the footer, but those are social links, not cross references. I added YouTube to the footer while I was at it.
This is what the note looks like:
Fixes #
```release-note
NONE
```
> Add references on docs landing page to other projects

- Dockerfile
Currently:
```
>docker run -it --rm ghcr.io/kcp-dev/kcp:main
I0703 14:20:21.146754       1 generic.go:91] "creating root directory" dir="/.kcp"
Error: mkdir /.kcp: permission denied
zsh: exit 1     docker run -it --rm ghcr.io/kcp-dev/kcp:main
```
Expected:
```
>docker run -it --rm kcp:dev
I0703 14:19:10.003794       1 generic.go:107] "using root directory" dir="/.kcp"
I0703 14:19:10.003870       1 controllers.go:84] "generating service account key file" file="/.kcp/sa.key"
W0703 14:19:11.188983       1 registry.go:345] setting componentGlobalsRegistry in SetFallback. We recommend calling componentGlobalsRegistry.Set() right after parsing flags to avoid using feature gates before their final values are set by the flags.
[...]
```
A simpler change would've been to set `WORKDIR` to …
> Allow docker image to run without mounting `/.kcp`

- .gitignore
- contrib/tilt/kind.sh
I had already done these changes a while ago - I don't think a dev script should install tools into non-user directories.
On top if the user has any of the tools installed the current script would still install (and then maybe not use) them.
I think we can assume that `kind` and `helm` are present and that someone wanting to use `tilt` can install it themselves.
/kind cleanup
Fixes #
```release-note
NONE
```
> Rely on user-installed tools

- pkg/admission/cachedresource/admission.go
- pkg/admission/cachedresource/admission_test.go
- pkg/admission/plugins.go
- pkg/reconciler/cache/cachedresources/indexers.go
- pkg/virtual/framework/transforming/transformer_test.go
The admission plugin validates CachedResources creation, and ensures that there is no other such CachedResource in the cluster that acts on the same GVR.
/kind bug
Fixes https://github.com/kcp-dev/kcp/issues/3469
```release-note
Make CachedResources GVR immutable and unique in the logicalcluster 
```
> Add admission plugin for CachedResources

- test/e2e/authorizer/authorizationorder_test.go
- test/e2e/authorizer/utils.go
While refactoring the authorder tests in #3281 we added a small mistake: in each subtest the webhook would get started and its shutdown function registered for cleanup. But then during the test, as intended, we shutdown the webhook and restart it with some other settings. To achieve this, the test manually calls the cancelFunc of the webhook (good) and then starts another webhook (also good).
But for the 2nd instance of the webhook, we do not keep track of its cancellation. Instead when the test finishes, Go will call the cancelFunc for the *1st* webhook *again*, which is pointless at this time.
Additionally, the cancel func for the webhook does not take into account that the webhook will technically *die* because we cancel its context. So the "signal: killed" error that cmd.Wait() …
> Improve authorizer webhook tests

- pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion.go
- pkg/reconciler/tenancy/workspace/workspace_reconcile_deletion_test.go
- test/e2e/workspace/deletion_test.go
This PR changes the deletion relationship between workspaces and logicalclusters to be one way. This means that the workspace will remain as the parent object of a logicalcluster and does not get deleted until the logicalcluster object is completely done. Prior to this, it was possible for a workspace object to be completely removed, even if it still had a logicalcluster (see the issue linked below for more info).
This PR also introduces an E2E test to verify the behavior. Commits are ordered accordingly: If you run the E2E test against the old code, it will fail; with the new code it will pass.
/kind bug
Fixes #3490 
```release-note
NONE
```
> Make deletion relationship between workspace and logicalcluster one way

- config/crds/tenancy.kcp.io_workspaceauthenticationconfigurations.yaml
- config/root-phase0/apiexport-tenancy.kcp.io.yaml
- config/root-phase0/apiresourceschema-workspaceauthenticationconfigurations.tenancy.kcp.io.yaml
- pkg/openapi/zz_generated.openapi.go
- sdk/apis/tenancy/v1alpha1/types_workspaceauthentication.go
- test/e2e/authentication/workspace_test.go
Add CEL validation mimicking the custom validation from upstream:
https://github.com/kubernetes/kubernetes/blob/091f87c10bc3532041b77a783a5f832de5506dc8/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go
It's currently not possible to define claimValidationRules as the generated spec expects all fields to be set.
/kind bug
Fixes #
```release-note
NONE
```
> Add CEL validation to WorkspaceAuthenticationConfiguration

- README.md
- docs/content/index.md
We got a brand new `#kcp-dev`, this PR adds it to the README and docs and cleans that section up a little bit.
Fixes #
```release-note
NONE
```
> Add new kcp-dev Slack channel to getting in touch section

- pkg/index/index.go
- pkg/index/metrics.go
This PR adds a new metric to the cluster index that reports the number of known logicalclusters per shard.
/kind feature
```release-note
Add new `kcp_indexed_logicalclusters` metric that contains the number of known logicalclusters per shard (metric has a `shard` label).
```
> Add kcp_indexed_logicalclusters metric

- test/e2e/authentication/workspace_test.go
- test/e2e/fixtures/authfixtures/authfixtures.go
- test/e2e/fixtures/authfixtures/mockoidc.go
Moves the helpers from `test/e2e/authentication` for OIDC to `test/e2e/fixtures/authfixtures` similar to `test/e2e/fixtures/apifixtures`.
#3513 needs e2e tests that verify that per-workspace users can be authorized to bind an APIExport.
After moving some tests around I feel like it would be overall more coherent to have the OIDC fixtures in a library to use where the core functionality is tested (e.g. APIBinding in test/e2e/apibinding), rather than adding an APIBinding test in test/e2e/authentication.
The package can also later be expanded for more authentication fixtures if need be.
/kind feature
Fixes #
```release-note
NONE
```
> Move e2e mockoidc to authfixtures

- docs/content/setup/kubectl-plugin.md
added a note in kubectl-plugin docs to guide users when to use `kubectl create workspace` instead of `kubectl create-workspace`
Fixes #3559 
```release-note
NONE
```
> Docs: added a note in kubectl-plugin docs to guide users when to use kubectl create workspace

- docs/content/concepts/authentication/workspace.md
- pkg/authentication/extra.go
- pkg/authentication/extra_test.go
- pkg/authentication/groups_test.go
- pkg/authentication/index.go
- pkg/authentication/index_test.go
- test/e2e/authentication/workspace_test.go
- test/e2e/fixtures/authfixtures/mockoidc.go
Filters keys containing `kcp.io` from user extra entries.
The `kcp.io` keys should only be set by KCP when necessary. 
For the future it will still be possible to explicitly allow explicit keys.
Relevant to #3513 
CEL validation: Would make later adjustments like allowing explicit keys, harder
/kind cleanup
Fixes #
```release-note
NONE
```
> Filter extra keys containing `kcp.io` on per-workspace authentication

- docs/content/contributing/.pages
- docs/content/contributing/governance/security-self-assessment.md
This adds a [security self-assessment](https://tag-security.cncf.io/community/assessments/guide/self-assessment/) document to the repository, which is one of the documents we require for applying to the incubating stage at CNCF (also see #3445).
Fixes #
```release-note
NONE
```
> Add security self-assessment

- README.md
```
Change adds a "Quick Start for Development" section to help developers get kcp
running locally with setup instructions.
```
Fixes #
[Fixes](https://github.com/kcp-dev/kcp/issues/3574)
```release-note
NONE
```
> add a quick how to start section to README

- docs/content/setup/.pages
- docs/content/setup/integrations.md
This adds an "Integrations" page to give practical advice on how to integrate other CNCF (and non-CNCF) projects. A general note is included that any CNCF project that is a controller/operator can be integrated.
Fixes #
```release-note
NONE
```
> Add integrations page to documentation

- cmd/sharded-test-server/cache.go
- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/virtual.go
- cmd/test-server/kcp/shard.go
- sdk/testing/helpers/repo.go
- sdk/testing/server/fixture.go
- sdk/testing/server/metrics.go
- test/e2e/framework/flags.go
- test/e2e/framework/kcp.go
- test/e2e/framework/kubectl.go
When using `sdk/testing` outside of the kcp repository this happens:
```
goroutine 127 [running]:
testing.(*M).startAlarm.func1()
/opt/homebrew/Cellar/go/1.25.1/libexec/src/testing/testing.go:2682 +0x490
created by time.goFunc
/opt/homebrew/Cellar/go/1.25.1/libexec/src/time/sleep.go:215 +0x44
goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0008b0a80, {0x105381641, 0x12}, 0x10626b7f0)
/opt/homebrew/Cellar/go/1.25.1/libexec/src/testing/testing.go:2005 +0x700
testing.runTests.func1(0xc0008b0a80)
/opt/homebrew/Cellar/go/1.25.1/libexec/src/testing/testing.go:2477 +0x78
testing.tRunner(0xc0008b0a80, 0xc000071ad8)
/opt/homebrew/Cellar/go/1.25.1/libexec/src/testing/testing.go:1934 +0x168
testing.runTests(0xc0002439f8, {0x107f78950, 0x1, 0x1}, {0x5e6752d3e2f4c05b?, 0x0?, 0x107feaf40?}) …
```
>  Fix sdk/testing panicking when used outside of a kcp clone 

- .github/workflows/goreleaser.yml
Manual cherry-pick of #3601.
/kind cleanup
Fixes #
```release-note
NONE
```
> [release-0.28] Free disk space in release workflow

- pkg/authorization/requiredgroups_authorizer.go
Fix code documentation for required-groups authorization behavior which was fixed in the docs in #3577 
Fixes #
```release-note
NONE
```
> Documentation fix: code documentation for required-groups annotation

- hack/gen-patch-defaultrestmapper.sh
We should not assume the sed revision based on the Operating system. For example on my Mac, I am using gnu sed, which causes the script to fail. I think in this case the fix is rather straightforward, but if you ever run into this in a more complicated setting you can make use of is_gnu_sed snippet https://github.com/kcp-dev/kcp/blob/e3c2d234c1e93f7e643ae600276090aaaeb7d7eb/hack/verify-contextual-logging.sh#L40-L45
/kind bug
Fixes #
```release-note
NONE
```
> don't assume sed revision based on OS

- cli/pkg/base/options.go
```
change fixes bug when rrunning workspace commands with 
either kubeconfig flag or environment variable
```
/kind bug
Fixes #
https://github.com/kcp-dev/kcp/issues/3594
```release-note
NONE
```
> fix bug when running ws command with kubeconfig flags

- docs/content/concepts/authorization/authorizers.md
- test/e2e/apibinding/cross_workspace_auth_test.go
- test/e2e/authorizer/scopes_test.go
- test/e2e/fixtures/authfixtures/serviceAccount.go
Needs https://github.com/kcp-dev/kubernetes/pull/176
This adds tests ensuring that global users (with scopes and with warrants), service accounts and per-workspace users can bind APIExports of another workspace when said workspace allows binding from the source workspace through the `system:cluster:<logical-cluster>` group, where `<logical-cluster>` is the name of the logical cluster backing the source workspace.
This is representative of other cross-workspace requests and should work for any cross-workspace authorization check.
Caveat:
Global users without scopes or warrants are not considered at the moment (though could be covered by simply adding the `system:cluster:..` group to the request when creating an APIBinding - but that would only work for APIBinding/-Exports). They will still …
> Add `system:cluster:<logical-cluster>` group to effective users to enhance cross-workspace authz
