kcp-dev/kcp

- cmd/cluster-controller/main.go
- cmd/crd-puller/pull-crds.go
- cmd/kcp/kcp.go
- cmd/syncer/main.go
- go.mod
- pkg/cmd/help/doc.go
- pkg/crdpuller/discovery.go
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/cluster/syncer.go
This PR accomodates the CRD tenancy hacks made on the `kubernetes` side in commit https://github.com/kcp-dev/kubernetes/commit/816623327aac1a22360e9d31d589cf11af8bc1ef
It also enables CRD tenancy support in the cluster controller and adds the ability to optionally integrate the cluster-controller, as well as the syncer deployment, directly inside the kcp command line.
When the corresponding flag is enabled, kcp will fetch CRDs from registered physical clusters, install them into KCP, and the corresponding logical clusters will be able to see them.
> Update the KCP command line to CRD-tenancy changes, and include the cluster controller.

- cmd/syncer/main.go
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/syncer.go
- pkg/syncer/syncer.go
- Make the syncer correctly point to the `to` cluster (with the option of passing a kubeconfig for it)
- Only try to synchronize the resource types that have effectively been been imported by the cluster controller
- Create the required rbac rules to enable the syncer service account to create the synced objects in the `to` cluster.
- Fix the syncer reconcile loop and add more detailed logs.
> More fixes on the Syncer

- pkg/crdpuller/discovery.go
Avoid pruning metadata fields that are inside spec
This fixes issue #43.
The problem was that the `ObjectMeta` hard-coded Schema was not defining the `x-preserve-unknown-fields` openapi extension.
So when creating a custom reosurce whose schema contains a field of this type inside its Spec, the content of the metadata map was systematically pruned.
> Avoid pruning metadata fields that are inside spec (Fix for issue #43)

- pkg/reconciler/cluster/controller.go
- pkg/reconciler/deployment/controller.go
Enqueue the object's key instead of the full object, so that when we process the item we don't panic trying to interpret the object as the key.
This is consistent with cluster-controller, and other controllers in general.
> Fix enqueueing in deployment splitter

- pkg/reconciler/deployment/controller.go
When you have a single downstream cluster, the `deployment-splitter` adds a `cluster: your-downstream` label to the fetched deployment struct `root` internally. But currently `pkg/reconciler/deployment/controller.go` only detects a diff in the `Status` field, so the `cluster` label cannot be included.
Instead of the `controller.go` as this PR, alternately we can update the deployment in `pkg/reconciler/deployment/deployment.go` like the following: Which is better?
```go
if len(cls) == 1 {
// nothing to split, just label Deployment for the only cluster.
if root.Labels == nil {
root.Labels = map[string]string{}
}
// TODO: munge cluster name
root.Labels[clusterLabel] = cls[0].Name
if _, err := c.kubeClient.AppsV1().Deployments(root.Namespace).Update(ctx, vd, metav1.UpdateOptions{}); err != …
```
> Reconcile a whole deployment not only its status

- cmd/cluster-controller/main.go
- cmd/kcp/kcp.go
- cmd/syncer/main.go
- ns.yaml
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/controller.go
- pkg/syncer/syncer.go
This adds a mode to the cluster controller that runs the syncer code as a separate loop inside the cluster controller, which allows syncing to happen from outside the cluster.
This is an alternative to the two existing modes: pull mode, which runs syncer as a deployment inside the target cluster, and "none-mode" (name needs work) where the syncer is run as a separate binary started up by the person running the other kcp machinery.
This new mode allows for kcp+controllers to more easily run as one standalone binary responsible for watching and managing multiple clusters, without having to run things inside them.
> Support --push_mode, where syncer runs inside cluster controller

- GOALS.md
- docs/investigations/minimal-api-server.md
Just a stub since this has the most need of feedback from different
efforts. Also add one more principle (discussed in terms of how
kcp can help with minimal API server).
Starts #48
> docs/investigations: Provide a stub for the minimal API server

- pkg/apis/cluster/v1alpha1/cluster_types.go
- pkg/apis/cluster/v1alpha1/conditions.go
- pkg/reconciler/cluster/cluster.go
The original implements for updating `cluster.status.conditions` is not correct.
The 
```
func (c Conditions) SetReady(status corev1.ConditionStatus, reason, message string) {
for idx, cond := range c {
if cond.Type == ClusterConditionReady {
c[idx] = Condition{
Type:               ClusterConditionReady,
Status:             status,
Reason:             reason,
Message:            message,
LastTransitionTime: metav1.Now(),
}
return
}
}
c = append(c, Condition{
Type:               ClusterConditionReady,
Status:             status,
Reason:             reason,
Message:            message,
LastTransitionTime: metav1.Now(),
})
}
```
can not modify the outer `cluster.status.conditions` with the `append`.
In `push` node, that's lead to every reconcile will try to create new `syncer` in the …
> Condition of cluster not set correct, lead to create infinited syncer

- contrib/demo/README.md
The example `cluster` is incorrect.
value of `kubeconfig` need indent
> Correct example of Cluster in the document

- pkg/syncer/syncer.go
Will get these message loop infinite like this:
```
2021-05-17 18:38:27.763163 I | stopping syncer worker
2021-05-17 18:38:27.763169 I | stopping syncer worker
2021-05-17 18:38:27.763177 I | stopping syncer worker
2021-05-17 18:38:27.763183 I | stopping syncer worker
2021-05-17 18:38:27.763189 I | stopping syncer worker
2021-05-17 18:38:27.763195 I | stopping syncer worker
2021-05-17 18:38:27.763201 I | stopping syncer worker
2021-05-17 18:38:27.763207 I | stopping syncer worker
2021-05-17 18:38:27.763213 I | stopping syncer worker
2021-05-17 18:38:27.763219 I | stopping syncer worker
2021-05-17 18:38:27.763223 I | stopping syncer worker
2021-05-17 18:38:27.763226 I | stopping syncer worker
2021-05-17 18:38:27.763232 I | stopping syncer worker
2021-05-17 18:38:27.763239 I | stopping …
```
> Avoid infinite loop when delete cluster with push mode

- .gitignore
- cmd/syncer/main.go
- contrib/demo/clusters/kind/createKindClusters.sh
- contrib/demo/clusters/kind/us-east1.config
- contrib/demo/clusters/kind/us-west1.config
- contrib/demo/script
- contrib/demo/startKcpForDemo.sh
- contrib/kcp.code-workspace
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/deployment/deployment.go
- pkg/syncer/specsyncer.go
- pkg/syncer/statussyncer.go
- pkg/syncer/syncer.go
- pkg/util/errors/retryable.go
This PR completes the remaining required implementation parts to have the Demo fully working as expected.
Main it:
- adds the synchronization of the object status from the physical clusters back to KCP.
- fixes a race condition that allowed ignoring the synchronization of an object when the corresponding API resource was not published and available in KCP soon enough.
It is paired with upcoming PRs in the [KCP Kubernetes feature branch](https://github.com/kcp-dev/kubernetes), but still can be compiled and run well without them.
> Add status sync and other demo fixes

- contrib/demo/startKcpAndClusterController.sh
fix typo in demo script.
```bash
$ ./startKcpAndClusterController.sh
Starting KCP
Starting Cluster Controller
Use ctrl-C to stop them
flag provided but not defined: -pull_model
Usage of /Users/aigarash/Developments/src/github.com/kcp-dev/kcp/bin/cluster-controller:
...
```
> Fix flag typo in startKcpAndClusterController.sh

- contrib/demo/script
Fixed the path to the `cluster.example.dev_clusters.yaml` in demo script so that it can be executed from the non-repository root directory.
> Fix path to the dev_cluster.yaml in demo script

- cmd/kcp/kcp.go
Flags and TLS setup based on code from kube-apiserver.
Tested and should work with both TLS enabled etcd and plain http.
> Add CLI flags to optionally connect to an external etcd.

- .gitignore
- Makefile
- cmd/cluster-controller/main.go
- config/apiresource.kcp.dev_apiresourceimports.yaml
- config/apiresource.kcp.dev_negotiatedapiresources.yaml
- contrib/demo/startKcpForDemo.sh
- pkg/apis/apiresource/v1alpha1/common_types.go
Also:
- gitignore `*.log` files created by demo scripts
- rewrite `make build` for brevity
- log resources that cluster controller will sync
- rebuild and apply CRDs in demo script
> Make group not required, to support core types

- DEVELOPMENT.md
- cmd/kcp/kcp.go
- pkg/server/config.go
- pkg/server/server.go
I sent a [Slack message](https://kubernetes.slack.com/archives/C021U8WSAFK/p1630021405002500) indicating that it would be useful if the KCP project could be structured in a way that we could easily combine both the KCP API server and our own custom controllers into a single binary. Currently, the KCP API server is constructed in the `cmd/kcp/kcp.go` file and is configured only with command line flags which is not conducive to importing into your own projects.
This PR aims to address a few things
* Moves the core construction of the API server to a new package (`pkg/server`) and replaces all the construction code in `cmd/kcp/kcp.go` with an implementation of the new API server package.
* Adds the ability to customize the API server by either passing a `*pflag.FlagSet` or a struct with all …
> Make the API server an importable package

- pkg/server/config.go
The var resources_to_sync was not being used as when trying to parse it, it was parsed as type `StringSlice` while being defined as `StringArray`.
``` 
resourcesToSync, err := flags.GetStringSlice("resources_to_sync")
if err == nil {
cfg.ResourcesToSync = resourcesToSync
}
```
I changed the var definition instead that the parsing as with StringSlice we can define multiple resources separated by commas and/or by adding extra `resouce_to_sync` flags.:
```
--resources_to_sync=deployments.apps --resources_to_sync=ingresses.networking.k8s.io,ingressclasses.networking.k8s.io
```
> Fixes "resources_to_sync" flag as it was type mismatched when parsing the flags.

- pkg/reconciler/cluster/syncer.go
- pkg/syncer/syncer.go
* Removing processing of items in the same namespace as the syncer.
fixes #83
> Adding downward API for the namespace of the syncer iamge

- embed.go
- pkg/reconciler/cluster/controller.go
This allows registering KCP CRDs (located inside the `config` folder) at KCP start, whatever be the current directory in which KCP is started.
> Use `go:embed` to embed KCP CRDs

- pkg/reconciler/deployment/deployment.go
This PR tries to fix an issue as follows.
In the implementation of deployment-splitter, if there is only one cluster, current logic is to directly convert the root Deployment into a virtual deployment.
Consequently, the virtual deployment becomes an 'orphan', with no root Deployment. Thus in the following reconciliation cycles, errors are generated by
https://github.com/kcp-dev/kcp/blob/e0096fefde31a6c4c3e309693205f1568886aa2b/pkg/reconciler/deployment/deployment.go#L66
Finally the controller runs out of retries, and following logic, which  updates status of the root Deployment, never gets a chance to run.
> Treat the 'single cluster' case the same as 'multiple clusters' in deployment-splitter

- pkg/schemacompat/schemacompat_test.go
This PR adds unit tests for schemacompat. After newly added unit tests,
code coverage increases to 68%.
fixes https://github.com/kcp-dev/kcp/issues/128 partially.
> Add unit tests for schemacompat

- hack/tools.go
Without this import, `go mod tidy` removes the useful tool.
> hack: import tools to keep go mod happy

- cmd/syncer/main.go
Experimenting with the syncing part of kcp, running the `syncer` binary was not yet entirely intuitive to me. These minor improvements should help make its purpose and configuration easier to grasp without having to read into the source code too much.
> Improve the help text of syncer + add logging

- pkg/syncer/statussyncer.go
Currently `deepEqualStatus` returns true when the status is empty/nil in both objects. This is causing reconciling to happen needlessly for objects with an empty status, and triggers errors in objects that do not have a status (e.g., a ConfigMap).
> Do not try to sync status when status field is empty or nil in both objects

- .codecov.yaml
- .github/workflows/ci.yaml
We can reenable it later if we think being constantly reminded of coverage is a benefit.
> Disable codecov

- cmd/cluster-controller/main.go
- pkg/etcd/etcd.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/apiresource/negotiation.go
- pkg/reconciler/cluster/apiimporter.go
- pkg/reconciler/cluster/controller.go
- pkg/server/server.go
Simplify etcd Server Run() so it returns the client info instead of taking in a run func.
Replace the runFunc with inline code.
Create clients and shared informer factories higher in the stack so they can be shared by multiple controllers.
Plumb the context's Done channel to as many places as possible.
> Refactor server run

- pkg/server/server.go
Use the passed in ctx for MemberList instead of context.Background() so
the MemberList call respects when the ctx is done (e.g. via ctrl-c).
> Use the correct ctx for MemberList

- cmd/cluster-controller/main.go
- cmd/deployment-splitter/main.go
- cmd/syncer/main.go
- go.mod
- go.sum
- pkg/crdpuller/discovery.go
- pkg/etcd/etcd.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/apiresource/negotiation.go
- pkg/reconciler/cluster/apiimporter.go
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/cluster/syncer.go
- pkg/reconciler/deployment/controller.go
- pkg/reconciler/deployment/deployment.go
- pkg/sharding/apiserver/handler.go
- pkg/sharding/apiserver/state.go
- pkg/syncer/specsyncer.go
- pkg/syncer/statussyncer.go
- pkg/syncer/syncer.go
The rest of k8s core is already on v2, there's no reason for us to use
the older library and it cuases some pain when using both at once.
> techdebt: use klog/v2

- cmd/cluster-controller/main.go
When try to start `cluster-controller` by calling
```
go run ./cmd/cluster-controller \
--syncer_image=$(ko publish ./cmd/syncer) \
--kubeconfig=.kcp/admin.kubeconfig
```
It's not work, since the `apiresourceController` is not started...
> Start controllers in its goroutines

- config/bootstrap.go
- pkg/reconciler/cluster/controller.go
- pkg/server/server.go
Today, we have a helper to apply some YAML to the default logical
cluster. However, we would like to be able to apply specific CRDs, as
not every controller needs all possible CRDs, we would like to direct
the application to specific logical clusters, and we would like to wait
for the system to establish the CRDs before moving on, or client calls
to these APIs will fail if made quickly after they are introduced. This
patch adds all of that functionality, as well as using Go's embedding
for the data so that the routine is portable.
> config: add a simple bootstrapping routine for CRDs

- .github/workflows/ci.yaml
- .gitignore
- Makefile
- config/apiresource.kcp.dev_apiresourceimports.yaml
- config/apiresource.kcp.dev_negotiatedapiresources.yaml
- config/cluster.example.dev_clusters.yaml
- config/tenancy.kcp.dev_workspaces.yaml
- config/tenancy.kcp.dev_workspaceshards.yaml
- go.mod
- go.sum
- hack/go-install.sh
- hack/tools.go
- hack/update-codegen.sh
- Now installing controller-gen in a consistent location for everyone hacking on this project - thanks to the Cluster API folks for the install script!
- Pinned controller-gen to v0.7.0
- Remove code-generator from hack/tools.go so it's not listed in our project's go.mod any more
- hack/update-codegen.sh now must be invoked via `make` (it errors if not)
- Fixed codegen script to work with controller-gen v0.7.0
- Regenerated CRDs using updated controller-gen version
> Pin controller-gen to v0.7.0

- go.mod
- go.sum
- hack/tools.go
Add the generators from code-generator to tools.go so the 'go list'
command in hack/update-codegent-client.sh can find k8s.io/code-generator
correctly.
(The additional gengo line in go.sum comes from running `go mod tidy` 🤷)
> Add code-generator to tools.go

- config/bootstrap.go
When bootstrapping CRDs, if they already exist, don't consider it an
error.
Fixes #232
> Fix CRD bootstrapping for already existing

- .github/workflows/gh-issues-issue-opened.yml
The normal token is read-only and cannot touch projects.
> Use environment secret gh token for gh-issues-issue-opened.yml

- pkg/reconciler/cluster/syncer.go
Since in `pull mode`, when create `clusterrole` we do not grant `delete` permission to the `sa`.
> fix issue: syncer cannot work when original resource was delete in logic cluster

- pkg/reconciler/deployment/deployment.go
The deployment `splitter` controller should only touch `root` deployment(no label `kcp.dev/cluster` exsited), or `leaf` deployment (with labels: `kcp.dev/cluster`, `kcp.dev/owned-by` both)
Current implement will keep raising `err: Root deployment not found`, when reconcile on a normal deployment(with label: `kcp.dev/cluster` but no `kcp.dev/owned-by`)
> Only reconcile on root deployment and leaf deployment

- pkg/reconciler/cluster/syncer.go
Missing parameter: `from_cluster`
> Correct syncer in pull mode, missing parameter: from_cluster

- cmd/cluster-controller/main.go
- cmd/kcp/kcp.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/cluster/startup.go
- pkg/server/config.go
- pkg/server/server.go
config: use a more common pattern for binding flags
---
server: refactor cluster controller to DRY it out
The server options loading and startup code is identical between the
standalone binary and the post-start-hook. This commit makes the code
actually shared.
---
> DRY out server startup

- Makefile
- go.mod
- go.sum
- hack/tools.go
Use go-install.sh for openshift-goimports so we don't leak tools-only
dependencies into our go.mod.
Fixes #256
> Use go-install.sh for openshift-goimports

- .github/workflows/ci.yaml
- .golangci.yaml
Looks like we catch instances of this in review, so there's nothing to
fix up in the codebase.
> ci: turn on more linters

- contrib/demo/apiNegotiation-startKcp.sh
- contrib/demo/kubecon-startKcp.sh
Due to the latest changes on how flags are parsed, demos were broken.
Demos just requiring only "deployments.app" to be synced, were working out of pure luck as it matched the set defaults for the unset flag.
Signed-off-by: Joaquim Moreno <joaquim@redhat.com>
> Adds missing flag to demo files

- config/bootstrap.go
We need to defer the call to `time.Since()` or we don't get a meaningful
result.
> config: fix timing log

- pkg/reconciler/workspace/controller.go
- test/e2e/reconciler/workspace/controller_test.go
We never set target to be an empty string, so this logic was bugged and
coudl race.
fixes https://github.com/kcp-dev/kcp/issues/268
> reconciler: workspace: deflake movement

- .github/workflows/ci.yaml
- Makefile
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/workspace/controller_test.go
e2e: framework: allow naming kcp servers
For better UX when poking around inside of the artifact directory for
tests with more than one kcp server, we allow naming them.
---
makefile: add a helper for running e2e tests
Since the e2e runs kcp servers via the binary, we need to make sure that
a) the built binaries are in $PATH and b) we re-build when running.
---
e2e: workspace: scope testCase variable
Without this scoping step, the reference leaks out to each test
goroutine.
---
test: e2e: improve artifact capture, run more tests
We now distinguish between the data directories for kcp servers we start
and the artifacts that a test …
> Improvements to E2E framework, artifact capture

- .github/workflows/gh-issues-issue-opened.yml
- do not use the projects environment, not needed anymore with GITHUB_TOKENS
- account = kcp-dev, the org
> workflows/gh-issues-issue-opened: no projects env and use kcp-dev org

- .github/workflows/ci.yaml
Not only does isolating different checks to different jobs improve the
UX of seeing a failure and understanding quickly what caused it, this
split also saves us about 50% of our test runtime as we're not waiting
to start compiling the k8s e2e.
> ci: reconfigure to isolate jobs for UX and speed

- .github/workflows/ci.yaml
- .golangci.yaml
Import checking is already covered by `make verify-codegen`
> Move misspell and gofmt into golangci-lint config

- config/bootstrap.go
When a KCP is restarted without wiping out the storage beforehand, bootstrapping CRDs will hang because the watch never gets any events since the CRDs already exist.
This will get the CRDs if they already exist and complete bootstrapping if they are already established.
> Complete bootstrap for CRDs that already exist

- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
Deferring the new framework.Artifact() will write a YAML file with the
object that you're asking to be saved. The file will be placed under
directories as necessary for the logical cluster and namespace it's in,
and named by kind.group_name.
fixes https://github.com/kcp-dev/kcp/issues/271
> test: e2e: framework: add a simple artifact saver

- .github/workflows/ci.yaml
- Makefile
- pkg/client/clientset/versioned/typed/apiresource/v1alpha1/apiresourceimport.go
- pkg/client/clientset/versioned/typed/apiresource/v1alpha1/negotiatedapiresource.go
- pkg/client/clientset/versioned/typed/cluster/v1alpha1/cluster.go
- pkg/client/clientset/versioned/typed/tenancy/v1alpha1/workspace.go
- pkg/client/clientset/versioned/typed/tenancy/v1alpha1/workspaceshard.go
- test/e2e/reconciler/cluster/client/clientset/versioned/typed/wildwest/v1alpha1/cowboy.go
Bump go CI version to 1.17.
Fix verify-codegen when running in CI. Because this repo is not cloned into GOPATH, we have to set up a symlink so the code generators that currently only support outputting in GOPATH will work correctly. Otherwise, it will look like code generation always passes verification because it's not checking the right files.
Regenerate clients to match generators in current Kubernetes version.
> Fix verify-codegen

- test/e2e/framework/expect.go
It is required that the reader lock be held when writing to the results
channel. That was true in all cases but one.
Without this, you may see:
```
==================
WARNING: DATA RACE
Write at 0x00c000537b70 by goroutine 66:
runtime.closechan()
/usr/local/go/src/runtime/chan.go:355 +0x0
github.com/kcp-dev/kcp/test/e2e/framework.(*expectationController).ExpectBefore.func2()
/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/test/e2e/framework/expect.go:139 +0xdd
github.com/kcp-dev/kcp/test/e2e/framework.(*expectationController).ExpectBefore()
/home/stevekuznetsov/code/kcp-dev/kcp/src/github.com/kcp-dev/kcp/test/e2e/framework/expect.go:161 +0x56c
github.com/kcp-dev/kcp/test/e2e/framework.ExpectWorkspaces.func1() …
```
> e2e: framework: squash one last concurrency bug

- pkg/etcd/etcd.go
- pkg/server/config.go
- pkg/server/server.go
- test/e2e/framework/kcp.go
Running tests does not require hundreds of MB of WAL, so allow
configuring it to be smaller.
> server: allow configuring etcd WAL size

- test/e2e/framework/expect.go
Fixes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d58a91]
goroutine 2539 [running]:
github.com/kcp-dev/kcp/test/e2e/framework.(*expectationController).ExpectBefore.func3()
/home/runner/work/kcp/kcp/test/e2e/framework/expect.go:148 +0x91
created by github.com/kcp-dev/kcp/test/e2e/framework.(*expectationController).ExpectBefore
/home/runner/work/kcp/kcp/test/e2e/framework/expect.go:146 +0x40a
```
> e2e: framework: fix segfault in race condition

- test/e2e/framework/util.go
Before:
```
$ tree /tmp/e2e/TestClusterController/create_an_object,_expect_spec_to_sync_to_sink/3102095384/artifacts/
/tmp/e2e/TestClusterController/create_an_object,_expect_spec_to_sync_to_sink/3102095384/artifacts/
└── kcp
├── sink
│   ├── kcp
│   │   └── sink
│   │       └── 192-168-0-243-41769---admin
│   │           └── cluster-controller-test
│   │               └── cowboys.wildwest.dev_timothy.yaml
│   └── kcp.log
└── source
├── kcp
│   └── source
│       ├── 192-168-0-243-41333---admin
│       │   └── clusters.cluster.example.dev_us-east1.yaml
│       └── 192-168-0-243-41769---admin
│           └── cluster-controller-test
│               └── cowboys.wildwest.dev_timothy.yaml
└── kcp.log
12 directories, 5 files
```
After:
```
$ …
```
> e2e: framework: fix double-nested artifacts

- pkg/gvk/gvk.go
- pkg/informer/informer.go
- pkg/reconciler/namespace/controller.go
- pkg/reconciler/namespace/namespace.go
- pkg/reconciler/namespace/namespace_test.go
- pkg/server/config.go
- pkg/server/server.go
- test/e2e/reconciler/namespace/controller_test.go
This does not yet include:
- syncer transforming namespace names when applying to physical clusters (probably in another more syncer-focused PR)
> Schedule namespaces and all resources in them to clusters

- test/e2e/framework/util.go
Scope the discovery client to match the produced object's logical
cluster, so discovery is going against the same/correct logical cluster
when trying to use the RESTMapper. Otherwise, we may get "no matches for
GVK" errors.
> e2e/artifacts: use a scoped discovery client

- config/tenancy.kcp.dev_workspaceshards.yaml
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/reconciler/workspaceshard/controller.go
- test/e2e/reconciler/workspaceshard/controller_test.go
Downstream consumers of shard credentials need to know when the
credentials are rotated. For instance, any client that first determines
that data they care about is on a shard, then begins some process to
monitor that data, must know when the credentials used to access that
shard change. In order to not require that all of these clients watch
Secrets, record the version of the credentials that are loaded.
> workspaceshard: record the version of loaded credentials

- Makefile
- contrib/demo/apiNegotiation-removeClusters.sh
- contrib/demo/clusters/kind/us-east1.config
- contrib/demo/clusters/kind/us-west1.config
- contrib/demo/ingress
- contrib/demo/ingress-prepareClusters.sh
- contrib/demo/ingress-removeClusters.sh
- contrib/demo/ingress-startKcp.sh
- contrib/demo/ingress.result
- contrib/demo/kubecon-removeClusters.sh
- contrib/demo/nginx-ingress.yaml
- contrib/demo/runDemos.sh
- contrib/examples/ingress-demo/full-example.yaml
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/apps.k8s.io_deployments.yaml
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/ingress/core.k8s.io_services.yaml
- test/e2e/reconciler/ingress/ingress.yaml
- test/e2e/reconciler/ingress/networking.k8s.io_ingresses.yaml
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
Added a new demo focused on the Ingress object.
- Showcases the ability to schedule Ingresses following a workload between physical clusters.
- Misc fixes on bash scripts (removes duplicated clusters names, adds a missing hashbang).
- Adds Makefile targets for the demos and some simple improvements, like a help message with some basic descriptions.
- Adds e2e tests for the Ingress controller
The demo can be run via: `make demo-ingress`. Requires envoy to be installed.  
Signed-off-by: Joaquim Moreno joaquim@redhat.com
> Ingress controller demo and e2e tests

- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/framework/test.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
When we're running many tests in parallel, random directories are chosen
for every invocation. In order to ensure that test processes are placing
artifacts and data in the correct place, we need to pass that
information down.
> e2e: framework: expose artifact and data dirs to tests

- cmd/shard-proxy/main.go
- pkg/apis/tenancy/v1alpha1/helper/helper.go
- pkg/apis/tenancy/v1alpha1/helper/helper_test.go
- pkg/reconciler/workspace/controller.go
- pkg/reconciler/workspaceindex/controller.go
- pkg/reconciler/workspaceindex/index.go
- pkg/reconciler/workspaceindex/server.go
- pkg/server/handler.go
- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/framework/accessory.go
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceindex/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
e2e: framework: expose artifact and data dirs to tests
When we're running many tests in parallel, random directories are chosen
for every invocation. In order to ensure that test processes are placing
artifacts and data in the correct place, we need to pass that
information down.
---
e2e: framework: isolate the accessory process code
---
e2e: rework how artifacts are deferred
Now, you can call server.Artifact() from anywhere and it should
correctly be run before the test is finished and kcp has been
terminated.
---
cmd: add a shard proxy server
Today, this server knows how to find all of the organizational
workspaces, the …
> cmd: add a shard proxy server

- config/apiresource.kcp.dev_apiresourceimports.yaml
- config/apiresource.kcp.dev_negotiatedapiresources.yaml
- pkg/apis/apiresource/v1alpha1/common_types.go
Set the x-kubernetes-map-type to atomic for the OpenAPIV3Schema field in
apiresourceimports and negotiatedapiresources. This causes server-side
apply to treat the schema as an atomic unit, instead of trying to track
each individual field/element of the schema (which causes 34-second
timeouts in the apiserver trying to process the data).
> Make OpenAPIV3Schema atomic

- pkg/server/handler.go
- pkg/server/server.go
Functionally unchanged, i.e. pure move, with this small exception:
- remove special case to serve core/v1 discovery directly if there is no core/v1 CRD. Better have one code path well tested rather than two where one in an exception.
> server: split apart CRD core/v1 merging

- .github/workflows/ci.yaml
- Makefile
- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/framework/accessory.go
- test/e2e/framework/expect.go
- test/e2e/framework/kcp.go
- test/e2e/framework/t.go
- test/e2e/framework/test.go
- test/e2e/framework/testhelper.go
- test/e2e/framework/testhelper_test.go
- test/e2e/framework/users.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceindex/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/framework/composite_test.go
- test/e2e/virtual/framework/compositecmd/cmd.go
- test/e2e/virtual/framework/compositecmd/rest.go
- test/e2e/virtual/helpers/helpers.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
With the new 'e2e' build tag, end-to-end tests do not compile by
default. This means that tools like `go test` and `golangci-lint` won't
run anything from those files by default, you need to ask for it. The
`make test-e2e` target does that for tests, and the `make lint` target
makes sure you do it for static analysis as well.
/assign @ncdc
> test/e2e: use a build tag for e2e tests

- cmd/kcp/kcp.go
- cmd/shard-proxy/main.go
- pkg/server/server.go
First ctrl-c closed context. Second ctrl-c exits.
Also post-start-hook should not return errors, but either return nil or keep going (otherwise you can a pretty `klog.Fatalf` stacktrace). `WaitForSync` only returns when the context is closed. So no need to put a loop around.
> cmd: wire genericapiserver.SetupSignalContext() into servers for proper shutdown behaviour

- contrib/demo/.setupEnv
- contrib/demo/.startUtils
- contrib/demo/apiNegotiation-script/prepareClusters.sh
- contrib/demo/clusters/kind/createKindClusters.sh
- contrib/demo/runDemoScripts.sh
- contrib/demo/startKcpAndClusterController.sh
Don't pass --posix to sed (breaks on Mac's BSD-based sed).
For podman 3.x, work around an issue where podman isn't able to
correctly port forward to a service bound to localhost in the podman vm
(see podman issue 11528). The workaround is to manually set up SSH port
forwarding.
> Better support for running the demos on Mac and with podman 3.x

- pkg/server/server.go
They accidentally got moved above controller initializtion, so none of the post-start hooks set up using s.AddPostStartHook were running (the ones that use server.AddPostStartHook were).
> Restore post-startup hooks

- pkg/authorization/workspace_content_authorizer.go
- pkg/server/server.go
Before this you could access lcluster that didn't exist as workspaces.
> rbac: check for workspace existence

- pkg/syncer/syncer.go
Syncers currently leak informers and workers after being stopped, so that events from informers are still processed by the workers, while the underlying workqueue is shut down, which leads to infinite loops that starve CPU. 
The Done channel from the cancellable context is passed to the syncer informers and workers, instead of the parent context one, so that the syncer stop is properly propagated.
Fixes #409.
> syncer: Fix informers and workers leak

- pkg/apis/tenancy/v1alpha1/helper/helper.go
- pkg/apis/tenancy/v1alpha1/helper/helper_test.go
- pkg/server/apiextensions.go
- test/e2e/api_inheritance/api_inheritance_test.go
Update the inheritance-enabled CRD lister to support the new naming
scheme for workspaces.
> Fix CRD inheritance

- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/test.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceindex/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/framework/composite_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Having a function mimicing `testing.Run`, but adding parallisim has smell. At least, use a honest name and call it `RunParallel`.
> e2e: use honest func name framework.RunParallel

- pkg/etcd/etcd.go
- pkg/server/apiextensions.go
- test/e2e/api_inheritance/api_inheritance_test.go
CRD inheritance didn't support inheriting from helper.OrganizationCluster (admin) because it's not actually a Workspace
- it's only a logical cluster. Add in a hack that enables inheriting from helper.OrganizationCluster.
This PR also adds an environment variable to speed up e2e testing on Macs.
> Enable inheriting CRDs from helper.OrganizationCluster (admin)

- .github/workflows/ci.yaml
- Makefile
- split test workflow into test and test-e2e
- limit concurrency to 2 for e2e
e2e tests with this run in 5:30min, instead of 7:50min before.
> Speed-up CI

- pkg/syncer/syncer.go
When deleting a resource, the syncer errors with the following message, that's repeated multiple times as the item gets re-queued for retry:
```
E0204 18:30:52.939061   49166 syncer.go:401] Object to synchronize is expected to be Unstructured, but is <nil>
E0204 18:30:53.589096   49166 syncer.go:319] Error reconciling key {{"apps" "v1" "deployments"} %!q(*unstructured.Unstructured=&{map[apiVersion:apps/v1 kind:Deployment metadata:map[annotations:map[deployment.kubernetes.io/revision:1 kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"kcp.dev/cluster":"kcp-cluster-a"},"name":"echo-deployment","namespace":"myns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"echo-server"}},"template":{"metadata":{"lab …
```
> syncer: Fix Object to synchronize is expected to be Unstructured, but is <nil>

- Makefile
`WHAT=./foo... make ...` should replace the default path
> Makefile: fix WHAT not overriding the default package path

- go.mod
- go.sum
- pkg/syncer/specsyncer.go
- pkg/syncer/syncer.go
The syncer currently fails to update resources into downstream, when some fields are initialised by downstream controllers or admission webhooks, because it currently PUTs the whole upstream resources spec.  
One example is Service resources, for which unsetting `clusterIP` or `ipFamilies` is not allowed, and that cannot be synced downstream, once created:
```
E0204 16:41:06.117204   47047 specsyncer.go:155] Updating resource kcp--admin--myns/httpecho:
Service "httpecho" is invalid: [spec.clusterIPs[0]: Invalid value: []string(nil):
primary clusterIP can not be unset, spec.ipFamilies[0]:
Invalid value: []core.IPFamily(nil): primary ipFamily can not be unset]
E0204 16:41:06.907285   47047 syncer.go:318] Error reconciling key {{"" "v1" "services"} …
```
> syncer: Use Server-Side Apply to sync resources into downstream

- cmd/cluster-controller/main.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/cluster/startup.go
- pkg/server/controllers.go
Informers and lister have to be created before shared informer factory start. This PR splits New() from Start().
> reconciler/cluster: fix startup races

- .github/workflows/ci.yaml
- Makefile
- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/framework/accessory.go
- test/e2e/framework/expect.go
- test/e2e/framework/kcp.go
- test/e2e/framework/t.go
- test/e2e/framework/test.go
- test/e2e/framework/testhelper.go
- test/e2e/framework/testhelper_test.go
- test/e2e/framework/users.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceindex/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/framework/composite_test.go
- test/e2e/virtual/framework/compositecmd/cmd.go
- test/e2e/virtual/framework/compositecmd/rest.go
- test/e2e/virtual/helpers/helpers.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Requiring build tags for e2e tests complicates invoking tests via editor shortcuts. The same result of limiting the `make test` target to non-e2e files can be accomplished by path exclusion.
> Remove e2e build tags

- .github/workflows/kcp-image.yaml
- Dockerfile
Build a kcp image from main and publish it to ghcr if the CI workflow succeeds.
> Build and publish kcp image

- test/e2e/framework/fixture.go
- test/e2e/reconciler/cluster/controller_test.go
The current `RunParallel` implementation prevents the use of `t.Fatal` (and any library that depends on its use). It also couples test invocation to fixture use such that each test must use newly-instantiated fixture.
This PR proposes a simplified fixture that supports vanilla `*t.Testing` so that `t.Fatal` is permitted. This fixture allows tests to choose whether to instantiate fixture per-test (as per `RunParallel`) or to instantiate fixture once and reuse it across
multiple tests.
This PR also serves as a stepping-stone to enabling more expansive fixture reuse (e.g. across packages), up to and including unmanaged fixture (i.e. targeting a previously-deployed set of kcp servers).
The cluster controller e2e testing has been targeted for initial conversion to the new fixture.
> e2e: Add kcp server fixture that allows t.Fatal

- .github/workflows/kcp-image.yaml
The workflow_run trigger doesn't populate context objects with expected
info about the commit. Since the CI workflow runs on PRs as well as
pushes to main, I'm removing the build/publish dependency on it and
packaging on all pushes to main.
> KCP build and publish image workflow fixes

- test/e2e/conformance/cross_logical_cluster_list_test.go
This test was missed in the previous PR that removed the build tags.
> Remove e2e build tag from conformance test

- cmd/syncer/main.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/cluster/controller.go
- pkg/reconciler/deployment/controller.go
- pkg/reconciler/namespace/controller.go
- pkg/reconciler/workspace/controller.go
- pkg/reconciler/workspaceindex/controller.go
- pkg/reconciler/workspaceshard/controller.go
- pkg/syncer/specsyncer.go
- pkg/syncer/statussyncer.go
- pkg/syncer/syncer.go
- test/e2e/framework/accessory.go
- test/e2e/framework/kcp.go
- test/e2e/framework/t.go
Switch to creating a cancelable context from the outside (i.e. not in
the Syncer) and letting the caller manage the cancel functions.
Make the controller code more idiomatic.
Fixes #455
> Improve syncer stopping

- cmd/cluster-controller/main.go
- config/bootstrap.go
- pkg/server/controllers.go
- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/workspaceindex/controller_test.go
Lower-case plural type names are resources, not kinds.
> Fix Group{Kind -> Resource} everywhere in CRD bootstrapping

- pkg/server/server.go
Because pkg/server/options.Options#Complete ensures
o.EmbeddedEtcd.Directory is absolute, remove the extra join (that was
previously required prior to refactoring).
Fixes #481
> Fix embedded etcd data dir location

- cmd/cluster-controller/main.go
- cmd/shard-proxy/main.go
Both commands expect `Parse` to return an error, which is consistent with `ContinueOnError`. `ExitOnError` would result in `Parse` calling os.Exit(2) rather than returning an error.
> Fix flag error handling mode for cluster-controller and shard-proxy

- pkg/reconciler/cluster/cluster.go
- pkg/reconciler/namespace/controller.go
- pkg/reconciler/namespace/namespace.go
- test/e2e/reconciler/namespace/controller_test.go
- Add simple cluster health check
- Don't schedule to unready clusters
- Reevaluate unscheduled namespaces for ready clusters
> Add simple cluster health check

- test/e2e/framework/fixture.go
#454 blithely ignored goroutine `t.Fatal` semantics, ensuring that any failure of a kcp server to start would stall the test run rather than failing fast. This PR ensures timely failure.
> Ensure new fixture fails properly if kcp servers do not become ready

- pkg/reconciler/namespace/namespace.go
Fix for:
```
I0215 09:29:49.082852   35998 namespace.go:146] Patching namespace "admin"|"default" status to indicate schedulable=%!s(bool=true)
```
> namespace: fix placeholder in log message

- test/e2e/authorizer/authorizer_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Previously, the new sharable fixture was running artifact-collecting functions registered at setup but not those registered during test execution. When executed in parallel, a sub-test's modification of a shared fixture's set of artifact functions wasn't propagating to the parent test.
This change switches to registering artifact functions with t.Cleanup() to ensure that artifact collection is tied to the scope of
the registering test rather than the scope of the fixture lifetime. It also ensures that artifacts for subtests using shared fixture are saved in a path specific to the subtest.
> e2e: Ensure artifacts are saved at test completion for shared fixture

- .github/workflows/ci.yaml
- Makefile
Previously, `make test-e2e` would execute each test 5 times which could be a surprising result for some. Developers would commonly have to set `COUNT=1` if they wanted quick feedback on changes they were making locally. This commit defaults `make test-e2e` to executing a single run, with multiple runs configurable by setting `COUNT=`.
In keeping with this change, the `e2e-single-run` ci job is renamed to `e2e` and no longer sets an explicit `COUNT=` to ensure it uses the default behavior of `make test-e2e`. The previous `e2e` suite - executing 5 runs - is accordingly renamed `e2e-multiple-runs`.
> Default `make test-e2e` to a single run

- test/e2e/framework/util.go
- test/e2e/reconciler/workspace/controller_test.go
This PR refactors `Artifact()` to fail rather than log if any error is encountered during artifact collection. A fix is included for a latent bug in one of the workspace e2e tests surfaced by the refactor.
> e2e: Refactor Artifact to ensure tests fail when collection fails

- Makefile
- hack/update-codegen.sh
We will need yaml-patch soonish to be able to set OpenAPI values like `{}` defaults on spec, or `metadata.name` restrictions. controller-tools unfortunately does not support all of CRD schemas.
> hack/tools: add yaml-patch

- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/admission/plugins.go
- pkg/admission/plugins_test.go
- pkg/server/options/options.go
- pkg/server/server.go
- wire a sensible subset of kube-apiserver's admission
- add kcp informer admission initializer
- add drift unit test to notice when upstream adds or removes admission plugins
> server: add kcp admission plumbing

- pkg/authorization/bootstrap_policy_authorizer.go
- pkg/server/options/authorization.go
The org workspace won't be the one providing a kube bootstrap policy.
> authorization: rename org to bootstrap authorizer

- contrib/demo/README.md
Awesome project, just a small one to help others running `kcp` themselves. This PR adds a README.md in the demo folder as an index to the existing demos. Might be obsolete with #373, but fixes #410 for now. I hope I got all the demos right.
> docs: add README.md in demo folder

- pkg/server/options/authentication.go
- pkg/server/server.go
We had our own logic to derive an external name from binding host+port somehow. As the cert is created with the external address data, diverging asks for trouble. This PR uses the same `DefaultExternalAdddress()" us in upstream for the cert.
> server: align with upstream logic to derive external address

- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
These are far to noisy for debugging sessions.
> e2e/framework: don't monitor {ready,live}z when in-process

- pkg/syncer/syncer.go
Otherwise, kcp namespaces would be excluded that happen to be called as the pcluster syncer namespace.
> syncer: only exclude syncer namespace in pcluster->kcp direction

- pkg/localenvoy/controllers/ingress/envoyingress.go
- pkg/localenvoy/controllers/ingress/envoyingresscontroller.go
- pkg/localenvoy/controlplane/controlplane.go
That PR fixes the label used to select Ingresses ready to be exposed via Envoy, from `ingress-controller/envoy` to `ingress.kcp.dev/envoy`.
I faced this issue while working on #550, after a rebase on #478.
/cc @jmprusi
> Fix the label used to select Ingresses for Envoy

- pkg/reconciler/ingresssplitter/controller.go
```
E0224 21:43:58.528568   24959 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x1b6c820), concrete:(*runtime._type)(0x1bca300), asserted:(*runtime._type)(0x1ad9ee0), missingMethod:""} (interface conversion: interface {} is sets.Empty, not string)
```
> ingresssplitter: fix panic

- pkg/reconciler/namespace/conditions.go
- pkg/reconciler/namespace/namespace.go
- test/e2e/reconciler/namespace/controller_test.go
Currently the namespace controller owns the responsibility of assigning namespaces to physical clusters. The only option for other controllers, like the `deployment-splitter` one, or users manually, to distribute resources across physical clusters is to deactivate the namespace controller by starting KCP with `--run-controllers=false --unsupported-run-individual-controllers="workspace-scheduler,cluster"`.
Meanwhile more advanced scheduling / placement scenarios are supported, this PR proposes to introduce the `experimental.scheduling.kcp.dev/disabled` label, that can be added to namespaces, in order to deactivate the automatic placement to physical clusters, performed by the namespace controller.
Setting this label to `false` prevents the namespace controller from overriding the …
> Add a label to deactivate automatic namespace scheduling

- test/e2e/virtual/workspaces/virtual_workspace_test.go
Use of `filepath.Base` instead of `filepath.Dir` meant the config was being written to the e2e path instead of a temp dir.
> e2e: Ensure cfg is written to temp dir for virtual workspace test

- pkg/reconciler/namespace/namespace.go
- pkg/reconciler/namespace/namespace_test.go
This refactor separates the decision of how to respond to a cluster event in the namespace scheduler from how that decision is implemented. This allows for unit testing of the decision-making.
This PR also ensures that when enqueueing scheduled namespaces, only namespaces scheduled to the specific cluster will be enqueued.
> Refactor namespace scheduler queueing behavior for testability

- .github/workflows/ci.yaml
- .github/workflows/demos.yaml
- .github/workflows/kcp-image.yaml
- .github/workflows/syncer-image.yaml
- Exclude docs and markdowns
- Reformat workflow files
- Fixes #573
> ci: don't run e2e & other tests for documentation-only PRs

- cmd/shard-proxy/main.go
- pkg/reconciler/apiresource/controller.go
- pkg/reconciler/namespace/controller.go
- pkg/reconciler/workspace/controller.go
- pkg/reconciler/workspaceindex/controller.go
- pkg/reconciler/workspaceshard/controller.go
@ncdc something like this? As far as I can tell, all callers were are already waiting for cache syncs using a `PostStartHook`. Except for `shard-proxy`, there I added  a `WaitForCacheSync`. Closes #574.
> refactor: remove syncChecks in controllers

- pkg/reconciler/namespace/namespace.go
- pkg/reconciler/namespace/scheduler.go
- pkg/reconciler/namespace/scheduler_test.go
This PR extracts cluster selection from the namespace scheduling  controller and adds preliminary unit test coverage of the result.
API interaction is limited to functions that can be replaced in tests. Care was taken to ensure functional behavior which is easier to reason about and validate. Testing of API mutation is out-of-scope since the fixture cost would likely exceed the benefit.
This strategy of factoring out logic that can be unit tested enables trivial validation of corner-cases and is intended to reduce the cost of ongoing maintenance.
> Refactor namespace scheduler cluster assignment for testability

- pkg/admission/clusterworkspace/admission.go
- pkg/admission/clusterworkspace/admission_test.go
- pkg/admission/clusterworkspacetypeexists/admission.go
- pkg/admission/clusterworkspacetypeexists/admission_test.go
- pkg/admission/plugins.go
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/reconciler/workspace/controller.go
- pkg/reconciler/workspaceindex/controller.go
- pkg/virtual/workspaces/registry/kubeconfig_rest.go
- pkg/virtual/workspaces/registry/kubeconfig_rest_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
This PR does the following:
1. To simplify the state machine as seen by users and controllers, this PR adds the invariant that
- After scheduling `status.baseURL` of a ClusterWorkspace stays valid.
In other words: there is no unscheduling. A workspace has state (obviously) and a workspace without a shard does not make sense.
Corrolary: We have to make sure (through movement and high availability measures) that a workspace is available. Clients should not be expected to hande the case that a workspace is not accessible. Reason:
- client-go clients don't watch the workspace object.
- processes talk to some URL via clients, and clients cannot update the URL they talk to (that's not part of the Kubernetes client contract).
tl/dr: we have to make sure the workspace baseURL keeps working at all …
> Add workspace invariant of valid baseURL

- config/organization/clusterworkspacetype-use-clusterrole.yaml
- config/organization/clusterworkspacetype-use-clusterrolebinding.yaml
- pkg/admission/clusterworkspacetypeexists/admission.go
- pkg/admission/clusterworkspacetypeexists/admission_test.go
- pkg/admission/helpers/authorize.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/server/server.go
Authorize ClusterWorkspace creation against a clusterworkspacetypes verb=use permission via SubjectAccessReview.
By default everybody (with org access) can create universal ClusterWorkspaces. This is done through a bootstrapped ClusterRole+Binding in every org workspace. If this is not desired, that binding could be removed on a per-org basis.
> admission: add SubjectAccessReview to ClusterWorkspaceType use

- test/e2e/workspacetype/controller_test.go
I noticed that the workspacetype initializer test was taking ~50s - quadruple the runtime of any other test. Investigation revealed that the test was broken in 3 ways:
- incorrect deletion of an element from a slice
- using Update instead of UpdateStatus to effect a status change
- not checking the result of a subsequent expect meant the first 2 issues were not failing the test
The extended duration of test execution was the result of the expect taking 30s before timing out, 2x5s sleeps, and the usual 10s overhead of starting a kcp server fixture.
> e2e: Fix broken workspacetype initializer test

- pkg/admission/clusterworkspace/admission.go
- pkg/admission/clusterworkspace/admission_test.go
Fix bug where it was possible to transition out of Initializing with status.initializers remaining.
Fix bug in test case for this that was incorrectly passing.
> clusterworkspace: admission: fix initializers check

- pkg/apis/tenancy/v1alpha1/helper/helper.go
- pkg/authorization/bootstrap/policy.go
- pkg/authorization/workspace_content_authorizer.go
- pkg/reconciler/clusterworkspacetypebootstrap/bootstrap_reconcile.go
- pkg/server/apiextensions.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/authorizer/resources.yaml
- test/e2e/framework/fixture.go
- test/e2e/reconciler/workspace/controller_test.go
This Pull Request has been opened as a supplementary part of https://github.com/kcp-dev/kcp/issues/606.
When creating clusterroles, kubectl requires a valid resource, hence the change from `workspaces` to `clusterworkspaces` with `content` subresource.
Fixes #606
> Rename workspaces to clusterworkspaces

- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
- test/e2e/workspacetype/controller_test.go
Stop requiring tests to supply the correct context (e.g. `Config("system:admin")`) to retrieve server configuration. Switch to using DefaultConfig() which hides that detail.
> e2e: Switch to DefaultConfig() function from Config("system:admin") 

- test/e2e/api_inheritance/api_inheritance_test.go
Not sure how #650 merged without the lint check failing :/
> e2e: Remove unused constant to satisfy linter

- Makefile
This enables the use of `-args [custom args]` and `-- [custom args]`, which have to appear after the package list.
> Move `TEST_ARGS` for `make test-e2e` to after the package list

- .github/workflows/ci.yaml
- Makefile
golanci-lint action job uses a custom format to annotate code within
GitHub, we can override it (forcefully) to achieve the desired output
(file and line numbers for lint issue in the output). Or we can just use
the make target directly :)
https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648
fixes https://github.com/kcp-dev/kcp/issues/634
Signed-off-by: jbpratt <jbpratt78@gmail.com>
> ci: use lint make target

- cmd/cluster-controller/main.go
- cmd/virtual-workspaces/main.go
Consistent Signal handling methods
*  changed signal.NotifyContext() and genericapiserver.SetupSignalHandler() to genericapiserver.SetupSignalContext()
> make signal handling consistent

- pkg/cliplugins/workspace/cmd/cmd.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
`kubectl kcp workspaces` now operates on the following org:
- when in the root, the org is the root
- when in an org, the org is the same org
- when in a non-org, the org is the parent.
Also adding a `workspaces` alias to the subcommand, and removing the confusion `'all'` scope output from current workspace. The latter needs another design session probably, but removing at least removes the confusion for now.
Closes #630.
> kubectl-kcp: fix logic to derive the orgClusterName

- pkg/cliplugins/workspace/cmd/cmd.go
- pkg/cliplugins/workspace/plugin/helpers.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/cliplugins/workspace/plugin/options.go
- pkg/virtual/workspaces/builder/build.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- Cleanup the CLI `workspaces` plugin to:
- remove completely the `workspace-directory` overrides
- use the same hostname and port as the current context by default (an alternate port can still be specified through a CLI if necessary, especially if this PR is merged before #640 )  
- have the scope be specified as a CLI arg
- Fixed an error when getting the `current` workspace on a non-org workspace
- Added (quick and dirty fix) the support of the `exec` user authentication method on the client-side.
> Better scope management and CLI plugin cleanup

- .github/workflows/ci.yaml
- pkg/etcd/etcd.go
- test/e2e/framework/kcp.go
A single and embedded etcd instance should not need to fsync, this will improve the performance for CI and avoid issues with slow disks
> disable etcd fsync on github actions tests, fail fast if kcp binary not found and increase kcp verbosity

- contrib/demo/prototype2-script/startKcp.sh
Changes `--virtual-workspaces-address` to `--virtual-workspace-address` to fix KCP startup command.
> prototype2-script: Fix virtual-workspace-address option to start KCP

- .github/workflows/kcp-image.yaml
- manifest/kcp.yaml
- Add new flags to kcp and virtual-workspace containers
- Pull external hostname into github actions variable
- Use variable to set external hostname via kustomize
- Update transformation command for virtual workspace kubeconfig
Co-authored-by: Chris Sams <csams@redhat.com>
> Update deployment manifest

- .github/workflows/kcp-image.yaml
Fixes error:
The identifier 'vars' may not be used more than once within the same scope.
> Rename Github Actions step to avoid conflict

- contrib/demo/clusters/kind/createKindClusters.sh
- contrib/demo/prototype2-script/script
- contrib/demo/prototype2-script/startKcp.sh
- contrib/demo/runDemoScripts.sh
- contrib/envoy/bootstrap.template.yaml
- contrib/envoy/bootstrap.yaml
This PR moves the Envoy proxy, used in the Ingress part of the P2 demo, to be running in container, so that it can connect to the network created by KinD, to be able to proxy downstream clusters, even while it runs in the extra virtualisation layer introduced by Docker or Podman on MacOS.
Fixes #550.
> prototype2-script: the Ingress demo can run on MacOS

- config/helpers/bootstrap.go
- test/e2e/framework/kcp.go
it never is ready
```
=== CONT  TestWorkspaceShardController/create_a_workspace_shard_referencing_credentials_without_data,_expect_to_see_status_reflect_invalid_credentials
util.go:84: Saving test artifacts for test "TestWorkspaceShardController/create_a_workspace_shard_referencing_credentials_without_data,_expect_to_see_status_reflect_invalid_credentials" under "/home/aojea/go/src/github.com/kcp-dev/kcp/_output/TestWorkspaceShardController/create_a_workspace_shard_referencing_credentials_without_data,_expect_to_see_status_reflect_invalid_credentials/346689547".
fixture.go:98: Starting kcp servers...
kcp.go:168: running: /home/aojea/go/src/github.com/kcp-dev/kcp/bin/kcp start --root-directory /home/aojea/go/src/github.com/kcp-dev/kcp/_output/TestWorkspaceShardController/create_a_workspace_ …
```
> Fix resource bootstrapping flake

- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
- test/e2e/workspacetype/controller_test.go
vs having to check the return value everywhere
> e2e: Pass `t` to DefaultConfig() to allow failing on error

- .github/workflows/kcp-image.yaml
The action step that discovers the deployment's external hostname was missing some kubectl options.
> Add CICD options to kubectl for external hostname discovery

- cmd/syncer/cmd/syncer.go
- cmd/syncer/main.go
- cmd/syncer/options/options.go
* added cobra command equivalent of existing go flags.
* moved the main logic from ./cmd/syncer/main.go to ./cmd/syncer/cmd/syncer.go
* created a new exported ```Options struct``` for flags binding.
* syncedResourceTypes is a flag now
* Build the source code
```bash
go build ./cmd/syncer
```
* Run it
```bash
./syncer -h
```
> Convert cmd/syncer/main.go to be a cobra.Command

- cmd/cluster-controller/main.go
- pkg/reconciler/apiresource/startup.go
- pkg/reconciler/cluster/apiimporter/apiimporter_controller_start.go
- pkg/reconciler/cluster/syncer/pullmanager.go
- pkg/reconciler/cluster/syncer/pushmanager.go
- pkg/reconciler/cluster/syncer/syncer_controller.go
- pkg/reconciler/cluster/syncer/syncer_controller_start.go
- pkg/reconciler/cluster/syncer/syncer_manager.go
- pkg/reconciler/namespace/controller.go
- pkg/server/controllers.go
- pkg/server/kubeconfig.go
- pkg/server/server.go
Non-functional change, just getting rid of the in-process loopback kubeconfig with multiple contexts.
> reconcilers: get rid of clientcmdapi.Config and pass rest.Config

- pkg/server/controllers.go
- pkg/server/server.go
- test/e2e/authorizer/rootcacertconfigmap_test.go
In order to get the ServiceAccounts working we will need to handle the `kube-root-ca.crt` configmap that contains the k8s CA certificate.
This PR wires the kube `rootCACert` controller into KCP.
Todo
~~- [ ] Bump the Kubernetes version (https://github.com/kcp-dev/kcp/pull/671)~~
> Enable the RootCACertPublisher

- pkg/cliplugins/workspace/plugin/helpers.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
Currently when running e.g. `kubectl kcp workspaces use my-workspace`, the context created in the user's kubeconfig will point to a new user that was cloned from the previously-active context.  This can fill a user's kubeconfig with lots of duplicate users if there are lots of workspace switches.  It also allows the authInfo to drift from the original context and the workspace-specific context, whereas they very likely need to be in sync.
This change will make the new context point to the already-existing authInfo instead of making a copy of it.
Co-authored-by: Chris Sams <csams@redhat.com>
> kubectl-kcp: point to authInfo config instead of clone

- cmd/kcp-front-proxy/main.go
- hack/admin-ext.cnf
- hack/client-ext.cnf
- hack/gen-certs.sh
- hack/server-ext.cnf
- pkg/proxy/doc.go
- pkg/proxy/proxy.go
- pkg/proxy/server.go
kcp-front-proxy is a reverse proxy that accepts client certificates and forwards Common Name and Organizations to backend API servers in HTTP headers. The proxy terminates TLS and communicates with KCP and virtual workspace servers via mTLS. Traffic is routed based on paths.
The intent is to deploy the proxy in the same pod as KCP and virtual workspace server pairs.
> Proxy to terminate TLS and handle client cert auth

- test/e2e/reconciler/cluster/controller_test.go
Return false instead of return err, as we want to retry until the object has the appropriate values.
> Fix TestClusterController tests

- config/organization/clusterworkspacetype-universal.yaml
- pkg/apis/tenancy/v1alpha1/helper/helper.go
- pkg/apis/tenancy/v1alpha1/helper/helper_test.go
- pkg/reconciler/namespace/controller.go
- pkg/reconciler/namespace/namespace.go
- pkg/reconciler/namespace/namespace_test.go
- pkg/reconciler/namespace/scheduler_test.go
- pkg/server/controllers.go
Not all use of kcp will involve namespace scheduling or synchronization with a workload cluster.
One such use case involves using a logical cluster (workspace) as a workload cluster for the purposes of syncer testing. Were namespace scheduling to remain enabled for such a workspace, the cluster label of namespaces created by the syncer in that workspace would be removed (due to the cluster not existing in the workspace). Since the syncer's downstream informer filters on the presence of the label in question, the syncer would not be able to see any resources for which the namespace scheduler had removed the label. Disabling the namespace scheduler for the workspace ensures the contents of the workspace more precisely reflect how a kubernetes cluster would behave.
Unlike disabling …
> Make namespace scheduling opt-in via label on containing workspace

- pkg/syncer/syncer.go
This PR adds to the default Sync list of the syncer, the GVRs of:
* Configmap
* ServiceAccounts
* Secrets
This means, that even if not specified via API imports, or "resources-to-sync" args, the syncer will sync those resources to the workloadclusters.
Pushing the discussion on how to improve the default syncing into Prototype4: https://github.com/kcp-dev/kcp/issues/727
This is related to: https://github.com/kcp-dev/kcp/issues/280
> Adds serviceaccounts,secrets and configmaps GVRs to the default Syncer sync list

- pkg/reconciler/workspace/controller.go
- test/e2e/reconciler/workspaceshard/controller_test.go
Also fixed a bug in the workspace shard controller that was uncovered in the process of updating the tests.
> e2e: Update workspace shard tests to use shared fixture

- cmd/kcp/kcp.go
- Fixed `help` and `options` commands
- Changed 
```go
setPartialUsageAndHelpFunc(cmd, namedStartFlagSets, cols, []string{
"etcd-servers",
"run-controllers",
"run-virtual-workspaces",
})
```
to
```go
setPartialUsageAndHelpFunc(startCmd, namedStartFlagSets, cols, []string{
"etcd-servers",
"run-controllers",
"run-virtual-workspaces",
})
```
- Run
```bash 
kcp --help
```
- Run
```bash
kcp start --help
```
- Run
```bash
kcp options
```
Fixes #602
> fix unknown command options for kcp

- config/crds/bootstrap.go
- config/crds/bootstrap_test.go
wait.Poll functions return ErrWaitTimeout instead the context cancellation error, for backward compatibility reasons, see:
https://github.com/kubernetes/kubernetes/blob/b5f8cca701575678819b5e9e6372df989ab6799f/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go
however, retryOnError swallows that error and replaces it for the last one, that is nil if it is still retrying, see:
https://github.com/kubernetes/kubernetes/blob/ee81e5ebfad1b3f3c1112e7b83b0a5113286a3d3/pkg/client/unversioned/util.go
if the context is cancelled, we have to inform the upper layers about that, so context error takes precedence.
> return error on context cancellation

- pkg/syncer/specsyncer.go
This PR strips finalizers before syncing downstream, to prevent deletion of downstream resources from being blocked. It also strips owner references, to avoid broken references and orphaning, and to make sure cascading deletion happens only once upstream.
> Strip finalizers and owner references before syncing downstream

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/apibinding_admission_test.go
- pkg/admission/clusterworkspacetypeexists/admission.go
- pkg/admission/clusterworkspacetypeexists/admission_test.go
- pkg/authorization/delegated/authorizer.go
- pkg/virtual/workspaces/builder/build.go
- pkg/virtual/workspaces/options/options.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Fixes https://github.com/kcp-dev/kcp/issues/716
We had that in ClusterWorkspaceTypeExists admission. But because the virtual-workspace apiserver creates as admin, that did not apply. Also impersonation would not work because users cannot create ClusterWorkspaces in the org workspace.
> virtual: authorize clusterworkspacetype use

- pkg/syncer/specsyncer.go
- pkg/syncer/statussyncer.go
- pkg/syncer/syncer.go
- pkg/syncer/syncer_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
Switch to test-managed syncer to enable syncer-requiring tests to use shared fixture.
> e2e: Switch to test-managed syncer and update syncer-dependent tests to use shared fixture

- pkg/authorization/bootstrap/policy.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/authorizer/resources.yaml
This Pull Request removed both `view` and `edit` verbs from the cluster workspace authorizer. Additionally, it maps the admin to cluster admin.
Fixes #725
Still to be done:
> Remove view and edit verbs from clusterworkspace authz

- test/e2e/api_inheritance/api_inheritance_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/fixtures/wildwest/bootstrap.go
- test/e2e/framework/accessory.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/util.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
- test/e2e/workspacetype/controller_test.go
No need to use deadline contexts, just ensure that contexts for goroutines and blocking functions have their cancel functions registered with `t.Cleanup()`.
> e2e: Cleanup context use

- pkg/cliplugins/workspace/plugin/helpers.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/virtual/workspaces/authorization/cache.go
- pkg/virtual/workspaces/authorization/cache_test.go
- pkg/virtual/workspaces/authorization/watch.go
- pkg/virtual/workspaces/authorization/watch_test.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- pkg/virtual/workspaces/util/util.go
- **Always** derive the current workspace name and org from the server URL of the current `kubeconfig` context (instead of reading it from the current workspace kubeconfig context key). This fixes issue #678
- Store **only one** `kubeconfig` context to store the current workspace context, and one for the previous workspace (instead of the whole history of current contexts)
- Correctly manage pretty names, so that they are shown **as an alias** in the `use` or `current` commands as shown below:
```
$ kubectl kcp workspace --token=another-token create my-workspace
Workspace "my-workspace" created.
$ kubectl kcp workspace --token=user-1-token create my-workspace 
Workspace "my-workspace" created.
$ kubectl kcp workspace --token=user-1-token current
Current workspace is "my-workspace" (an …
```
> Simplify `kubectl kcp workspace` plugin usage and implementation

- config/crds/bootstrap.go
Add support for multiple goroutines (e.g. post start hooks) that try to
install the same CRD at the same time. There was a race where one
goroutine checked for the CRD's existence, didn't find it, and proceeded
to create it. Meanwhile, another goroutine created it. Before this
change, the first goroutine would return an error ("already exists").
Now, it recognizes the existence and tries to do an update instead of
returning an error.
Fixes #
> crd bootstrap: better goroutine support

- cmd/kcp-front-proxy/filters.go
- cmd/kcp-front-proxy/main.go
- cmd/kcp-front-proxy/options/authentication.go
- cmd/kcp-front-proxy/options/options.go
- pkg/proxy/proxy.go
This PR wires up kube machinery for client cert auth in the front proxy.
> kube client cert auth in the proxy

- Makefile
- test/e2e/framework/accessory.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/ingress/controller_test.go
How many times did I miss that I have to `go install` instead of `make build` to run an e2e test via `go test`. This is probably the reason for half of the times where we I added `RunInProcess: true` to the fixture because without the test behaves differently in Goland than via `make test-e2e`. This PR unifies that by basing both on `<repo-dir>/bin`.
> e2e: unify make-build bin/ dir and e2e search path for binaries

- pkg/authorization/workspace_content_authorizer.go
Follow-up of https://github.com/kcp-dev/kcp/pull/726.
- removed duality between v1beta1 `Workspaces` in some virtual workspace path and the `ClusterWorkspaces` in an org. Now you can do `kubectl get workspaces` in an org
- simplified and complete kubectl plugin to implement the second section in https://docs.google.com/document/d/1XJJCr16bg22QuJnQB2W98A-djRTtrLr2JE2IWZUHzJU/edit#heading=h.nn8danthd1ys.
> authorization: finish removing edit+view from workspace content authz

- pkg/authorization/workspace_content_authorizer.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
There is more in https://github.com/kcp-dev/kcp/pull/780 for the virtual workspace side.
> 1. authorization: don't leak authz information in authz errors

- pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
ingress-controller used generated-name, i.e. without any guarantee that there is only one leaf per workload cluster. Moreover, the controller didn't delete the leaves that are too many. Finally, the e2e test waits for exactly one 🤷‍♂️ 
This PR switches to `<root-name>-<cluster-name>`.
Also: revert 034f5c4f0 which was wrong. The list is a string list.
> 0. ingress-controller: fix race leading to too many leaves when informers are stale

- pkg/authorization/workspace_content_authorizer.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/framework/users.go
This is preprartion for the virtual workspace apiserver to do proper authorization, and also for users to access the root and see their org.
> authorization: give everybody authenticated root org access

- .github/workflows/ci.yaml
The job runs tests twice to ensure tests don't interfere with one another when using shared fixture.
> e2e: Add new shared server ci job

- pkg/server/handler.go
- pkg/server/server.go
```
$ kubectl kcp workspace create foo <- old kubectl plugin
W0329 10:22:54.753682   33759 warnings.go:70] the /clusters/<org>:<cluster> URL pattern is deprecated. Update your kubeconfig and use /clusters/root:<org>:<cluster> instead.
Workspace "foo" (type "Universal") created.
```
> server: send warning header to client on /clusters/<org>:<workspace> access

- Makefile
- pkg/cliplugins/workspace/plugin/kubeconfig.go
Fixing https://github.com/kcp-dev/kcp/issues/645.
Plugin user agent: `kubectl-kcp/v0.2.3 (darwin/arm64) kubernetes/96ce0be`
Server version:
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v0.2.3-1-g96ce0beb59c389+kcp", GitCommit:"96ce0beb", 
GitTreeState:"clean", BuildDate:"2022-03-29T16:58:29Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"darwin/arm64"}
```
See how major and minor version are the kube ones, but the GitVersion has the `kcp` term inside. This is the same way that k3s and OpenShift servers version themselves.
> kubectl-kcp+server: set user-agent and version information

- manifest/kcp.yaml
Currently the admin token and the sa.key are getting regenerated every time the kcp pod restarts. We need to start persisting this, especially because folks are starting to use service account tokens.
This also includes a commit to change the update strategy to recreate (this helps with the PVC getting stuck upon rollout).
> Update manifest to persist KCP configs between restarts

- test/e2e/apibinding/apibinding_test.go
> e2e: cleanup misleading log output from apibinding test

- Makefile
- test/e2e/framework/kcp.go
Follow-up to #753 that hopefully addresses the cleanup problem.
> e2e: run via go-run by default, NO_GORUN=1 for opt-out from Makefile

- .github/workflows/ci.yaml
This validates that the e2e tests can run repeatedly without error
against a shared server. Important for local development and testing.
> e2e: Update shared-server job to run twice

- .github/workflows/ci.yaml
- cmd/test-server/main.go
- test/e2e/framework/config.go
- test/e2e/framework/fixture.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Rather than requiring developers to supply the qualified path to
.kcp/admin.kubeconfig to run against shared fixture, rely on the fact
that the repository root is discoverable to allow --use-default-server
to supply the same configuration.
> e2e: Add --use-default-server to simplify use of persistent fixture

- .github/workflows/ci.yaml
- test/e2e/framework/accessory.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/ingress/controller_test.go
This ensures that a test run will always be using the latest source of
the tree vs whatever binaries are in the path.
> e2e: Update ingress testing to use go run by default

- .github/workflows/ci.yaml
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/framework/test.go
- test/e2e/reconciler/workspace/controller_test.go
- test/e2e/reconciler/workspaceshard/controller_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
These tests operate against global state which precludes successive
invocations against shared fixture without error.
Fixes #802
> e2e: Update cross logical cluster testing to use private fixture

- pkg/server/options/authentication.go
Hard coding push-mode syncer to use localhost so it works for local development and behind a service where the public facing hostname, port, and cert may not be those configured for kcp itself.
> push-mode syncer uses localhost for KCP

- cmd/kubectl-workspaces/main.go
- cmd/kubectl-ws/main.go
- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
- config/crds/tenancy.kcp.dev_workspaces.yaml
- config/system-crds/bootstrap.go
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/apis/tenancy/v1beta1/types.go
- pkg/cliplugins/workspace/cmd/cmd.go
- pkg/cliplugins/workspace/plugin/helpers.go
- pkg/cliplugins/workspace/plugin/helpers_test.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/cliplugins/workspace/plugin/kubeconfig_test.go
- pkg/cliplugins/workspace/plugin/options.go
- pkg/server/apiextensions.go
- pkg/server/handler.go
- pkg/server/server.go
- pkg/virtual/workspaces/printers/printer.go
Implementing UX from https://docs.google.com/document/d/1XJJCr16bg22QuJnQB2W98A-djRTtrLr2JE2IWZUHzJU/edit#heading=h.nn8danthd1ys.
- simplified and complete kubectl plugin to implement the second section in https://docs.google.com/document/d/1XJJCr16bg22QuJnQB2W98A-djRTtrLr2JE2IWZUHzJU/edit#heading=h.nn8danthd1ys.
- removed duality between v1beta1 `Workspaces` in some virtual workspace path and the `ClusterWorkspaces` in an org. Now you can do `kubectl get workspaces` in an org
Based on https://github.com/kcp-dev/kcp/pull/744.
> 5. kubectl-kcp: get rid of workspace duality and implement logical cluster path semantics

- contrib/demo/prototype3-script/deployment-kuard.yaml
- contrib/demo/prototype3-script/script-cordon-evict.sh
Adds demo script to show workload cluster cordoning (`unschedulable: true`) and immediate eviction (`evictAfter: $date-in-the-past`).
#415
> Add demo script for cordon and evict behavior

- manifest/kcp.yaml
If port is not present in external hostname, the --secure-port value is
used instead.
> manifest: Add explicit port number to external hostname

- .github/workflows/ci-docs-only.yaml
- .github/workflows/ci.yaml
- .github/workflows/kcp-image.yaml
- .github/workflows/syncer-image.yaml
Start using Github Action Environments so the `CICD_KUBE_*` environment
variables can be set depending on which deployment environment (i.e.
stable/unstable) is targeted.
> Enable CI/CD for release branches

- pkg/cliplugins/workspace/plugin/kubeconfig.go
It got lost in some recent PR, leading to ugly warnings on the console of the client.
@csams worth to pick into the release branch?
> kubectl-kcp: fix user-agent regression

- .github/workflows/ci-docs-only.yaml
- .github/workflows/ci.yaml
- .github/workflows/kcp-image.yaml
- .github/workflows/syncer-image.yaml
- manifest/kcp.yaml
If port is not present in external hostname, the --secure-port value is
used instead.
> [0.3] manifest: Add explicit port number to external hostname

- cmd/cluster-controller/main.go
- pkg/reconciler/workload/syncer/pushmanager.go
- pkg/reconciler/workload/syncer/syncer_controller_start.go
- pkg/server/controllers.go
- pkg/server/server.go
- pkg/syncer/mutators/deployment.go
- pkg/syncer/mutators/deployment_test.go
- pkg/syncer/specsyncer.go
- pkg/syncer/statussyncer.go
- pkg/syncer/syncer.go
The push mode syncer configures itself to talk to kcp over localhost,
and the deployment mutator was using that same localhost configuration
to set env vars allowing a deployment to talk back to kcp. If the
cluster that a deployment was synced to was on a different host,
though, that deployment wouldn't be able to talk to kcp as intended.
This change ensures the push mode syncer is explicitly provided the
external address that synced deployments should be updated with rather
than extracting it from the kubeconfig the syncer uses to talk to kcp.
> Ensure push mode syncer sets kube env vars correctly on deployments

- Dockerfile
This is required to properly get the version strings baked into the
binaries.
* .git dir is copied in to build image, but it doesn't end up in the
shipped image.  We can follow up later to remove the need to copy over
the whole .git dir.
* CGO_ENABLED=0 is required for alpine/distroless, so I've kept that
here.
* Had to list out the binaries to put into the shipped image.  Using `*`
resulted in an 800MB image!
Fixes #645
> dockerfile: Use make to build go binaries

- pkg/syncer/syncer.go
If the syncer can't find a namespace on the p-cluster, it returns an err which causes a hotloop. This change should cause it to ignore the missing ns, and then the syncer will recreate it.
> Ignore missing namespace on p-cluster

- Dockerfile
Upstream: https://github.com/kcp-dev/kcp/pull/850
This is required to properly get the version strings baked into the
binaries.
* .git dir is copied in to build image, but it doesn't end up in the
shipped image.  We can follow up later to remove the need to copy over
the whole .git dir.
* CGO_ENABLED=0 is required for alpine/distroless, so I've kept that
here.
* Had to list out the binaries to put into the shipped image.  Using `*`
resulted in an 800MB image!
> [0.3] dockerfile: Use make to build go binaries

- Makefile
Was using kcp version, but instead needs to use kube version followed by kcp version.
> Fix git version string returned by kcp server

- Makefile
Upstream: https://github.com/kcp-dev/kcp/pull/859
Was using kcp version, but instead needs to use kube version followed by kcp
version.
> [0.3] Fix git version string returned by kcp server

- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Uses test changes from https://github.com/kcp-dev/kcp/pull/833
The `access` verb is explicitly checked in the virtual workspace server, so just give users that verb in addition to `admin` when creating a workspace on behalf of said user.
Perhaps we could modify the authorizer to check for `admin` as well as `access`, but this one-liner at least seems like a quick fix.
> virtual: Grant 'access' verb to user upon workspace creation

- .github/workflows/add-to-project.yml
Wire up https://github.com/marketplace/actions/add-to-github-projects-beta to auto-add issues to our beta project.
> actions: add Github's beta add-to-project

- test/e2e/framework/fixture.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/cluster/syncerheartbeat_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
This PR adds a new SyncerFixture to replace StartWorkspaceSyncer. This will make adding a kind e2e simpler.
* This new SyncerFixture handles the creation of a downstream server (fakeWorkloadServer) and its registration into an upstream server, creating the ClusterWorkload object. Provides methods for starting the Syncer associated, and also, for waiting for the downstream cluster to be ready
* Adapts current e2e tests to use the NewSyncerFixture.
> e2e Syncer fixture

- pkg/reconciler/workload/syncer/pushmanager.go
- pkg/reconciler/workload/syncer/syncer_controller_start.go
- pkg/server/controllers.go
- pkg/server/server.go
- pkg/syncer/specsyncer.go
- pkg/syncer/syncer.go
#832 provided the syncer the external address of kcp with the expectation that the syncer would parse out the host and port for use in deployment mutation. The missing detail was that url.Parse returns empty string and no error if the url string it is provided doesn't have a prefix like https://. Fixing that should fix the syncer but manual testing is required because there is no e2e coverage of this code path.
> Ensure push-mode syncer is provided a parseable external url

- manifest/kcp.yaml
Until push-mode is removed, default the resources to sync (and the APIs
to import) to deployments, services, ingresses.
Fixes #
> manifest: add resources to sync

- manifest/kcp.yaml
Until push-mode is removed, default the resources to sync (and the APIs
to import) to deployments, services, ingresses.
(cherry picked from commit 2aff0ab35d2cbd08d1505054a26c1b44992e08b6)
Backport of #871
> [0.3] manifest: add resources to sync

- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/apiimporter/apiimporter_manager.go
- pkg/reconciler/workload/heartbeat/heartbeat_manager.go
- pkg/reconciler/workload/heartbeat/heartbeat_manager_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
- pkg/reconciler/workload/namespace/namespace_test.go
- pkg/reconciler/workload/namespace/scheduler.go
- pkg/reconciler/workload/namespace/scheduler_test.go
- pkg/reconciler/workload/syncer/pullmanager.go
- pkg/reconciler/workload/syncer/pushmanager.go
- pkg/reconciler/workload/syncer/syncer_manager.go
- test/e2e/framework/fixture.go
Give each controller its own condition and make heartbeat manager responsible for setting `Ready` by accounting for all conditions via `conditions.SetSummary`
Update the namespace scheduler to depend on total readiness.
Fixes #865
> Stop apiimporter, syncer, heartbeat from fighting over the Ready condition

- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
Previously the scheduler enqueued resources contained by a namespace when the namespace was reconciled for any reason. This change updates the scheduler to keep track of namespace scheduling decisions and only enqueue contained resources if the scheduling is changed by the controller.
> Update namespace scheduler to enqueue resources on scheduling change

- pkg/admission/clusterworkspaceshard/admission.go
- pkg/admission/clusterworkspaceshard/admission_test.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/server/server.go
- test/e2e/framework/expect.go
- test/e2e/reconciler/clusterworkspace/controller_test.go
This PR makes sure the external address admission initialiser relies on a completed configuration, with the default secure serving port.
The logic is taken from the generic options completion method. While it fixes the issues below, there may be a better, more idiomatic, way to fully complete the options.
Fixes #853 
Fixes #854
> server: Set external address based on completed serving config

- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Since workspace deletion currently leaves all resources inside that
workspace effectively orphaned, we should not allow users to delete
workspaces for now.  Admins can still delete clusterworkspaces, and we
can always add the "delete" verb to the "workspace" subresource by hand.
> virtual: Disable workspace deletion for now

- pkg/syncer/specsyncer.go
Fix it so we only log that we created a downstream namespace when we
actually did, instead of every time ensureDownstreamNamespaceExists
returns successfully.
Fixes #
> specsyncer: fix when logging namespace creation

- manifest/etcd.yaml
- manifest/kcp.yaml
This includes:
* kcp container
* virtual-workspaces container
* 3 etcd pods
The initial goal here is to protect the infrastructure running KCP from a memory leak in KCP.  This should give us some decent head room for now.
We've actually seen node instability (i.e. memory thresholds hit on nodes) on the OSD cluster running the KCP shared service, so this is a step to try and prevent that from happening.
> Apply resource constraints to kcp instance

- .github/workflows/kcp-image.yaml
Backports #882.  The intent is for the image to still be built on this branch, but the deploy step is disabled.
> [0.3] Disable deploy pipeline on release branch

- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/apiimporter/apiimporter_manager.go
- pkg/reconciler/workload/heartbeat/heartbeat_manager.go
- pkg/reconciler/workload/heartbeat/heartbeat_manager_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
- pkg/reconciler/workload/namespace/namespace_test.go
- pkg/reconciler/workload/namespace/scheduler.go
- pkg/reconciler/workload/namespace/scheduler_test.go
- pkg/reconciler/workload/syncer/pullmanager.go
- pkg/reconciler/workload/syncer/pushmanager.go
- pkg/reconciler/workload/syncer/syncer_manager.go
- test/e2e/framework/fixture.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/cluster/syncerheartbeat_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
Backports fix in #864 for a hotloop.  Requires testing fixture changes from #861.
> [0.3] Stop apiimporter, syncer, heartbeat from fighting over the Ready condition

- cmd/crd-puller/pull-crds.go
- cmd/ingress-controller/main.go
- cmd/kcp/kcp.go
- go.mod
- go.sum
- pkg/cmd/help/doc.go
There is already internal code to detect the terminal width, so we don't
need to carry a dependency that does it by exec'ing stty.
Signed-off-by: James Peach <jpeach@cloudflare.com>
> Remove stty dependency.

- pkg/features/kcp_features.go
- pkg/server/options/flags.go
- pkg/server/options/flags_test.go
- pkg/server/options/genericcontrolplane.go
- pkg/server/options/options.go
Used as in kube:
- on the command line: `--feature-gates=Foo=true`
- in code: `if utilfeature.DefaultFeatureGate.Enabled(kcpfeatures.Foo)`.
- In `kcp start options`: <img width="1721" alt="Bildschirmfoto 2022-04-25 um 14 07 13" src="https://user-images.githubusercontent.com/730123/165086051-8ef71f20-f2d2-4e98-838e-4fc81d865f69.png">
> cmd/kcp: add --feature-gates flag

- .github/workflows/kcp-image.yaml
- .github/workflows/syncer-image.yaml
By adding branch names to the tags of the kcp and syncer images it is easier to consume them from other projects
> Add branch name to the tag list of kcp and syncer images

- pkg/admission/plugins.go
- pkg/admission/reservedcrdannotations/admission.go
- pkg/admission/reservedcrdannotations/admission_test.go
- test/e2e/customresourcedefinition/customresourcedefinition_test.go
- test/e2e/customresourcedefinition/wildwest.dev_cowboys.yaml
* Validate that CRD does not have bound-crd annotation unless in the
shadow workspace
Fixes #844
> Adding admission plugin to validate CRDs

- pkg/syncer/syncer.go
Before informers were started twice.
> syncer: don't sync standard resources twice

- .github/workflows/syncer-image.yaml
call `ko` with the `-B` option to prevent adding the MD5 hash of the import path to the resulting image name.
see https://github.com/google/ko#naming-images
the resulting image names will be:
* ghcr.io/kcp-dev/kcp/syncer:${git short commit sha}
* ghcr.io/kcp-dev/kcp/syncer:${git ref name} (e.g. main)
e.g. see https://github.com/geoberle/kcp/pkgs/container/kcp%2Fsyncer
Fixes #941
> fix syncer image name

- cmd/ingress-controller/main.go
- cmd/kcp-front-proxy/options/options.go
- cmd/kcp/kcp.go
- cmd/syncer/options/options.go
- cmd/virtual-workspaces/command/cmd.go
Default to -v=2 for kcp, ingress-controller, kcp-front-proxy, virtual-workspaces (the 4 components that use logs.Options)
Fixes #
> Default to -v=2

- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
The namespace scheduler used `namespaceContentsEnqueuedForMap` to avoid double requeuing of resources. @ncdc found a bug of this logic that led to resources missed during reschedule of the namespace resources:
> I have a theory on the syncer flakes:
> 1. Namespace get scheduled to `cluster-x`
>     a. It’s patched
>     b. `c.namespaceContentsEnqueuedForMap[nsKey]` is set to `cluster-x`
> 2. Dynamic informer sees new deployment, ns controller `reconcileResource` is called
>     a. When it gets the ns from the cache, it’s stale (doesn’t have the cluster label yet)
>     b. It compares the deployment’s cluster label (unset) with the ns’s cluster label (unset) and returns early -> no assignment
> 3. NS informer sees updated ns (after it was patched), reconcileNamespace is called, which calls …
> reconciler/workload/scheduling: remove wrong resource enqueuing avoiding optimization

- pkg/cliplugins/workload/plugin/sync.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/syncer/syncer_test.go
Signed-off-by: Dominique Vernier <dvernier@redhat.com>
Avoid creating workloadcluster, sa and clusterolebinding if they already exist
Overwrite the sa, crb with the calculated values
Fixes https://github.com/kcp-dev/kcp/issues/920
> Make 'kubectl kcp workload sync' idempotent

- pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
- test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
1. increase wait time
2. pass the test when list workspace return 404
Fixes https://github.com/kcp-dev/kcp/issues/950
> Fix workspace deletion e2e flake

- pkg/proxy/proxy.go
This PR updates the KCP front proxy to use sane transport defaults and allow http2 to backends.
https://github.com/kcp-dev/kcp/pull/973#issuecomment-1116990919
> Front proxy: set sane transport defaults and enable http2 to backends

- .github/workflows/ci.yaml
Reverts kcp-dev/kcp#965
Because upload fails again, compare https://github.com/kcp-dev/kcp/runs/6325920274?check_suite_focus=true.
> Revert "ci: update to actions/upload-artifact@v3"

- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
Delete the `ClusterRoleBinding` that is left behind when a `ClusterWorkspace` creation fails late.
Fixes #977
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
> cleanup ClusterRoleBinding on failed workspace creation

- .github/workflows/kcp-image.yaml
- manifest/etcd.yaml
- manifest/issuer.yaml
- manifest/kcp-front-proxy.yaml
- manifest/kcp.yaml
- manifest/kustomization.yaml
This adds the front proxy into the topology of the deployment manifest.
Instead of terminating TLS at the ingress router, it will instead terminate at the front proxy, and the proxy will route requests to either KCP or the virtual workspaces process.
This also leverages cert-manager to add the ability to authenticate using a certificate.  Groups will be assigned using the organizations listed on the cert.
> Add front proxy

- pkg/admission/plugins.go
- pkg/admission/reservedcrdgroups/admission.go
- pkg/admission/reservedcrdgroups/admission_test.go
- pkg/server/apiextensions_test.go
- test/e2e/customresourcedefinition/customresourcedefinition_test.go
- test/e2e/customresourcedefinition/wildwest.kcp.dev_cowboys.yaml
Signed-off-by: Robin Y Bobbitt <rbobbitt@redhat.com>
Adds an admission plugin that ensures *.kcp.dev CRDs are only allowed in system:system-crds.
Fixes #772
> Forbid kcp.dev CRD groups outside system:system-crds

- .github/workflows/kcp-image.yaml
Deployment github action should fetch external hostname from the new `kcp-front-proxy` route.
> Fetch external hostname from kcp-front-proxy route.

- pkg/apis/apiresource/v1alpha1/doc.go
- pkg/apis/apis/v1alpha1/doc.go
- pkg/apis/workload/v1alpha1/doc.go
- pkg/openapi/zz_generated.openapi.go
This PR enables openapiv2 generation for all the KCP APIs. This is particularly useful when such APIs should be used in some virtual workspace implementation.
The changes in this PR were part of the work initially done in the context of PR #724 (issue  #487)
> Generate openapiv2 code for all KCP APIs

- .dockerignore
- Dockerfile
* Ignore local ./bin for container image builds
* add .kcp directory to container image
Signed-off-by: Micah Hausler <mhausler@amazon.com>
Fixes #1019
> image: Add entrypoint to container image

- pkg/apis/apiresource/v1alpha1/common_types.go
- pkg/reconciler/apis/apiresource/negotiation.go
- pkg/reconciler/workload/apiexport/apiresourceschema.go
This PR add helpers to the `CommonAPIResourceSpec` to make the conversion to `CustomResource` objects easier.
This PR is based on PR #1023 to which the first commit belongs, so that only the last commit is really part of this PR.
The changes in this PR were part of the work initially done in the context of PR #724 (issue  #487)
> Add helpers in `CommonAPIResourceSpec`

- pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
Prepare for other types of virtuall workspaces by moving an `openapiv2` special case out of the `rootapiserver`.
This PR is based on PR #1024 to which the 2 first commits belongs, so that only the last commit is really part of this PR.
The changes in this PR were part of the work initially done in the context of PR #724 (issue  #487)
> Prepare for other types of virtuall workspaces

- cmd/virtual-workspaces/command/cmd.go
- cmd/virtual-workspaces/options/options.go
- pkg/server/options/virtual.go
- pkg/server/server.go
- pkg/server/virtual.go
- pkg/virtual/options/options.go
Allow several virtual workspace commands, in addition to the only existing one (`workspaces`).
The changes in this PR were part of the work initially done in the context of PR https://github.com/kcp-dev/kcp/pull/724 (issue https://github.com/kcp-dev/kcp/issues/487)
> Allow several virtual workspace commands

- pkg/virtual/framework/doc.go
- pkg/virtual/framework/dynamic/apidefinition/types.go
- pkg/virtual/framework/dynamic/apiserver/apiserver.go
- pkg/virtual/framework/dynamic/apiserver/discovery.go
- pkg/virtual/framework/dynamic/apiserver/doc.go
- pkg/virtual/framework/dynamic/apiserver/handler.go
- pkg/virtual/framework/dynamic/apiserver/handler_test.go
- pkg/virtual/framework/dynamic/apiserver/serving_info.go
- pkg/virtual/framework/dynamic/context/keys.go
- pkg/virtual/framework/dynamic/doc.go
- pkg/virtual/framework/dynamic/doc_test.go
- pkg/virtual/framework/dynamic/example_test.go
- pkg/virtual/framework/dynamic/register.go
- pkg/virtual/framework/dynamic/types.go
Dynamic Virtual workspace implementation that allows exposing CRD-like APIs per API domains
(one base virtual workspace URL per API domain)
Largly inspired from the current code of the `apiextensions-apiserver/pkg/apiserver`
package of the `kcp-dev/kubernetes` fork
This is a pre-requisite for https://github.com/kcp-dev/kcp/pull/754.
> Dynamic Virtual workspace implementation

- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
authz: use an import alias for tenancy api
---
top-level-authz: improve a name
---
I pulled these out from some draft PR that @sttts had ... figured we can merge as-is
/cc @sttts @ncdc
> authorization: nits

- pkg/virtual/framework/dynamic/types.go
Many editors are able to follow Golang-style type references in GoDoc
comments, but only if they are correct and able to be resolved. This
commit changes some GoDoc to use appropriate names to enable that
feature.
/assign @sttts @ncdc
> virtual: fix some GoDoc

- .github/workflows/kcp-image.yaml
Gitops has been set up using a private repo for the manifests and ArgoCD.  This will facilitate separating out manifests for the shared service for Red Hat from the community repo.  We still want to update the "unstable" version of the shared service upon a push to main, though.  So this is implementing that integration.
> Use private gitops repo to deploy from main

- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/context/keys.go
This a a pre-requisite for the implementation of transformations in the Syncer virtual workspace.
In a number of cases, especially for transformations that manage syncer-specific views of a KCP resource,
knowing the workload cluster for a given request context is important. 
This is a first standalone PR, split out from the complete syncer strategies PR: https://github.com/kcp-dev/kcp/pull/1064
> Add the WorkloadCluster name to the current context in the syncer virtual workspace

- .github/workflows/kcp-image.yaml
Follow up for https://github.com/kcp-dev/kcp/pull/928
Fixes this error in the [CI job](https://github.com/kcp-dev/kcp/runs/6479175167?check_suite_focus=true#step:3:43):
```Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@fv-az200-895.f5bee3wnw2gu3k5g3q4wfpt2ta.dx.internal.cloudapp.net>) not allowed
Error: Process completed with exit code 128.```
> ci: Config author for commit to gitops repo

- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process.go
- pkg/syncer/syncer.go
After recent changes, it seems that the syncer constantly tries to sync namespace resources, as other namespaced resources, which of course is not possible.
Surely namespaces should be received by the informer and present in the informer caches, but not effectively synced by the syncer `process` functions.
Fixes #
Not sure there was an issue for this.
> Avoid trying to sync namespaces as namespaced resources.

- .github/workflows/ci.yaml
- Makefile
Signed-off-by: Chris Ahl <cahl@redhat.com>
`make test-e2e` is broken if `WHAT` parameter is passed.
With this fix, you would need to run with `WHAT-TESTS` instead of `WHAT`
```
make test-e2e WHAT-TESTS=./test/e2e/syncer...
```
Fixes #1089
> Fix make test-e2e WHAT so that it works by using WHAT-TESTS

- pkg/virtual/framework/forwardingregistry/rest.go
- pkg/virtual/framework/forwardingregistry/rest_test.go
- pkg/virtual/framework/forwardingregistry/store.go
- pkg/virtual/syncer/builder/forwarding.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
This makes the underlying code more reusable for other types of filters
that virtual workspaces might want to use.
/assign @sttts
> virtual: factor label selector injection out

- pkg/virtual/framework/dynamic/apidefinition/internalapis.go
- pkg/virtual/framework/dynamic/apidefinition/internalapis_test.go
- pkg/virtual/framework/dynamic/apidefinition/types.go
If we are to be able to use this thing from outside the package, these
fields need to be exported.
/assign @davidfestal @sttts
> virtual: expose fields in internal api struct

- pkg/syncer/syncer.go
This PR builds on top of PR https://github.com/kcp-dev/kcp/pull/1018 and wires the syncer to the syncer virtual workspace.
This is a minimal implementation that reads only the first VirtualWorkspace URL at start.
When tackling sharding, we would have to revisit this to create clients / informers (or even SpecSyncer / StatusSyncer)  for each virtual workspace URL (and maintain them if the list of URLs changes)
> Wire syncer to the virtual workspace

- pkg/cliplugins/workload/plugin/sync_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
The diff output from this helper is objectively worse by a large margin
from that produced by cmp.Diff - and, furthermore, it does not allow for
complex comparison logic, determining how to compare unexported fields,
etc. The `cmp` library is better, so use it.
> test: stop using require.Equal for composite objects

- .github/workflows/kcp-image.yaml
When updating gitops repo with new commit hash, it needs to be wrapped
in quotes so that it doesn't get incorrectly interpolated into something
else.
Example: 69353e8 gets interpolated like scientific notation
> ci: Wrap commit ID in quotes

- pkg/virtual/framework/forwardingregistry/rest.go
- pkg/virtual/framework/forwardingregistry/rest_test.go
- pkg/virtual/framework/forwardingregistry/store.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/builder/forwarding.go
- pkg/virtual/syncer/controllers/apireconciler/apireconciler_controller.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Support `APIExport` identity in the Syncer virtual workspace.
This is a pre-quisite for PR #927
> Support APIExport identity in the Syncer virtual workspace

- pkg/syncer/shared/finalizer.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
- test/e2e/reconciler/scheduling/controller_test.go
This PR builds on top of the basic Syncer virtual workspace PR( [#1111](https://github.com/kcp-dev/kcp/pull/1111)), and introduce the required Syncer changes to allow syncers (wire to the syncer virtual workspace) to sync from mltiple workspaces having consistent APIs.
Only the 2 last commits add on top of PR [#1111](https://github.com/kcp-dev/kcp/pull/1111)
- Start KCP:
```bash
./bin/kcp start --auto-publish-apis --feature-gates KCPLocationAPI=true
```
- Export KCP kubeconfig:
```bash
export KUBECONFIG=$(pwd)/.kcp/admin.kubeconfig
```
- Create a `negotiation` workspace:
```bash
kubectl ws create negotiation --enter
```
- Prepare for the Syncer installation:
```
kubectl kcp workload sync us-west1 --replicas=0 --resources=ingresses.networking.k8s.io,deployments.apps,services …
```
> Sync from multiple workspaces

- Makefile
Align with `make test`:
```
$ make test-e2e WHAT=./test/e2e/reconcilers/...
```
> Makefile: fix WHAT for test-e2e

- pkg/reconciler/workload/apiexport/apiexport_controller.go
The index is used (in `enqueueNegotiatedAPIResource`), but not created. Hence, we lose triggers for APIExport updates.
> reconciler/workloads/apiexport: fix missing byWorkspace index for exports

- test/e2e/framework/kcp.go
Logs without newlines are mostly useless as unreadable.
> e2e: print failing server log with newlines

- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/namespace/conditions_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
- pkg/reconciler/workload/namespace/namespace_test.go
- pkg/reconciler/workload/namespace/scheduler_test.go
- test/e2e/framework/fixture.go
- test/e2e/reconciler/namespace/controller_test.go
Those labels belong into the API package.
> apis/workloads: move scheduling labels here

- pkg/apis/apis/v1alpha1/types.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor_test.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
- pkg/server/controllers.go
- test/e2e/apibinding/apibinding_deletion_test.go
- test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
add controller to delete all CRs with apibinding is deleting
followup: avoid CR creation when apibinding is deleting
Fixes https://github.com/kcp-dev/kcp/issues/846
> Delete custom resources when apibinding is deleted

- pkg/syncer/spec/mutators/deployment.go
- pkg/syncer/spec/mutators/deployment_test.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process.go
- pkg/syncer/syncer.go
- test/e2e/syncer/syncer_test.go
We are syncing the default serviceaccount from KCP to downstream, but it is not actually used downstream.
* Syncer: Stop syncing the serviceaccount by default.
* Syncer: Don't rename serviceaccount resources.
* Mutators: Deployment, don't add the serviceaccount to the downstream deployment podTemplate spec.
> Don't sync ServiceAccounts by default

- pkg/admission/apiresourceschema/validation.go
- pkg/apis/apis/v1alpha1/types.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/apibinding/apiresourceschema_tlsroutes.yaml
- test/e2e/apibinding/support.go
This PR enables the binding of APIs whose groups are _protected_, as defined in kubernetes/enhancements#1111.
The proposed solution delegates to the user the responsibility of adding the `api-approved.kubernetes.io` annotation to the `APIResourceSchema` resource, as for standard CRDs, so it makes it explicit, and prevents from accidentally declaring APIs in a protected group. With this PR, the APIBinding controller will simply propagate the annotation to the projected CRDs.
In the API import case, where CRDs are generated following the creation of `APIResourceImport` resources, the `NegociatedAPIResource` controller already adds the _approval_ annotation, assuming the API have already been explicitly declared as approved in the downstream workload cluster.    
TODO:
Fixes #1083
> api: Enables the binding of APIs in protected groups

- Makefile
In contrast to BSD make, https://www.gnu.org/software/make/manual/make.html#Target_002dspecific seems to be broken.
> Makefile: fix build-all target for GNU make

- config/organization/clusterworkspacetype-team.yaml
- config/organization/clusterworkspacetype-universal.yaml
- config/root/clusterworkspacetype-organization.yaml
- config/team/clusterworkspacetype-universal.yaml
- pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
We know these are names for initializers. We do not need to state as
much in their domain.
/assign @sttts
> *: shorten initializer names

- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
There already is a GroupResource filter to prevent the deletor from
querying virtual resources (i.e. workspaces), but it wasn't quite hooked
up correctly.
Fixes #1142
> Filter out workspaces type from workspace content deletor

- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
- config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
- pkg/admission/clusterworkspace/admission.go
- pkg/admission/clusterworkspace/admission_test.go
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller_test.go
We cannot enforce that labels match the values in a status update, as a
client cannot update metadata and status in the same call. Therefore, we
move this logic from a mutating admission plugin to the controller.
/assign @sttts
> reconciler: clusterworkspace: enforce labels

- pkg/server/handler.go
- pkg/server/server.go
Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>
Initializes Audit Annotations with `kaudit.WithAuditAnnotations`.
It is necessary to be done by some early middleware. I verified that with the change we annotate the workspace.
Previous PR lost reference and couldn't be changed anymore.
https://github.com/kcp-dev/kcp/pull/1113
https://github.com/kcp-dev/kcp/issues/862
> pkg/server: add audit annotation init

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/apis/apiresource/negotiation.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/workload/basecontroller/controller.go
- pkg/reconciler/workload/heartbeat/heartbeat_manager.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
- pkg/virtual/workspaces/registry/rest.go
Removing getting logicalcluster from objects metadata, and instead use logicalcluster.From.
Handeling Setting the value, will be completed in a followup PR.
Partial fix for #1008
> remove getting cluster name from object meta 

- pkg/syncer/syncer.go
- pkg/virtual/syncer/builder/build.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Pass through the handler chain, which eventually ends as 403 or 404 depending on authz.
> virtual: ignore requests without clusters/ suffix

- .github/workflows/ci.yaml
I _think_ we're running `test/e2e...` twice in e2e-shared-server, once from the defaulting of `WHAT` in Makefile for `test-e2e` and a second time in ci.yaml where we have `test/e2e...` in `TEST_ARGS`. Let's see if this reduces test time...
Fixes #
> e2e-shared-server: stop running 2x

- .github/workflows/ci.yaml
- Makefile
- hack/verify-imports.sh
We should not require more than a simple `make` target to run any test.
> makefile: update things to be consistent & simple

- pkg/virtual/framework/internalapis/fixtures/workloadclusters.yaml
- pkg/virtual/framework/internalapis/import.go
Wasn't a problem because everything in internal APIs is v1.
> virtual: fix internalapi APIResourceSchema version

- Makefile
This will allow us to put it into a build cache, but still own the
definition of them.
> make: add a target for all of our tools

- test/e2e/framework/fixture.go
During e2e the normal component-base klog initialization is not running.
> e2e/framework: set klog verbosity 2

- .github/workflows/ci.yaml
- Makefile
There's no real reason to expect every single user to manage their path
individually when calling `make`, and it furthermore never makes sense
to use an out-of-date binary that we create, so our output should be a
prefix to the path.
> makefile: update path to include output binaries

- cmd/virtual-workspaces/command/cmd.go
- pkg/server/virtual.go
- pkg/virtual/framework/forwardingregistry/wrappers.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- pkg/virtual/initializingworkspaces/doc.go
- pkg/virtual/initializingworkspaces/options/options.go
- pkg/virtual/options/options.go
- pkg/virtual/syncer/builder/build.go
- test/e2e/framework/fixture.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
virtual: add initializingworkspaces endpoint
This endpoint shows a client the ClusterWorkspaces which are
a) initializing
b) waiting for the client's initalizer to be removed
This endpoint is accessed under
/services/initilizingworkspaces/<initializer>
---
based off of #https://github.com/kcp-dev/kcp/pull/1140
/assign @sttts @ncdc 
Follow-ups:
> virtual: add initializingworkspaces endpoint

- cmd/kubectl-kcp/main.go
- pkg/apis/apis/v1alpha1/crd_to_apiresourceschema.go
- pkg/cliplugins/crd/cmd/cmd.go
- pkg/cliplugins/crd/plugin/options.go
- pkg/cliplugins/crd/plugin/snapshot.go
- pkg/cliplugins/crd/plugin/snapshot_test.go
Add a new command, `kubectl kcp crd snapshot`, to make it easy to convert.
```
crdExample = `
%[1]s crd snapshot -f crd.yaml --prefix 2022-05-07 > api-resource-schema.yaml
%[1]s crd snapshot -f - --prefix today > output.yaml
```
Fixes #
> Add kubectl kcp crd snapshot command

- pkg/virtual/framework/context/keys.go
- pkg/virtual/framework/dynamic/apiserver/apiserver.go
- pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
Do not use `context.WithValue` directly for the VirtualWorkspace name.
No related issue afaict
Fixes #
Cleanup to match good practice patterns.
> Do not use `context.WithValue` directly for the VirtualWorkspace name.

- pkg/syncer/spec/mutators/deployment.go
- pkg/syncer/spec/mutators/deployment_test.go
- pkg/syncer/spec/mutators/secrets.go
- pkg/syncer/spec/mutators/secrets_test.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- test/e2e/syncer/syncer_test.go
The Deployment Mutator will look for a ServiceAccount token, and use its full name for syncing downstream, instead of hardcoding one secret name (kcp-default-token).
* only the default token is prefixed with: "kcp-", to avoid possible conflicts with the downstream default tokens.
* the token secret type is set to `Opaque`, instead of ServiceAccount type
* the token annotations for a `ServiceAccount` are removed
closes https://github.com/kcp-dev/kcp/issues/1062
related to: https://github.com/kcp-dev/kcp/issues/1058 https://github.com/kcp-dev/kcp/issues/280
> Syncer: Deployment Mutator use the full secret name instead of a hardcoded one 

- Dockerfile
Now that pkg/apis is a separate go module, and the root go.mod points to
it using a relative replace directive, we have to make sure we copy
pkg/apis/go.{mod,sum} into the build container before invoking 'go mod
download'
Follow up to #1175
> Fix kcp image build

- pkg/virtual/framework/context/keys.go
- pkg/virtual/framework/dynamic/apiserver/apiserver.go
- pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
Cleanup followup on PR https://github.com/kcp-dev/kcp/pull/1180
We should not consider non-virtual-workspace requests (like `/readz` requests) as errors and dump errors in logs
> virtual: Avoid error logs for `/readz` requests

- cmd/virtual-workspaces/command/cmd.go
- cmd/virtual-workspaces/options/options.go
- contrib/kcp.code-workspace
- pkg/server/virtual.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/framework/authorization/authorizer.go
- pkg/virtual/framework/context/keys.go
- pkg/virtual/framework/dynamic/apiserver/apiserver.go
- pkg/virtual/framework/dynamic/types.go
- pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
- pkg/virtual/framework/fixedgvs/types.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
- pkg/virtual/framework/types.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/options/authorization.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/workspaces/builder/build.go
Add authorizers in virtual workspaces
This is a pre-requisite for issues  #1172 and #1151
> Add authorizers in virtual workspaces

- pkg/cliplugins/crd/plugin/snapshot.go
- pkg/cliplugins/crd/plugin/snapshot_test.go
Support multi-doc yaml with `kubectl kcp crd snapshot`, such as
```
kustomize build config/crd | kubectl kcp crd snapshot -f - --prefix today | kubectl apply -f -
```
Fixes #
> kubectl/crd snapshot: support multidoc

- pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission.go
- pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission_test.go
- pkg/admission/plugins.go
introduces an admission plugin for ensuring CRD's Group and Resource fields for logical clusters are unique and don't overlap with bound CRDs.
TODO:
- change the binding controller to check for conflicting GRVs (separate PR)
xref: https://github.com/kcp-dev/kcp/issues/748
> adds crdNoOverlappingGVRAdmission admission 

- pkg/cliplugins/workload/plugin/sync.go
- pkg/virtual/options/options.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/options/options.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
Implement  the Syncer virtual workspace authorizer by issuing a `SubjectAccessReview` with "sync" verb against the `WorkloadCluster` name resource
Fixes #1172
> Implement the Syncer virtual workspace authorizer

- .github/workflows/ci.yaml
- Makefile
Similarly to how we use `go install` to get tools we need for other
tasks, we can just download this script ourselves, as we need nothing
else from the repo-infra repository.
/cc @sttts @ncdc
> makefile: manage boilerplate verification locally

- .github/workflows/kcp-image.yaml
The folders in the gitops repo were renamed.
> Change gitops folder commit hash update is applied to

- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/framework/types.go
- pkg/virtual/options/options.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/virtual/apiexport/apiresourceschema_cowboys.yaml
- test/e2e/virtual/apiexport/support.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Adding the authorizer for apiexport that will check that the requesting user has access to the apiexport context subresource for the specific API export. the verb being used will be forwarded along to be checked.
example: watch cowboys
request path: `/services/apiexport/root:org:ws/cowboys-export/clusters/*/api/v1/cowboys`
SAR check would ask if I can `list` on the specific `cowboys-export` `/content` subresource.
Follow on for: https://github.com/kcp-dev/kcp/pull/1176
Fixes #1151
> adding authorizer for the api export virtual workspace

- pkg/cliplugins/workspace/cmd/cmd.go
Signed-off-by: Mike Spreitzer <mspreitz@us.ibm.com>
This PR updates the outdated command line flag cited in #1189 .
Fixes #1189
> Replace `--use` with `--enter`

- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/fixtures/apifixtures/apibinding.go
- test/e2e/fixtures/apifixtures/sheriffs.go
- test/e2e/framework/json.go
- test/e2e/virtual/apiexport/support.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Temporarily add namespaces, configmaps, secrets, and serviceaccounts to
every APIExport virtual workspace, until "ThingPermissionClaim" is
implemented.
Temporary until #1219 is implemented
Only 2nd commit is new. First commit is #1218
> APIExport virtual workspace: add core/v1

- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/fixtures/apifixtures/apibinding.go
- test/e2e/fixtures/apifixtures/sheriffs.go
- test/e2e/framework/json.go
Extract helpers for APIResourceSchema, APIExport, APIBinding from the cross cluster conformance test so they can be more easily reused.
Fixes #1194
> e2e: extract APIExport/APIBinding helpers

- test/e2e/syncer/syncer_test.go
Signed-off-by: Chris Ahl <cahl@redhat.com>
Added E2E tests for `kubectl kcp workload` commands cordon, uncordon and drain
Adds tests for what was added in issue #525
> Add E2E tests for cordon/uncordon/drain CLI

- pkg/server/server.go
- pkg/server/virtual.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
- Add virtual workspace readiness checks to the KCP server when the virtual workspaces are started inside
the KCP server process.
- Also rework virtual workspace readiness checks to add each virtual workspace check individually in the virtual workspace root API Server, instead of having only a readiness summary that fails on the first failing check.
Fixes #1223
> Add virtual workspace readiness checks to the KCP server in the embedded case

- test/e2e/apibinding/apibinding_protected_test.go
```
--- FAIL: TestProtectedAPI (4.78s)
fixture.go:115: shared kcp server will target configuration "/home/runner/work/kcp/kcp/.kcp/admin.kubeconfig"
fixture.go:246: Created organization workspace root:e2e-org-pc4kq
fixture.go:309: Created Universal workspace root:e2e-org-pc4kq:e2e-workspace-zmc6p
fixture.go:309: Created Universal workspace root:e2e-org-pc4kq:e2e-workspace-dbq[29](https://github.com/kcp-dev/kcp/runs/6782662897?check_suite_focus=true#step:10:30)
apibinding_protected_test.go:59: Install today cowboys APIResourceSchema into service provider workspace "root:e2e-org-pc4kq:e2e-workspace-zmc6p"
apibinding_protected_test.go:64: Create an APIExport for it
apibinding_protected_test.go:76: Create an APIBinding in consumer workspace "root:e2e-org-pc4kq:e2e-workspace-dbq29" that points …
```
> e2e/apibinding: require.Eventually for discovery

- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Prune fields that get touched by other actors.
```
--- FAIL: TestInitializingWorkspacesVirtualWorkspaceAccess (0.65s)
fixture.go:115: shared kcp server will target configuration "/home/runner/work/kcp/kcp/.kcp/admin.kubeconfig"
fixture.go:246: Created organization workspace root:e2e-org-k8skn
fixture.go:309: Created Universal workspace root:e2e-org-k8skn:e2e-workspace-2qpv2
virtualworkspace_test.go:117: Create workspace types that add initializers
virtualworkspace_test.go:162: Create workspaces that using the new types, which will get stuck in initializing
virtualworkspace_test.go:167: 
Error Trace:	virtualworkspace_test.go:167
Error:      	Received unexpected error:
clusterworkspaces.tenancy.kcp.dev "e2e-workspace-" is forbidden: spec.type "Alphaeannsuvqzy" does not exist
Test: …
```
> e2e/virtual/initializers: fix flake in TestInitializingWorkspacesVirtualWorkspaceDiscovery

- pkg/admission/clusterworkspacetypeexists/admission.go
- pkg/admission/clusterworkspacetypeexists/admission_test.go
As our bootstrap controller will re-try the list of resources until they
all succeed, no further changes are necessary other than to stop
special-casing the Universal type.
Part of #1149 
/assign @sttts
> clusterworkspacetype: stop special-casing Universal

- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- test/e2e/syncer/syncer_test.go
This PR enables the syncer finalizers, k8s-based and virtual ones by default, and the required per-location deletion timestamps. Those features were before feature-gated: https://github.com/kcp-dev/kcp/pull/942
closes https://github.com/kcp-dev/kcp/issues/1193
> Enable syncer finalizers (k8s & virtual) by default.

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_indexes.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
- pkg/reconciler/apis/apibinding/conflict_checker.go
- pkg/reconciler/apis/apibinding/conflict_checker_test.go
changes the APIBinding controller to check for CRDs with overlapping GVRs in a logical cluster. Initially, we wanted to implement it as an admission plugging. Since it might involve network calls we decided to move it to the controller.
Fixes #748
> APIBinding reconciler checks for overlapping CRDs in a logical cluster

- pkg/reconciler/workload/resource/resource_reconcile.go
Ingresses are currently not assigned to workload clusters based on the Placement API. This PR lifts that exception, so the Placement API also applies to Ingress resources.
This should ideally be back-ported to 0.5.0.
Note that this impacts the in-tree ingress-splitter controller, which is to be re-worked already. 
Fixes #896
> Fix Ingress cluster assignment based on namespace placement

- test/e2e/virtual/syncer/virtualworkspace_test.go
Fixes https://github.com/kcp-dev/kcp/issues/1187.
> e2e/virtual/syncer: fixing race with resource controller in TestSyncerVirtualWorkspace

- pkg/etcd/etcd.go
- pkg/server/options/embeddedetcd.go
- pkg/server/options/flags.go
- pkg/server/server.go
Adding `--embedded-etcd-force-new-cluster` to be able to start the etcd with an existing etcd database.
This is useful for debugging and local development.
See https://etcd.io/docs/v3.3/op-guide/recovery/#restoring-a-cluster-from-membership-mis-reconfiguration-with-wrong-urls for more details.
> pkg/etcd,server: add --embedded-etcd-force-new-cluster

- README.md
Video on readme was two versions out of date. This updates to the latest v0.4 video on Youtube.
> Update video on readme to v0.4

- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml-patch
- config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
- config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml-patch
- config/crds/tenancy.kcp.dev_workspaces.yaml
- config/crds/tenancy.kcp.dev_workspaces.yaml-patch
This was from the time before we had hierarchy.
> ClusterWorkspace+Types: allow name "org"

- pkg/authorization/workspace_content_authorizer.go
Currently checking for initialize permissions on the parent cluster relies nil-checking the cluster workspace lister.
This worked under the assumption that clusterworkspace CRDs are being installed in the workspace controller/scheduler.
This does not hold true any more. Clusterworkspace CRDs are now initialized as part of the server bootstrap,
independent of the workspace controller/scheduler, hence these CRDs are always available.
Even if we omit bootstrapping those CRDs the value will not be nil (verified in a debugger session).
This fixes it.
#425, #422
> pkg/authorization: don't check for cluster workspace lister.

- pkg/cliplugins/workspace/plugin/kubeconfig.go
Now that types are qualified with their workspace, using %q
double-quotes things and is not ideal.
/assign @jmprusi 
Saw this during your demo today
> kubectl kcp ws: fix type printing

- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
The Location DeletionTimestamp annotation was using an incorrect timestamp format, this PR fixes it by formating the Timestamp as specified by the RFC3339 format.
/cc @sttts
> reconciler/workload/resource: use RF3339 timestamp format

- config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml
- pkg/apis/tenancy/initialization/utils.go
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/options/options.go
- pkg/virtual/options/options.go
- test/e2e/framework/util.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
initializingworkspaces: enforce permissions
The user must be able to verb=initialize on the ClusterWorkspaceType
that the initializer is for.
/hold
/assign @sttts 
Part of #1149 
Why doesn't this cause the test to fail ... ?
> initializingworkspaces: enforce permissions

- pkg/virtual/apiexport/builder/forwarding.go
This PR removes the `create`, `delete` and `deletecollection` verbs from the discovery results returned by the virtual API server, as these are not supported by the underlying storage implementation, and leads the virtual API server to panic when the corresponding operations are being requested, and the client requests to be closed abruptly without further details.
Support for these operations will be provided in a future PR. In the interim, this PR prevents the virtual API server from panicking, and makes it return "405 Method Not Allowed" to clients, that try to perform these not supported operations. 
Relates to #1253.
> virtual: Remove unsupported verbs from virtual API server discovery

- pkg/server/virtual.go
the recommended config used by the virtual workspaces server attaches `healthz.PingHealthz`, `healthz.LogHealthz`
these checks have already been added to the previous server 
so we need to skip them otherwise we will panic with:
```
E0615 10:08:47.692463   34375 pathrecorder.go:109] duplicate path registration of "/readyz/ping": original registration from goroutine 1 [running]:
runtime/debug.Stack()
/Users/lszaszki/.gimme/versions/go1.17.darwin.amd64/src/runtime/debug/stack.go:24 +0x65
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).trackCallers(0xc001761570, {0xc001f59090, 0xc})
/Users/lszaszki/go/pkg/mod/github.com/p0lyn0mial/kubernetes/staging/src/k8s.io/apiserver@v0.0.0-20220614143607-6d7f770e8387/pkg/server/mux/pathrecorder.go:107 +0x35 …
```
> virtual workspaces: skips registartion of default health checks

- README.md
This trivial PR fixes #1282 about mentioning prerequisites (kubectl but mainly minimum Go version) on the README when users go through the guide and try to start kcp before reading the CONTRIBUTING guide.
> Added prerequisites on the README

- cmd/test-server/main.go
Helpful for experimentation with alternative test args.
> cmd/test-server: pass flags to kcp

- config/crds/tenancy.kcp.dev_clusterworkspaces.yaml
- config/crds/tenancy.kcp.dev_workspaces.yaml
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/apis/tenancy/v1beta1/types.go
- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/virtual/workspaces/printers/printer.go
With the move to fully-qualified workspaces types we broke table output.
> cli: fix ClusterWorkspace columns output

- cmd/kcp/kcp.go
> cmd/kcp: non-zero return code on error

- pkg/apis/workload/v1alpha1/types.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/apibinding/apibinding_deletion_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/apibinding/apibinding_webhook_test.go
- test/e2e/authorizer/rootcacertconfigmap_test.go
- test/e2e/authorizer/serviceaccounts_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/conformance/webhook_test.go
- test/e2e/customresourcedefinition/customresourcedefinition_test.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/apiexport/apiexport_controller_test.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/syncer/syncer_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
- test/e2e/workspacetype/controller_test.go
Pre-req for more customization of ClusterWorkspaces in tests (for scheduling), and removal of redundant `"Universal"` everywhere.
> e2e: switch NewWorkspaceFixture to options

- pkg/virtual/workspaces/printers/printer.go
A user-facing cosmetical change for `Workspace`. The ClusterWorkspace has no Deleting phase formally.
> tenancy: show Deleting in phase column during ClusterWorkspace deletion

- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_indexes.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_phase.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
- test/e2e/reconciler/clusterworkspace/controller_test.go
For easier testing and less monolithic code. This is pre-req for more advanced logic around ClusterWorkspace scheduling.
> reconciler/clusterworkspace: split into independent reconcilers

- pkg/server/options/authentication.go
> admin.kubeconfig: remove cross-cluster context

- test/e2e/framework/util.go
Less noise in e2e while preserving the output for the cases where we need it.
> e2e/framework: wait some time until printing message in Eventually

- go.mod
- pkg/server/apiextensions.go
- pkg/server/apiextensions_test.go
The accept header can have multiple clauses, but we were only supporting
one. The Kubernetes metadataSharedInformerFactory generates requests
with the accept header having multiple clauses, and our previous logic
didn't handle them correctly, leading to thinking the request was not
for partial metadata, when in fact it was supposed to be.
Discovered while working on #1061
> Fix partial meta request determination logic

- pkg/server/apiextensions.go
- pkg/server/indexes.go
- pkg/server/server.go
- fix meta data lookup to only be for wildcard requests
- fix cache mutation
- use indexes.
> server/apiextensions: use indexes and fixes

- cmd/virtual-workspaces/command/cmd.go
- pkg/server/virtual.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/framework/authorization/authorizer.go
- pkg/virtual/framework/dynamic/example_test.go
- pkg/virtual/framework/dynamic/register.go
- pkg/virtual/framework/dynamic/types.go
- pkg/virtual/framework/fixedgvs/register.go
- pkg/virtual/framework/handler/handler.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
- pkg/virtual/framework/types.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/options/options.go
- pkg/virtual/options/authorization.go
- pkg/virtual/options/options.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/options/options.go
- pkg/virtual/workspaces/options/options.go
- name how a VW is registered externally, don't make it know its name and register it like that. The former is much more idiomatic.
- remove unused extra informer code, an anti-pattern we don't want to encourage. Informers should be instatiated in external plumbing.
> pkg/virtual: externalize VW name and remove extra informers

- cmd/kcp-front-proxy/filters.go
- cmd/kcp-front-proxy/main.go
- pkg/apis/apis/v1alpha1/crd_to_apiresourceschema.go
- pkg/metadata/dynamic.go
- pkg/server/requestinfo/util.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- test/e2e/framework/fixture.go
- test/e2e/framework/kcp.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
A consumer of the initializingworkspaces virtual workspace can today see
the list of workspaces they need to iniitalize, and now they can also
update those workspaces to remove their own initializer, but no other,
once they are done.
---
Depends on #1329 
Part of #1149 
/assign @sttts 
This is not fully functional yet but overall approach is reviewable.
> virtualworkspaces: allow access to remove iniitalizers

- config/crds/scheduling.kcp.dev_placements.yaml
- pkg/admission/plugins.go
- pkg/admission/reservedmetadata/admission.go
- pkg/admission/reservedmetadata/admission_test.go
- pkg/apis/scheduling/v1alpha1/types_placement.go
- pkg/openapi/zz_generated.openapi.go
This adds a new plugin locking down reserved system labels and annotations.
Fixes #1138
Accompanying document about kcp labels/annotations: https://docs.google.com/spreadsheets/d/1DfcEqKG3koLOveddpLwebvULK2imOGJnpe0nwWZmhAY/edit#gid=0
**Question:** We marked a lot of labels/annotations as internal. I suggest I create a separate PR with the naming changes.
/cc @sttts @ncdc
> pkg/admission: add reserved metadata admission plugin

- pkg/reconciler/workload/apiexport/apiexport_controller.go
- pkg/reconciler/workload/apiexport/apiexport_reconcile.go
- pkg/reconciler/workload/apiexport/apiexport_reconcile_test.go
Only `"kubernetes"` is our current, temporary name. This will change with location workspaces.
> Do not stomp other APIExports in a workspace with NegotatedAPIResources

- test/e2e/framework/fixture.go
Print the artifact paths, don't force the dev to guess and search.
> e2e: print artifact paths

- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/workspaces/builder/build.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Post-start-hooks should never return an error. They should just block. An error leads to stack trace output. Why? Legacy reasons 🤷
With this the terminal is not filled with stack traces on ctrl-c on startup.
> virtual: clean up post-start errors and var names

- test/e2e/fixtures/kcp-test-image/icc-test.go
Before this the first run of the container created the configmap, the second and following failed with AlreadyExists and panic'ed, leading to unavailable deployment under bad timing.
> e2e/syncer: make the test app sleep, not restart with AlreadyExists

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_indexes.go
- pkg/server/apiextensions.go
- pkg/server/indexes.go
- pkg/server/server.go
Per workspace no identity is necessary as GVR is unique. This mode of access was never expected to work.
> server/apiextensions: stop serving non-wildcard identity requests

- cmd/kcp/kcp.go
- pkg/server/options/authentication.go
- pkg/server/options/embeddedetcd.go
- pkg/server/options/flags_test.go
- pkg/server/options/options.go
- test/e2e/framework/kcp.go
This old code didn't make sense. If I pass foo.key as flag, I don't want it to mean `.kcp/foo.key`. The reason why things should be abolute (best effort only btw.) is that logs make more sense, i.e. that you see when a wrong path is chosen.
> server: only make default paths absolute, not user-provided ones

- cmd/kcp-front-proxy/authentication/groups.go
- cmd/kcp-front-proxy/authentication/groups_test.go
Currently, the filter busy-loops when pass on groups and pass on groups prefixes are configured.
This fixes it.
Further, this removes unnecessary allocation during iteration.
Finally this adds unit tests for the group filter.
/cc @sttts
> cmd/kcp-front-proxy/authentication/groups.go: fix groups filtering

- Makefile
This is useful if the source directory is synced via i.e. rsync or mutagen for development on remote machines and the sync mechanism omits `.git`.
/cc @sttts
> Makefile: be tolerant if local directory is not a git checkout

- pkg/authorization/toplevel_org_authorizer.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
We got some more places where a custom string was used.
> Use authorization.WorkspaceAcccessNotPermittedReason

- contrib/kcp.code-workspace
VSCode workspace configuration clneaup:
- Remove useless or obsolete launch configurations
- Use the e2e tests user tokens CSV file when starting the KCP server. 
Done when working on EPIC #1069
> VSCode: cleanup KCP launch configurations and use tokens

- .dockerignore
Fix image build by adding cmd/sharded-test-server to .dockerignore, as
we don't want to include it in the kcp image.
Fixes #1406
> Fix image build

- pkg/authorization/system_crd_authorizer.go
- pkg/server/options/authorization.go
Only core controllers should touch the status of APIBindings and APIExport.
Note: with #1316 this will be enough as these will be the only remaining system CRDs.
> authz: protect status subresource from non-system:masters

- pkg/indexers/indexers.go
- pkg/informer/informer.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/server/controllers.go
- pkg/server/server.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- Add global indexers for cluster- and namespace-scoped resources.
- Install these indexers by default into the shared informer factories
that need them (i.e. most of them).
- Make the dynamic discovery shared informer factory a field on Server to
prep for using it
- Remove IndexerFor method - require callers to get the informer, then
call .Informer().GetIndexer() (only had 1 caller).
- Remove gvrs field that was redundant - go by informers field instead.
- Move event handler configuration to where the informer is actually
created (informerForResourceLockHeld) because the upcoming quota monitor code
creates informers by calling InformerForResource (indirectly).
- Add Start(stopCh <-chan struct{}) function to support the way kube quota
starts newly created informers.
- Rename previous …
> Various dynamic discovery shared informer factory updates

- cmd/kcp/kcp.go
- cmd/syncer/cmd/syncer.go
This commit adds version to  syncer and kcp
commands.
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
Fixes #1380
> Fix: Add version for kcp and syncer

- cmd/sharded-test-server/main.go
- pkg/admission/finalizer/finalizer_admission.go
- pkg/admission/finalizer/finalizer_admission_test.go
- pkg/admission/reservedmetadata/admission_test.go
- pkg/server/options/authorization.go
- pkg/virtual/options/authorization.go
- pkg/virtual/workspaces/registry/rest.go
This cleans up the code base to refer to the underlying constant of `system:masters`.
Also it cleans up package usage in some places.
/cc @sttts @davidfestal
> cmd,pkg: use constant for system:master

- pkg/server/options/options.go
- test/e2e/watchcache/watchcache_enabled_test.go
In addition, it provides coverage of `DynamicDiscoverySharedInformerFactory` to prove it works when the cache is on
Fixes #
> brings back the watch cache

- Makefile
Check the the environment variables holding the Kubernetes version numbers are set. In case of the values missing abort the build process since it is likely the case that `jq` is not installed on the machine.
Fixes #1417
> Exit build process if Kubernetes version is missing

- test/e2e/virtual/apiexport/virtualworkspace_test.go
Wait after RBAC role creation.
> e2e/virtual/apiexport: fix authz flake

- pkg/syncer/syncer.go
Client requests without retries are dangerous. This one was even unnecessary.
> syncer: avoid fatal WorkloadCluster get

- config/root/namespace-default.yaml
- config/universal/default-namespace.yaml
This might have caused scheduling annotations and labels to be reset during e2e 🤦‍♂️ 
So innocent:
> config/universal: mark default ns create-only

- cmd/virtual-workspaces/command/cmd.go
- pkg/server/server.go
- test/e2e/watchcache/watchcache_enabled_test.go
~~How could that work before, ever?~~ Probably this still worked because https://github.com/kcp-dev/kcp/pull/1395 hasn't merged.
> e2e/watchcache: fix missing identity logic

- pkg/etcd/etcd.go
- pkg/server/options/embeddedetcd.go
- pkg/server/options/flags.go
- pkg/server/server.go
This PR extends the start options of kcp with one that can specify a list of URLs at which the embedded etcd server will listen for metrics scrapes. If secured, regular client credentials will be required.
This is a hopefully better alternative to #1431 .
I did not take on the task of introducing a Config struct in this PR, expecting it should go in a separate PR.
Fixes #1427
> Add kcp start options for embedded etcd server Prometheus scrape URLs

- pkg/etcd/etcd.go
- pkg/server/options/embeddedetcd.go
- pkg/server/options/flags.go
- pkg/server/server.go
Signed-off-by: Mike Spreitzer <mspreitz@us.ibm.com>
Add `kcp start` option to configure the embedded etcd server's `--quota-backend-bytes`.
Fixes #1426
> Add kcp start option --embedded-etcd-quota-backend-bytes

- cmd/kubectl-kcp/main.go
This commit adds --version flag for `kubectl-kcp`
https://github.com/kcp-dev/kcp/issues/1380
Fixes #1380
> Add --version flag for kubectl-kcp plugin

- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Introduce a way to go to the user Home workspace doing:
```
kubectl workspace '~'
```
This PR depends on PR #1373 which implements the feature on the KCP server side.
Part of the [User Home Workspaces EPIC](#1069)
> CLI: Support home workspace through `~`

- pkg/admission/clusterworkspaceshard/admission.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
Add `shard-base-url` flag to make the `BaseURL` default value configurable for `ClusterWorkspaceShards`
> Add shard-base-url flag to default clusterworkspaceshards

- config/crds/workload.kcp.dev_synctargets.yaml
- config/crds/workload.kcp.dev_synctargets.yaml-patch
- config/root-phase0/apiexport-workload.kcp.dev.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
- docs/syncer.md
- pkg/cliplugins/workload/cmd/cmd.go
- pkg/cliplugins/workload/plugin/sync.go
- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
- pkg/syncer/syncer.go
- test/e2e/framework/fixture.go
- test/e2e/syncer/syncer_test.go
- add mandatory `--output-file | -o` flag. It works with `-`.
- shorten default syncer namespace to `kcp-syncer-<synctarget>-<8-char-hash-of-uid>`, and reuse this as syncer ID for all resources. With this you can run multiple syncer in the same namespace.
- add `--namespace | -n` flag to customize syncer namespace
- document how to `kubectl apply -f -` directly:
```
$ kubectl kcp workload sync --help
Create a synctarget in kcp with service account and RBAC permissions. Output a manifest to deploy a syncer for the given sync target in a physical cluster.
Usage:
kcp workload sync <sync-target-name> --syncer-image <kcp-syncer-image> [--resources=<resource1>,<resource2>..] -o <output-file> [flags]
Examples:
kubectl kcp workload sync <sync-target-name> --syncer-image <kcp-syncer-image> -o …
```
> cli/workload/sync: improve usability

- cmd/syncer/options/options.go
- docs/locations-and-scheduling.md
- pkg/apis/workload/v1alpha1/helpers.go
- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
- pkg/reconciler/workload/namespace/namespace_reconcile_status_test.go
- pkg/reconciler/workload/resource/resource_controller.go
- pkg/reconciler/workload/resource/resource_reconcile.go
- pkg/reconciler/workload/resource/resource_reconcile_test.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/shared/helpers.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
- pkg/virtual/syncer/builder/build.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
As we need external coordinators to be able to use this API, this PR renames and makes public the workload state label:
- from: `InternalClusterResourceStateLabelPrefix: state.internal.workload.kcp.dev/<cluster-id>`
- to: `ClusterResourceStateLabelPrefix: state.workload.kcp.dev/<cluster-id>`
> API: Rename and make ClusterResourceStateLabelPrefix public

- cmd/syncer/cmd/syncer.go
- cmd/syncer/options/options.go
- pkg/cliplugins/workload/cmd/cmd.go
- pkg/cliplugins/workload/plugin/sync.go
- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
- test/e2e/framework/fixture.go
- Add `--qps` and `--burst` flags to the syncer and to the `kubectl kcp workload sync` command.
- Use --qps=-1 (no client-side throttling) for the syncer in e2e tests
Fixes #
> Syncer: add support for qps and burst

- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
the flag will be used to:
- create/update the correct ClusterWorkspaceShard 
- to have custom logic to setup the two informers and the merging, i.e. to know whether this is the root shard or the other one.
the default value of the flag is the `root` name.
Fixes #
> adds a shard-name flag for assigning a name to a shard instance

- pkg/apis/tenancy/projection/workspaces.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
We don't need the user info on a) ready workspaces b) on user-visible Workspaces.
> Wipe owner info as soon as possible

- cmd/sharded-test-server/main.go
- cmd/sharded-test-server/shard.go
This PR exposes a `number-of-shards` flag (e.g `. ./bin/sharded-test-server --number-of-shards=2`)  for specifying the number of shards to create. The first created is assumed root.
Fixes #
> sharded-test-server: allows for specifying the number of shards to create

- pkg/admission/reservedmetadata/admission.go
- pkg/apis/apis/v1alpha1/types.go
- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
- pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
Does not have anything to do with apis.kcp.dev/v1alpha1 in general.
> apis/workload: move workload.kcp.dev/skip-default-object-creation here from apis.kcp.dev/v1alpha1

- pkg/admission/reservedmetadata/admission.go
- pkg/apis/apis/v1alpha1/types.go
- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go
- pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go
- pkg/syncer/syncer.go
This PR makes the syncer AdvancedSchedulingFeature feature flag Annotation public and adds it to the admission allow list.
requires: https://github.com/kcp-dev/kcp/pull/1481
> Allows syncer feature gate annotation in reserved-metadata admission

- go.mod
- pkg/apis/go.mod
- pkg/apis/go.sum
Align the logicalcluster dependency in pkg/apis/go.mod with the main
go.mod.
Run 'go mod tidy' on both.
Fixes #
> pkg/apis: fix go mod

- pkg/proxy/mapping.go
The proxy has a stub readyz handler but not one for livez. This PR adds one for livez.
> Add stub livez handler in the proxy

- cmd/sharded-test-server/shard.go
- cmd/test-server/kcp/audit-policy.yaml
- cmd/test-server/kcp/shard.go
- cmd/test-server/main.go
- pkg/server/controllers.go
Enables us to 
- trace the whole life-cycle of every object. I.e. which state at which time, changed by which actor. Everything.
- identify hotlooping or just which component produces most load.
> test-servers: enable audit logs

- docs/locations-and-scheduling.md
Fixing a typo in the locations & scheduling .md doc.
s/matchins/matching
Fixes #
> Fix a typo s/matchins/matching

- pkg/admission/reservedmetadata/admission.go
The label doesn't exist anymore. No need to allow it.
> Remove non-existing scheduling-disabled label from ReservedMetadata allow list

- pkg/cliplugins/workload/plugin/sync.go
Fixes calculation of MaxSyncTargetNameLength. Currently MaxSyncTargetNameLength is 255, which is greater than DNS1123SubdomainMaxLength 253.
> cli/workload/sync: MaxSyncTargetNameLength decreased by SyncerIDPrefix length

- config/root/clusterrolebinding-apiresource-apiexport-bind.yaml
- config/root/clusterrolebinding-scheduling-apiexport-bind.yaml
- config/root/clusterrolebinding-tenancy-apiexport-bind.yaml
- config/root/clusterrolebinding-workload-apiexport-bind.yaml
Fix typos in APIExport bootstrapped `ClusterRoleBinding`s that prevented correct Authorization in some use-cases.
No related issue. This was met when working on issue https://github.com/kcp-dev/kcp/issues/1457
> Fix typos in APIExport bootstrapped `ClusterRoleBinding`s

- config/root/bootstrap.go
- config/root/clusterrole-clusterworkspace-home-get.yaml
- config/root/clusterrole-clusterworkspace-home-prefix-access.yaml
- config/root/clusterrolebinding-apiresource-apiexport-bind.yaml
- config/root/clusterrolebinding-clusterworkspace-home-get.yaml
- config/root/clusterrolebinding-clusterworkspace-home-prefix-access.yaml
- config/root/clusterrolebinding-scheduling-apiexport-bind.yaml
- config/root/clusterrolebinding-tenancy-apiexport-bind.yaml
- config/root/clusterrolebinding-workload-apiexport-bind.yaml
- config/root/clusterworkspace-homeroot-home-prefix.yaml
- pkg/server/options/flags.go
- pkg/server/options/homeworkspaces.go
- pkg/server/options/options.go
- pkg/server/server.go
- test/e2e/homeworkspaces/home_workspaces_test.go
Add KCP CLI arguments to enable home workspaces as well as specific options, especially the groups bound to the get/create ~ permissions
This PR is based on PR https://github.com/kcp-dev/kcp/pull/1540 (== first commit) 
Fixes #1457
> Add KCP CLI arguments to enable home workspaces as well as specific options, especially the groups bound to the get/create ~ permissions

- pkg/server/home_workspaces.go
- pkg/server/home_workspaces_test.go
- test/e2e/homeworkspaces/home_workspaces_test.go
Backport of https://github.com/kcp-dev/kcp/pull/1530
> [release-0.6] server/home: create home workspace with final URL on '~' access

- pkg/admission/clusterworkspaceshard/admission.go
- pkg/admission/clusterworkspaceshard/admission_test.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
kcp deployers optionally need to be able to set the URL external clients
use when connecting to kcp (e.g., via a front proxy). Add a new
--shard-external-url flag that is used as the default value for
ClusterWorkspaceShard.Spec.ExternalURL.
Fixes #
> server: add --shard-external-url

- pkg/informer/informer.go
> The function copy copies slice elements from a source src to a destination dst and returns the number of elements copied. The core types of both arguments must be slices with identical element type. The number of elements copied is the minimum of len(src) and len(dst).
> ddsif: fix lost event handlers

- config/crds/tenancy.kcp.dev_workspaces.yaml
- config/root-phase0/apiexport-tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml
- pkg/apis/tenancy/v1beta1/types.go
For command `kubectl get workspaces`, it is better (and feasible) to have a shortname like `kubectl get ws`. Checked existing resources via `kubectl api-resources | grep "\bw"`, no conflict found.
N/A
@sttts @pweil- , could you help check / tag? Thanks
> Add shortName ws for workspace

- pkg/informer/informer.go
- pkg/informer/informer_test.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/fixture.go
- test/e2e/watchcache/watchcache_enabled_test.go
Replace the polling mechanism that wouldn't scale as the number of
ClusterWorkspaces increased with one that is based on a fixed-set of
built-in types + a dynamic set of informers driven by all the unique
group-resources across all the CRDs in the system.
Fixes #1350
> ddsif: replace discovery polling

- Makefile
- pkg/admission/clusterworkspace/admission.go
- pkg/admission/clusterworkspace/admission_test.go
- pkg/admission/reservedmetadata/admission.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata_test.go
- pkg/server/home_workspaces.go
- pkg/server/home_workspaces_test.go
- pkg/softimpersonation/softimpersonation.go
- fix home workspace logic to conside the owner annotation as JSON, not just a string
- allow system master to pre-set the owner
- keep the owner username on a workspace when ready
- check the owner on GET `~`
> server/home: check owner properly

- pkg/syncer/shared/namespace.go
- pkg/syncer/shared/namespace_test.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
This PR renames the "path" field to "workspace". 
~~*This is a breaking change that will trigger a resync of all the resources*~~ It's compatible with old namespace locators.
> syncer/namespace-locator: Rename path to workspace

- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/kcp.go
- test/e2e/watchcache/watchcache_enabled_test.go
Disable client-side throttling in our e2e kcp server rest.Configs and in
the cross cluster list test, which uses discovery and is subject to
throttling.
Fixes #
> e2e: reduce client-side throttling

- pkg/server/options/flags.go
- pkg/server/options/options.go
the new flag holds a path to the Kubeconfig for the root kcp shard. It will be used by the other shards to communicate with the root shard. 
It paves the way for supporting multiple shards.
Fixes #
> kcp server: introduce root-shard-kubeconfig-file flag

- cmd/syncer/cmd/syncer.go
- cmd/syncer/options/options.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/status/status_controller.go
- pkg/syncer/syncer.go
- test/e2e/framework/fixture.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
Various refactors and improvements to logging messages
> Syncer:  Refactors KCPClusterName to SyncTargetWorkspace.

- docs/locations-and-scheduling.md
The "operation concerns" bit was clarified elsewhere by Stefan. 
Suggesting dropping the "kube conformance" bit because it probably needs further clarification so that it doesn't conflict with 
https://github.com/kcp-dev/kcp/blob/main/FAQ.md#will-kcp-be-able-to-pass-the-k8s-conformance-tests-in-cncf-conformance-suites
> docs: tweaks to the Location concept description

- pkg/server/handler.go
Currently all requests from bound service accounts get `/clusters/`
prepended to the path in the front proxy with a few exeptions.  None of
those exceptions are for `/services/` requests.
With `/services/` requests prepended with `/clusters/`, the front proxy will
then route them to the KCP container instead of the virtual workspace
server.  KCP will remove the `/clusters/` prefix, create the logical
cluster context, and then try to redirect the `/services/` request to the
virtual workspace server.
Rinse and repeat until the client gives up.
This fix is to stop prepending `/clusters/` on requests to the virtual
workspace server.
> Don't add /clusters/ prefix to /services/ requests

- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/kcp.go
- test/e2e/homeworkspaces/home_workspaces_test.go
- test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
- test/e2e/watchcache/watchcache_enabled_test.go
The deletion checks have to skip authorization because authz would lead to 403 on deleted workspaces, i.e. you cannot look into the logical cluster then. Hence, we need a `system:master` client. We have that wired for the root shard.
> e2e/clusterworkspacedeletion: use correct root shard system:master client for deletion checks

- pkg/reconciler/scheduling/location/location_controller.go
- pkg/reconciler/scheduling/location/location_reconcile.go
- pkg/reconciler/scheduling/placement/placement_controller.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go
- pkg/server/controllers.go
> Part 5: Wrap controllers in scheduling/tenancy pkgs

- pkg/apis/tenancy/v1alpha1/types.go
- pkg/server/server.go
the root workspace is only available on the root shard, this pr makes sure it will be only created on it.
Fixes #
> bootstrap the root workspace only on the root shard

- pkg/informer/informer.go
- pkg/informer/informer_test.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/fixture.go
- test/e2e/watchcache/watchcache_enabled_test.go
Backport of #1473.
Replace the polling mechanism that wouldn't scale as the number of
ClusterWorkspaces increased with one that is based on a fixed-set of
built-in types + a dynamic set of informers driven by all the unique
group-resources across all the CRDs in the system.
> 0.6: ddsif: replace discovery polling

- pkg/etcd/etcd.go
- pkg/server/server.go
it defines the interval for etcd watch progress notify events.
note:
- gcp, ocp and upstream k8s set it to 5s, so we simply follow suit
- in practice this value never changes so we are not exposing it as a flag/option
- we enable it only when the watch cache is on, otherwise it might not scale,
sending an event every 5s to thousands of clients
Fixes #
> enable ExperimentalWatchProgressNotifyInterval for etcd

- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
if no specific shard was required, we are going to schedule the given ws onto the root shard.
this step is temporary until working with multi-shard env works,
until then we need to assign ws to the root shard otherwise all e2e test will break.
Fixes #
> clusterworkspace scheduling: default to assigning to the root shard

- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
- test/e2e/framework/fixture.go
> cli/sync: create service account secret in advance to trigger token creation

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/server/controllers.go
- pkg/server/server.go
it enables non-root shards to read APIExports and APISchemas from the root shard so that they can create the root APIs for:
`"shards.tenancy.kcp.dev", "tenancy.kcp.dev", "scheduling.kcp.dev", "workload.kcp.dev", "apiresource.kcp.dev"`
Fixes #
> apibinding controller with root shard informers

- docs/workspaces.md
Per https://kubernetes.slack.com/archives/C021U8WSAFK/p1658217760034109
> Documentation: Add Home, Homebucket, and Homeroot workspace info

- pkg/logging/constants.go
- pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go
Example output:
```
clusterworkspaceshard_controller.go:99] "Starting controller" reconciler="clusterworkspaceshard"
clusterworkspaceshard_controller.go:88] "queueing workspace shard" reconciler="clusterworkspaceshard" key="root|root"
clusterworkspaceshard_controller.go:125] "processing key" reconciler="clusterworkspaceshard" key="root|root"
clusterworkspaceshard_controller.go:197] "processed ClusterWorkspaceShard" reconciler="clusterworkspaceshard" key="root|root" workspace="root" namespace="" name="root"
clusterworkspaceshard_controller.go:88] "queueing workspace shard" reconciler="clusterworkspaceshard" key="root|root"
clusterworkspaceshard_controller.go:125] "processing key" reconciler="clusterworkspaceshard" key="root|root" …
```
> logging: move clusterworkspaceshard reconciler to structured logging

- pkg/server/home_workspaces.go
When a user tries to create content in the home workspace hierarchy, if
the ancestor clusterworkspaces are slow to bootstrap and/or the
apibindings are slow to become ready, there is a chance that the logic
that tries to create intermediate home buckets might get a 404 because
the apibinding for tenancy.kcp.dev isn't ready yet.
Handle a 404 and instruct the client to retry.
Fixes #1626
> home workspaces: handle slow bootstrapping

- pkg/apis/workload/v1alpha1/types.go
- pkg/reconciler/workload/namespace/namespace_controller.go
- pkg/reconciler/workload/namespace/namespace_reconcile.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
- pkg/reconciler/workload/placement/placement_controller.go
- pkg/reconciler/workload/placement/placement_indexes.go
- pkg/reconciler/workload/placement/placement_reconcile.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
- pkg/server/controllers.go
- pkg/server/server.go
1. add a internal annotation for placement to
schedule synctarget
2. ns controller only update sync label by collecting
the annotation result from the placements
Fixes #
> Refactor ns scheduler for location workspace

- contrib/demos-unmaintained/demo/clusters/kind/createKindClusters.sh
Allow using the `CreateKindClusters.sh` script without  `podman`, even though podman is installed on the system (for example on linux boxes where you have both `docker` and `podman`)
> Enable avoiding using podman

- pkg/server/config.go
- pkg/server/server.go
Move `Config`, `CompletedConfig` and the related parts from `server.go` to `config.go`
No code change, just file split to make it easier to consume and reason about. As discussed with @sttts
> move Config to separate file

- test/e2e/fixtures/apifixtures/sheriffs.go
Towards no global fixture libraries with helper inflation.
> e2e: reduce global, trivial Sheriff fixture

- pkg/cliplugins/workspace/cmd/cmd.go
Removes the deprecated 'list' command from the kubectl kcp ws help.
Fixes #1580
> remove deprecated command from use description

- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/options/options.go
- pkg/virtual/framework/authorization/authorizer.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/options/options.go
- pkg/virtual/options/authorization.go
- pkg/virtual/options/options.go
- pkg/virtual/syncer/options/options.go
- pkg/virtual/workspaces/options/options.go
To allow shadowing one VW another, e.g. a by-default APIBinding VW shadowed by a PermissionClaim VW: if the user does not claim APIBindings, just the bindings for their own exports are visible. But through a claim all bindings in those workspaces become visible. This needs an order of VW layers.
> virtual: give VWs an order in order to control precedence

- .gitignore
- CONTRIBUTING.md
* Updates minimum Go version in CONTRIBUTING.md doc to 1.18
* Adds Jetbrains IDE files to gitignore
Fixes #1650
> Update minimum Go version in CONTRIBUTING.md doc to 1.18

- cmd/sharded-test-server/shard.go
- pkg/server/bootstrap/identity.go
- pkg/server/config.go
- pkg/server/server.go
wires TemporaryRootShardKcpSharedInformerFactory, essentially when c.Options.Extra.RootShardKubeconfigFile is set then:
- we start a new SharedInformerFactory for the root shard
- we create a KcpClusterClient to the root shard
- we registerer a new shard in the root namespace
Fixes #
> wire TemporaryRootShardKcpSharedInformerFactory

- pkg/syncer/shared/finalizer.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
This PR fixes some corner cases or behaviors in the Syncer that would not be compatible with the Syncer Virtual Workspace transformations. More precisely:
- We now [stop reconciling just after adding the Syncer Finalizer](https://github.com/kcp-dev/kcp/pull/1629/commits/af19673c45f1c7e668162919791620d025843f14). The Update of the upstream resource with the syncer finalizer will trigger a new reconcile round anyway. We should avoid updating both the upstream resource and the downstream resource, and thus combine distinct purposes in the same reconciliation round.
- [Don't add the syncer finalizer to a resource already marked for deletion](https://github.com/kcp-dev/kcp/pull/1629/commits/14c391941f063640f48a0350d5b338d905092b93). This will lead to some sort of hot-looping with the VW logic …
> Cleanup Syncer to prepare for Syncer Virtual Workspace transformations

- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
Simpler to normalize in the decoding flow rather than in the logic.
> syncer: move namespace locator normalization to indexer

- Makefile
```
make test-e2e-shared WAIT=1
```
will pause after the tests for inspection. Also works with `make test-e2e-sharded`.
> Makefile: allow WAIT=1 to keep server running in test-e2e-{sharded,shared} targets

- go.mod
- pkg/apis/workload/v1alpha1/helpers.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go
- pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling.go
- pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
- pkg/syncer/shared/finalizer.go
- pkg/syncer/spec/spec_controller.go
- pkg/syncer/spec/spec_process.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_controller.go
- pkg/syncer/status/status_process.go
- pkg/syncer/status/status_process_test.go
- pkg/syncer/syncer.go
- pkg/virtual/syncer/builder/build.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_controller.go
- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/ingress/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/reconciler/scheduling/controller_test.go
- test/e2e/reconciler/scheduling/multi_placements_test.go
- test/e2e/reconciler/scheduling/placement_scheduler_test.go
- test/e2e/syncer/syncer_test.go
This PR improves the uniqueness of the labels/annotations/finalizers that rely currently on the SyncTarget Name by replacing it with a hash generated from the SyncTarget Name + SyncTarget workspace.
* Introduces a new helper in `workloadv1alpha1`: `ToSyncTargetKey(syncTargetName, syncTargetWorkspace)`
* Replaces all usages of SyncTarget Name in labels/annotations/finalizers
> SyncTarget Uniqueness

- pkg/apis/workload/v1alpha1/types.go
The value of `InternalSyncTargetPlacementAnnotationKey` is not `{location workspace}/{syncTarget name}` anymore. 
Now the API expects the hash generated by the ToSyncTargetKey(..) helper func.
> apis/workload/v1alpha1: Fix comment as the value of InternalSyncTargetPlacementAnnotationKey changed

- config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml
- config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml
- pkg/apis/tenancy/v1alpha1/types.go
- pkg/openapi/zz_generated.openapi.go
VirtualWorkspaceURL is the address of the virtual workspace server associated with this shard.
It can be a direct address, an address of a front-proxy or even an address of an LB.
As of today this address is assigned to APIExports.
This will be defaulted to the shard's base address if not specified.
Fixes #
> api change: adds VirtualWorkspaceURL to ClusterWorkspaceShard

- config/root/bootstrap.go
- config/root/clusterworkspaceshard.yaml
- pkg/admission/clusterworkspaceshard/admission.go
- pkg/admission/clusterworkspaceshard/admission_test.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
this PR:
- exposes the new field as `shard-virtual-workspace-url` flag.
when set points to an external URL address of a virtual workspace server
associated with as shard.
- updates the admission plugin so that it defaults the new field to the shard's base address.
Fixes #
> use ClusterWorkspaceShard.VirtualWorkspaceURL

- pkg/reconciler/apis/apiexport/apiexport_reconcile.go
- test/e2e/apibinding/apibinding_test.go
updates the apiexport controller to assign `ClusterWorkspaceShard.VirtualWorkspaceURL` to `APIExports`
Fixes #
> apiexport controller: assigns ClusterWorkspaceShard.VirtualWorkspaceURL

- Makefile
- test/e2e/virtual/apiexport/virtualworkspace_test.go
> runs e2e-sharded with two shards

- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/conformance/webhook_test.go
- test/e2e/fixtures/wildwest/bootstrap.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- test/e2e/watchcache/watchcache_enabled_test.go
To verify if e2e tests pass in CI
Fixes #
> Part 10: scope cross_logical_cluster tests

- config/root/clusterrolebinding-tenancy-workspace-reader.yaml
- pkg/authorization/bootstrap/policy.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
We should only skip permission checking in the `root` workspace for the `list` verb, so that any user can always list the workspaces he has `access` to and can `get`.
No issues
> VW: Fix permission checking in `root`

- cmd/syncer/cmd/syncer.go
- cmd/syncer/options/options.go
- pkg/cliplugins/workload/plugin/sync.go
- pkg/cliplugins/workload/plugin/sync_test.go
- pkg/cliplugins/workload/plugin/syncer.yaml
- pkg/reconciler/workload/synctarget/synctarget_reconcile.go
- pkg/syncer/syncer.go
- pkg/virtual/syncer/builder/build.go
- test/e2e/framework/syncer.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
The changes in this PR are focused on avoiding a Syncer running with an old SyncTarget, this is accomplished by:
- Syncer: 
- New flag for providing the expected sync target UID: `--sync-target-uid`
- When starting will check that the provided UID matches the existing sync target UID, if not, fail to start
- When patching a sync target status for setting the heartbeat, tries to match the expected sync target UID, if not, refuses to patch 
- KCP Kubectl plugin: The generated manifests include the sync target UID flag.
- SyncTarget controller: Appends the desired sync target UID to the VirtualWorkspace URLs.
- Syncer VirtualWorkspace: validates that the sync target name and UID in the request 
match.
related to: https://github.com/kcp-dev/kcp/issues/1679
> Syncer: refuse to work on sync target UID discrepancy.

- Makefile
Let's see how much (if at all) faster this is.
> Makefile: set UNSAFE_E2E_HACK_DISABLE_ETCD_FSYNC=true in all e2e tests

- contrib/demos-unmaintained/demo/prototype2-script/user-rbac.yaml
- docs/authorization.md
- pkg/authorization/toplevel_org_authorizer.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
It was being removed from virtual workspace handling hence unused.
https://github.com/kcp-dev/kcp/pull/1685
> *: remove member verb

- pkg/virtual/syncer/builder/build.go
Fixes wrong order in a comment.
follow-up: https://github.com/kcp-dev/kcp/pull/1687
> pkg/virtual/syncer/builder: fix incorrect comment

- cmd/kcp/kcp.go
- config/helpers/bootstrap.go
- config/homebucket/bootstrap.go
- config/homeroot/bootstrap.go
- config/root-phase0/bootstrap.go
- config/root/bootstrap.go
- config/root/clusterworkspacetype-organization.yaml
- config/root/clusterworkspacetype-root.yaml
- config/root/clusterworkspacetype-team.yaml
- config/system-crds/bootstrap.go
- config/universal/bootstrap.go
- pkg/authorization/bootstrap/policy.go
- pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
- pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
- pkg/server/config.go
- pkg/server/controllers.go
- pkg/server/options/authentication.go
- pkg/server/options/batteries/batteries.go
- pkg/server/options/flags.go
- pkg/server/options/options.go
- pkg/server/server.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/apibinding/apibinding_deletion_test.go
- test/e2e/apibinding/apibinding_permissionclaims_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/apibinding/apibinding_webhook_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/customresourcedefinition/customresourcedefinition_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
This adds a mechanism that allows to have certain defaults when running `kcp start`, but gives system integrators a way to disable the "integrated batteries". Canonical example: organization and team cluster workspace types. These were always just meant as examples, nothing set in stone for a service offering.
```
Start the control plane process
The server process listens on port 6443 and will act like a Kubernetes API server. It will initialize any necessary data to the provided start location or as a '.kcp' directory in the current directory. An admin kubeconfig file will be generated at initialization time that may be used to access the control plane.
Usage:
kcp start [flags]
Most important flags:
--batteries-included strings
A list of batteries included (= default objects that might …
```
> Add --batteries-included

- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
Signed-off-by: Robin Y Bobbitt <rbobbitt@redhat.com>
Exclude authentication.k8s.io and authorization.k8s.io from list of claimable APIs.
Fixes #1697
> exclude authn/authz apis from claimable list

- pkg/logging/constants.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibinding/apibinding_reconcile.go
- pkg/reconciler/apis/apiexport/apiexport_reconcile.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go
Part of #1694 
/assign @sttts 
Using the resource instead of the kind would be cool but I don't know that there's any lightweight way to figure that out.
> logging: use kind-prefixed fields instead of string-formatting

- pkg/syncer/status/status_process.go
Small fix to a log line: it looks like `klog.InfoS` was used instead of `klog.Infof` accidentally.
Currently it prints something like this:
```
"Downstream GVR %q object %s|%s/%s does not exist. Removing finalizer upstream" apps/v1, Resource=deployments="" default="test-deployment"
```
> Fixes log line formatting

- pkg/server/config.go
- pkg/server/handler.go
- pkg/server/options/flags.go
- pkg/server/options/virtual.go
- pkg/server/server.go
- pkg/server/virtual.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Remove the redirect from shard to virtual workspaces in case of standalone virtual workspace deployment.
Npw that the old "personal workspaces" feature has been removed from both the `workspaces` virtual workspace and the CLI, there's no need to point to virtual workspaces through the KCP server host.
In the future explicit virtual workspace Base URL (carried by the Shard resource) should be used.
So when a virtual workspace is started in standalone mode, there's no need anymore to setup a redirection from the KCP shard host to the virtual workspace host.
This is a followup of PR https://github.com/kcp-dev/kcp/pull/1685
> Remove the redirect from shard to virtual workspaces

- .github/workflows/ci.yaml
- .github/workflows/goreleaser.yml
- .goreleaser.yaml
- Makefile
This will upload tar.gzs for `kcp` and `kubectl-kcp-plugin` as artifacts, and in case of tags it will create a release if not pre-existing, but not publish it. If it is preexisting it will attach the tars.
> Add goreleaser

- .github/workflows/goreleaser.yml
Our token is restricted. So we have to ask for content write.
> goreleaser: add write permissions to GITHUB_TOKEN

- pkg/logging/constants.go
- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/apis/apiexport/apiexport_reconcile.go
- pkg/reconciler/apis/apiexport/crypto.go
- pkg/reconciler/kubequota/kubequota_controller.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go
- pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
- pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go
- pkg/reconciler/workload/placement/placement_reconcile.go
logging: format Kind better when none is present
---
logging: stop using formatted strings for object identifiers
---
Part of #1694 
/assign @sttts @ncdc
> logging: stop using formatted strings for object identifiers

- .github/workflows/kcp-image.yaml
- .github/workflows/kcp-test-image.yaml
- .github/workflows/syncer-image.yaml
- Dockerfile
- Makefile
- hack/verify-go-versions.sh
So many places where we reference a go version.
Check that the build go version matches.
> hack: verify-go-version.sh in all the repo

- pkg/cliplugins/workspace/plugin/kubeconfig.go
- pkg/cliplugins/workspace/plugin/kubeconfig_test.go
- pkg/virtual/workspaces/registry/rest.go
- pkg/virtual/workspaces/registry/rest_test.go
The former GET request meant that a user needs both `verb=access` access for the target workspace *and* the parent workspace. That was never intended. With this PR we just check discovery inside of the target workspace.
Note the TODO in the PR:
```
In both the cases of `root` and absolute paths here we assume that the current cluster client
is talking to the right external URL. This obviously not guaranteed, and hence we
silently assume that the front-proxy will route to every workspace.
We might want to add permanent redirections to the front-proxy if the external
URL does not match the workspace's shard, and then add redirect support here to
use the right front-proxy URL in the kubeonfig.
```
> cli/workspace: don't get Workspace in parent on absolute use, but check inside the workspace

- pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
virtual/syncer: compare values, not pointers
Comparing the interface header is not always correct. Compare the UID
and SchemaIdentityHash to be certain we're doing the right thing.
---
virtual/syncer: only handle the kubernetes export
---
/assign @sttts @ncdc 
Fixes #1742
> syncer: handle only the k8s export

- pkg/admission/permissionclaims/mutating_permission_claims.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
Extracted from https://github.com/kcp-dev/kcp/pull/1563/commits.
> Permission claim fixes / cleanups

- test/e2e/fixtures/apifixtures/sheriffs.go
- test/e2e/quota/quota_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
> Part 15: Scope clients in test/e2e/fixtures

- cmd/kcp-front-proxy/main.go
- cmd/virtual-workspaces/command/cmd.go
- config/shard/bootstrap.go
- pkg/server/bootstrap/api-export-identity_controller.go
- pkg/server/bootstrap/identity.go
- pkg/server/config.go
- pkg/server/server.go
the config map is maintained by a controller and contains identities for the root API Exports.
the config map is used by non-root shards and provides higher fault tolerance than reading directly from the root shard.
if the config map doesn't exist or there were some errors during getting it we always fall back to the previous behavior of getting identities from exports directly.
xref: see item `1. add identities configmap in system:shard` from  https://github.com/kcp-dev/kcp/issues/1225
> the identity provider gets data from a local cm too

- .goreleaser.yaml
This PR is to add official ppc64le support to kcp binaries. I have tested the binaries built for ppc64le locally and it works as expected. @ncdc @sttts can you please review this?
Issue: https://github.com/kcp-dev/kcp/issues/968
> Add ppc64le support

- docs/syncer.md
This is missing some basic instructions how to deploy some workload using the syncer.
/cc @sttts @ncdc @stevekuznetsov
> docs/syncer.md: add missing instructions

- pkg/crdpuller/discovery.go
Hard-code defaults for known fields appearing in `x-kubernetes-list-map-keys`.
After auditing https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json, it seems that only one field needs to be patched. The other occurrences are required.
This is a partial fix for #498
> Generate CRD defaults for known types

- pkg/indexers/apiexport.go
- pkg/indexers/indexers.go
- pkg/indexers/util.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Move the definition of APIExport index functions needed across multiple controllers to pkg/indexers
Fixes #1752
> Start centralizing APIExport indexers

- pkg/reconciler/apis/apibinding/apibinding_controller.go
- pkg/reconciler/apis/apiexport/apiexport_controller.go
- pkg/reconciler/committer/committer.go
- pkg/reconciler/postreconcile/postreconcile.go
Unify post-reconcile spec and status updating logic in a type safe way. The `APIBinding` and `APIExport` controllers are updated as examples.
> Generic helper for consistent post-reconcile spec and status updates

- config/shard/bootstrap.go
- config/shard/default-namespace.yaml
- pkg/server/server.go
the ns is required to store the apiexport-identity-cache config map
Fixes #
> bootstrap: create the default ns in the system:shard ws

- .github/workflows/ci-docs-only.yaml
- .github/workflows/ci.yaml
No need to run e2e-shared-server or e2e-sharded if we change .goreleaser.yaml.
Fixes #
> Ignore .goreleaser.yaml in GH CI

- Makefile
- cmd/sharded-test-server/frontproxy.go
- cmd/sharded-test-server/third_party/library-go/crypto/crypto.go
- pkg/authorization/apibinding_authorizer.go
- pkg/crdpuller/discovery.go
- pkg/localenvoy/controlplane/controlplane.go
- pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go
- pkg/reconciler/workload/apiexport/apiresourceschema.go
- pkg/reconciler/workload/deploymentsplitter/deploymentsplitter_reconcile.go
- pkg/server/options/options.go
- pkg/syncer/spec/spec_process_test.go
- pkg/syncer/status/status_process_test.go
- pkg/virtual/framework/authorization/authorizer.go
- pkg/virtual/framework/fixedgvs/apiserver/apiserver.go
- pkg/virtual/framework/forwardingregistry/rest_test.go
- test/e2e/conformance/cross_logical_cluster_list_test.go
- test/e2e/framework/config.go
- test/e2e/framework/syncer.go
- test/e2e/reconciler/clusterworkspace/controller_test.go
- test/e2e/syncer/syncer_test.go
Follow up of https://github.com/kcp-dev/kcp/pull/1772
> Introduce staticcheck linter for deprecations

- pkg/informer/informer.go
Don't inform on v1beta1 Workspaces as these are a projection from
v1alpha1 ClusterWorkspaces, and it breaks in a topology where the
virtual-workspaces server is standalone.
Fixes #1654
> ddsif: exclude v1beta1 Workspaces

- cmd/cache-server/main.go
- pkg/cache/server/config.go
- pkg/cache/server/options/options.go
- pkg/cache/server/server.go
Allows for starting empty `apiextentions server` on port 6443. It runs with the embedded etcd. 
As of today, it has disabled `authN/Z` stack which needs to be restored in the future.
The server can be started with `go run ./cmd/cache-server/main.go` which produces:
```
I0822 12:03:17.366752   76028 server.go:44] Starting embedded etcd server
{"level":"warn","ts":"2022-08-22T12:03:17.580+0200","caller":"etcdserver/metrics.go:224","msg":"failed to get file descriptor usage","error":"cannot get FDUsage on darwin"}
W0822 12:03:17.642213   76028 authentication.go:47] Authentication is disabled
W0822 12:03:17.744823   76028 genericapiserver.go:590] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
I0822 12:03:17.749135   76028 dynamic_serving_content.go:132] "Starting …
```
> cache-server: starts empty apiextentions-server

- cmd/cluster-controller/main.go
- go.mod
- go.sum
- pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go
- pkg/server/controllers.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/apibinding/apibinding_deletion_test.go
- test/e2e/apibinding/apibinding_permissionclaims_test.go
- test/e2e/apibinding/apibinding_protected_test.go
- test/e2e/apibinding/apibinding_test.go
- test/e2e/apibinding/apibinding_webhook_test.go
- test/e2e/conformance/metadata_test.go
- test/e2e/framework/kcp.go
- test/e2e/reconciler/cluster/controller_test.go
- test/e2e/reconciler/clusterworkspace/controller_test.go
- test/e2e/reconciler/clusterworkspaceshard/controller_test.go
- test/e2e/reconciler/namespace/controller_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
- test/e2e/virtual/syncer/virtualworkspace_test.go
- test/e2e/watchcache/watchcache_enabled_test.go
adding a user agent changes the original config, which might be used by other clients.
Fixes #
> controllers: avoid double copy of the rest config

- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/clusterworkspacetypeexists/admission.go
- pkg/admission/initializers/initializer.go
- pkg/admission/initializers/interfaces.go
- pkg/authorization/deep_sar.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
- pkg/authorization/workspace_content_authorizer_test.go
- pkg/server/config.go
- test/e2e/apibinding/apibinding_authorizer_test.go
- test/e2e/authorizer/authorizer_test.go
- test/e2e/authorizer/org-resources.yaml
- test/e2e/authorizer/workspace1-resources.yaml
- test/e2e/virtual/apiexport/virtualworkspace_test.go
- test/e2e/workspacetype/controller_test.go
This is a follow-up for #1680
TODOs:
/cc @sttts
> authorization: add system:masters-only deep SAR via X-Kcp-Internal-Deep-SubjectAccessReview header

- config/crds/bootstrap.go
- pkg/cache/server/bootstrap/bootstrap.go
- pkg/cache/server/config.go
- pkg/cache/server/crd_lister.go
- pkg/cache/server/server.go
- pkg/server/controllers.go
- pkg/server/server.go
- pkg/util/util.go
exposes schema-less `apiresourceschemas` and `apiexports` resources. It allows us to store any fields we need. Since this server will be used by the shards, schemas will be implicit.
I did the following manual test which indicates storing `"foo": "bar"` with an `apiexport` obj works. 
POST:
```
curl -k -X POST 'https://localhost:6443/apis/apis.kcp.dev/v1alpha1/apiexports' -H 'Content-Type: application/json' -d '{"apiVersion":"apis.kcp.dev/v1alpha1","kind":"APIExport","metadata":{"name":"ab"},"foo":"bar"}'
```
GET:
```
curl -k 'https://localhost:6443/apis/apis.kcp.dev/v1alpha1/apiexports/ab'
{
"apiVersion": "apis.kcp.dev/v1alpha1",
"foo": "bar",
"kind": "APIExport",
"metadata": {
"annotations": {
"kcp.dev/cluster": "system:admin"
},
"creationTimestamp": "2022-08-24T08:50:09Z", …
```
> cache-server: expose apiresourceschemas and apiexports

- pkg/cache/server/config.go
It changes the storage prefix under which all resources are kept.
This allows us to store the same GR under a different
prefix than the kcp server (`/registry`).
It is useful when this server shares the database with a kcp instance.
It boils down to the following on the storage level:
for listing across shard:  `/cache/<group>/<resource>:<identity>/*`
for listing for one shard: `/cache/<group>/<resource>:<identity>/<shard>/*`
Fixes #
> cache-server: set the storage prefix  to /cache

- pkg/informer/informer.go
- pkg/projection/projected_apis.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
Skip attempting to delete projected resources in the APIBinding and
Workspace Resource Deletors. These projected resources will
automatically go away when their underlying resources are deleted.
Fixes #
> deletors: skip projected resources

- test/e2e/framework/config.go
- test/e2e/framework/syncer.go
- test/e2e/framework/util.go
- test/e2e/reconciler/ingress/controller_test.go
If we need to track down e.g. the etcd WALs in the future based on
tests, we can think about this more.
/cc @ncdc
> e2e: save data in some temporary directory

- pkg/informer/informer.go
- pkg/projection/projected_apis.go
- pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go
- pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go
Skip attempting to delete projected resources in the APIBinding and
Workspace Resource Deletors. These projected resources will
automatically go away when their underlying resources are deleted.
(cherry picked from commit 6d3c78a2234b922d75a2c5e121e6b9d8037d0761)
Backport of #1860
/approve
> [release-0.7] deletors: skip projected resources

- pkg/authorization/apibinding_authorizer.go
- pkg/authorization/bootstrap_policy_authorizer.go
- pkg/authorization/decision.go
- pkg/authorization/local_authorizer.go
- pkg/authorization/system_crd_authorizer.go
- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
This adds audit logs for remaining authorizers.
Fixes #1307
> pkg/authorization: add audit logging

- cmd/sharded-test-server/virtual.go
Logs the full command line with parameters before starting virtual workspaces in sharded-test-server.
Fixes #1858
> sharded-test-server: log the full command line with parameters

- pkg/server/home_workspaces.go
- test/e2e/homeworkspaces/home_workspaces_test.go
If the incoming request is in the home workspaces hierarchy and it's for `clusterworkspaces`, there is a chance the tenancy APIBinding is not yet ready (or the cache is stale). If that is the case, return a retry-after to give the APIBinding cache a
chance to catch up.
Fixes #1693
> home-ws: wait for tenancy binding readiness

- pkg/cache/client/context.go
- pkg/cache/client/round_tripper.go
- pkg/cache/client/round_tripper_test.go
- pkg/cache/client/shard/shard.go
`WithDefaultShardRoundTripper` for setting a default shard in the context.
`WithShardRoundTripper` for changing the URL path to contain a shard name defined in the context.
`WithShardInContext` and `ShardFromContext` for writting/reading a shard name to/from the context.
A shard package for holding a shard name in the memory.
Fixes #
> cache-server: provides client-related functionality for dealing with a shard on the HTTP level

- pkg/cliplugins/workspace/cmd/cmd.go
As sub-commands like create/create-context required additional details about workspace, whereas rest of the commands did not. So, the usage section `workspace [create|create-context|<workspace>|..|.|-|~|<root:absolute:workspace>] [flags]` might lead to a confusion as some sub-commands aren't specified. Modified the usage section as below, using the generic keywords:
`Usage:
workspace [command] [flags]
workspace [command]
` 
Considered keeping (workspace [command]) for commands like `use`.
Let me know, if we should only keep `workspace [command] [flags]` instead of both the statements.
Fixes #1579
> modified cmd.Use for kubectl-workspaces

- Makefile
- hack/verify-contextual-logging.sh
The script alone does not find logcheck if it is not in the path. So, let's add a Makefile target that uses the tool download logic.
> Makefile: add update-contextual-logging

- pkg/server/handler.go
- pkg/virtual/framework/rootapiserver/root_apiserver.go
Generally, the RawPath is only available when some chars have been encoded. The Path always fully expands the URL.
Since we trim the Path, naturally we would like also to trim the RawPath. To do that correctly we would have to consider encoded slash char as well (%2F).
For example the code breaks on %2Fclusters%2F*/apis/apis.kcp.dev/v1alpha1/apiexports
Because we don't really need to deal with encoded chars and we don't use the RawPath only the Path we could simplify.
This PR simply recomputes the URL after trimming and overwrites it in the HTTP requests.
Fixes #
> KCP: stop messing with the RawPath

- pkg/cache/server/config.go
- pkg/cache/server/handler.go
- pkg/cache/server/options/options.go
The filter reads a shard name from the URL path and puts it into the context.
It also trims `/shards/` prefix from the URL. 
So that the next filter in the chain doesn't have to deal with `/shards/` prefix.
If the path doesn't contain the shard name then a default "cache" name is assigned.
For example:
`/shards/amber/apis/apis.kcp.dev/v1alpha1/apiexports` assigns `amber`
`/shards/*/apis/apis.kcp.dev/v1alpha1/apiexports` assigns `*`
`/shards/amber/clusters/system:admin/apis/apis.kcp.dev/v1alpha1/apiexports` also assigns `amber`
Tested manually with
PUT:
```
curl -k -X POST 'https://localhost:6443/shards/amber/clusters/system:amber/apis/apis.kcp.dev/v1alpha1/apiexports' -H 'Content-Type: application/json' -d '{"apiVersion":"apis.kcp.dev/v1alpha1","kind":"APIExport","metadata":{"name":"ab"}," …
```
> cache-server: adds WithShardScope HTTP filter

- pkg/virtual/framework/forwardingregistry/rest_test.go
- pkg/virtual/framework/forwardingregistry/store.go
- pkg/virtual/framework/forwardingregistry/store_test.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
This PR switches update operations made to the virtual workspace API server, to calling create operations on the forwarding API server, for non-existent objects. This enables support for server-side apply patch requests in that case.
Fixes #1852
> virtual: Support SSA patch requests for non-existent objects

- config/crds/bootstrap.go
- hack/logcheck.out
- pkg/admission/apibinding/apibinding_admission.go
- pkg/admission/apibinding/apibinding_admission_test.go
- pkg/admission/permissionclaims/mutating_permission_claims.go
- pkg/apis/apis/v1alpha1/permissionclaims/labels.go
- pkg/apis/apis/v1alpha1/types_apibinding.go
- pkg/permissionclaim/permissionclaim_labeler.go
- pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_reconcile.go
- pkg/virtual/apiexport/builder/build.go
- pkg/virtual/apiexport/builder/forwarding.go
- pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
- pkg/virtual/apiexport/schemas/apis.go
- pkg/virtual/framework/forwardingregistry/rest.go
- pkg/virtual/initializingworkspaces/builder/build.go
- pkg/virtual/initializingworkspaces/builder/forwarding.go
- test/e2e/virtual/apiexport/virtualworkspace_test.go
- test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
Virtual workspaces should make the defining objects of workspaces visible. For APIExports, this is the APIBindings, for initializing workspace this would be the Workspace.
This PR adds the APIBindings (both wildcard requests and normal requests) to the APIExport VW.
It does that by adding a "reflexive claim label" to APIBindings marking the binding visible for the corresponding APIExport. The APIExport VW then can filter via a "IN" label selector, matching either the reflexive label or a real claim label:
```golang
// ToReflexiveAPIBindingLabelKeyAndValue returns label key and value that is set (as fallback for filtering)
// on APIBindings that point to the given APIExport and the binding has not accepted a claim to it.
func ToReflexiveAPIBindingLabelKeyAndValue(exportClusterName …
```
> virtual/apiexport: serve wildcard apibindings

- docs/syncer.md
* Updates instructions on how to enable a syncer on a physical cluster.
* Updates development guide on how to build a syncer image and run syncer in a kind cluster with a local registry.
* Adds a guide on how to run a syncer locally for development.
> Syncer docs: adds a guide on running the syncer locally and updates slightly outdated doc

- go.mod
- go.sum
Important performance bug on CRDs that use ` x-kubernetes-preserve-unknown-fields: true`
```
grep -r preserve-unk config/
config/crds/apiresource.kcp.dev_apiresourceimports.yaml:                x-kubernetes-preserve-unknown-fields: true
config/crds/apiresource.kcp.dev_negotiatedapiresources.yaml:                x-kubernetes-preserve-unknown-fields: true
config/crds/apis.kcp.dev_apiresourceschemas.yaml:                      x-kubernetes-preserve-unknown-fields: true
config/root-phase0/apiresourceschema-apiresourceimports.apiresource.kcp.dev.yaml:              x-kubernetes-preserve-unknown-fields: true
config/root-phase0/apiresourceschema-negotiatedapiresources.apiresource.kcp.dev.yaml:              x-kubernetes-preserve-unknown-fields: true
```
xref: …
> bump strategic-merge-diff to 4.2.3

- pkg/authorization/toplevel_org_authorizer.go
- pkg/authorization/workspace_content_authorizer.go
- pkg/virtual/workspaces/builder/build.go
- pkg/virtual/workspaces/registry/rest.go
- test/e2e/virtual/workspaces/virtual_workspace_test.go
Admins or users in their home workspace can see all workspaces. Filtering is not necessary, and until GC is implemented (see https://github.com/kcp-dev/kcp/pull/1774) even wrong.
Fixes https://github.com/kcp-dev/kcp/issues/1723.
> virtual/workspaces: do not filter if able to get all

- pkg/virtual/workspaces/registry/rest.go
This PR should fix a panic in the `workspaces` virtual workspace. 
A panic is occuring in the `workspaces` virtual workspace, forcing the virtual workspace command to restart:
```
panic: send on closed channel
goroutine 431 [running]:
github.com/kcp-dev/kcp/pkg/virtual/workspaces/registry.withProjection.ResultChan.func1()
/workspace/pkg/virtual/workspaces/registry/rest.go:442 +0xf7
created by github.com/kcp-dev/kcp/pkg/virtual/workspaces/registry.withProjection.ResultChan
/workspace/pkg/virtual/workspaces/registry/rest.go:431 +0xc5
```
> pkg/virtual/workspaces/registry: fix panic sending to a closed channel

- README.md
- hack/verify-go-versions.sh
Update the version in the README, to align with the CONTRIBUTING file change mande in #1651
To ensure these stay aligned with the required version in future, add both to the `verify-go-versions.sh` script
> Update README.md golang version and add to verify script

- pkg/authorization/apibinding_authorizer.go
apiBinding.Status.BoundAPIExport can be nil, causing a panic. This fixes it.
Fixes #1919
> pkg/authorization/apibinding_authorizer: fix nil panic

- pkg/cache/client/context.go
it will panic when the context is not set.
Fixes #
> cache-client: fix npe when the context wasn't set

- hack/verify-go-versions.sh
This check breaks the Dockerfile build as the file isn't COPY'd
This was introduced via #1894 but I didn't notice that the `verify-go-versions` Makefile target is run by the default all/build target in the Dockerfile
> verify-go-versions.sh make CONTRIBUTING.md check conditional

- pkg/cache/client/round_tripper.go
- pkg/cache/client/shard/shard.go
Knows how to read a shard name from an object and store it in the context. 
It should be only used by the internal kube-clients that are not aware of a shard name.
Fixes #
> cache-server: adds ShardNameFromObjectRoundTripper

- config/root-phase0/apiexport-scheduling.kcp.dev.yaml
- config/root-phase0/apiexport-tenancy.kcp.dev.yaml
- config/root-phase0/apiexport-workload.kcp.dev.yaml
- config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml
- config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml
- config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml
#1908 applied spellcheck fixes to our generated APIResourceSchemas, and accidentally bypassed our verification checks to update their names. This reverts the changes to the generated files and then regenerates them with new names.
Fixes #
> 🐛 Fix generated APIResourceSchema names
