cmd/deployment-splitter/main.go, contrib/kcp.code-workspace, pkg/reconciler/deployment/controller.go, pkg/reconciler/deployment/deployment.go
Fixes of the deployment Splitter, as well as VSCode debug configuration for standalone Syncer and Deployment Splitter.
=> Fixes of the Deployment Splitter

README.md
=> doc: correct kubeconfig path

contrib/demo/README.md
Please let me know if there is anything incorrect in the new text
=> feat(demo): Add how to add new logical clusters

cmd/kcp/kcp.go
Probably not the best way to do this, but it was a fairly straightforward way to address #15 
Signed-off-by: Jesse Jaggars <jhjaggars@gmail.com>
=> adding --listen to configure host and port

cmd/syncer/main.go, pkg/reconciler/deployment/deployment.go
Fixes #70 
This aligns code with docs at https://github.com/kcp-dev/kcp/blob/main/contrib/demo/README.md#object-syncer
=> Sync objects with kcp.dev/cluster label

README.md
Based on feedback from @gyliu513 in https://github.com/kcp-dev/kcp/pull/77
=> Document that kcp-dev members can see the drive

pkg/reconciler/cluster/cluster.go, pkg/reconciler/cluster/syncer.go
Fixes https://github.com/kcp-dev/kcp/issues/80
=> Delete syncer-system namespace on cleanup

docs/investigations/logical-clusters.md
=> Fix broken link in investigation document

.gitignore, cmd/syncer/main.go, contrib/demo/clusters/kind/createKindClusters.sh, contrib/demo/clusters/us-east1.yaml, contrib/demo/clusters/us-west1.yaml, contrib/demo/script, contrib/demo/startKcpAndClusterController.sh, contrib/demo/startKcpForDemo.sh, pkg/crdpuller/discovery.go, pkg/reconciler/cluster/cluster.go, pkg/syncer/syncer.go
This PRs provides additional fixes to enable using the push mode to run the demo.
It's WIP and might need to be more tested / completed before merging.
=> Fixes for running the demo with push mode

pkg/crdpuller/discovery.go
Seems we missing `additionalPrinterColumns` when pull crd from downstream cluster. like this
```
NAME                                             SUCCEEDED   REASON   STARTTIME   COMPLETIONTIME
pipelinerun-with-taskspec-to-echo-good-morning
```
for now, only `NAME` and `AGE` is displayed by default.
=> Pull crd with its additionalPrinterColumns

pkg/reconciler/cluster/cluster.go
In multiple `cluster` scenario, when CRD in new real `cluster` is exactly same as existed one, should append `imported-from/clustername` to the labels of CRD rather than replacement.
Current implements will cause no CRD in `kcp` when uninstall one of the `cluster`, until next regular reconcile (default 1 min).
=> In multiple cluster scenario, CRD sync is incorrect

.github/workflows/ci.yaml, .github/workflows/misspell.yaml, cmd/cluster-controller/main.go, cmd/kcp/kcp.go, pkg/reconciler/cluster/cluster.go, pkg/reconciler/cluster/controller.go, pkg/reconciler/deployment/deployment.go, pkg/syncer/syncer.go
FWIW I'm not totally in love with klog either, but standardizing on _something_ should at least make it easier to change to something else if we find something we like.
=> Standardize on klog for logging

GOALS.md, docs/investigations/minimal-api-server.md, docs/investigations/transparent-multi-cluster.md
Articulate some of the common use cases mentioned over the last few
weeks.
=> docs/investigations: Add more detail to minimal API server

.github/workflows/syncer-image.yaml
=> Build and push a syncer image to ghcr for each push

.codecov.yaml, .github/workflows/ci.yaml, .gitignore
https://github.com/kcp-dev/kcp/issues/128
=> Add code coverage to CI tests

.codecov.yaml
=> Don't block PRs on coverage

pkg/apis/apiresource/v1alpha1/apiresourceimport_types.go, pkg/reconciler/apiresource/negotiation.go
Signed-off-by: Sally O'Malley <somalley@redhat.com>
I'm assuming this is a minor typo?
Feel free to close this/fix in another PR if it's easier. :)
=> typo Udpate/Update

docs/investigations/self-service-policy.md
Logical clusters offer opportunities for efficient and strong
multi-tenancy. Explore some of the possible use cases that would
benefit large deployers of Kubernetes applications by standardizing
self-service and exposing new policy constructs that allow better
subdivision.
Addresses #138
=> Describe a self-service policy investigation

pkg/reconciler/cluster/cluster.go, pkg/reconciler/cluster/controller.go
Include Core KCP resources into what can be synchronized with a physical cluster
And add fixes for some small bugs at the same time.
=> Include core kcp resources in syncing

pkg/server/server.go
* Adding this to the Server hooks because I don't think you want this
running without it
fixes #165
=> Adding namespace controller to minimal kube controllers

pkg/apis/apiresource/v1alpha1/common_types.go
=> fix issue: the apiresource without group can not learn from local cluster

pkg/server/config.go, pkg/server/server.go
=> Add pprof to kcp server

pkg/reconciler/cluster/syncer.go
The syncer was not running for me otherwise and the status was always 'syncer not found'.
=> Fixes for running instructions in DEVELOPMENT.md

.github/workflows/ci.yaml, hack/update-codegen-clients.sh, hack/update-codegen.sh, hack/verify-codegen-clients.sh, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/typed/apiresource/v1alpha1/apiresource_client.go, pkg/client/clientset/versioned/typed/apiresource/v1alpha1/apiresourceimport.go, pkg/client/clientset/versioned/typed/apiresource/v1alpha1/negotiatedapiresource.go, pkg/client/clientset/versioned/typed/cluster/v1alpha1/cluster.go, pkg/client/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go, pkg/client/clientset/versioned/typed/tenancy/v1alpha1/tenancy_client.go, pkg/client/clientset/versioned/typed/tenancy/v1alpha1/workspace.go, pkg/client/clientset/versioned/typed/tenancy/v1alpha1/workspaceshard.go
hack: add a script to validate generated clients
---
pkg/client: regenerate clients for multi-cluster
---
/assign @ncdc @sttts @imjasonh
=> Updated generated clients

contrib/localdev/localdev.sh
=> localdev: revert to generic replacement command

DEVELOPMENT.md, README.md, cmd/deployment-splitter/README.md, contrib/demo/apiNegotiation, contrib/demo/apiNegotiation-startKcp.sh, contrib/demo/kubecon, contrib/demo/kubecon-startKcp.sh, contrib/demo/runDemos.sh, contrib/demo/sharding/run.sh, contrib/demo/startKcpAndClusterController.sh, contrib/kcp.code-workspace, hack/run-sharded-kcp.sh, pkg/server/config.go, pkg/server/server.go
config: allow configuring kubeconfig path
---
server: allow absolute data directories
---
server: start controllers in their own goroutines
The code today blocks on the first Start() call, ensuring that the
second controller never starts and the server is never ready.
---
=> Misc fixes

.github/workflows/gh-issues-issue-opened.yml
The previously tried workflow did not work yet with beta projects. This one is promised to do so.
=> Fix gh-issues-issue-opened.yml workflow

.golangci.yaml, pkg/reconciler/cluster/controller.go, pkg/server/server.go, pkg/sharding/apiserver/delegating_storage.go, pkg/sharding/apiserver/sharded_storage.go, pkg/sharding/apiserver/state.go
ci: add a check for properly wrapped errors
---
*: fix errors found by the wrapping checker
---
=> ci: add a check for properly wrapped errors

.golangci.yaml
=> ci: actually turn on the error linter

contrib/demo/apiNegotiation-startKcp.sh, contrib/demo/kubecon-startKcp.sh, contrib/demo/startKcpAndClusterController.sh, contrib/kcp.code-workspace
Signed-off-by: Joaquim Moreno <joaquim@redhat.com>
=> Use double hyphen for cluster-controller args

ns.yaml
Seems to have snuck in with https://github.com/kcp-dev/kcp/commit/7704b61a0a6fdd4f4794d134a1936447debce7ca 🤦‍♂️
=> Remove accidentally added file

.github/workflows/ci.yaml, go.mod, go.sum, pkg/reconciler/workspace/controller.go, pkg/server/server.go, test/e2e/framework/kcp.go, test/e2e/framework/t.go, test/e2e/framework/test.go, test/e2e/framework/testhelper.go, test/e2e/framework/testhelper_test.go, test/e2e/framework/util.go, test/e2e/reconciler/workspace/controller_test.go
=> Workspace Scheduling Controller

.github/workflows/gh-issues-issue-opened.yml
Set write permissions for issues and projects via GITHUB_TOKEN.
=> workflow/gh-issues-opened-issue.yml: use GITHUB_TOKEN with custom permissions

.github/workflows/ci.yaml
=> ci: fix the artifacts glob

pkg/server/config.go, pkg/server/server.go
=> Support OIDC authentication flags

test/e2e/framework/test.go
=> e2e: framework: improve UX for never-ready servers

.github/workflows/ci.yaml, Makefile
Set COUNT=1 or whatever locally when you don't want to be deflaking
yourself all the time.
=> make: add a test target, update counts

hack/bump-k8s.sh
Fix issues running sed on Mac.
=> Make bump-k8s.sh cross-platform

test/e2e/framework/expect.go
=> e2e: framework: fix deadlock in expectation code

test/e2e/framework/kcp.go
=> e2e: framework: debug raw config when we find a corrupt one

test/e2e/reconciler/cluster/controller_test.go
=> Fix linting

pkg/server/server.go
=> Adds debug logging if specs mismatch in findCRD

test/e2e/framework/kcp.go
If we try to read the kubeconfig and the file is 0 bytes, we get an
empty/default Config struct back. Check for this condition, and keep
waiting for a non-empty Config if that's the case.
I _think_ this will fix #301 but I'm not making this auto-close the issue until we've had several e2e iterations in CI that don't flake on this.
=> e2e: guard against 0-byte kubeconfig

cmd/kcp/kcp.go, test/e2e/framework/kcp.go
=> Silence deprecation warnings

test/e2e/framework/expect.go
=> e2e: framework: ensure that expectations are serial

DEVELOPMENT.md, contrib/demo/apiNegotiation-startKcp.sh, contrib/demo/kubecon-startKcp.sh, contrib/demo/sharding/run.sh, contrib/demo/startKcpAndClusterController.sh, contrib/kcp.code-workspace, pkg/reconciler/cluster/startup.go, pkg/server/config.go, test/e2e/framework/kcp.go, test/e2e/reconciler/cluster/controller_test.go, test/e2e/reconciler/namespace/controller_test.go, test/e2e/reconciler/workspace/controller_test.go, test/e2e/reconciler/workspaceshard/controller_test.go
This PR makes all flags naming consistent.
Fixes #313 
/cc @stevekuznetsov @ncdc
=> fix: make all flags naming consistent

pkg/server/handler.go
Using the metav1.Status for errors allows clients to be intelligent with
what they understand the error to be. A blank 404 and text will cause
pretty unintelligible messages downstream.
=> pkg/server: appropriately signal errors

pkg/reconciler/cluster/cluster.go, pkg/reconciler/cluster/syncer.go
This PR makes the cluster controller reinstall syncer when in pull mode and syncer image has changed.
=> Reinstall syncer when in pull mode and image changes

cmd/syncer/main.go
This PR makes `syncer` shutdown more nicely.
=> Make syncer shutdown more nicely

pkg/server/server.go
=> Consolidate shared informer factories to 1 each

pkg/server/handler.go, pkg/server/server.go
=> server: don't pre-create loopback client

pkg/authorization/bootstrap/policy.go, pkg/authorization/local_authorizer.go, pkg/authorization/org_workspace_authorizer.go, pkg/authorization/workspace_content_authorizer.go, pkg/server/controllers.go, pkg/server/server.go
=> Prototype authorization

cmd/kubectl-kcp/main.go, pkg/cliplugins/workspace/plugin/options.go
=> cmd: rename to kubectl-kcp, add root command, add klog flags

pkg/authorization/bootstrap/policy.go, pkg/authorization/workspace_content_authorizer.go
=> authorization: associate edit verb with cluster-admin

pkg/server/config.go, pkg/server/server.go
Found this helpful when debugging some things
=> server: enable auditing

test/e2e/framework/kcp.go, test/e2e/reconciler/namespace/controller_test.go
=> e2e: namespace: use a test-local flag for interval

pkg/reconciler/namespace/conditions.go, pkg/reconciler/namespace/controller.go, pkg/reconciler/namespace/namespace.go, pkg/reconciler/namespace/namespace_test.go, test/e2e/reconciler/namespace/controller_test.go
- Ensure e2e testing validates desired scenarios
- Ensure scheduling status is communicated via namespace conditions
- Ensure cluster removal prompts rescheduling
=> Ensure namespace scheduling satisfies prototype 2 requirements

test/e2e/api_inheritance/api_inheritance_test.go
Make the API inheritance easier to understand when something goes wrong by using `t.Log` steps.
=> e2e/api_inheritance: use t.Logf

test/e2e/framework/kcp.go, test/e2e/framework/t.go
Needs https://github.com/kcp-dev/kcp/pull/431.
=> e2e: flush error channel on termination

.github/workflows/kcp-image.yaml
=> Fix expression in kcp image workflow conditional

test/e2e/framework/util.go
The controllers might be faster than the watch start, and hence we might miss events. So start the watch early (we could also start a watch at the RV of the created object).
=> e2e: fix race of a watch missing early events

test/e2e/framework/kcp.go
Contexts should not be a synchronization mechanism.
=> e2e: streamline kcpServer.loadCfg

pkg/syncer/syncer.go
=> Fix linting issues

test/e2e/api_inheritance/api_inheritance_test.go
We cannot expect that the workspace API exists in every workspace (even if this is the case for some reason, it won't be in the near future).
=> e2e/api-inheritance: clarify test flow

contrib/demo/.startUtils, contrib/demo/apiNegotiation-script/startKcp.sh, contrib/demo/ingress-script/startKcp.sh, contrib/demo/kubecon-script/startKcp.sh, contrib/demo/prototype2-script/deployment-kuard.yaml, contrib/demo/prototype2-script/kcp-tokens, contrib/demo/prototype2-script/prepareClusters.sh, contrib/demo/prototype2-script/removeClusters.sh, contrib/demo/prototype2-script/script, contrib/demo/prototype2-script/startKcp.sh, contrib/demo/prototype2-script/workspace-shard.yaml, contrib/demo/runDemoScripts.sh, contrib/demo/sharding/run.sh, contrib/demo/startKcp.sh, contrib/demo/startKcpAndClusterController.sh, contrib/demo/workspaceKubectlPlugin-script/startKcp.sh, contrib/kcp.code-workspace
=> Add prototype 2 script on-top of options PR

Makefile
=> Add TEST_ARGS flag to customize test and test-e2e execution

pkg/syncer/syncer.go, test/e2e/reconciler/cluster/controller_test.go
Fix a bug in the syncer where, after it got an error, it failed to
return immediately after adding the key back to the queue with a rate
limit. Because it didn't return immediately, the key was subsequently
forgotten (i.e. rate limit reset), which broke rate limited backoff.
Refactor the holder struct not to store an object instance, which is
consistent with standard controller/queue best practices.
Update the process method code to (hopefully) correctly determine the
"from" and "to" namespaces and item keys.
Fixes #482
=> syncer: fix hotloop & minor cleanup

pkg/server/handler.go, pkg/server/server.go
=> server: only allow list+watch in cross-cluster

pkg/syncer/syncer.go
=> Fix syncer hotloop take 2

pkg/reconciler/cluster/cluster.go
=> Fix broken import

test/e2e/authorizer/authorizer_test.go, test/e2e/authorizer/resources.yaml
=> test/e2e: add authz tests

Makefile
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>
Fixes #513
=> fix: TEST_ARGS unset in makefile

config/crds/bootstrap.go, test/e2e/framework/util.go
To be used in e2e in https://github.com/kcp-dev/kcp/pull/508.
=> config/crds: allow multiple CRDs from filesystem

pkg/reconciler/cluster/syncer/syncer_manager.go
The refactor unintentionally resulted in health checks only being performed when a given syncer needed updating.
=> Ensure syncer health checks on every reconcile

test/e2e/authorizer/authorizer_test.go, test/e2e/authorizer/resources.yaml
Use resource bootstrapper and simplify test.
=> e2e/authorization: simplify

config/crds/bootstrap.go
Resource bootstrapping retried naturally already, CRD bootstrapping (which is special because it waits for the Established condition to be true) did not.
=> config/crds: retry retryable errors on bootstrapping

README.md
Co-authored-by: Dr. Stefan Schimanski <stefan.schimanski@gmail.com>
=> Update README for prototype2

Makefile, contrib/demo/prototype2-script/script, contrib/demo/prototype2-script/startKcp.sh
Adds the missing Ingress parts to the demo and some small fixes. 
The recording, done in asciinema, can be found here: 
https://asciinema.org/a/FliBHChjeHZxhVtSbAVrekfT4
=> Flesh out the ingress portion of the prototype 2 demo

pkg/localenvoy/controlplane/controlplane.go, pkg/reconciler/namespace/namespace.go, test/e2e/reconciler/ingress/controller_test.go, test/e2e/reconciler/namespace/controller_test.go
Follow up as per https://github.com/kcp-dev/kcp/pull/537#discussion_r815919590
=> e2e: Remove scheduler dependency on controller patch method

.github/ISSUE_TEMPLATE/epic.md, .github/workflows/ci-docs-only.yaml, .github/workflows/ci.yaml, CONTRIBUTING.md
=> Add epic template, update CONTRIBUTING

test/e2e/reconciler/namespace/controller_test.go
Now that most of the logic of namespace scheduling is unit tested, e2e coverage can be limited to validating that the results of scheduling (cluster assignment and status) are set correctly in the API.
=> e2e: Cleanup namespace scheduler e2e in light of unit-test additions 

pkg/admission/clusterworkspacetypeexists/admission.go
=> admission: simplify informer sync in ClusterWorkspaceTypeExists

docs/workspaces.md, pkg/admission/clusterworkspacetypeexists/admission.go
Follow-up of https://github.com/kcp-dev/kcp/pull/611.
=> Document ClusterWorkspaceType authz

.github/workflows/kcp-image.yaml, manifest/etcd.yaml, manifest/issuer.yaml, manifest/kcp.yaml, manifest/kustomization.yaml
Also includes the manifest of resources to apply every time an image is built.
=> Set up deploy pipeline using Github Actions

config/organization/clusterworkspacetype-use-clusterrolebinding.yaml
=> config/organization: fix clusterrolebindings

pkg/informer/informer.go
Signed-off-by: pradeepnnv <pradeepnnv@gmail.com>
This PR fixes #644.
=> Increase V log level for resources the DynamicDiscoverySharedInformerFactory can't list+watch

config/helpers/bootstrap.go, config/root/secret-shard.yaml
=> bootstrap: support create-only resources

pkg/server/options/flags.go, pkg/server/options/options.go
For race-less port allocation in tests.
=> server: add --experimental-bind-free-port

test/e2e/authorizer/authorizer_test.go, test/e2e/framework/users.go
This test verifies if only cluster admins can use wildcard clusters.
=> Wildcard cluster authorization test

pkg/apis/apiresource/v1alpha1/common_types.go
=> apis/apiresource: fix subresource panic

contrib/demo/prototype2-script/workspace-shard.yaml, contrib/demo/prototype3-script/kcp-tokens, contrib/demo/prototype3-script/prepareClusters.sh, contrib/demo/prototype3-script/removeClusters.sh, contrib/demo/prototype3-script/script-preamble.sh, contrib/demo/prototype3-script/script-template.sh, contrib/demo/prototype3-script/startKcp.sh
Next steps:
- copy `script-template.sh` to `script-<your-epic>.sh`
- produce demo for your epic
=> contrib/prototype3: start demo script

docs/terminology.md
I took text from the original google doc created by @sttts and moved it here as I found it very helpful while learning about kcp terminology.
=> kcp terminology doc

pkg/admission/apiresourceschema/admission.go, pkg/admission/apiresourceschema/admission_test.go, pkg/admission/clusterworkspace/admission.go, pkg/admission/clusterworkspace/admission_test.go, pkg/admission/clusterworkspacetype/admission.go, pkg/admission/clusterworkspacetype/admission_test.go, pkg/admission/clusterworkspacetypeexists/admission.go, pkg/admission/clusterworkspacetypeexists/admission_test.go, pkg/admission/helpers/unstructured.go
Follow-up of https://github.com/kcp-dev/kcp/pull/508.
=> admission: move to runtime.DefaultUnstructuredConverter

pkg/cliplugins/workspace/plugin/kubeconfig.go
This PR adds the organization name to the kubectl-kcp ws use|current
output, which requires refactoring of some re-usable code into helpers.
Fixes #631
=> [kcp-plugin] add org name to kubectl-kcp ws use|current output

config/crds/apis.kcp.dev_apibindings.yaml, pkg/apis/apis/v1alpha1/types.go
Needed for https://github.com/kcp-dev/kcp/pull/702.
=> apis/apibinding: make reference required

cmd/cluster-controller/main.go, pkg/reconciler/apiresource/startup.go, pkg/reconciler/cluster/apiimporter/apiimporter_controller_start.go, pkg/reconciler/cluster/syncer/pullmanager.go, pkg/reconciler/cluster/syncer/pushmanager.go, pkg/reconciler/cluster/syncer/syncer_controller.go, pkg/reconciler/cluster/syncer/syncer_controller_start.go, pkg/reconciler/cluster/syncer/syncer_manager.go, pkg/reconciler/namespace/controller.go, pkg/server/controllers.go, pkg/server/kubeconfig.go, pkg/server/server.go
Fixes https://github.com/kcp-dev/kcp/issues/549.
=> reconcilers: add user-agent to all controller clients

docs/kubectl-kcp-plugin.md, docs/syncer.md, manifest/syncer.yaml
=> instructions to install a syncer on a pcluster

contrib/crds/generate-crds.sh, hack/go-install.sh
see https://go.dev/doc/go-get-install-deprecation
=> go get was deprecated and no longer works with 1.18

cmd/virtual-workspaces/command/cmd.go, cmd/virtual-workspaces/main.go, cmd/virtual-workspaces/options/options.go
Add logging options to the virtual workspaces server.
=> Add logging options to virtual workspaces server

pkg/cliplugins/workspace/cmd/cmd.go, pkg/cliplugins/workspace/plugin/kubeconfig.go
Like in `kubectl kcp ws create foo --type Organization`.
=> kubectl-kcp: add create --type flag

GOALS.md, config/crds/tenancy.kcp.dev_clusterworkspaces.yaml, docs/architecture/README.md, docs/investigations/transparent-multi-cluster.md, pkg/apis/tenancy/v1alpha1/types.go, pkg/apis/workload/v1alpha1/types.go, pkg/openapi/zz_generated.openapi.go, pkg/reconciler/apiresource/negotiation.go, pkg/server/controllers.go, pkg/server/handler.go, pkg/virtual/workspaces/registry/rest.go
=> Fix misspell words

pkg/virtual/framework/rootapiserver/root_apiserver.go
```
$ kubectl kcp workspaces list
W0329 19:56:35.101114   28559 warnings.go:70] You are using an old kubectl-kcp plugin. Please update to a version matching the kcp server version "v0.3.0-alpha.0-14-gca4125b6fd9dc0+kcp".
NAME       TYPE        PHASE   URL
foo        Universal   Ready   https://192.168.86.95:6443/clusters/root:default:foo
```
=> virtual: add warning header with old kubectl plugin

test/e2e/framework/kcp.go
This ensures that a test run will use the most recent built artifact
rather than a potentially stale binary in the path somewhere.
=> e2e: Use ./bin/kcp instead of finding it from the path

pkg/cliplugins/workspace/plugin/kubeconfig.go
@davidfestal told you that it will bite us :)
=> kubectl-kcp: wait for workspace to show up in personal virtual workspace

pkg/cliplugins/workspace/cmd/cmd.go, pkg/cliplugins/workspace/plugin/kubeconfig.go, pkg/cliplugins/workspace/plugin/kubeconfig_test.go, pkg/cliplugins/workspace/plugin/options.go
=> 6. kubectl-kcp: add create-context command

contrib/demo/ingress-script/nginx-ingress.yaml, contrib/demo/prototype3-script/.gitignore, contrib/demo/prototype3-script/apibinding/cert-manager-apibinding.yaml, contrib/demo/prototype3-script/apibinding/cert-manager-apiexport.yaml, contrib/demo/prototype3-script/apibinding/cert-manager.yaml, contrib/demo/prototype3-script/apibinding/certificate.yaml, contrib/demo/prototype3-script/apibinding/certificates-apiresourceschema.yaml, contrib/demo/prototype3-script/apibinding/deployment-kuard-tls.yaml, contrib/demo/prototype3-script/apibinding/issuer.yaml, contrib/demo/prototype3-script/apibinding/kuard-ingress.yaml, contrib/demo/prototype3-script/apibinding/kuard-service.yaml, contrib/demo/prototype3-script/apibinding/openssl.cnf, contrib/demo/prototype3-script/script-apibindings.sh, contrib/demo/prototype3-script/script-preamble.sh
Part of #417.
Co-authored by @varshaprasad96.
=> apibinding demo

pkg/cliplugins/workspace/cmd/cmd.go, pkg/cliplugins/workspace/plugin/kubeconfig.go
=> kubectl-kcp: add --short to current command for use in prompt

pkg/authorization/local_authorizer.go, pkg/virtual/framework/wrappers/rbac/merging.go, test/e2e/authorizer/authorizer_test.go, test/e2e/authorizer/org-resources.yaml
=> Referencing k8s CRB by workspace admins

pkg/reconciler/workload/apiimporter/apiimporter_manager.go
Use workload cluster name and logical cluster name as key for apiImporters map
Fixes #730 
This is rather a workaround until the Location and virtual workspace APIs have been implemented.
This allows to have APIs of multiple workspaces imported and synced with a single physical cluster.
=> workaround for #730: API import does not work when adding the same cluster into multiple workspaces

pkg/reconciler/workload/apiimporter/apiimporter_manager.go
Use workload cluster name and logical cluster name as key for apiImporters map.
Apply #856 to the release-0.3 branch
Adresses  #730 in release-0.3 branch
=> [0.3] workaround for #730: API import does not work when adding the same cluster into multiple workspaces

manifest/kcp.yaml
Set `--v=2` for the kcp container to help with debugging.
Fixes #
=> manifest: set --v=2

pkg/syncer/apiimporter.go, pkg/syncer/syncer.go
Add more details to the syncer and api importer log messages to help with debugging service issues.
Fixes #
=> syncer: add more details to log messages

.github/workflows/kcp-image.yaml
No longer want to deploy to the "stable" environment from the release branch.
=> Disable deploy pipeline on release branch

.github/workflows/kcp-image.yaml
Every job must explicitly check out the code
=> Check out code in deploy job

pkg/admission/namespacelifecycle/admission.go, pkg/admission/namespacelifecycle/admission_test.go, pkg/admission/plugins.go, pkg/apis/tenancy/v1alpha1/types.go, pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go, pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go, pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor_test.go, pkg/server/controllers.go, pkg/server/server.go, test/e2e/framework/expect.go, test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
basically reuse the namespace deletion code to delete all resources in a workspace when workspace is deleting. Still need to add tests
Fixes https://github.com/kcp-dev/kcp/issues/527
=> delete resources in workspace when workspace is deleted

pkg/virtual/workspaces/registry/rest.go, pkg/virtual/workspaces/registry/rest_test.go, test/e2e/virtual/workspaces/virtual_workspace_test.go
=> Revert "virtual: Disable workspace deletion for now"

pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go, test/e2e/syncer/syncer_test.go
Towards https://github.com/kcp-dev/kcp/issues/947.
=> e2e/syncer: check deployment available independently and output yaml

CONTRIBUTING.md
Clarify feature-gates in the contribution process.
=> CONTRIBUTING.md: add feature-gates

test/e2e/framework/fixture.go, test/e2e/framework/util.go
=> e2e: create syncer log artifacts when running in kind

.github/workflows/ci.yaml, test/e2e/syncer/deployment.yaml
Use a smaller busybox image 1.6GB => 2.66MB 🤡
=> e2e/syncer: stop (some of) the bleeding

config/crds/workload.kcp.dev_workloadclusters.yaml, pkg/apis/workload/v1alpha1/types.go, test/e2e/framework/util.go
Signed-off-by: Dominique Vernier <dvernier@redhat.com>
Remove WorkloadClusterSpec.Kubeconfig
Fixes # https://github.com/kcp-dev/kcp/issues/934
=> Remove WorkloadClusterSpec.Kubeconfig

pkg/reconciler/workload/namespace/namespace_controller.go, pkg/reconciler/workload/namespace/namespace_reconcile.go, pkg/syncer/statussyncer.go, test/e2e/framework/fixture.go, test/e2e/framework/util.go
We were trying to use the KUBECONFIG env var, but it's not set up.
Fixes #
=> Towards more stable syncer

pkg/reconciler/workload/namespace/namespace_controller.go, pkg/reconciler/workload/namespace/namespace_reconcile.go, pkg/syncer/statussyncer.go, test/e2e/framework/fixture.go, test/e2e/framework/util.go
Backport of https://github.com/kcp-dev/kcp/pull/978/
Required backporting https://github.com/kcp-dev/kcp/pull/955/ as well
=> [0.4] reconciler/workload/scheduling: remove wrong resource enqueuing avoiding optimization

cmd/ingress-controller/main.go, cmd/kcp-front-proxy/options/options.go, cmd/kcp/kcp.go, cmd/syncer/options/options.go, cmd/virtual-workspaces/command/cmd.go
Backport #979 to release-0.4
Fixes #
=> [0.4] Default to -v=2

pkg/server/apiextensions.go
The systemCRDProvider was logging an error every time a request for a system CRD was received and the workspace couldn't be found. Stop doing that, as it's a legitimate situation.
Fixes #
=> Don't log when systemCRDProvider can't find ws

docs/auth.md, docs/authorization.md
This is a preliminary attempt to document authorization in kcp.
Fixes #618
/cc @ncdc @sttts
=> docs/auth: document authorization

pkg/admission/clusterworkspace/admission.go, pkg/admission/clusterworkspaceshard/admission.go, pkg/admission/clusterworkspacetype/admission.go
=> admission: complain about the type of the correct object

pkg/reconciler/workload/basecontroller/controller.go
=> reconcilers/workload: shut down controllers correctly

pkg/apis/workload/v1alpha1/types.go, pkg/server/apiextensions.go, pkg/syncer/spec/spec_process.go, pkg/syncer/spec/spec_process_test.go, pkg/syncer/status/status_process.go, pkg/syncer/status/status_process_test.go, pkg/syncer/syncer.go, test/e2e/fixtures/kube/apps.k8s.io_deployments.yaml, test/e2e/fixtures/kube/core.k8s.io_services.yaml
Misc changes in #754 that should not be squashed.
=> Misc pre-754 changes

.github/workflows/kcp-image.yaml, manifest/etcd.yaml, manifest/issuer.yaml, manifest/kcp-front-proxy.yaml, manifest/kcp.yaml, manifest/kustomization.yaml, pkg/proxy/proxy.go
Backports https://github.com/kcp-dev/kcp/pull/973 and https://github.com/kcp-dev/kcp/pull/993 as a dependency.
=> [0.4] Add front proxy

pkg/virtual/syncer/builder/build.go
=> virtual/syncer: add documentation to the URL parsing

pkg/virtual/framework/dynamic/apidefinition/types.go, pkg/virtual/framework/dynamic/apiserver/discovery.go, pkg/virtual/framework/dynamic/apiserver/handler.go, pkg/virtual/framework/dynamic/apiserver/handler_test.go, pkg/virtual/syncer/controllers/apireconciler/apireconciler_controller.go
I saw in https://github.com/kcp-dev/kcp/pull/1052 @ncdc had similar requirements, so I'm pulling this out for us to share.
/assign @davidfestal @sttts @ncdc
=> virtual: expand APIDefinitionSetGetter

pkg/cliplugins/workload/cmd/cmd.go, pkg/cliplugins/workload/plugin/workload.go
Signed-off-by: Chris Ahl <cahl@redhat.com>
Add kcp cli cmds for workload cordon/drain/uncordon
Fixes #525
=> add kcp workload cordon/uncordon/drain

test/e2e/framework/fixture.go, test/e2e/framework/util.go, test/e2e/virtual/syncer/virtualworkspace_test.go
=> test/e2e: quiet down spammy log messages

config/crds/apis.kcp.dev_apibindings.yaml, pkg/admission/apibinding/apibinding_admission.go, pkg/admission/apibinding/apibinding_admission_test.go, pkg/apis/apis/v1alpha1/types.go, pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go, pkg/openapi/zz_generated.openapi.go, pkg/reconciler/apis/apibinding/apibinding_reconcile.go
These were unused and are not needed.
=> apibinding: remove initializers

pkg/server/handler.go, pkg/server/server.go
Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>
Annotate audit logs with cluster name set in request context.
https://github.com/kcp-dev/kcp/issues/862
Fixes #
=> pkg/server: add workspace annotation

test/e2e/framework/fixture.go
=> test/e2e: quiet down more spam

pkg/server/server.go
This will enable audit logging if configured via flags.
=> Apply audit config to server

test/e2e/reconciler/namespace/controller_test.go
Remove code that was trying to force the WorkloadCluster's Ready
condition to true that was most likely fighting w/the heartbeat
controller. We already have a goroutine in the e2e that updates the
heartbeat time to simulate a syncer running.
Fixes #1103 🤞
=> Deflake namespace reconciler e2e

pkg/apis/apis/v1alpha1/types.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletor.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletor_test.go, pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go, pkg/server/apiextensions.go, pkg/server/apiextensions_test.go, pkg/server/controllers.go, pkg/server/handler.go, test/e2e/apibinding/apibinding_deletion_test.go, test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
follow up PR of https://github.com/kcp-dev/kcp/pull/1040
Fixes https://github.com/kcp-dev/kcp/issues/846
=> forbid resource creation when APIBinding is deleting

GOALS.md
=> Fix typo in goals.md

pkg/virtual/framework/dynamic/apiserver/discovery.go, pkg/virtual/framework/dynamic/apiserver/handler_test.go, test/e2e/virtual/syncer/virtualworkspace_test.go
/assign @ncdc @sttts @davidfestal
=> virtualworkspace: inspect available verbs from storage

pkg/reconciler/apis/apiresource/negotiation.go
Fix cache mutation of apiresourceimport
Fixes #
=> apiresourceimport: fix cache mutation

pkg/crdpuller/discovery.go, pkg/reconciler/apis/apiresource/negotiation.go, pkg/reconciler/workload/apiexport/apiresourceschema.go, pkg/syncer/apiimporter.go, test/e2e/fixtures/kube/apps.k8s.io_deployments.yaml, test/e2e/fixtures/kube/core.k8s.io_services.yaml
Completing https://github.com/kcp-dev/kcp/pull/1104.
=> Propagate api-approved.kubernetes.io annotation from pcluster upwards

config/crds/tenancy.kcp.dev_clusterworkspaces.yaml, config/crds/tenancy.kcp.dev_clusterworkspacetypes.yaml, pkg/admission/clusterworkspace/admission.go, pkg/apis/tenancy/v1alpha1/types.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller_test.go
=> tenancy: improve initializer label mechanism

CONTRIBUTING.md
=> document kubebuilder validations

pkg/virtual/framework/internalapis/import_test.go
/assign @davidfestal 
/cc @sttts
=> virtual: update some names in a test for clarity

Makefile
This utility brings a lot of user-experience benefits to testing, as
well as emitting nice jUnit XML files that publish the output of our
tests for consumption by structured CI displays.
=> make: use gotestsum for tests

pkg/cliplugins/workspace/plugin/kubeconfig.go
Return a nicer error instead of the `resource not found`
Signed-off-by: Roy Golan <rgolan@redhat.com>
Fixes #831
=> Better error when failing to create a sub workspace

.ci-operator.yaml, OWNERS
=> *: bootstrap some items for CI

Makefile
=> make: fix a copy-pasta error

test/e2e/framework/kcp.go
e2e: use a channel to coordinate waiting for kcp server shutdown and close the log file during cleanup so waiting for kcp server termination can complete.
Possible alternative to #1035
=> e2e: fix kcp server shutdown/waiting

pkg/authorization/apibinding_authorizer.go, pkg/server/options/authorization.go
Currently, indexer initalization is being ignored, this fixes it.
cc @sttts @ncdc
=> pkg/authorization/apibinding_authorizer: don't ignore indexer errors.

pkg/apis/workload/v1alpha1/types.go, pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go, pkg/reconciler/workload/namespace/namespace_reconcile.go, pkg/reconciler/workload/resource/resource_reconcile_test.go, pkg/syncer/shared/finalizer.go, pkg/syncer/spec/spec_process_test.go, pkg/syncer/status/status_process_test.go, pkg/syncer/syncer.go, test/e2e/reconciler/cluster/controller_test.go, test/e2e/reconciler/namespace/controller_test.go, test/e2e/reconciler/scheduling/controller_test.go
=> 0.5: Unify workloads.kcp.dev => workload.kcp.dev

pkg/syncer/spec/mutators/deployment.go, pkg/syncer/spec/mutators/deployment_test.go
In order to avoid Deployment Pods getting the downstream namespace instead of the KCP namespace,we need to resolve the downwardAPI references of the Env vars before pushing to the pcluster, right now we are only handling the "metadata.namespace" case.
Fixes https://github.com/kcp-dev/kcp/issues/1191
Follow-up issue for volumes https://github.com/kcp-dev/kcp/issues/1198
=> Syncer/mutators: Resolve fieldRef "metadata.namespace" Envs before pushing to pcluster

.github/workflows/kcp-image.yaml
This PR adds PPC64Le support to the KCP image. It has used qemu user static for emulating the PPC64Le architecture.
Fixes #
=> Added ppc64le support to KCP image

.github/workflows/syncer-image.yaml
=> Added ppc64le and arm64 support to the Syncer image

pkg/informer/informer.go, pkg/reconciler/workload/resource/resource_controller.go, pkg/reconciler/workload/resource/resource_reconcile.go, pkg/server/controllers.go, pkg/server/indexes.go, pkg/server/server.go, test/e2e/conformance/cross_logical_cluster_list_test.go
Pre-req for use of the dynamic informers in other controllers. It also matches the pattern we have for every other informer.
=> server: centrally create and start ddsif

pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/workload/resource/resource_reconcile.go
- reconciler/apibinding: V(2) log patching
- reconciler/workload/resource: reduce log noise when doing nothing
=> Reduce log noise

pkg/admission/clusterworkspace/admission_test.go
=> admission/clusterworkspace: check errors in unit test

pkg/reconciler/apis/apiexport/apiexport_controller.go
follow-up for https://github.com/kcp-dev/kcp/pull/1291/files#r901409147
=> pkg/reconciler/apis/apiexport: clarify patching strategy in case of programming errors

Makefile, cmd/test-server/main.go
To be added to https://github.com/openshift/release/blob/befda62f718d7b84b37a3ed8cc722ec6de51286f/ci-operator/config/kcp-dev/kcp/kcp-dev-kcp-main.yaml.
=> Makefile: add test-e2e-shared

pkg/authorization/toplevel_org_authorizer.go, pkg/authorization/workspace_content_authorizer.go, pkg/authorization/workspace_content_authorizer_test.go
=> authorizer: unify workspace access reason

pkg/admission/clusterworkspacetypeexists/admission.go, pkg/admission/clusterworkspacetypeexists/admission_test.go, pkg/apis/tenancy/v1alpha1/types.go
=> admission: record the user creating a workspace

cmd/kcp-front-proxy/authentication/groups.go
We want to eventually disallow `system:masters` and maybe other system groups. I.e. through the front-proxy only "normal" users should connect or controller kcp-admins.
=> front-proxy: add --authentication-{pass-on,drop}-groups

cmd/virtual-workspaces/command/cmd.go, pkg/server/server.go, pkg/server/virtual.go, pkg/virtual/apiexport/options/options.go, pkg/virtual/framework/handler/doc.go, pkg/virtual/framework/handler/handler.go, pkg/virtual/framework/types.go, pkg/virtual/initializingworkspaces/builder/build.go, pkg/virtual/initializingworkspaces/options/options.go, pkg/virtual/options/options.go, pkg/virtual/syncer/options/options.go, pkg/virtual/workspaces/options/options.go, test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go
virtualworkspace: add a proxy for workspace content
---
Part of #1149 
Depends on #1321 
/assign @sttts
=> virtualworkspace: add a proxy for workspace content

pkg/virtual/apiexport/builder/build.go, pkg/virtual/framework/dynamic/example_test.go, pkg/virtual/framework/dynamic/types.go, pkg/virtual/framework/fixedgvs/register.go, pkg/virtual/framework/fixedgvs/types.go, pkg/virtual/initializingworkspaces/builder/build.go, pkg/virtual/syncer/builder/build.go, pkg/virtual/workspaces/builder/build.go
Follow-up to #1323 
/assign @sttts @davidfestal
=> virtualworkspaces: propagate clarifying changes

test/e2e/syncer/deployment.yaml
=> e2e/syncer: switch to multi-arch image

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/server/handler.go, pkg/sharding/apiserver/delegating_storage.go, pkg/sharding/apiserver/sharded_storage.go
Follow-up of https://github.com/kcp-dev/logicalcluster/pull/9.
=> Use logicalcluster.ClusterHeader constant for X-Kubernetes-Cluster

pkg/reconciler/scheduling/placement/placement_reconcile_scheduling.go, pkg/reconciler/scheduling/placement/placement_reconcile_scheduling_test.go
Fix hotloop in placement due to bad patch
Fixes #1351
=> Fix hotloop in placement due to bad patch

test/e2e/fixtures/apifixtures/sheriffs.go
As in kube, CRDs can be slightly delayed because they are served informer based.
=> e2e: cope with asynchronously served (bound) CRDs

pkg/admission/reservedmetadata/admission.go, pkg/admission/reservedmetadata/admission_test.go
Follow-up of https://github.com/kcp-dev/kcp/pull/1343#discussion_r905976617
https://github.com/kcp-dev/kcp/pull/1343, https://github.com/kcp-dev/kcp/issues/1138
/cc @sttts
=> pkg/admission/reservedmetadata: optimize allocations

pkg/cliplugins/workspace/plugin/kubeconfig.go, pkg/cliplugins/workspace/plugin/kubeconfig_test.go
previously, cli used to proceed creating bad state even
if the workspace doesn't exist on the cluster.
now, it validate the workspace if it exist on the cluster.
Fixes #1190
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>\
Changes applied on cluster:
Current workspaces in the cluster
```
> ~ > k kcp ws
Current workspace is "root".
> ~ > k kcp ws list
NAME      TYPE           PHASE   URL
default   Organization   Ready   https://10.76.98.68:6443/clusters/root:default
green     Organization   Ready   https://10.76.98.68:6443/clusters/root:green
> ~ > k kcp ws use green
Current workspace is "root:green" (type "Organization").
> ~ > k kcp ws list
NAME   TYPE        PHASE   URL
g1     Universal   Ready   https://10.76.98.68:6443/clusters/root:green:g1
g2     Universal   Ready …
```
=> kcp CLI: error out for an non existent workspace while changing ws

pkg/admission/reservedcrdgroups/admission.go, pkg/admission/reservedcrdgroups/admission_test.go, test/e2e/customresourcedefinition/customresourcedefinition_test.go, test/e2e/customresourcedefinition/tenancy.kcp.dev_cowboys.yaml
Part of #1149 
Pre-requisite for #1341 
/assign @sttts @ncdc
=> admission: only reserve our exact groups

pkg/virtual/framework/forwardingregistry/wrappers.go, pkg/virtual/initializingworkspaces/builder/build.go, pkg/virtual/initializingworkspaces/builder/forwarding.go, pkg/virtual/syncer/builder/build.go
Little restructuring to avoid a panic in a func without error return type.
=> virtual: generalize label selector wrapper and get rid of panic

pkg/virtual/framework/fixedgvs/types.go
=> virtual/fixedgvs: import cleanup

OWNERS
I was added with the wrong name here.
=> Update OWNERS to fix my name

pkg/cliplugins/workspace/plugin/kubeconfig.go
Before:
```
$ kubectl kcp workspace create test --type Universal
Workspace "test" (type root:Universal) created. Waiting for being ready.
```
After:
```
$ kubectl kcp workspace create test --type Universal
Workspace "test" (type root:Universal) created. Waiting for it to be ready...
Workspace "test" (type root:Universal) is ready to use.
```
/assign @ncdc @davidfestal 
/cc @MatousJobanek
=> kcp workspaces: improve wording for workspace creation

pkg/virtual/workspaces/registry/rest.go, pkg/virtual/workspaces/registry/rest_test.go
The `workspaces` virtual workspace is currently managing cluster workspace type permission on creation in a broken way: 
- It always checks (with a SAR) for the `use` permission on the named CTW **in the current workspace**, instead of taking in account the `Path` part of the workspace CTW reference 
- When no type is given it checks by default for the `universal` CWT **in the current workspace**, which is particularly wrong, and error-prone.
The temporary, short-term fix proposed here:
- Issues  the CWT SAR against the right parent workspace (== Path of the CWT reference) 
- Fixes the type to `root:Universal` if not type is set
Of course this is not the complete fix because it reintroduces a static default type, though the default now should depend on the parent workspace, which has a …
=> workspaces VW: Fix CWT management

pkg/virtual/workspaces/builder/build.go
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
Fixes minor typo, I noticed on the log
=> Noticed typo on the log

test/e2e/framework/fixture.go
=> e2e: stop spamming entire objects

pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Sometimes APIBinding resources don't get served. This might help a little to understand what going on.
Looks like some resources stay in Established forever. Would be interesting to see why.
=> Hunting APIBinding flake

config/root-phase0/apiexport-apiresource.kcp.dev.yaml, config/root-phase0/apiexport-scheduling.kcp.dev.yaml, config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml, config/root-phase0/apiexport-tenancy.kcp.dev.yaml, config/root-phase0/apiexport-workload.kcp.dev.yaml, pkg/admission/clusterworkspacetypeexists/admission_test.go, pkg/apis/apis/v1alpha1/types.go, pkg/apis/tenancy/v1alpha1/types.go, pkg/apis/tenancy/v1beta1/types.go, pkg/openapi/zz_generated.openapi.go
Very rough approximation of where necessary:
```
$ git grep -A 1 '+optional' | grep -v optional | grep -v omitempty | grep json
```
=> apis: add omitempty to optional fields

README.md
=> README: update docs for starting

pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go, pkg/reconciler/apis/apiexport/apiexport_controller.go, pkg/reconciler/apis/apiexport/apiexport_reconcile.go, pkg/reconciler/scheduling/location/location_controller.go, pkg/reconciler/scheduling/location/location_reconcile.go, pkg/reconciler/scheduling/location/location_reconcile_test.go, pkg/reconciler/scheduling/placement/placement_controller.go, pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go, pkg/reconciler/workload/apiexport/apiexport_controller.go, pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go, pkg/reconciler/workload/namespace/namespace_controller.go, pkg/reconciler/workload/namespace/namespace_reconcile_scheduling.go, pkg/reconciler/workload/namespace/namespace_reconcile_scheduling_test.go, pkg/server/apiextensions.go, test/e2e/conformance/cross_logical_cluster_list_test.go
Let's see whether this already gets green pre-#1316.
=> server/apiextensions: disable non-system-CRD non-identity wildcard requests

config/root/clusterworkspacetype-home.yaml, config/root/clusterworkspacetype-homebucket.yaml, config/root/clusterworkspacetype-homeroot.yaml
Part of #1149 
/assign @ncdc 
/cc @sttts
=> config/root: fix CWTs

.github/workflows/ci-docs-only.yaml
Align ci-docs-only actions with ci
Fixes #
=> Add e2e-sharded docs only job

CONTRIBUTING.md
Add flake hunting docs
Fixes #
=> Add flake hunting docs

docs/virtual-workspaces.md
Since this demo is referenced as the canonical example of this use case, make it easier to find.
=> docs: link to virtual workspaces demo

test/e2e/apibinding/apibinding_test.go, test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go, test/e2e/virtual/syncer/virtualworkspace_test.go
=> e2e: add user-agents to hand-crafted rest configs

cmd/test-server/main.go, pkg/reconciler/apis/apibinding/apibinding_reconcile.go, pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go
Even during rebinding, the APIBinding is not stopping working, i.e. it is Bound at all points in time.
=> reconciler/apis/apibinding: make phase=Bound permanent

docs/locations-and-scheduling.md
=> Update placement doc

pkg/admission/clusterworkspace/admission.go, pkg/admission/clusterworkspace/admission_test.go, pkg/admission/clusterworkspacetypeexists/admission.go, pkg/admission/clusterworkspacetypeexists/admission_test.go
The owner annotation has nothing to do with types.
=> admission/clusterworkspace: move owner annotation code here

test/e2e/framework/kcp.go
To whatever extent our test setup is causing etcd to have a hiccup here
or there, it does not seem to then cause the rest of the tests to have
any issues. While it's useful to know that there are some latent etcd
issues (or whatever) in the tests, we should be more tolerant of probing
failures, since things happen and distributed, eventually consistent
systems are hard.
---
Depends on #1488 
/assign @sttts @ncdc @davidfestal
=> e2e: require two failed pings to fail the test

test/e2e/virtual/apiexport/virtualworkspace_test.go
The right thing, is the refactor #1500 but this should stop the bleeding.
=> Waiting for the binding to have observed the permission claims in test

pkg/cliplugins/workspace/cmd/cmd.go
This will go away when we remove the personal workspace / pretty name logic.
=> cli: deprecate list command

pkg/reconciler/workload/resource/resource_reconcile.go, pkg/reconciler/workload/resource/resource_reconcile_test.go
This PR changes the resource reconciler's behavior to avoid removing the sync state from a resource if a finalizer, either syncer or cluster, exists. 
fixes: https://github.com/kcp-dev/kcp/issues/1482
=> Don't unschedule a resource if blocked by a cluster or syncer finalizer

pkg/cliplugins/workspace/cmd/cmd.go, pkg/cliplugins/workspace/plugin/kubeconfig.go, pkg/cliplugins/workspace/plugin/kubeconfig_test.go
Fixing https://github.com/kcp-dev/kcp/issues/1502.
=> cli: switch meaning of 'kubectl ws' to go to home workspace, add 'kubectl ws .'

pkg/cliplugins/workspace/plugin/kubeconfig.go
Take the right URL from the workspace object for e.g. `kubectl ws root:example`.
Note: this does not contain a solution for the root workspace yet. Probably we need a similar solution to the `~` workspace where we fake a `Workspace` object.
=> cli: take URL from Workspace also in absolute references

cmd/cluster-controller/main.go, pkg/reconciler/apis/apiresource/controller.go, pkg/reconciler/apis/apiresource/negotiation.go, pkg/server/controllers.go
=> Part 3: Make APIResource controller client calls scoped

pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go, pkg/reconciler/workload/basecontroller/controller.go, pkg/reconciler/workload/heartbeat/heartbeat_controller.go, pkg/server/controllers.go
=> Part 4: Wrap client calls in API Binding and Heartbeat controller

test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
Wait for the default namespace to exist before trying to delete it. The
default namespace is created async when a workspace is created, and in
some cases, the e2e test code that is trying to delete the namespace
executes before the namespace has been created, resulting in an
unexpected not-found error.
Fixes #
=> e2e/clusterworkspacedeletion: deflake

pkg/reconciler/apis/apibinding/apibinding_controller.go
=> remove unused apiResourceSchemaIndexer from the apibinding controller

README.md
This PR adds a brief overview of workspaces to the README.
This is a more evolved version of #1213
=> Add workspaces overview to README

test/e2e/framework/fixture.go
=> e2e: use a better helper for waiting for readiness

cmd/ingress-controller/main.go, pkg/reconciler/workload/apiexport/workload_apiexport_controller.go, pkg/reconciler/workload/apiexport/workload_apiexport_reconcile.go, pkg/reconciler/workload/apiexportcreate/apiexportcreate_controller.go, pkg/reconciler/workload/defaultplacement/defaultplacement_controller.go, pkg/reconciler/workload/ingresssplitter/ingresssplitter_controller.go, pkg/reconciler/workload/ingresssplitter/ingresssplitter_reconcile.go, pkg/reconciler/workload/namespace/namespace_controller.go, pkg/reconciler/workload/resource/resource_controller.go, pkg/reconciler/workload/resource/resource_reconcile.go, pkg/reconciler/workload/virtualworkspaceurls/virtualworkspaceurls_controller.go, pkg/server/controllers.go
=> Part 6: Scope workload controllers

README.md
This PR adds an introduction to workspaces into the README.  It is needed because there was not really such a thing there before.  This was noted in https://github.com/kcp-dev/kcp/pull/1584#discussion_r926798368 .
none
=> Extend README with introduction to workspaces

pkg/server/controllers.go
as `ClusterWorkspaceShards` resource is managed only by the root shard
requires https://github.com/kcp-dev/kcp/pull/1587
=> run the clusterworkspaceshard controller only on the root shard

Makefile, cmd/sharded-test-server/frontproxy.go, cmd/sharded-test-server/main.go, cmd/sharded-test-server/shard.go
Extracted from @stevekuznetsov's rebase PR plus some extensions:
- require ko and kind
- separate image building into its own target
- better error logic
=> Makefile improvements

Makefile
=> make: explicitly list build deps

pkg/cliplugins/workload/plugin/sync_test.go, pkg/cliplugins/workload/plugin/syncer.yaml
Backport of https://github.com/kcp-dev/kcp/pull/1613.
=> 0.6: cli/sync: create service account secret in advance to trigger token creation

pkg/server/options/options.go
This was panic'ing in non-embedded mode.
=> server/embeddedetcd: fix npe

config/crds/scheduling.kcp.dev_locations.yaml, config/root-phase0/apiexport-scheduling.kcp.dev.yaml, config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml, pkg/apis/scheduling/v1alpha1/types_location.go
Fixes https://github.com/kcp-dev/kcp/issues/1625
=> Fix print column on location labels

pkg/admission/webhook/generic_webhook.go
Pulling this out of #1635 to just fix the webhook npe.
Fixes #1634
=> webhook: fix npe

test/e2e/apibinding/apibinding_authorizer_test.go, test/e2e/apibinding/apibinding_deletion_test.go, test/e2e/apibinding/apibinding_permissionclaims_test.go, test/e2e/apibinding/apibinding_protected_test.go, test/e2e/apibinding/apibinding_test.go, test/e2e/apibinding/apibinding_webhook_test.go, test/e2e/conformance/cross_logical_cluster_list_test.go, test/e2e/fixtures/apifixtures/apibinding.go, test/e2e/fixtures/apifixtures/sheriffs.go, test/e2e/framework/kcp.go, test/e2e/virtual/apiexport/virtualworkspace_test.go, test/e2e/watchcache/watchcache_enabled_test.go
=> Part 8: Wrap clients in test/e2e/apibinding

pkg/server/server.go
A single error could stop server bootstrapping.
=> server: keep retrying bootstrapping

config/crds/apis.kcp.dev_apibindings.yaml, config/crds/apis.kcp.dev_apiexports.yaml, config/crds/apis.kcp.dev_apiresourceschemas.yaml, config/crds/scheduling.kcp.dev_locations.yaml, config/crds/scheduling.kcp.dev_placements.yaml, config/crds/tenancy.kcp.dev_clusterworkspaces.yaml, config/crds/tenancy.kcp.dev_clusterworkspaceshards.yaml, config/crds/tenancy.kcp.dev_workspaces.yaml, config/crds/workload.kcp.dev_synctargets.yaml, config/root-phase0/apiexport-scheduling.kcp.dev.yaml, config/root-phase0/apiexport-shards.tenancy.kcp.dev.yaml, config/root-phase0/apiexport-tenancy.kcp.dev.yaml, config/root-phase0/apiexport-workload.kcp.dev.yaml, config/root-phase0/apiresourceschema-clusterworkspaces.tenancy.kcp.dev.yaml, config/root-phase0/apiresourceschema-clusterworkspaceshards.tenancy.kcp.dev.yaml, config/root-phase0/apiresourceschema-locations.scheduling.kcp.dev.yaml, config/root-phase0/apiresourceschema-placements.scheduling.kcp.dev.yaml, config/root-phase0/apiresourceschema-synctargets.workload.kcp.dev.yaml, config/root-phase0/apiresourceschema-workspaces.tenancy.kcp.dev.yaml, pkg/apis/apis/v1alpha1/types_apibinding.go, pkg/apis/apis/v1alpha1/types_apiexport.go, pkg/apis/apis/v1alpha1/types_apiresourceschema.go, pkg/apis/scheduling/v1alpha1/types_location.go, pkg/apis/scheduling/v1alpha1/types_placement.go, pkg/apis/tenancy/v1alpha1/types.go, pkg/apis/tenancy/v1beta1/types.go, pkg/apis/workload/v1alpha1/synctarget_types.go, pkg/openapi/zz_generated.openapi.go
Kube resource have an age column. In CRDs this is optional. Let's add it.
=> apis: add age column where it makes sense

test/e2e/apibinding/apibinding_authorizer_test.go, test/e2e/apibinding/apibinding_deletion_test.go, test/e2e/apibinding/apibinding_permissionclaims_test.go, test/e2e/apibinding/apibinding_protected_test.go, test/e2e/apibinding/apibinding_test.go, test/e2e/apibinding/apibinding_webhook_test.go, test/e2e/authorizer/authorizer_test.go, test/e2e/authorizer/rootcacertconfigmap_test.go, test/e2e/authorizer/serviceaccounts_test.go
=> Part 9: Scope client calls in test/e2e

test/e2e/framework/syncer.go
Accidentally came in with the 1.24 rebase
=> e2e: undo ForeverTestTimeout/30

test/e2e/apibinding/apibinding_test.go
Workspace names can be customized. Makes debugging and logs so much easier to read.
=> e2e/apibinding: improve log output and workspace names

test/e2e/syncer/syncer_test.go, test/e2e/workspacetype/controller_test.go
=> Part 12: Scope syncer and workspacetype tests

pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go, pkg/server/home_workspaces.go, pkg/server/home_workspaces_test.go
- log clusterworkspace patches
- minor cleanups of home workspace code
- add logging to home workspaces to help debug future home workspace creation failures
Fixes #
=> Add more logging

pkg/logging/constants.go, pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/apis/apibinding/apibinding_reconcile.go, pkg/reconciler/apis/apibinding/apibinding_reconcile_permissionclaim.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go, pkg/reconciler/apis/apiexport/apiexport_controller.go, pkg/reconciler/apis/apiexport/apiexport_reconcile.go, pkg/reconciler/apis/apiexport/crypto.go, pkg/reconciler/apis/apiresource/controller.go, pkg/reconciler/apis/apiresource/negotiation.go, pkg/reconciler/scheduling/location/location_controller.go, pkg/reconciler/scheduling/placement/placement_controller.go, pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go, pkg/reconciler/tenancy/bootstrap/bootstrap_reconcile.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_controller.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_metadata.go, pkg/reconciler/tenancy/clusterworkspace/clusterworkspace_reconcile_scheduling.go, pkg/reconciler/tenancy/clusterworkspacedeletion/clusterworkspace_deletion_controller.go, pkg/reconciler/tenancy/clusterworkspacedeletion/deletion/workspace_resource_deletor.go, pkg/reconciler/tenancy/clusterworkspaceshard/clusterworkspaceshard_controller.go, pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller.go, pkg/reconciler/tenancy/clusterworkspacetype/clusterworkspacetype_controller_reconcile.go
=> reconciler/{apis,scheduling,tenancy}: use structured, contextual logging

pkg/virtual/workspaces/builder/build.go, pkg/virtual/workspaces/registry/rest.go, pkg/virtual/workspaces/registry/rest_test.go, test/e2e/homeworkspaces/home_workspaces_test.go, test/e2e/virtual/workspaces/virtual_workspace_test.go
Cleanup, and getting rid of the warning in the logs that no authorizer is defined.
=> virtual/workspace: use real authorizer

pkg/server/server.go
changes the way we register the remote shard so that it handles the following cases:
- the resource has already been registered and is up to date
- the resource has been registered but requires an update
- the resource hasn't been added
all the above cases tolerate any availability issues while connecting to the root shard.
Fixes #
=> server: hardens the remote shard registration

test/e2e/apibinding/apibinding_test.go, test/e2e/virtual/apiexport/virtualworkspace_test.go
so that the final list is not empty. Basically, we require a shard resource to have assigned a VirtualWorkspace URL.
Fixes #
=> updates the tests building a list of VirtualWorkspaceURLs assigned to ClusterWorkspaceShards

test/e2e/framework/config.go, test/e2e/framework/syncer.go, test/e2e/framework/workspaces.go
=> Part 14: scope clients in tests/e2e/framework

.github/workflows/ci.yaml, .github/workflows/goreleaser.yml, .goreleaser.yaml, Makefile
Backport of https://github.com/kcp-dev/kcp/pull/1721.
=> 0.7: Add goreleaser

.github/workflows/goreleaser.yml, .goreleaser.yaml
60min timeout and no arm, only arm64 and amd64.
=> goreleaser: increase timeout and reduce archs

test/e2e/virtual/apiexport/virtualworkspace_test.go, test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go, test/e2e/virtual/syncer/virtualworkspace_test.go, test/e2e/virtual/workspaces/virtual_workspace_test.go, test/e2e/watchcache/watchcache_enabled_test.go
=> Part 13: Scope clients in test/e2e/virtual

pkg/virtual/apiexport/options/options.go, pkg/virtual/options/options.go, pkg/virtual/syncer/options/options.go, pkg/virtual/workspaces/options/options.go
=> virtual: stutter less in constructors

pkg/indexers/apiexport.go, pkg/indexers/indexers.go, pkg/indexers/util.go, pkg/reconciler/apis/apiexport/apiexport_controller.go, pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go, pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_reconcile.go
Backport of #1762 from main to release-0.7
=> [release-0.7] Start centralizing APIExport indexers

pkg/authorization/toplevel_org_authorizer.go, pkg/authorization/workspace_content_authorizer.go
Add more audit annotations to add details to the audit log when
workspace access is not permitted.
Fixes #1768
Part of #1307
=> Add content, toplevel audit annotations

pkg/crdpuller/discovery.go
This is a follow-up on #1769. Adding missing defaults on Service protocol field.
=> Set service protocol defaults

pkg/admission/apiresourceschema/validation.go
Fixes https://github.com/kcp-dev/kcp/issues/1784
=> Add missing autoscaling single-word group name

pkg/server/controllers.go, pkg/server/server.go
requires https://github.com/kcp-dev/kcp/pull/1782
=> wires the APIIdentityCacheController

pkg/schemacompat/schemacompat.go, pkg/schemacompat/schemacompat_test.go
=> Fix schemacompat npe

pkg/syncer/spec/spec_process.go, pkg/syncer/status/status_process.go
fixes https://github.com/kcp-dev/kcp/issues/1720
Follow-up: https://github.com/kcp-dev/kcp/issues/398
=> Fix leftover resource when deleting a namespace

pkg/logging/constants.go, pkg/server/apiextensions.go, pkg/server/bootstrap/identity.go, pkg/server/controllers.go, pkg/server/handler.go, pkg/server/home_workspaces.go, pkg/server/home_workspaces_test.go, pkg/server/options/controllers.go, pkg/server/options/options.go, pkg/server/server.go, pkg/server/virtual.go
Part of #1694 
/assign @ncdc 
/cc @davidfestal @sttts
=> pkg/server: use structured, contextual logging

cmd/ingress-controller/main.go, pkg/localenvoy/controllers/ingress/envoyingresscontroller.go
=> Part 18: Scope ingress controller

cmd/kcp-front-proxy/main.go, cmd/virtual-workspaces/command/cmd.go, pkg/proxy/index/index_controller.go, pkg/server/bootstrap/identity.go, pkg/server/config.go
=> Part 19: Scoped cmd/front-proxy

test/e2e/watchcache/watchcache_enabled_test.go
Remove testing the ddsif as part of the watch cache tests as this flow
was an attempt to diagnose an issue that ultimately was from a bug in
our Kubernetes fork (see https://github.com/kcp-dev/kubernetes/pull/85
for details).
=> e2e/watchcache: remove ddsif testing

pkg/syncer/shared/namespace.go
workloadLogicalClusterName was incorrect - it should be syncTargetName
=> Fix NewNamespaceLocator param name

config/crds/apis.kcp.dev_apibindings.yaml, pkg/admission/permissionclaims/mutating_permission_claims.go, pkg/apis/apis/v1alpha1/types_apibinding.go, pkg/apis/apis/v1alpha1/types_apiexport.go, pkg/apis/apis/v1alpha1/zz_generated.deepcopy.go, pkg/openapi/zz_generated.openapi.go, pkg/permissionclaim/permissionclaim_labeler.go, pkg/reconciler/apis/apibinding/apibinding_reconcile.go, pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_resource_controller.go, pkg/server/controllers.go, test/e2e/apibinding/apibinding_permissionclaims_test.go
=> Add exported claims

test/e2e/virtual/apiexport/virtualworkspace_test.go
- verify apiexport vw returns empty lists for claimed resources when
claims have not been accepted yet
- verify apiexport vw successfully returns at least some data after the
claims have been accepted
- verify apiexport vw gets an error when trying to list a resource after
that resource has been removed from the export's claims
- verify apiexport vw returns an empty list for a claimed resource after
the binding changes the claim from accepted to rejected
Part of #1219
=> Add more e2e test cases for permission claims

pkg/reconciler/workload/resource/resource_controller.go
Fix NPE in resource controller. Also try to do as much work as possible in enqueueResourcesForNamespace
and return an aggregate of any errors encountered at the end, instead of stopping at the first lister error encountered.
Fixes #1879
=> resource controller: fix NPE

pkg/cliplugins/workload/plugin/sync_test.go, pkg/cliplugins/workload/plugin/syncer.yaml, pkg/syncer/namespace/namespace_controller.go, pkg/syncer/namespace/namespace_process.go, pkg/syncer/namespace/namespace_process_test.go, pkg/syncer/syncer.go, test/e2e/syncer/syncer_test.go
Fixes https://github.com/kcp-dev/kcp/issues/398
=> Delete downstream namespace on upstream deletion

cmd/virtual-workspaces/command/cmd.go
Updates the usage text for the virtual-workspaces command to be accurate
with current status.
n/a -- good to see you folks :)
=> Update usage text for virtual-workspaces to be accurate

.github/pull_request_template.md, .github/workflows/pr-verifier.yaml
Add the PR verifier GitHub action from https://github.com/kubernetes-sigs/kubebuilder-release-tools#pr-verification-github-action
Part of #1931
=> Enable PR verifier

cmd/cache-server/main.go, pkg/cache/server/options/options.go, pkg/cache/server/server.go
=> :seedling: cache: small refactor to make wiring into kcp easier

hack/bump-k8s.sh, hack/verify-contextual-logging.sh
Better way to detect which sed is available (BSD vs gnu). 
Fixes #
=> :bug: Fix scripts to run on mac with gnu sed

pkg/admission/webhook/generic_webhook.go
pkg/admission/webhook: fix nil panic
Fixes #2028
=> :bug: pkg/admission/webhook: fix nil panic

hack/logcheck.out, pkg/proxy/handler.go, pkg/proxy/index/index_controller.go
Follow up from #2002 with some more incremental changes moving the proxy code to contextual logging
Part of #1694
=> :seedling: pkg/proxy use contextual logging

pkg/apis/apis/v1alpha1/types_apiexport.go, pkg/apis/scheduling/v1alpha1/types_location.go, pkg/apis/scheduling/v1alpha1/types_placement.go, pkg/apis/tenancy/v1alpha1/types.go, pkg/apis/workload/v1alpha1/synctarget_types.go
Fixes https://github.com/kcp-dev/kcp/issues/2066
@ncdc did you expect this to change the output of the code generators?
=> :bug: apis: use correct annotation to require fields

pkg/reconciler/kubequota/kubequota_controller.go, pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
This requirement is enforced by the `waitForSync` method.
All controllers must be gated on that method before they are run.
Fixes #
=> 🌱 kcp: controllers don't have to check if caches have been synced during startup

Dockerfile
This PR updates a COPY command in the Dockerfile so that Docker will not complain when building.
Fixes #2076
=> :bug: Add trailing slash to COPY command in Dockerfile

Makefile
=> 🐛 fix OS and ARCH not being properly initialized

Makefile
https://github.com/kcp-dev/kcp/pull/2097 follow-up.
=> 🐛 Fix make install

FAQ.md
Updates all terminology links in the FAQ.md to instead point to concepts.md.
xref https://github.com/kcp-dev/kcp/pull/1911
=> 📖 Update FAQ links to point to renamed concepts.md

FAQ.md
Fixes format of a few links that were not rendering properly.
n/a
=> 🐛 Fix link rendering in FAQ.md

docs/quickstart-tenancy-and-apis.md
Adds a link to the source location for the apigen tool used in the API quickstart guide.
n/a
=> 📖 Link to apigen source in quickstart API doc

cmd/crd-puller/pull-crds.go, go.mod, hack/logcheck.out, pkg/crdpuller/discovery.go, pkg/crdpuller/discovery_test.go, pkg/syncer/apiimporter.go
- Replace fake client usage in crd-puller
- Switch to contextual logging
Fixes #
=> 🌱 crd-puller: replace fakes in tests

pkg/virtual/workspaces/registry/rest.go
Workspaces with `metaname.generateName` have empty name. But the VW code depended on `workspace.name` for roles and bindings and error messages.
=> :bug: virtualworkspace/workspaces: fix generateName

cmd/kcp/kcp.go, hack/logcheck.out
Switch to structural logging in cmd/kcp
Part of #1694
=> 🌱 cmd/kcp: use structural logging

pkg/reconciler/cache/replication/replication_reconcile.go
I'm going to add an e2e test to cover this scenario.
=> 🐛 replication: fix the Kind for APIResourceSchema

pkg/virtual/workspaces/authorization/cache.go, pkg/virtual/workspaces/authorization/cache_test.go, pkg/virtual/workspaces/authorization/metrics/metrics.go, pkg/virtual/workspaces/builder/build.go, pkg/virtual/workspaces/builder/clusterworkspaces.go
=> :sparkles: virtual/workspaces: add metrics for authorization cache syncs

cmd/sharded-test-server/shard.go, cmd/test-server/kcp/shard.go, pkg/server/options/flags.go, pkg/virtual/workspaces/authorization/cache.go, pkg/virtual/workspaces/builder/build.go, pkg/virtual/workspaces/builder/clusterworkspaces.go, pkg/virtual/workspaces/options/options.go, test/e2e/framework/kcp.go
=> :sparkles: virtual/workspaces: allow configuring authorization cache resync

test/e2e/syncer/syncer_test.go
Needed for #2278 
/assign @jmprusi
=> :seedling: test/e2e: add more logging for syncer e2e

pkg/virtual/framework/forwardingregistry/store.go
Client getters runs inside api-server context so expect user errors in apierrors.status format. Otherwise NPE happens. We clearly state in the error that request is bad.
Fixes https://github.com/kcp-dev/kcp/issues/2285
=> :bug: Return apierrors.StatusError inside client getters

pkg/cliplugins/workload/plugin/sync.go
Ensure that the Kubernetes host contains the port, for the syncer configuration generated  by the "kcp workload sync" command. 
Fixes https://github.com/kcp-dev/kcp/issues/2187
=> 🐛 cmd/sync: ensure port is set on cluster url

docs/content/en/main/concepts/developers/library-usage.md
`server.NewServer` should take an instance of `CompletedConfig` instead of `CompletedOptions` as its parameter. This PR tries to make the developers doc easier to follow.
=> 📖 Improve docs for developers/library-usage

test/e2e/virtual/syncer/virtualworkspace_test.go
Skip virtual syncer tests to unblock main branch.
(This should be reverted once fixed)
=> :bug: test/e2e/virtual/syncer: skip tests until fixed

test/e2e/framework/syncer.go
=> 🐛 Fix BoundWorkspace race condition

pkg/virtual/syncer/builder/forwarding.go, test/e2e/virtual/syncer/virtualworkspace_test.go
Enables the Status subresource on the Upsyncer VW.
=> ✨ Upsyncer VW: Enable status subresource

pkg/server/filters/filters.go, pkg/server/home_workspaces.go, test/e2e/conformance/cross_logical_cluster_list_test.go, test/e2e/framework/users.go, test/e2e/homeworkspaces/home_workspaces_test.go, test/e2e/quota/quota_test.go, test/e2e/reconciler/clusterworkspacedeletion/controller_test.go, test/e2e/virtual/initializingworkspaces/virtualworkspace_test.go, test/e2e/workspacetype/controller_test.go
=> continuation of phase b

pkg/server/home_workspaces.go, test/e2e/conformance/cross_logical_cluster_list_test.go, test/e2e/reconciler/clusterworkspacedeletion/controller_test.go
=> fixes for e2e tests

test/e2e/framework/users.go
=> test/e2e/framework/users: fix AdmitWorkspaceAccess

go.mod, go.sum
Updates dependency for logicalcluster/v2 to match valdation changes done in https://github.com/kcp-dev/kcp/pull/2341
Fixes #
=> :seedling: Update logicalcluster dependency

pkg/admission/clusterworkspacetypeexists/admission_test.go, pkg/admission/namespacelifecycle/admission.go, pkg/admission/namespacelifecycle/admission_test.go, pkg/admission/thisworkspace/admission_test.go, pkg/cliplugins/workspace/plugin/kubeconfig_test.go, pkg/index/rewriters/user.go, pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go, pkg/server/filters/filters_test.go, pkg/virtual/framework/internalapis/fixtures/synctargets.yaml
=> fix unit tests

pkg/reconciler/committer/committer.go
This is useful when trying to commit changes and patch a resource that is scoped.
Signed-off-by: Sébastien Han <seb@redhat.com>
Fixes #
=> ✨ Implement a scoped committer

pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go
=> units for workspace_reconcile_scheduling

pkg/reconciler/workload/placement/placement_reconcile_scheduling.go, pkg/reconciler/workload/placement/placement_reconcile_scheduling_test.go
fix the issue to make the getter immutable.
Fixes https://github.com/kcp-dev/kcp/issues/2470
=> 🐛 Avoid updating placement from getter

.github/workflows/ci.yaml, .github/workflows/e2e-ci-ppc64le.yml
/assign @ncdc @avinal
Fixes #2156
=> 🌱  Add github action concurrency based on workflow-ref

.github/workflows/goreleaser.yml
Run the goreleaser workflow in CI if there are changes to goreleaser files.
Fixes #
=> 🌱 Test goreleaser changes in CI

pkg/server/apiextensions_test.go
=> 🌱 Add test for shallow copy and make partial metadata CRD

docs/content/en/main/concepts/workspaces.md
.. but I do not understand the Workspace/ClusterWorkspace duality, so that part is still not clear.
This PR attempts to update the doc on workspaces.
Note: I do not understand the Workspace/ClusterWorkspace duality, so this doc may need more work in that regard.
Fixes #623
=> :book: Attempt to update doc on workspaces

test/e2e/apibinding/apibinding_test.go
Wrap the patch in an eventually call to make sure we see the correct error (due eventual consistency of APIExports).
Fixes #
=> 🌱 Deflake apibinding immutability test

pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
Switch the logicalcluster deletion code to use .Cluster() instead of the context-based RoundTripper.
Fixes #
=> 🌱 logicalcluster deletion: switch to .Cluster()

pkg/admission/apibinding/apibinding_admission.go, pkg/admission/webhook/generic_webhook.go, pkg/admission/workspacetypeexists/admission.go, pkg/authorization/maximal_permission_policy_authorizer.go, pkg/indexers/indexers.go, pkg/permissionclaim/permissionclaim_labeler.go, pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go, pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go, pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go, pkg/reconciler/tenancy/workspace/workspace_controller.go, pkg/reconciler/tenancy/workspace/workspace_reconcile.go, pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling_test.go, pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller.go, pkg/reconciler/workload/placement/placement_reconcile.go, pkg/reconciler/workload/synctargetexports/synctargetexports_controller.go, pkg/server/home_workspaces.go, pkg/virtual/syncer/controllers/apireconciler/syncer_apireconciler_reconcile.go
Add indexers.ByPathAndName helper to reduce lots of copying 😄 
Fixes #
=> 🌱 Add indexers.ByPathAndName helper

pkg/admission/crdnooverlappinggvr/crdnooverlappinggvr_admission.go, pkg/admission/reservedcrdannotations/admission.go, pkg/reconciler/apis/apibinding/apibinding_controller.go, pkg/reconciler/apis/apibinding/apibinding_reconcile.go, pkg/reconciler/apis/apibinding/apibinding_reconcile_test.go, pkg/reconciler/apis/apibinding/conflict_checker.go, pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go, pkg/server/apiextensions.go
=> :seedling:  *: s/SystemBoundCRDSClusterName/SystemBoundCRDsClusterName/g

pkg/reconciler/apis/apibinding/apibinding_reconcile.go
Scope logger so it's unique per APIResourceSchema each time through the for loop.
=> 🌱 Scope APIBinding logger

pkg/server/home_workspaces.go, test/e2e/homeworkspaces/home_workspaces_test.go
=> ✨ Allow home workspaces to be accessed via `user:<username>`

pkg/index/index.go, pkg/index/index_test.go
https://github.com/kcp-dev/kcp/pull/2510
=> 🌱 add missing unit tests for the index

pkg/proxy/index/index_controller.go
This renames a couple of occurences of clusterworkspace.
https://github.com/kcp-dev/kcp/pull/2510
=> 🌱 index controller rename

test/e2e/framework/util.go, test/e2e/framework/workspaces.go, test/e2e/reconciler/deployment/deployment_coordinator_test.go, test/e2e/syncer/dns/dns_test.go, test/e2e/syncer/dns/workspace1/0-namespace1.yaml, test/e2e/syncer/dns/workspace1/0-namespace2.yaml, test/e2e/syncer/dns/workspace1/embed.go, test/e2e/syncer/dns/workspace1/ping-across-namespace.yaml, test/e2e/syncer/dns/workspace1/ping-fully-qualified.yaml, test/e2e/syncer/dns/workspace1/ping-not-qualified.yaml, test/e2e/syncer/dns/workspace1/service.yaml, test/e2e/syncer/dns/workspace2/0-namespace.yaml, test/e2e/syncer/dns/workspace2/embed.go, test/e2e/syncer/dns/workspace2/ping-fully-qualified-fail.yaml
Add e2e tests related to the kcp DNS service. Check names correctly resolves across namespaces in the same workspace and that they don't resolve across workspaces
Fixes #
=> 🌱 Add e2e DNS tests

pkg/reconciler/apis/apiexport/apiexport_controller.go
Strongly type the params used in our enqueue functions to avoid accidentally enqueueing the wrong kind of object.
Also switch to struct function pointers for lister access.
Fixes #
=> 🌱 apiexport: strongly type enqueue params

hack/generate/crd-ref/config.yaml
Update crd-ref config file, forgotten in workspace refactor PR #2510.
Your PR description is *really* short.
Your PR description is *really* short.
Your PR description is *really* short.
Your PR description is *really* short.
Your PR description is *really* short.
Your PR description is *really* short.
=> :book: crd-ref: update for core group

config/crds/tenancy.kcp.io_workspacetypes.yaml, config/crds/tenancy.kcp.io_workspacetypes.yaml-patch, config/root-phase0/apiexport-tenancy.kcp.io.yaml, config/root-phase0/apiresourceschema-workspacetypes.tenancy.kcp.io.yaml, pkg/admission/workspacetypeexists/admission.go, pkg/admission/workspacetypeexists/admission_test.go
=> 🐛 WorkspaceType admission should respect LimitAllow{Parents, Children}.None

.github/workflows/pr-verifier.yaml
Well well well, we need still for this PR to have some description, I guess?
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
=> 🌱  Stop checking PR descriptions in CI

pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go
Update the permissionclaimlabel controller to use the committer package.
#2635 
=> :seedling: permissionclaimlabel_controller uses committer

test/e2e/reconciler/workspace/controller_test.go
previously the tests were trying to access a workspace by providing a full path to a root shard client which couldn't have been resolved by the local proxy.
xref: https://github.com/kcp-dev/kcp/pull/2596
=> 🐛 e2e/reconciler/workspace: use cluster client

pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go
Update the bootstrap_controller to use the committer package.
#2635
=> :seedling: bootstrap_controller uses committer

pkg/reconciler/tenancy/workspacetype/clusterworkspacetype_controller.go
Update the clusterworkspacetype_controller to use the committer package.
#2635
=> :seedling: clusterworkspacetype_controller uses committer.

pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go
Update the logicalcluster_deletion_controller to use the committer package.
#2635
=> :seedling: logicalcluster_deletion_controller uses committer

Makefile, go.mod, go.sum, pkg/client/listers/apiresource/v1alpha1/apiresourceimport.go, pkg/client/listers/apiresource/v1alpha1/negotiatedapiresource.go, pkg/client/listers/apis/v1alpha1/apibinding.go, pkg/client/listers/apis/v1alpha1/apiconversion.go, pkg/client/listers/apis/v1alpha1/apiexport.go, pkg/client/listers/apis/v1alpha1/apiexportendpointslice.go, pkg/client/listers/apis/v1alpha1/apiresourceschema.go, pkg/client/listers/core/v1alpha1/logicalcluster.go, pkg/client/listers/core/v1alpha1/shard.go, pkg/client/listers/scheduling/v1alpha1/location.go, pkg/client/listers/scheduling/v1alpha1/placement.go, pkg/client/listers/tenancy/v1alpha1/workspace.go, pkg/client/listers/tenancy/v1alpha1/workspacetype.go, pkg/client/listers/topology/v1alpha1/partition.go, pkg/client/listers/topology/v1alpha1/partitionset.go, pkg/client/listers/workload/v1alpha1/synctarget.go, test/e2e/fixtures/wildwest/client/listers/wildwest/v1alpha1/cowboy.go
Fixes https://github.com/kcp-dev/kcp/issues/2679
/assign @ncdc
=> :bug: *: update listers to have correct NotFound messages

pkg/reconciler/tenancy/workspace/workspace_reconcile_scheduling.go
=> :seedling: reconcilers/workspace: add logging to outgoing client calls

cmd/sharded-test-server/main.go, cmd/test-server/kcp/shard.go, cmd/test-server/main.go, test/e2e/framework/kcp.go
test-server and sharded-test-server now gather metrics from all the shards when shutting down.
Metrics are also gathered when a PrivateKcpServer() shuts down.
Fixes #
=> 🌱 tests: gather metrics

test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go, test/e2e/virtual/apiexport/authorizer_test.go
Wrap creating an APIBinding in an Eventually block to give the system time to be eventually consistent.
Change the expected error when service provider 2 tries to list cowboys in a workspace where the APIBinding shadowed a CRD.
Fixes #2732
=> 🌱 More APIExport VW e2e deflaking

test/e2e/reconciler/cache/replication_test.go
=> 🌱 Use a private kcp per disruptive replication test

docs/content/en/main/concepts/developers/replicate-new-resource.md
Describes required steps for adding a new resource for replication.
Fixes #
=> 📖 document replicating a new resource

docs/content/en/main/concepts/developers/replicate-new-resource.md
Fixes the frontmatter on replicating a new resource doc.
n/a
=> 🐛 Fix frontmatter on replicating new resource doc

test/e2e/virtual/syncer/virtualworkspace_test.go
Fix TMC e2e test flake in the `TestUpsyncerVirtualWorkspace`
Fixes #2762
=> 🐛 Fix TMC flake in the Upsyncer VW e2e test

.gitignore, docs/Dockerfile, docs/config/en/mkdocs.yml, docs/overrides/partials/header.html
Make the version selector work.
Use requirements.txt in the docs Dockerfile.
=> 🌱 More mkdocs updates

hack/logcheck.out, pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go
=> 🌱 Remove direct klog usage

test/e2e/reconciler/partitionset/partitionset_test.go
Adding logs to investigate  flake #2865 
flake #2865
=> :seedling: adding logs to investigate E2E flake

pkg/reconciler/core/shard/shard_controller.go
=> 🌱 shard controller: use committer

docs/content/concepts/placement-locations-and-scheduling.md
=>  📖 Fix obsolete wording

docs/content/concepts/placement-locations-and-scheduling.md
This PR attempts to make some udpates to bring that doc more in line with current truth.  It only goes as far as I understand right now.
Fixes #
=> 📖 Update Placement, Locations, and Scheduling doc

pkg/cliplugins/workload/plugin/sync.go
Removes the hard coded `os.Stdout` as output for the `kcp workload sync` command, and relies on the provided IO streams instead.
This makes it easier to test / leverage the syncer command from code.
=> :bug: fix(CLI): sync command should honor provided IO streams

test/e2e/reconciler/scheduling/upsynced_scheduling_test.go, test/e2e/syncer/tunnels_test.go, test/e2e/virtual/syncer/virtualworkspace_test.go
Small cleanup commit to remove data races in TMC e2e tests
No issue.
=> 🐛 Cleanup tmc e2e tests to remove data races

tmc/pkg/server/controllers.go, tmc/pkg/server/server.go
=> :seedling: Unify workload[s] names in the tmc controller.go

sdk/go.mod
I think adding those was a mistake as they prevent `go install` so removing
Fixes #https://github.com/kcp-dev/kcp/issues/2978
```release-note
NONE
```
=> :bug: Remove replace stanzas

.github/pull_request_template.md
Fixes #
```release-note
NONE
```
=> :seedling:  Add release notes into PR template

docs/content/developers/publishing-a-new-kcp-release.md
Nit updates to release docs
Fixes #
```release-note
NONE
```
=> :book:  Update release process doc

.gitignore
=> :seedling: add vendor into .gitignore

hack/build-image.sh
To make it possible to write documentation that is somewhat stable over time, it would be nice to have something like the `latest` tag on container images. However `latest` can be super misleading, especially when there are multiple active release branches at the same time.
This PR therefore does not use `latest`, but instead simply the branch name (e.g. `main`) as additional tags on the generated manifests. This would allow for example the kcp helm-charts to just reference `kcp-dev/kcp:main`.
```release-note
Container images are now not just tagged with their version, but also the branch name.
```
=> ✨ tag container images with branch name, too

OWNERS_ALIASES
Fixes #
```release-note
NONE
```
=> :seedling:  Add owner aliases to API approvers

hack/build-image.sh
For every commit to a release branch, we want to update the `release-X.Y` tag on GHCR. Likewise, when a `vX.Y.Z` is tagged, we also want to update `release-X.Y`.
However my original code assumed that we could always deduce the branch name from the tag. Since we only ran the script (before 0.21 was released) for untagged commits, this worked, because those have `PULL_BASE_REF=<branchname>` as their env variables. But for tagged releases, the `PULL_BASE_REF` is the tag and there is no actual branch in the Prow pod (technically, the tag becomes the branch). So it's simply not possible to get the correct branch. Additionally, a tag might be set on a commit that is included in multiple branches -- which would win?
To work around this, I adjusted the script to _construct_ the branch name, …
=> 🐛 Fix container image tags for tagged kcp releases

README.md
Add basic badges
Fixes #
```release-note
NONE
```
=> :sparkles: Add basic badges

pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go, pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go, pkg/reconciler/core/logicalcluster/logicalcluster_controller.go, pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go, pkg/reconciler/tenancy/workspace/workspace_controller.go
Fix copy paste signature confusion :) 
Fixes #
```release-note
NONE
```
=> :book: Fix commit  function signature name order

Dockerfile
Publish cache-server binary into image
Fixes #
```release-note
Add cache-server binary into image
```
=> :sparkles:  Build cache server into image

pkg/index/index_test.go
Fixes #
```release-note
NONE
```
=> :seedling: add mount test into index

pkg/index/index.go, pkg/index/index_test.go
Workspaces are not being reloaded if mount changes/updates/removed
Fixes #
```release-note
Fix workspaces hot reload for index controller 
```
=> :bug:  fix mount workspace reload

.github/workflows/goreleaser.yml, .goreleaser.yaml
krew should publish RC candidates, but not drafts! 
Fixes #
```release-note
NONE
```
=> :seedling: Publish RC candidates 

README.md
This link was no longer working since I updated the docs structure.
Fixes #
```release-note
NONE
```
=> :book: Update link to contributing guide

README.md
Updating the video section.
Fixes #
```release-note
NONE
```
=> :book: README.md: update videos

.github/ISSUE_TEMPLATE/adopters.yaml, ADOPTERS.md
As discussed in a previous community call, we'd like to list adopters of kcp from the community. This PR adds an issue template (an adopters form) and creates the `ADOPTERS.md` with Kubermatic as an adopter.
If you want your adoption to be added to the PR, just leave a quick review.
Fixes #
```release-note
NONE
```
=> :book: Add `ADOPTERS.md` and adopters form

pkg/virtual/framework/forwardingregistry/rest_test.go, test/e2e/fixtures/webhook/webhook.go
Fixes #
```release-note
NONE
```
=> :seedling: Fix bad smells

go.mod
Fixes #
```release-note
NONE
```
=> :seedling:  Nit fix go mod version for 'go list'

docs/content/setup/quickstart.md
Updates the `kubectl version` output in the quickstart docs to the latest version.
Fixes #
```release-note
NONE
```
=> :book: docs: update kubectl version output in quickstart

pkg/reconciler/topology/partitionset/partitionset_controller_test.go, pkg/reconciler/topology/partitionset/partitionset_reconcile.go, sdk/apis/topology/v1alpha1/types_partitionset.go, sdk/client/applyconfiguration/topology/v1alpha1/partitionsetstatus.go, test/e2e/reconciler/partitionset/partitionset_test.go
Possible integer overflow when converting int -> uint16. This bug may never occur, but it is better to have proper handling of this case.
Fixes #
```release-note
NONE
```
=> :bug: Fix probable bug

pkg/logging/constants.go, pkg/proxy/options/authentication.go, pkg/server/filters/filters.go, pkg/virtual/apiexport/authorizer/content_test.go, pkg/virtual/initializingworkspaces/builder/build.go
Such type conversions may be omitted
Fixes #
```release-note
NONE
```
=> :seedling: Remove redundant type conversion

ADOPTERS.md
Add faros.sh 
Fixes #
```release-note
NONE
```
=> :sparkles:  Update ADOPTERS.md

ADOPTERS.md
This updates the adopters file with more information about how Kubermatic adopted kcp since the product has been launched now.
Fixes #
```release-note
NONE
```
=> :book: Update Kubermatic adopter entry

.github/workflows/docs-gen-and-push.yaml, .github/workflows/goreleaser.yml, .prow.yaml, Dockerfile
What it says on the title. Little housekeeping update to the Go version we use.
Fixes #
```release-note
kcp is built with Go 1.22.10
```
=> :seedling: Update to Go 1.22.10

ADOPTERS.md
Documenting SAP as adopters as per adopter questionnaire (#3215).
Fixes #3215
```release-note
NONE
```
=> 📖  Add SAP (ApeiroRA) as adopters

pkg/authorization/decorator.go
The logging of authz failures was not very helpful by just printing `fmt.Sprintf("reason: %v, error: %v", reason, err)` for the failing step in the chain. This PR adds the context of the user and request to it, similarly as it would show up as audit log message.
Fixes #
```release-note
NONE
```
=> :seedling: authz: make step logs useful

SECURITY.md
Since we're working on moving the project towards maturity (as per the last few community meetings), we should establish a security policy to replace the "WIP" document that we have.
We can use GitHub's built-in security advisory process (which gives us goodies like GitHub assigning CVEs for us) for accepting security reports.
This is a draft/proposal for an initial security policy. I assume that we want to refine it at some point, but having one over having none is probably a good idea.
Please leave some feedback on this PR.
Fixes #
```release-note
NONE
```
=> :book: Proposal for initial security policy

.github/workflows/gh-image-purge.yaml, hack/build-image.sh
Attempt 1 didn't account how prow works :/ Now trying now more prow native way to use prow metadata variables. 
Fixes #
```release-note
NONE
```
=> :sparkles:  Add image prefix for PRs.

pkg/virtual/initializingworkspaces/builder/build.go, pkg/virtual/initializingworkspaces/builder/build_test.go
As a first step of improvement to the initializingworkspaces virtual workspace, this PR adds basic unit tests to ensure the functionality.
```release-note
NONE
```
=> 🌱 initializingworkspaces virtual workspace unit tests

pkg/server/handler.go, pkg/server/handler_test.go
It looks like you can do only groups impersonation, without users. So this should not allow this.
Fixes #
```release-note
NONE
```
=> :bug:  Add additional impersonation check

docs/content/concepts/workspaces/.pages, docs/content/concepts/workspaces/workspace-initialization.md
Workspace initializers were added three years ago under work on https://github.com/kcp-dev/kcp/issues/1149. However, there is no documentation on this subject. It would be good to introduce a new page, that will cover this topic.
Fixes #
```release-note
NONE
```
=> 📖 docs: workspace initializers and initializingworkspaces virtual workspace

docs/content/concepts/workspaces/workspace-initialization.md
Fixes #
```release-note
NONE
```
=> 📖  docs: fix list in workspace initialization page

pkg/authorization/maximal_permission_policy_authorizer.go, pkg/authorization/requiredgroups_authorizer.go, pkg/authorization/workspace_content_authorizer.go, pkg/authorization/workspace_content_authorizer_test.go, pkg/server/options/authorization.go, test/e2e/authorizer/serviceaccounts_test.go
Some simple prefactoring towards warrants https://github.com/kcp-dev/kcp/pull/3156.
Fixes #
```release-note
NONE
```
=> :seedling: authorizers: misc prefactorings

pkg/admission/kubequota/kubequota_clusterworkspace_monitor.go, pkg/features/kcp_features.go, pkg/proxy/index/index_controller.go, pkg/proxy/proxy.go, pkg/reconciler/apis/apibindingdeletion/apibinding_deletion_controller.go, pkg/reconciler/apis/apiexport/apiexport_controller.go, pkg/reconciler/apis/apiexportendpointslice/apiexportendpointslice_controller.go, pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go, pkg/reconciler/apis/extraannotationsync/apibindingannotation_controller.go, pkg/reconciler/apis/identitycache/api_export_identity_controller.go, pkg/reconciler/apis/permissionclaimlabel/permissionclaimlabel_controller.go, pkg/reconciler/apis/replicatelogicalcluster/replicatelogicalcluster_controller.go, pkg/reconciler/cache/labelclusterrolebindings/labelclusterrolebinding_controller.go, pkg/reconciler/cache/labelclusterroles/labelclusterrole_controller.go, pkg/reconciler/cache/labelclusterroles/labelclusterrole_reconcile.go, pkg/reconciler/cache/labellogicalcluster/labellogicalcluster_controller.go, pkg/reconciler/cache/replication/replication_controller.go, pkg/reconciler/cache/replication/replication_reconcile.go, pkg/reconciler/core/logicalcluster/logicalcluster_controller.go, pkg/reconciler/core/logicalclusterdeletion/logicalcluster_deletion_controller.go, pkg/reconciler/core/shard/shard_controller.go, pkg/reconciler/tenancy/bootstrap/bootstrap_controller.go, pkg/reconciler/tenancy/initialization/apibinder_initializer_controller.go, pkg/reconciler/tenancy/logicalcluster/logicalcluster_controller.go, pkg/reconciler/tenancy/replicatelogicalcluster/replicatelogicalcluster_controller.go, pkg/reconciler/tenancy/workspace/workspace_controller.go, pkg/reconciler/tenancy/workspacemounts/workspacemounts_controller.go, pkg/reconciler/tenancy/workspacetype/workspacetype_controller.go, pkg/reconciler/topology/partitionset/partitionset_controller.go, pkg/virtual/apiexport/controllers/apireconciler/apiexport_apireconciler_controller.go
Started with my PR and got into `sed` nightmare :D 
Fixes #
```release-note
NONE
```
=> :seedling:  noop: Fixup imports to be consistent.

docs/content/developers/investigations/transparent-multi-cluster.md
if you search for `transparent multi-cluster` - it is still the first result:
This makes it a bit cleaner if somebody reaches this page. 
Fixes #
```release-note
NONE
```
=> :book: notice in TMC investigation docs

pkg/proxy/index/index_controller.go
It seems there was a bad copy-paste in the update handler?
```release-note
NONE
```
=> :bug:  Fix update handler in pkg/proxy/index controller

.github/workflows/goreleaser.yml, .goreleaser.yaml, Makefile
Fixes https://github.com/kcp-dev/kcp/issues/3325
Fixes https://github.com/kcp-dev/kcp/issues/3309 
```release-note
build apigen binary on releases
```
=> :sparkles: Build apigen on releases

sdk/testing/config.go, sdk/testing/doc.go, sdk/testing/kcp.go, sdk/testing/server/config.go, sdk/testing/server/fixture.go, sdk/testing/server/ready.go, test/e2e/framework/flags.go
Some fixes and more exposed options to be usable outside. Successfully tested in github.com/kcp-dev/multicluster-provider 🎉
Fixes #
```release-note
NONE
```
=> :seedling: Make exposed testing package work outside

cli/pkg/bind/cmd/cmd.go, cli/pkg/bind/plugin/bind.go
This PR fixes parsing permission claims passed through `--{accept,reject}-permission-claim` flags.
```release-note
NONE
```
=> :bug: cli/bind: fix parsing permission claims passed by cli args

pkg/virtual/apiexport/authorizer/binding.go, pkg/virtual/apiexport/builder/build.go, pkg/virtual/apiexport/options/options.go, pkg/virtual/options/options.go, test/e2e/virtual/apiexport/authorizer_test.go
Manual backport of #3338.
Fixes #
```release-note
Add additional authorizer to APIExport Virtual Workspace that queries APIBinding for authorization decisions
```
=> [release-0.26] 🐛 Add binding authorizer to APIExport virtual workspace

.github/workflows/goreleaser.yml
Manual backport of the goreleaser action fix in #3326.
Fixes #
```release-note
NONE
```
=> [release-0.26] :bug: Use normal upload-artifact action

cli/pkg/bind/cmd/cmd.go
Fixes #
```release-note
NONE
```
=> :bug:  Typo in example

.github/workflows/gh-image-purge.yaml
Fixes #
```release-note
NONE
```
=> :bug: Fix purge job

docs/content/concepts/.pages, docs/content/concepts/authentication/index.md, docs/content/concepts/authentication/oidc.md, pkg/server/options/authentication.go
Introducing a new documentation page on the concepts of authentication in KCP server and front-proxy.
Fixes https://github.com/kcp-dev/kcp/issues/3297
```release-note
NONE
```
=>  📖 Add authentication document page

pkg/proxy/options/authentication.go
/kind feature
Enable webhook and request-header authentication in kube-front-proxy.
Fixes #
```release-note
NONE
```
=> kube-front-proxy/authentication: enable webhook and request header authn

.prow.yaml, sdk/testing/workspaces.go, test/e2e/apibinding/maximalpermissionpolicy_authorizer_test.go, test/e2e/authorizer/serviceaccounts_test.go, test/e2e/authorizer/utils.go, test/e2e/authorizer/workspace_test.go, test/e2e/conformance/crd_partial_metadata_test.go, test/e2e/reconciler/apiexportendpointslice/apiexportendpointslice_test.go, test/e2e/reconciler/workspacedeletion/controller_test.go, test/e2e/watchcache/watchcache_enabled_test.go
There's a bunch of tests that keep flaking. Some more often than others.
There's also a flaking test in regards to the service accounts but I think that is more intricate, see https://github.com/kcp-dev/kcp/issues/3289#issuecomment-2849154251
/kind bug
/kind flake
Fixes #
```release-note
NONE
```
=> Fix (some of) the flakes

test/e2e/apibinding/apibinding_test.go
The user gets Forbidden error even though it should have access to the resources. Retrying listing on the correct shard will eventually make it succeed.
Btw, the diff looks larger than it really is.
/kind flake
Fixes https://github.com/kcp-dev/kcp/issues/3371
```release-note
NONE
```
=> test: APIBinding: wrap listing VWs between shards with Eventually

hack/gen-patch-defaultrestmapper.sh
/kind bug
Fixes #
```release-note
NONE
```
=> Fix DynamicRestMapper bash

test/e2e/framework/inprocess.go
So - etcd and kcp are killed at the same time. Apparently somewhere the context isn't propagated, which leads to requests timing out and panicking, e.g.:
https://s3.eu-west-1.amazonaws.com/prow-public-data/pr-logs/pull/kcp-dev_kcp/3411/pull-kcp-test-integration/1925558768003715072/build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAUXHT7IH25XHMMYM5%2F20250522%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20250522T143338Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=b95fd87a5f0fa4b4a99b7b188022d50a5d371a3266828b9ec788a63d6888dac1
This also triggers the goleak test:
```
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
/usr/local/go/src/runtime/sema.go:95 +0x28
sync.(*Mutex).lockSlow(0x40081d5cd4)
/usr/local/go/src/sync/mutex.go:173 +0x174
sync.(*Mutex).Lock(...) …
```
=> Close etcd after kcp

docs/content/concepts/apis/exporting-apis.md, docs/content/concepts/quickstart-tenancy-and-apis.md
This PR documents the PermissionClaims verbs.
xref #3255
```release-note
NONE
```
/assign @xrstf @embik
=> Add the PermissionClaims verbs to the docs

test/integration/framework/server.go
Add methods to the integration famework `InProcessServer` to satisfy the `kcptestingserver.RunningServer` interface.
/kind feature
Fixes #
```release-note
NONE
```
=> Implement kcptestingserver.RunningServer

pkg/reconciler/apis/logicalclustercleanup/logicalclustercleanup_controller.go, pkg/reconciler/dynamicrestmapper/dynamicrestmapper_controller.go, pkg/reconciler/dynamicrestmapper/forcluster.go, pkg/reconciler/tenancy/workspacemounts/workspace_indexes.go, pkg/server/controllers.go, test/integration/dynamicrestmapper/assets/assets.go, test/integration/dynamicrestmapper/assets/crd_kubecluster.yaml, test/integration/dynamicrestmapper/dynamicrestmapper_test.go
See what test will show 
/kind cleanup
Fixes #
```release-note
Fix consistency for DynamicRestMapper & workspace cleaner
```
=> Start using dynamicRestMapper & fix it usage 

.typos.toml, GOVERNANCE.md, Makefile, docs/content/concepts/authorization/authorizers.md, docs/content/concepts/sharding/shards.md, docs/content/concepts/workspaces/workspace-types.md, docs/content/contributing/index.md, pkg/admission/workspace/admission.go, pkg/authorization/workspace_content_authorizer_test.go, pkg/network/dialer.go, pkg/network/dialer_linux.go, pkg/network/dialer_other.go, pkg/reconciler/apis/apibinding/logical_cluster_lock.go, pkg/reconciler/apis/crdcleanup/crdcleanup_controller.go, pkg/reconciler/cache/cachedresources/cachedresources_controller.go, pkg/reconciler/cache/cachedresources/cachedresources_finalizer.go, pkg/reconciler/cache/cachedresources/cachedresources_reconcile.go, pkg/reconciler/dynamicrestmapper/dynamicrestmapper_test.go, pkg/reconciler/tenancy/workspace/workspace_reconcile_phase.go, pkg/server/apiextensions_test.go, pkg/server/filters/impersonation.go, pkg/server/filters/impersonation_test.go, pkg/virtual/apiexport/authorizer/binding.go, pkg/virtual/framework/rootapiserver/config.go, sdk/apis/apis/group.go, sdk/apis/core/v1alpha1/logicalcluster_types.go, sdk/apis/roundtrip_test.go, sdk/apis/tenancy/v1alpha1/types_workspacetype.go, test/e2e/reconciler/workspacedeletion/controller_test.go
This runs [typos](https://github.com/crate-ci/typos) 1.33 on kcp and fixes all issues it found.
/kind cleanup
```release-note
NONE
```
=> fix a bunch of typos

.goreleaser.yaml, config/crds/crd-bundler.sh
Add a bundled yaml file with the crds into the release.
/kind feature
Fixes #
```release-note
When doing a release, the kcp specific CRDs are now bundled into one yaml file that is part of the release.
```
=> Add a bundled crds to the release

pkg/permissionclaim/permissionclaim_labeler.go
Signed-off-by: Mangirdas Judeikis <mangirdas@judeikis.lt>
On-behalf-of: SAP <mangirdas.judeikis@sap.com>
If you claim events via Permissionclaims, they get dual behaviour. Due to fact they exist in core group and non-core, they are treated differently (one required labeling, another not). This normalizes them at the permissionclaims labeler level to be core events. If k/k ever (we know its never....) removes events from core group - we will revert this.
Simphtom of this is that same controller adds and removed label on the same object, based on which API it gets triggered creating very "nice" hot loop. 
This just impact labeling, nothing more. 
/kind bug
Fixes #
```release-note
Fix event PermissionClaims hot loop.
```
=> Normalize events via claims

contrib/tilt/generate-frontproxy-admin-kubeconfig.sh
Add script to generate a kubeconfig targeting the frontproxy
/kind feature
Fixes #
```release-note
NONE
```
=> [tilt] Add script to generate a kubeconfig targeting the frontproxy

test/e2e/authorizer/serviceaccounts_test.go
This test failed if the ServiceAccount is on another castle than the workspace that it is trying to access. This is simply because the ServiceAccountGetter in kcp currently works with the shard's loopback config and so can only see shard-local ServiceAccounts. See the linked ticket for more information.
This PR makes the test ensure that everything happens on the same shard, thereby fixing the flakiness. Multi-shard support is left for the future and tracked in #3510.
/kind flake
Fixes #3397
```release-note
NONE
```
=> fix flaky TestServiceAccounts

test/integration/workspace/leak_test.go
Related to #3520 
Cleaning up the test overall a bit and making the output nicer:
```
assertions.go:1949: Waiting for condition, but got: found unexpected goroutines:
[Goroutine 57903 in state sleep, with time.Sleep on top of the stack:
time.Sleep(0x174876e800)
/opt/homebrew/Cellar/go/1.25.0/libexec/src/runtime/time.go:363 +0x150
...
]
assertions.go:1949: Waiting for condition, but got: found unexpected goroutines:
[Goroutine 57903 in state sleep, with time.Sleep on top of the stack:
time.Sleep(0x174876e800)
/opt/homebrew/Cellar/go/1.25.0/libexec/src/runtime/time.go:363 +0x150
created by github.com/kcp-dev/kcp/test/integration/workspace.TestWorkspaceDeletionLeak in goroutine 128
/Users/I567861/SAPDevelop/code/kcp/test/integration/workspace/leak_test.go:106 +0x12c
]
leak_test.go:109:
Error …
```
=> Update goleak test

docs/content/concepts/quickstart-tenancy-and-apis.md, docs/content/contributing/governance/security-self-assessment.md, docs/content/contributing/guides/rebasing-kubernetes.md
Low hanging fruit contribution, I ran `typos` against our docs. Turns out I made a typo in the security self-assessment.
Fixes #
```release-note
NONE
```
=> Fix some minor documentation typos

.github/workflows/goreleaser.yml
Broke the workflow in #3602. 
/kind bug
/kind regression
Fixes #
```release-note
NONE
```
=> [release-0.28] Fix goreleaser workflow YAML

README.md
Add the crossplane and kcp talk from containerdays to our references
Fixes #
```release-note
NONE
```
=> add kcp and crossplane talk to references
